/*
 * GENERATED FILE — do not edit by hand.
 * Produced by scripts/extract-knowledge.mjs from fact_phrasal_collocations.
 * Re-run `pnpm content:extract` to regenerate; output is deterministic.
 */
import type { KnowledgeEntry } from '../types.ts';

export const COLLOCATION: KnowledgeEntry[] = [
  {
    id: 'col.01',
    kind: 'collocation',
    statement: 'wake up / get up — I usually wake up at 6:00 AM every morning.',
    glossVi: 'thức giấc / rời khỏi giường',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-a1', 'daily-phrasals'],
  },
  {
    id: 'col.02',
    kind: 'collocation',
    statement: 'turn on / turn off — Please turn off the lights before leaving the room.',
    glossVi: 'bật / tắt thiết bị',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-a1', 'daily-phrasals'],
  },
  {
    id: 'col.03',
    kind: 'collocation',
    statement: 'look forward to — I look forward to hearing from you soon.',
    glossVi: 'rất mong đợi điều gì',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-a2', 'work-study'],
  },
  {
    id: 'col.04',
    kind: 'collocation',
    statement: 'find out — We need to find out what caused the server downtime.',
    glossVi: 'tìm ra, phát hiện thông tin',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-a2', 'work-study'],
  },
  {
    id: 'col.05',
    kind: 'collocation',
    statement: 'make a decision — The executive team must make a decision by Friday.',
    glossVi: 'đưa ra quyết định',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-b1', 'business-collocations'],
  },
  {
    id: 'col.06',
    kind: 'collocation',
    statement: 'meet the deadline — Everyone worked overtime to meet the project deadline.',
    glossVi: 'kịp thời hạn',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-b1', 'business-collocations'],
  },
  {
    id: 'col.07',
    kind: 'collocation',
    statement: 'carry out — They carried out an extensive user research survey.',
    glossVi: 'tiến hành, thực thi',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-b1', 'phrasal-verbs'],
  },
  {
    id: 'col.08',
    kind: 'collocation',
    statement: 'bring to the table — She brings extensive architectural expertise to the table.',
    glossVi: 'đóng góp giá trị, kỹ năng đặc biệt',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-b2', 'professional-idioms'],
  },
  {
    id: 'col.09',
    kind: 'collocation',
    statement: 'boil down to — Success in language learning boils down to consistent daily practice.',
    glossVi: 'chung quy lại là do điều gì cốt lõi',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-b2', 'professional-phrasals'],
  },
  {
    id: 'col.10',
    kind: 'collocation',
    statement: 'draw a conclusion — Based on the experimental data, researchers drew a clear conclusion.',
    glossVi: 'rút ra kết luận khoa học',
    sourceRefs: ['nep-collocations'],
    researchRefs: ['lsrules-chunks'],
    evidenceLevel: 'corpus-measured',
    tags: ['cefr-b2', 'academic-collocations'],
  },
];
