/*
 * GENERATED FILE — do not edit by hand.
 * Produced by scripts/extract-knowledge.mjs from fact_learner_painpoints (aggregated themes only).
 * Re-run `pnpm content:extract` to regenerate; output is deterministic.
 */
import type { KnowledgeEntry } from '../types.ts';

export const PAINPOINT: KnowledgeEntry[] = [
  {
    id: 'pp.general_discussion.general_english',
    kind: 'painpoint-theme',
    statement: 'GENERAL_DISCUSSION in General_English — 2686 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'general_english'],
  },
  {
    id: 'pp.general_discussion.grammar',
    kind: 'painpoint-theme',
    statement: 'GENERAL_DISCUSSION in Grammar — 1482 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'grammar'],
  },
  {
    id: 'pp.general_discussion.speaking',
    kind: 'painpoint-theme',
    statement: 'GENERAL_DISCUSSION in Speaking — 1314 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'speaking'],
  },
  {
    id: 'pp.general_discussion.listening',
    kind: 'painpoint-theme',
    statement: 'GENERAL_DISCUSSION in Listening — 1122 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'listening'],
  },
  {
    id: 'pp.general_discussion.pronunciation',
    kind: 'painpoint-theme',
    statement: 'GENERAL_DISCUSSION in Pronunciation — 908 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'pronunciation'],
  },
  {
    id: 'pp.general_discussion.exam_preparation',
    kind: 'painpoint-theme',
    statement: 'GENERAL_DISCUSSION in Exam_Preparation — 377 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'exam_preparation'],
  },
  {
    id: 'pp.feature_request_ai_app.general_english',
    kind: 'painpoint-theme',
    statement: 'FEATURE_REQUEST_AI_APP in General_English — 329 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'general_english'],
  },
  {
    id: 'pp.feature_request_ai_app.grammar',
    kind: 'painpoint-theme',
    statement: 'FEATURE_REQUEST_AI_APP in Grammar — 248 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'grammar'],
  },
  {
    id: 'pp.feature_request_ai_app.pronunciation',
    kind: 'painpoint-theme',
    statement: 'FEATURE_REQUEST_AI_APP in Pronunciation — 213 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'pronunciation'],
  },
  {
    id: 'pp.feature_request_ai_app.listening',
    kind: 'painpoint-theme',
    statement: 'FEATURE_REQUEST_AI_APP in Listening — 195 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'listening'],
  },
  {
    id: 'pp.pronunciation_accuracy.general_english',
    kind: 'painpoint-theme',
    statement: 'PRONUNCIATION_ACCURACY in General_English — 178 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'general_english'],
  },
  {
    id: 'pp.feature_request_ai_app.speaking',
    kind: 'painpoint-theme',
    statement: 'FEATURE_REQUEST_AI_APP in Speaking — 168 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'speaking'],
  },
  {
    id: 'pp.general_discussion.vocabulary',
    kind: 'painpoint-theme',
    statement: 'GENERAL_DISCUSSION in Vocabulary — 147 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'vocabulary'],
  },
  {
    id: 'pp.resource_demand.general_english',
    kind: 'painpoint-theme',
    statement: 'RESOURCE_DEMAND in General_English — 147 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'general_english'],
  },
  {
    id: 'pp.general_discussion.ai_speech_system',
    kind: 'painpoint-theme',
    statement: 'GENERAL_DISCUSSION in AI_Speech_System — 127 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'ai_speech_system'],
  },
  {
    id: 'pp.resource_demand.speaking',
    kind: 'painpoint-theme',
    statement: 'RESOURCE_DEMAND in Speaking — 102 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'speaking'],
  },
  {
    id: 'pp.pronunciation_accuracy.speaking',
    kind: 'painpoint-theme',
    statement: 'PRONUNCIATION_ACCURACY in Speaking — 98 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'speaking'],
  },
  {
    id: 'pp.resource_demand.pronunciation',
    kind: 'painpoint-theme',
    statement: 'RESOURCE_DEMAND in Pronunciation — 82 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'pronunciation'],
  },
  {
    id: 'pp.resource_demand.grammar',
    kind: 'painpoint-theme',
    statement: 'RESOURCE_DEMAND in Grammar — 63 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'grammar'],
  },
  {
    id: 'pp.grammar_overload.general_english',
    kind: 'painpoint-theme',
    statement: 'GRAMMAR_OVERLOAD in General_English — 55 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'general_english'],
  },
  {
    id: 'pp.feature_request_ai_app.exam_preparation',
    kind: 'painpoint-theme',
    statement: 'FEATURE_REQUEST_AI_APP in Exam_Preparation — 50 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'exam_preparation'],
  },
  {
    id: 'pp.pronunciation_accuracy.grammar',
    kind: 'painpoint-theme',
    statement: 'PRONUNCIATION_ACCURACY in Grammar — 47 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'grammar'],
  },
  {
    id: 'pp.grammar_overload.grammar',
    kind: 'painpoint-theme',
    statement: 'GRAMMAR_OVERLOAD in Grammar — 45 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'grammar'],
  },
  {
    id: 'pp.resource_demand.exam_preparation',
    kind: 'painpoint-theme',
    statement: 'RESOURCE_DEMAND in Exam_Preparation — 42 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'exam_preparation'],
  },
  {
    id: 'pp.pronunciation_accuracy.pronunciation',
    kind: 'painpoint-theme',
    statement: 'PRONUNCIATION_ACCURACY in Pronunciation — 34 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'pronunciation'],
  },
  {
    id: 'pp.resource_demand.listening',
    kind: 'painpoint-theme',
    statement: 'RESOURCE_DEMAND in Listening — 34 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'listening'],
  },
  {
    id: 'pp.grammar_overload.speaking',
    kind: 'painpoint-theme',
    statement: 'GRAMMAR_OVERLOAD in Speaking — 29 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'speaking'],
  },
  {
    id: 'pp.feature_request_ai_app.vocabulary',
    kind: 'painpoint-theme',
    statement: 'FEATURE_REQUEST_AI_APP in Vocabulary — 25 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'vocabulary'],
  },
  {
    id: 'pp.general_discussion.system_architecture',
    kind: 'painpoint-theme',
    statement: 'GENERAL_DISCUSSION in System_Architecture — 24 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'system_architecture'],
  },
  {
    id: 'pp.pronunciation_accuracy.exam_preparation',
    kind: 'painpoint-theme',
    statement: 'PRONUNCIATION_ACCURACY in Exam_Preparation — 23 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'exam_preparation'],
  },
  {
    id: 'pp.pronunciation_accuracy.listening',
    kind: 'painpoint-theme',
    statement: 'PRONUNCIATION_ACCURACY in Listening — 21 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'listening'],
  },
  {
    id: 'pp.speaking_environment_anxiety.speaking',
    kind: 'painpoint-theme',
    statement: 'SPEAKING_ENVIRONMENT_ANXIETY in Speaking — 14 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'speaking'],
  },
  {
    id: 'pp.grammar_overload.exam_preparation',
    kind: 'painpoint-theme',
    statement: 'GRAMMAR_OVERLOAD in Exam_Preparation — 10 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'exam_preparation'],
  },
  {
    id: 'pp.grammar_overload.listening',
    kind: 'painpoint-theme',
    statement: 'GRAMMAR_OVERLOAD in Listening — 10 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'listening'],
  },
  {
    id: 'pp.speaking_environment_anxiety.general_english',
    kind: 'painpoint-theme',
    statement: 'SPEAKING_ENVIRONMENT_ANXIETY in General_English — 10 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'general_english'],
  },
  {
    id: 'pp.feature_request_ai_app.ai_speech_system',
    kind: 'painpoint-theme',
    statement: 'FEATURE_REQUEST_AI_APP in AI_Speech_System — 9 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'ai_speech_system'],
  },
  {
    id: 'pp.grammar_overload.pronunciation',
    kind: 'painpoint-theme',
    statement: 'GRAMMAR_OVERLOAD in Pronunciation — 6 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'pronunciation'],
  },
  {
    id: 'pp.resource_demand.vocabulary',
    kind: 'painpoint-theme',
    statement: 'RESOURCE_DEMAND in Vocabulary — 6 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'vocabulary'],
  },
  {
    id: 'pp.vocabulary_retention.grammar',
    kind: 'painpoint-theme',
    statement: 'VOCABULARY_RETENTION in Grammar — 6 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'grammar'],
  },
  {
    id: 'pp.speaking_environment_anxiety.listening',
    kind: 'painpoint-theme',
    statement: 'SPEAKING_ENVIRONMENT_ANXIETY in Listening — 5 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'listening'],
  },
  {
    id: 'pp.vocabulary_retention.general_english',
    kind: 'painpoint-theme',
    statement: 'VOCABULARY_RETENTION in General_English — 5 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'general_english'],
  },
  {
    id: 'pp.grammar_overload.vocabulary',
    kind: 'painpoint-theme',
    statement: 'GRAMMAR_OVERLOAD in Vocabulary — 4 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'vocabulary'],
  },
  {
    id: 'pp.speaking_environment_anxiety.grammar',
    kind: 'painpoint-theme',
    statement: 'SPEAKING_ENVIRONMENT_ANXIETY in Grammar — 4 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'grammar'],
  },
  {
    id: 'pp.vocabulary_retention.pronunciation',
    kind: 'painpoint-theme',
    statement: 'VOCABULARY_RETENTION in Pronunciation — 4 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'pronunciation'],
  },
  {
    id: 'pp.feature_request_ai_app.system_architecture',
    kind: 'painpoint-theme',
    statement: 'FEATURE_REQUEST_AI_APP in System_Architecture — 1 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'system_architecture'],
  },
  {
    id: 'pp.pronunciation_accuracy.ai_speech_system',
    kind: 'painpoint-theme',
    statement: 'PRONUNCIATION_ACCURACY in AI_Speech_System — 1 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'ai_speech_system'],
  },
  {
    id: 'pp.pronunciation_accuracy.vocabulary',
    kind: 'painpoint-theme',
    statement: 'PRONUNCIATION_ACCURACY in Vocabulary — 1 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'vocabulary'],
  },
  {
    id: 'pp.resource_demand.ai_speech_system',
    kind: 'painpoint-theme',
    statement: 'RESOURCE_DEMAND in AI_Speech_System — 1 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'ai_speech_system'],
  },
  {
    id: 'pp.speaking_environment_anxiety.exam_preparation',
    kind: 'painpoint-theme',
    statement: 'SPEAKING_ENVIRONMENT_ANXIETY in Exam_Preparation — 1 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'exam_preparation'],
  },
  {
    id: 'pp.speaking_environment_anxiety.vocabulary',
    kind: 'painpoint-theme',
    statement: 'SPEAKING_ENVIRONMENT_ANXIETY in Vocabulary — 1 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'vocabulary'],
  },
  {
    id: 'pp.vocabulary_retention.vocabulary',
    kind: 'painpoint-theme',
    statement: 'VOCABULARY_RETENTION in Vocabulary — 1 community posts',
    sourceRefs: ['nep-painpoints'],
    researchRefs: ['lake-painpoints'],
    evidenceLevel: 'corpus-measured',
    tags: ['needs-analysis', 'vocabulary'],
  },
];
