/*
 * GENERATED FILE — do not edit by hand.
 * Produced by scripts/extract-knowledge.mjs from dim_pronunciation_phonemes + vietnamese_english_phonetic_contrast.json.
 * Re-run `pnpm content:extract` to regenerate; output is deterministic.
 */
import type { KnowledgeEntry } from '../types.ts';

export const PHONETIC: KnowledgeEntry[] = [
  {
    id: 'ph.01',
    kind: 'phonetic-contrast',
    statement: '/iː/ Long Vowel — confusions: /iː/ vs /ɪ/ (sheep - ship, reach - rich)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'long-vowel'],
  },
  {
    id: 'ph.02',
    kind: 'phonetic-contrast',
    statement: '/ɪ/ Short Vowel — confusions: /ɪ/ vs /iː/, /ɪ/ vs /e/ (bit - bet)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'short-vowel'],
  },
  {
    id: 'ph.03',
    kind: 'phonetic-contrast',
    statement: '/e/ Short Vowel — confusions: /e/ vs /æ/ (pen - pan, men - man)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'short-vowel'],
  },
  {
    id: 'ph.04',
    kind: 'phonetic-contrast',
    statement: '/æ/ Short Vowel — confusions: /æ/ vs /e/, /æ/ vs /ʌ/ (cat - cut)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'short-vowel'],
  },
  {
    id: 'ph.05',
    kind: 'phonetic-contrast',
    statement: '/ʌ/ Short Vowel — confusions: /ʌ/ vs /ɑː/ (duck - dark), /ʌ/ vs /æ/',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'short-vowel'],
  },
  {
    id: 'ph.06',
    kind: 'phonetic-contrast',
    statement: '/ɑː/ Long Vowel — confusions: /ɑː/ vs /ɔː/ (park - pork)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'long-vowel'],
  },
  {
    id: 'ph.07',
    kind: 'phonetic-contrast',
    statement: '/ɒ/ Short Vowel — confusions: /ɒ/ vs /ɔː/ (cot - caught)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'short-vowel'],
  },
  {
    id: 'ph.08',
    kind: 'phonetic-contrast',
    statement: '/ɔː/ Long Vowel — confusions: /ɔː/ vs /ɒ/, /ɔː/ vs /oʊ/ (walk - woke)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'long-vowel'],
  },
  {
    id: 'ph.09',
    kind: 'phonetic-contrast',
    statement: '/ʊ/ Short Vowel — confusions: /ʊ/ vs /uː/ (pull - pool, full - fool)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'short-vowel'],
  },
  {
    id: 'ph.10',
    kind: 'phonetic-contrast',
    statement: '/uː/ Long Vowel — confusions: /uː/ vs /ʊ/ (fool - full, boot - book)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'long-vowel'],
  },
  {
    id: 'ph.11',
    kind: 'phonetic-contrast',
    statement: '/ɜː/ Long Vowel — confusions: /ɜː/ vs /ɔː/ (first - forced)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'long-vowel'],
  },
  {
    id: 'ph.12',
    kind: 'phonetic-contrast',
    statement: '/ə/ Schwa (Weak) — confusions: Dạng âm yếu xuất hiện trong 80% từ không mang trọng âm',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'schwa-weak-'],
  },
  {
    id: 'ph.13',
    kind: 'phonetic-contrast',
    statement: '/eɪ/ Diphthong — confusions: /eɪ/ vs /e/ (taste - test, gate - get)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'diphthong'],
  },
  {
    id: 'ph.14',
    kind: 'phonetic-contrast',
    statement: '/aɪ/ Diphthong — confusions: /aɪ/ vs /ɔɪ/ (buy - boy, tie - toy)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'diphthong'],
  },
  {
    id: 'ph.15',
    kind: 'phonetic-contrast',
    statement: '/ɔɪ/ Diphthong — confusions: /ɔɪ/ vs /aɪ/ (coin - kind)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'diphthong'],
  },
  {
    id: 'ph.16',
    kind: 'phonetic-contrast',
    statement: '/aʊ/ Diphthong — confusions: /aʊ/ vs /oʊ/ (now - no, clown - clone)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'diphthong'],
  },
  {
    id: 'ph.17',
    kind: 'phonetic-contrast',
    statement: '/oʊ/ Diphthong — confusions: /oʊ/ vs /ɔː/ (boat - bought)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'diphthong'],
  },
  {
    id: 'ph.18',
    kind: 'phonetic-contrast',
    statement: '/ɪə/ Diphthong — confusions: /ɪə/ vs /eə/ (fear - fare)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'diphthong'],
  },
  {
    id: 'ph.19',
    kind: 'phonetic-contrast',
    statement: '/eə/ Diphthong — confusions: /eə/ vs /ɪə/ (chair - cheer)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'diphthong'],
  },
  {
    id: 'ph.20',
    kind: 'phonetic-contrast',
    statement: '/ʊə/ Diphthong — confusions: /ʊə/ vs /ɔː/ (poor - pour)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'diphthong'],
  },
  {
    id: 'ph.21',
    kind: 'phonetic-contrast',
    statement: '/p/ Plosive — confusions: /p/ vs /b/ (pat - bat, rope - robe)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'plosive'],
  },
  {
    id: 'ph.22',
    kind: 'phonetic-contrast',
    statement: '/b/ Plosive — confusions: /b/ vs /p/, /b/ vs /v/ (berry - very)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'plosive'],
  },
  {
    id: 'ph.23',
    kind: 'phonetic-contrast',
    statement: '/t/ Plosive — confusions: /t/ vs /d/ (two - do, bet - bed)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'plosive'],
  },
  {
    id: 'ph.24',
    kind: 'phonetic-contrast',
    statement: '/d/ Plosive — confusions: /d/ vs /t/, /d/ vs /ð/ (dare - there)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'plosive'],
  },
  {
    id: 'ph.25',
    kind: 'phonetic-contrast',
    statement: '/k/ Plosive — confusions: /k/ vs /g/ (coat - goat, lock - log)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'plosive'],
  },
  {
    id: 'ph.26',
    kind: 'phonetic-contrast',
    statement: '/g/ Plosive — confusions: /g/ vs /k/ (gain - cane)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'plosive'],
  },
  {
    id: 'ph.27',
    kind: 'phonetic-contrast',
    statement: '/tʃ/ Affricate — confusions: /tʃ/ vs /ʃ/ (chair - share, watch - wash)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'affricate'],
  },
  {
    id: 'ph.28',
    kind: 'phonetic-contrast',
    statement: '/dʒ/ Affricate — confusions: /dʒ/ vs /tʃ/ (joke - choke), /dʒ/ vs /ʒ/',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'affricate'],
  },
  {
    id: 'ph.29',
    kind: 'phonetic-contrast',
    statement: '/f/ Fricative — confusions: /f/ vs /v/ (fan - van, leaf - leave)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'fricative'],
  },
  {
    id: 'ph.30',
    kind: 'phonetic-contrast',
    statement: '/v/ Fricative — confusions: /v/ vs /w/ (vine - wine, vest - west)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'fricative'],
  },
  {
    id: 'ph.31',
    kind: 'phonetic-contrast',
    statement: '/θ/ Fricative — confusions: /θ/ vs /s/ (think - sink), /θ/ vs /t/ (three - tree)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'fricative'],
  },
  {
    id: 'ph.32',
    kind: 'phonetic-contrast',
    statement: '/ð/ Fricative — confusions: /ð/ vs /d/ (then - den, they - day), /ð/ vs /z/',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'fricative'],
  },
  {
    id: 'ph.33',
    kind: 'phonetic-contrast',
    statement: '/s/ Fricative — confusions: /s/ vs /ʃ/ (sea - she, sue - shoe), /s/ vs /z/',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'fricative'],
  },
  {
    id: 'ph.34',
    kind: 'phonetic-contrast',
    statement: '/z/ Fricative — confusions: /z/ vs /s/ (prize - price), /z/ vs /dʒ/',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'fricative'],
  },
  {
    id: 'ph.35',
    kind: 'phonetic-contrast',
    statement: '/ʃ/ Fricative — confusions: /ʃ/ vs /s/ (shoot - suit), /ʃ/ vs /tʃ/',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'fricative'],
  },
  {
    id: 'ph.36',
    kind: 'phonetic-contrast',
    statement: '/ʒ/ Fricative — confusions: /ʒ/ vs /ʃ/, /ʒ/ vs /dʒ/',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'fricative'],
  },
  {
    id: 'ph.37',
    kind: 'phonetic-contrast',
    statement: '/h/ Fricative — confusions: /h/ vs silent h (hear - ear, hat - at)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'fricative'],
  },
  {
    id: 'ph.38',
    kind: 'phonetic-contrast',
    statement: '/m/ Nasal — confusions: /m/ vs /n/ (sum - sun, comb - cone)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'nasal'],
  },
  {
    id: 'ph.39',
    kind: 'phonetic-contrast',
    statement: '/n/ Nasal — confusions: /n/ vs /ŋ/ (thin - thing, win - wing)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'nasal'],
  },
  {
    id: 'ph.40',
    kind: 'phonetic-contrast',
    statement: '/ŋ/ Nasal — confusions: /ŋ/ vs /n/ (sing - sin, bang - ban)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'nasal'],
  },
  {
    id: 'ph.41',
    kind: 'phonetic-contrast',
    statement: '/l/ Approximant — confusions: /l/ vs /r/ (light - right, load - road) - Lỗi người Việt hay gặp',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'approximant'],
  },
  {
    id: 'ph.42',
    kind: 'phonetic-contrast',
    statement: '/r/ Approximant — confusions: /r/ vs /l/ (row - low, pray - play)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'approximant'],
  },
  {
    id: 'ph.43',
    kind: 'phonetic-contrast',
    statement: '/w/ Approximant — confusions: /w/ vs /v/ (wine - vine, wet - vet)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'approximant'],
  },
  {
    id: 'ph.44',
    kind: 'phonetic-contrast',
    statement: '/j/ Approximant — confusions: /j/ vs /dʒ/ (year - jeer, yet - jet)',
    sourceRefs: ['nep-phonemes'],
    researchRefs: ['vn-phonology'],
    evidenceLevel: 'framework',
    tags: ['phoneme', 'approximant'],
  },
  {
    id: 'phvn.vp_01',
    kind: 'phonetic-contrast',
    statement:
      "/iː/ vs /ɪ/ (Tense vs Lax High Front Vowels) — VN risk: Người Việt có xu hướng phát âm cả hai âm thành âm 'i' ngắn tiếng Việt, làm mất đi sự đối lập nghĩa giữa các cặp từ. Pairs: sheep/ship, seat/sit, reach/rich, leave/live",
    glossVi:
      "Người Việt có xu hướng phát âm cả hai âm thành âm 'i' ngắn tiếng Việt, làm mất đi sự đối lập nghĩa giữa các cặp từ.",
    sourceRefs: ['nep-phonetic-db'],
    researchRefs: ['vn-phonology', 'vn-final-consonants'],
    evidenceLevel: 'corpus-measured',
    tags: ['vn-contrast', 'vowel-pair'],
  },
  {
    id: 'phvn.vp_02',
    kind: 'phonetic-contrast',
    statement:
      "/uː/ vs /ʊ/ (Tense vs Lax High Back Vowels) — VN risk: Người Việt hay phát âm cả hai âm thành âm 'u' tiếng Việt, không làm tròn môi và không kéo dài âm căng. Pairs: fool/full, pool/pull, Luke/look",
    glossVi: "Người Việt hay phát âm cả hai âm thành âm 'u' tiếng Việt, không làm tròn môi và không kéo dài âm căng.",
    sourceRefs: ['nep-phonetic-db'],
    researchRefs: ['vn-phonology', 'vn-final-consonants'],
    evidenceLevel: 'corpus-measured',
    tags: ['vn-contrast', 'vowel-pair'],
  },
  {
    id: 'phvn.vp_03',
    kind: 'phonetic-contrast',
    statement:
      "/æ/ vs /e/ (Near-open Front /æ/ vs Mid-front /e/) — VN risk: Người Việt hay đọc âm /æ/ (bẹt) thành âm 'e' hoặc 'a' thuần Việt mà không mở rộng khẩu hình dọc. Pairs: man/men, bad/bed, pan/pen",
    glossVi: "Người Việt hay đọc âm /æ/ (bẹt) thành âm 'e' hoặc 'a' thuần Việt mà không mở rộng khẩu hình dọc.",
    sourceRefs: ['nep-phonetic-db'],
    researchRefs: ['vn-phonology', 'vn-final-consonants'],
    evidenceLevel: 'corpus-measured',
    tags: ['vn-contrast', 'vowel-pair'],
  },
  {
    id: 'phvn.cp_01',
    kind: 'phonetic-contrast',
    statement:
      "/θ/ vs /t/ and /s/ (Voiceless Dental Fricative vs Alveolar Plosive) — VN risk: Tiếng Việt không có âm đặt lưỡi giữa 2 hàm răng, người Việt hay phát âm /θ/ thành 'th' tiếng Việt (giống /t/ hoặc /s/). Pairs: think/sink, three/tree, path/pass, thick/tick",
    glossVi:
      "Tiếng Việt không có âm đặt lưỡi giữa 2 hàm răng, người Việt hay phát âm /θ/ thành 'th' tiếng Việt (giống /t/ hoặc /s/).",
    sourceRefs: ['nep-phonetic-db'],
    researchRefs: ['vn-phonology', 'vn-final-consonants'],
    evidenceLevel: 'corpus-measured',
    tags: ['vn-contrast', 'consonant-pair'],
  },
  {
    id: 'phvn.cp_02',
    kind: 'phonetic-contrast',
    statement:
      "/ʃ/ vs /s/ (Palato-Alveolar Fricative vs Alveolar Fricative) — VN risk: Đặc biệt người miền Bắc hay lẫn lộn giữa 'x' và 's', không chu môi để tạo luồng khí vòm họng sâu của âm /ʃ/. Pairs: she/see, shoe/sue, ship/sip",
    glossVi:
      "Đặc biệt người miền Bắc hay lẫn lộn giữa 'x' và 's', không chu môi để tạo luồng khí vòm họng sâu của âm /ʃ/.",
    sourceRefs: ['nep-phonetic-db'],
    researchRefs: ['vn-phonology', 'vn-final-consonants'],
    evidenceLevel: 'corpus-measured',
    tags: ['vn-contrast', 'consonant-pair'],
  },
  {
    id: 'phvn.cp_03',
    kind: 'phonetic-contrast',
    statement:
      "/dʒ/ vs /tʃ/ and /z/ (Voiced vs Voiceless Post-Alveolar Affricates) — VN risk: Người Việt hay biến /dʒ/ thành 'd/gi' nhẹ của tiếng Việt (âm /z/ hoặc /j/) hoặc nuốt âm bật hơi. Pairs: joke/choke, gin/chin, badge/batch",
    glossVi: "Người Việt hay biến /dʒ/ thành 'd/gi' nhẹ của tiếng Việt (âm /z/ hoặc /j/) hoặc nuốt âm bật hơi.",
    sourceRefs: ['nep-phonetic-db'],
    researchRefs: ['vn-phonology', 'vn-final-consonants'],
    evidenceLevel: 'corpus-measured',
    tags: ['vn-contrast', 'consonant-pair'],
  },
  {
    id: 'phvn.cp_04',
    kind: 'phonetic-contrast',
    statement:
      'Ending Consonant Clusters: /-ks/, /-st/, /-ts/, /-dz/ (Word-Final Consonants & Clusters) — VN risk: Tiếng Việt là ngôn ngữ đơn lập không có âm đuôi bật hơi (closed syllables without release), dẫn đến lỗi phổ biến nhất của người Việt là nuốt âm cuối (Ending Sounds). Pairs: ',
    glossVi:
      'Tiếng Việt là ngôn ngữ đơn lập không có âm đuôi bật hơi (closed syllables without release), dẫn đến lỗi phổ biến nhất của người Việt là nuốt âm cuối (Ending Sounds).',
    sourceRefs: ['nep-phonetic-db'],
    researchRefs: ['vn-phonology', 'vn-final-consonants'],
    evidenceLevel: 'corpus-measured',
    tags: ['vn-contrast', 'consonant-pair'],
  },
];
