/*
 * Track A — Essential Interaction (8 lessons).
 * Survival spoken functions for a Vietnamese adult beginner. Inputs are
 * original FlashDay-authored dialogues informed by the lakehouse
 * speech-act inventory (dim_speaking_functions A1 rows) and the needs
 * analysis in LEARNER_AND_ENVIRONMENT.md.
 */
import type { PackLesson } from './types';

export const TRACK_A: PackLesson[] = [
  {
    id: 'a01',
    track: 'a',
    title: 'Introduce yourself',
    titleVi: 'Tự giới thiệu',
    cefr: 'a1',
    task: 'Introduce yourself to someone you meet for the first time',
    context: 'A new colleague joins your team chat or a workshop; you meet in person or on a call.',
    outcome: 'The other person learns your name, where you are from, and what you do — and can respond.',
    input: {
      title: 'A01 · Introduce yourself',
      text: [
        'Minh: Hi, my name is Minh. Nice to meet you.',
        'Sara: Nice to meet you too. I am Sara.',
        'Minh: I am from Vietnam. I am a developer.',
        'Sara: Oh, great. I am from Canada. I am a designer.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Hai người gặp nhau lần đầu: tên, quê quán, nghề nghiệp.',
    },
    explanationVi:
      'Người Việt hay dịch "Tôi tên là Minh" thành "My name..." rồi đứng hình. Chỉ cần 3 cụm: tên (My name is / I am), quê quán (I am from), nghề (I am a + nghề). Kết bằng "Nice to meet you" là đủ lịch sự.',
    targets: [
      {
        id: 'fd01.a01.t1',
        chunk: 'my name is',
        cueVi: 'tên tôi là ~',
        sourceSentence: 'Minh: Hi, my name is Minh. Nice to meet you.',
        productionPattern: 'My name is <your name>',
        transferContext: 'a phone call or online form where nobody sees your face',
      },
      {
        id: 'fd01.a01.t2',
        chunk: 'Nice to meet you',
        cueVi: 'rất vui được gặp bạn',
        sourceSentence: 'Minh: Hi, my name is Minh. Nice to meet you.',
        productionPattern: 'Nice to meet you <optional: too / too, Name>',
        transferContext: 'greeting a client, not a colleague — same politeness, new person',
      },
      {
        id: 'fd01.a01.t3',
        chunk: 'I am from Vietnam',
        cueVi: 'tôi đến từ Việt Nam',
        sourceSentence: 'Minh: I am from Vietnam. I am a developer.',
        productionPattern: 'I am from <place>',
        transferContext: 'someone asks where your accent is from — answer with a different place',
      },
      {
        id: 'fd01.a01.t4',
        chunk: 'I am a developer',
        cueVi: 'tôi là lập trình viên',
        sourceSentence: 'Minh: I am from Vietnam. I am a developer.',
        productionPattern: 'I am a <job/role>',
        transferContext: 'you meet a student instead — they say "I am a student"',
      },
      {
        id: 'fd01.a01.t5',
        chunk: 'I am a designer',
        cueVi: 'tôi là nhà thiết kế',
        sourceSentence: 'Sara: Oh, great. I am from Canada. I am a designer.',
        productionPattern: 'I am a <job/role>',
        transferContext: 'introducing a teammate who is a tester or a manager',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt:
        'A new teammate from another country joins your chat. Introduce yourself in 2–3 lines: name, country, job.',
      promptVi: 'Một đồng nghiệp nước ngoài vừa vào team. Giới thiệu bản thân 2–3 câu: tên, quê, nghề.',
      changesDimension: 'the person and channel (teammate in chat, not Sara in person)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'audio-to-meaning', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-stage0', 'oxford-5000'],
    researchRefs: ['lsrules-loop', 'vn-assembly', 'vn-l1-support', 'lsrules-chunks', 'lake-functions', 'a0-evidence'],
  },
  {
    id: 'a02',
    track: 'a',
    title: "Ask someone's name and basic information",
    titleVi: 'Hỏi tên và thông tin cơ bản',
    cefr: 'a1',
    task: 'Ask a new person their name, spelling, where they are from, and what they do',
    context: 'After introductions at a meetup or first day at work, you want their details right.',
    outcome: 'You get a name, a spelling, a place, and a job — and the exchange stays friendly.',
    input: {
      title: 'A02 · Ask for basic information',
      text: [
        'Minh: Sorry, what is your name again?',
        'Sara: Sara. S-A-R-A.',
        'Minh: How do you spell it? Sorry, S-A-R-A?',
        'Sara: Yes, exactly.',
        'Minh: And where are you from, Sara?',
        'Sara: I am from Toronto. What do you do, Minh?',
        'Minh: I am a developer. I work at a small company.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Hỏi lại tên, đánh vần, quê quán, nghề nghiệp một cách lịch sự.',
    },
    explanationVi:
      'Hỏi thông tin cá nhân bằng câu Wh- ngắn. Thêm "Sorry," hoặc "again" để mềm giọng khi hỏi lại. "What do you do?" = hỏi nghề, không phải "bạn đang làm gì".',
    targets: [
      {
        id: 'fd01.a02.t1',
        chunk: 'what is your name',
        cueVi: 'tên bạn là gì',
        sourceSentence: 'Minh: Sorry, what is your name again?',
        productionPattern: 'What is your <name / email / phone number>?',
        transferContext: 'asking for an email address on a registration call, not a name',
      },
      {
        id: 'fd01.a02.t2',
        chunk: 'How do you spell it',
        cueVi: 'bạn đánh vần nó thế nào',
        sourceSentence: 'Minh: How do you spell it? Sorry, S-A-R-A?',
        productionPattern: 'How do you spell <it / your name / that>?',
        transferContext: 'confirming a difficult surname over the phone',
      },
      {
        id: 'fd01.a02.t3',
        chunk: 'where are you from',
        cueVi: 'bạn đến từ đâu',
        sourceSentence: 'Minh: And where are you from, Sara?',
        productionPattern: 'Where are you from? / Where is <he / she> from?',
        transferContext: 'asking about a third person who just left the room',
      },
      {
        id: 'fd01.a02.t4',
        chunk: 'What do you do',
        cueVi: 'bạn làm nghề gì',
        sourceSentence: 'Sara: I am from Toronto. What do you do, Minh?',
        productionPattern: 'What do you do? / What does <he / she> do?',
        transferContext: 'asking about a colleague who is not present',
      },
      {
        id: 'fd01.a02.t5',
        chunk: 'I work at a small company',
        cueVi: 'tôi làm ở một công ty nhỏ',
        sourceSentence: 'Minh: I am a developer. I work at a small company.',
        productionPattern: 'I work at <a company / a startup / a bank>',
        transferContext: 'describing a friend who works at a big company',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt:
        'You are filling in a visitor form with a receptionist. Ask them to repeat their name spelling and where their office is.',
      promptVi: 'Bạn đang điền form với lễ tân. Hỏi lại cách đánh vần tên và hỏi văn phòng của họ ở đâu.',
      changesDimension: 'the information type (spelling + location, not name + origin)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'en-to-meaning'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-dialogues', 'oxford-5000'],
    researchRefs: ['lsrules-loop', 'lsrules-retrieval', 'lake-functions', 'vn-l1-support', 'a0-evidence'],
  },
  {
    id: 'a03',
    track: 'a',
    title: 'Say what you do',
    titleVi: 'Nói về công việc của bạn',
    cefr: 'a1',
    task: 'Describe your job, employer or field of study in one or two sentences',
    context: 'Someone asks "What do you do?" — at a meetup, in an interview warm-up, or in a team intro.',
    outcome: 'The listener understands your role and your workplace or field.',
    input: {
      title: 'A03 · Say what you do',
      text: [
        'Sara: So, what do you do, Minh?',
        'Minh: I am a developer. I work for a small software company.',
        'Sara: Nice. What do you work on?',
        'Minh: I build mobile apps. It is interesting work.',
        'Sara: I am a student, actually. I study design at college.',
        'Minh: Oh, cool. Do you like it?',
        'Sara: Yes, I really enjoy it.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Nói nghề nghiệp, nơi làm việc, hoặc ngành học.',
    },
    explanationVi:
      'Ba mẫu đủ dùng: "I am a + nghề", "I work for/at + nơi", "I study + ngành". "What do you work on?" hỏi sâu hơn — bạn đang làm sản phẩm gì. Người Việt hay thiếu mạo từ: là "a developer", không phải "developer".',
    targets: [
      {
        id: 'fd01.a03.t1',
        chunk: 'I work for a small software company',
        cueVi: 'tôi làm cho một công ty phần mềm nhỏ',
        sourceSentence: 'Minh: I am a developer. I work for a small software company.',
        productionPattern: 'I work for <a company / an agency / a startup>',
        transferContext: 'describing a freelancer instead — "I work for myself"',
      },
      {
        id: 'fd01.a03.t2',
        chunk: 'What do you work on',
        cueVi: 'bạn đang làm (dự án) gì',
        sourceSentence: 'Sara: Nice. What do you work on?',
        productionPattern: 'What do you work on? / What are you working on?',
        transferContext: 'asking a teammate about their current project',
      },
      {
        id: 'fd01.a03.t3',
        chunk: 'I build mobile apps',
        cueVi: 'tôi xây dựng ứng dụng di động',
        sourceSentence: 'Minh: I build mobile apps. It is interesting work.',
        productionPattern: 'I build <mobile apps / websites / tools>',
        transferContext: 'a backend developer answers the same question — "I build APIs"',
      },
      {
        id: 'fd01.a03.t4',
        chunk: 'I study design',
        cueVi: 'tôi học ngành thiết kế',
        sourceSentence: 'Sara: I am a student, actually. I study design at college.',
        productionPattern: 'I study <design / English / computer science>',
        transferContext: 'your younger sibling studies economics — same pattern, new field',
      },
      {
        id: 'fd01.a03.t5',
        chunk: 'I really enjoy it',
        cueVi: 'tôi thật sự thích nó',
        sourceSentence: 'Sara: Yes, I really enjoy it.',
        productionPattern: 'I really enjoy <it / my job / the work>',
        transferContext: 'someone asks if you like your new course',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt:
        'In an online profile bio, write what you do in one or two sentences — role plus what you build or study.',
      promptVi: 'Viết bio online 1–2 câu: nghề của bạn + bạn làm/học cái gì.',
      changesDimension: 'written bio, no partner asking — self-prompted production',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-grammar-errors', 'oxford-5000'],
    researchRefs: ['lsrules-loop', 'vn-assembly', 'vn-grammar-errors', 'lake-functions', 'lsrules-chunks'],
  },
  {
    id: 'a04',
    track: 'a',
    title: 'Ask for clarification',
    titleVi: 'Hỏi để hiểu rõ hơn',
    cefr: 'a1',
    task: 'Ask what a word or sentence means when you do not understand',
    context: 'A coworker or teacher uses a word you do not know mid-conversation.',
    outcome: 'The speaker explains the word and the conversation continues instead of stalling.',
    input: {
      title: 'A04 · Ask for clarification',
      text: [
        'Sara: We need to deploy the fix today.',
        'Minh: Sorry, what does deploy mean?',
        'Sara: It means to put the code on the server.',
        'Minh: Oh, I see. And what do you mean by today?',
        'Sara: Before six PM.',
        'Minh: Got it. Sorry, one more question — what is a fix here?',
        'Sara: A change that repairs a bug.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Khi nghe từ chưa rõ: hỏi nghĩa, hỏi ý, xác nhận lại.',
    },
    explanationVi:
      'Đừng im lặng giả vờ hiểu. Ba công cụ: "What does X mean?" (hỏi nghĩa từ), "What do you mean by X?" (hỏi ý cụm/câu), "Got it" / "I see" (xác nhận đã hiểu). Thêm "Sorry," cho mềm.',
    targets: [
      {
        id: 'fd01.a04.t1',
        chunk: 'what does deploy mean',
        cueVi: 'từ "deploy" nghĩa là gì',
        sourceSentence: 'Minh: Sorry, what does deploy mean?',
        productionPattern: 'What does <word> mean?',
        transferContext: 'a doctor uses the word "fasting" — ask what it means',
      },
      {
        id: 'fd01.a04.t2',
        chunk: 'what do you mean by',
        cueVi: 'ý bạn là gì khi nói ~',
        sourceSentence: 'Minh: Oh, I see. And what do you mean by today?',
        productionPattern: 'What do you mean by <word/phrase>?',
        transferContext: 'a landlord says "utilities included" — clarify what they mean',
      },
      {
        id: 'fd01.a04.t3',
        chunk: 'one more question',
        cueVi: 'một câu hỏi nữa',
        sourceSentence: 'Minh: Got it. Sorry, one more question — what is a fix here?',
        productionPattern: 'Sorry, one more question — <question>',
        transferContext: 'in a meeting, after two explanations you still need one detail',
      },
      {
        id: 'fd01.a04.t4',
        chunk: 'I see',
        cueVi: 'à, tôi hiểu rồi',
        sourceSentence: 'Minh: Oh, I see. And what do you mean by today?',
        productionPattern: 'I see. / Oh, I see.',
        transferContext: 'a shopkeeper explains the discount — acknowledge before the next question',
      },
      {
        id: 'fd01.a04.t5',
        chunk: 'Got it',
        cueVi: 'hiểu rồi / nắm được rồi',
        sourceSentence: 'Minh: Got it. Sorry, one more question — what is a fix here?',
        productionPattern: 'Got it. / Got it, thanks.',
        transferContext: 'a teammate explains a git command — confirm then move on',
      },
    ],
    supportLadder: ['context', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'In a recipe video you hear "fold in the flour". Ask what it means, then confirm you understood.',
      promptVi: 'Trong video nấu ăn bạn nghe "fold in the flour". Hỏi nghĩa của nó, rồi xác nhận bạn đã hiểu.',
      changesDimension: 'domain (cooking, not code) — same clarification functions',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'audio-to-meaning'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-painpoints'],
    researchRefs: ['lsrules-loop', 'lsrules-retrieval', 'vn-l1-support', 'lake-functions', 'lake-painpoints'],
  },
  {
    id: 'a05',
    track: 'a',
    title: 'Ask someone to repeat or slow down',
    titleVi: 'Nhờ người ta nói lại hoặc nói chậm',
    cefr: 'a1',
    task: 'Get the speaker to repeat, slow down, or say something one more time',
    context: 'Native-speed speech on a call, in a shop, or in a meeting is too fast.',
    outcome: 'The speaker repeats or slows down and you catch the information.',
    input: {
      title: 'A05 · Repeat or slow down',
      text: [
        'Agent: The gate changes to B22, boarding at nine forty-five.',
        'Minh: Sorry, I did not catch that. Could you say that again?',
        'Agent: Sure. Gate B22.',
        'Minh: Could you speak more slowly, please?',
        'Agent: Of course. B as in Bravo, 22. Boarding at nine forty-five.',
        'Minh: B22 at nine forty-five. Thank you.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Không nghe kịp → xin lặp lại, xin nói chậm, nhắc lại để xác nhận.',
    },
    explanationVi:
      'Bộ ba cứu mọi tình huống nghe: "I did not catch that" (tôi không nghe kịp), "Could you say that again?" (nói lại), "Could you speak more slowly?" (nói chậm hơn). Nhắc lại thông tin cuối cùng để xác nhận là thói quen tốt.',
    targets: [
      {
        id: 'fd01.a05.t1',
        chunk: 'I did not catch that',
        cueVi: 'tôi không nghe kịp / không bắt được',
        sourceSentence: 'Minh: Sorry, I did not catch that. Could you say that again?',
        productionPattern: 'Sorry, I did not catch <that / the name / the number>',
        transferContext: 'a phone number spoken once on a noisy call',
      },
      {
        id: 'fd01.a05.t2',
        chunk: 'Could you say that again',
        cueVi: 'bạn có thể nói lại được không',
        sourceSentence: 'Minh: Sorry, I did not catch that. Could you say that again?',
        productionPattern: 'Could you say that again <, please>?',
        transferContext: 'a teacher reads a homework instruction too fast',
      },
      {
        id: 'fd01.a05.t3',
        chunk: 'Could you speak more slowly',
        cueVi: 'bạn có thể nói chậm hơn không',
        sourceSentence: 'Minh: Could you speak more slowly, please?',
        productionPattern: 'Could you speak more <slowly / clearly>?',
        transferContext: 'a taxi dispatcher gives an address you cannot follow',
      },
      {
        id: 'fd01.a05.t4',
        chunk: 'B as in Bravo',
        cueVi: 'B như trong Bravo (đánh vần theo mẫu tự)',
        sourceSentence: 'Agent: Of course. B as in Bravo, 22. Boarding at nine forty-five.',
        productionPattern: '<letter> as in <word>',
        transferContext: 'spelling your own Vietnamese name — "N as in November"',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model'],
    transferTask: {
      prompt:
        'A hotel receptionist gives a wifi password too fast. Get them to repeat it and slow down, then confirm it back.',
      promptVi: 'Lễ tân đọc mật khẩu wifi quá nhanh. Nhờ họ nhắc lại + nói chậm, rồi đọc lại để xác nhận.',
      changesDimension: 'information type (password, not gate number) and setting',
    },
    reviewVariants: ['audio-to-meaning', 'meaning-to-en', 'context-to-phrase'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-painpoints'],
    researchRefs: ['lsrules-loop', 'lsrules-retrieval', 'lake-functions', 'lake-painpoints', 'day28-support-scale'],
  },
  {
    id: 'a06',
    track: 'a',
    title: 'Say what you need',
    titleVi: 'Nói bạn cần gì',
    cefr: 'a1',
    task: 'State a concrete need — an object, information, or help',
    context: 'At work or in a shop you must say what you need instead of waiting to be offered.',
    outcome: 'The listener knows exactly what to give you or do next.',
    input: {
      title: 'A06 · Say what you need',
      text: [
        'Minh: Excuse me, I need a minute. My laptop does not work.',
        'Sara: No problem. Do you need the charger?',
        'Minh: Yes, please. And I need help with the wifi password.',
        'Sara: The password is on the wall. Anything else?',
        'Minh: I am looking for the meeting room. Is it on this floor?',
        'Sara: Second floor, room two-oh-four.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Nói rõ thứ bạn cần: vật, thông tin, sự giúp đỡ.',
    },
    explanationVi:
      '"I need + danh từ" (I need a minute) và "I need help with + việc" (I need help with the password). "I am looking for + X" khi tìm vật/chỗ. Kết thúc nhu cầu bằng câu hỏi cụ thể.',
    targets: [
      {
        id: 'fd01.a06.t1',
        chunk: 'I need a minute',
        cueVi: 'tôi cần một chút thời gian',
        sourceSentence: 'Minh: Excuse me, I need a minute. My laptop does not work.',
        productionPattern: 'I need <a minute / help / a pen>',
        transferContext: 'a waiter rushes your order — buy time politely',
      },
      {
        id: 'fd01.a06.t2',
        chunk: 'I need help with',
        cueVi: 'tôi cần giúp về ~',
        sourceSentence: 'Minh: Yes, please. And I need help with the wifi password.',
        productionPattern: 'I need help with <the password / this form / my code>',
        transferContext: 'asking a colleague for help with an error message',
      },
      {
        id: 'fd01.a06.t3',
        chunk: 'I am looking for',
        cueVi: 'tôi đang tìm ~',
        sourceSentence: 'Minh: I am looking for the meeting room. Is it on this floor?',
        productionPattern: 'I am looking for <the meeting room / the exit / a café>',
        transferContext: 'in a supermarket, looking for an aisle item',
      },
      {
        id: 'fd01.a06.t4',
        chunk: 'Is it on this floor',
        cueVi: 'nó có ở tầng này không',
        sourceSentence: 'Minh: I am looking for the meeting room. Is it on this floor?',
        productionPattern: 'Is it on <this floor / the second floor>?',
        transferContext: 'finding a clinic room inside a hospital building',
      },
      {
        id: 'fd01.a06.t5',
        chunk: 'Anything else',
        cueVi: 'còn gì nữa không',
        sourceSentence: 'Sara: The password is on the wall. Anything else?',
        productionPattern: 'Anything else? / Anything else <you need>?',
        transferContext: 'you are the one helping a visitor — offer more help',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'At a pharmacy, say what you need: something for a headache, and help reading the label.',
      promptVi: 'Ở hiệu thuốc, nói bạn cần gì: thuốc đau đầu + nhờ đọc giúp nhãn thuốc.',
      changesDimension: 'setting (pharmacy, not office) — same need-stating functions',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'en-to-meaning'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-collocations'],
    researchRefs: ['lsrules-loop', 'vn-assembly', 'lsrules-chunks', 'lake-functions', 'esl2-ilh'],
  },
  {
    id: 'a07',
    track: 'a',
    title: 'Make a simple request',
    titleVi: 'Yêu cầu lịch sự đơn giản',
    cefr: 'a1',
    task: 'Ask another person to do something for you, politely',
    context: 'You need a door opened, a photo taken, a message sent, a seat swapped.',
    outcome: 'The listener understands the request and can say yes or no.',
    input: {
      title: 'A07 · Make a simple request',
      text: [
        'Minh: Could you open the window, please? It is hot in here.',
        'Sara: Sure, no problem.',
        'Minh: And can you send me the photo later?',
        'Sara: Of course.',
        'Minh: Would you mind sending it tonight? I need it for tomorrow.',
        'Sara: No, not at all. I will send it after dinner.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Ba mức lịch sự: Can you… → Could you… → Would you mind…',
    },
    explanationVi:
      'Thang lịch sự: "Can you X?" (bạn bè), "Could you X?" (trung lập, an toàn nhất), "Would you mind -ing?" (lịch sự nhất — chú ý động từ thêm -ing). Trả lời "Would you mind" bằng "Not at all".',
    targets: [
      {
        id: 'fd01.a07.t1',
        chunk: 'Could you open the window',
        cueVi: 'bạn có thể mở cửa sổ không',
        sourceSentence: 'Minh: Could you open the window, please? It is hot in here.',
        productionPattern: 'Could you <verb phrase>, please?',
        transferContext: 'ask a stranger on a train to move their bag',
      },
      {
        id: 'fd01.a07.t2',
        chunk: 'can you send me',
        cueVi: 'bạn có thể gửi cho tôi ~',
        sourceSentence: 'Minh: And can you send me the photo later?',
        productionPattern: 'Can you send me <the photo / the file / the link>?',
        transferContext: 'asking a support agent to email you a receipt',
      },
      {
        id: 'fd01.a07.t3',
        chunk: 'Would you mind sending it tonight',
        cueVi: 'bạn có phiền gửi nó tối nay không',
        sourceSentence: 'Minh: Would you mind sending it tonight? I need it for tomorrow.',
        productionPattern: 'Would you mind <verb-ing> <object>?',
        transferContext: 'asking a roommate to turn down music — "Would you mind turning it down?"',
      },
      {
        id: 'fd01.a07.t4',
        chunk: 'No, not at all',
        cueVi: 'không, không phiền gì',
        sourceSentence: 'Sara: No, not at all. I will send it after dinner.',
        productionPattern: 'No, not at all. / Not at all.',
        transferContext: 'someone asks "Would you mind closing the door?" — accept',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'On a plane you want the aisle passenger to let you out. Make the request politely, then add a reason.',
      promptVi: 'Trên máy bay bạn muốn người ngồi lối đi nhường bạn ra. Yêu cầu lịch sự + thêm lý do.',
      changesDimension: 'request type (physical accommodation, not sending something)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-grammar-errors'],
    researchRefs: ['lsrules-loop', 'lake-functions', 'vn-grammar-errors', 'lsrules-chunks', 'a0-contract'],
  },
  {
    id: 'a08',
    track: 'a',
    title: 'Handle "I don\'t understand"',
    titleVi: 'Xử lý khi không hiểu',
    cefr: 'a1',
    task: 'Say clearly that you do not understand and steer the conversation to a workaround',
    context: 'The explanation failed — words too hard, too fast, accent unfamiliar. You must not freeze.',
    outcome: 'The speaker adapts — writes it down, uses simpler words, or you both switch channel.',
    input: {
      title: 'A08 · Handle not understanding',
      text: [
        'Officer: You need to fill out form I-94 before the interview.',
        'Minh: I am sorry, I do not understand. I am still learning English.',
        'Officer: No problem. This paper — write your information here.',
        'Minh: Can you write it down, please? The form name.',
        'Officer: Sure. I-94.',
        'Minh: Thank you. Let me check it on my phone.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Nói thẳng là chưa hiểu + đề nghị cách khác: viết ra, nói đơn giản hơn.',
    },
    explanationVi:
      'Đừng gật đầu giả vờ. Công thức: "I am sorry, I do not understand" + lý do ngắn ("I am still learning English") + đề xuất cụ thể ("Can you write it down?" / "Let me check").',
    targets: [
      {
        id: 'fd01.a08.t1',
        chunk: 'I do not understand',
        cueVi: 'tôi không hiểu',
        sourceSentence: 'Minh: I am sorry, I do not understand. I am still learning English.',
        productionPattern: 'I do not understand <this word / the question>',
        transferContext: 'a pharmacist explains dosage with hard words — admit it',
      },
      {
        id: 'fd01.a08.t2',
        chunk: 'I am still learning English',
        cueVi: 'tôi vẫn đang học tiếng Anh',
        sourceSentence: 'Minh: I am sorry, I do not understand. I am still learning English.',
        productionPattern: 'I am still learning <English>. / Sorry, my English is not good yet.',
        transferContext: 'on a call, before asking them to slow down',
      },
      {
        id: 'fd01.a08.t3',
        chunk: 'Can you write it down',
        cueVi: 'bạn có thể viết nó ra không',
        sourceSentence: 'Minh: Can you write it down, please? The form name.',
        productionPattern: 'Can you write <it / the name / the address> down?',
        transferContext: 'a bus number you cannot catch by ear — ask for it written',
      },
      {
        id: 'fd01.a08.t4',
        chunk: 'Let me check',
        cueVi: 'để tôi kiểm tra',
        sourceSentence: 'Minh: Thank you. Let me check it on my phone.',
        productionPattern: 'Let me check <it / on my phone / the map>',
        transferContext: 'a colleague gives you a ticket id — verify before replying',
      },
    ],
    supportLadder: ['context', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt:
        'A doctor explains a medicine schedule too fast with hard words. Say you do not understand and ask for it written down.',
      promptVi: 'Bác sĩ giải thích lịch uống thuốc quá nhanh. Nói rõ bạn không hiểu và nhờ viết ra giấy.',
      changesDimension: 'setting and stakes (medical, not immigration)',
    },
    reviewVariants: ['meaning-to-en', 'audio-to-meaning', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-painpoints'],
    researchRefs: ['lsrules-loop', 'lsrules-feedback', 'lake-functions', 'lake-painpoints', 'vn-l1-support'],
  },
];
