/*
 * Track B — Everyday Functional English (6 lessons).
 * Routines, time, plans, problems, past events, opinions. Grammar serves
 * the task: present simple for routines, past simple for events —
 * informed by lakehouse fact_grammar_mastery (VN error notes) and the
 * speech-act inventory.
 */
import type { PackLesson } from './types';

export const TRACK_B: PackLesson[] = [
  {
    id: 'b01',
    track: 'b',
    title: 'Talk about your routine',
    titleVi: 'Nói về thói quen hàng ngày',
    cefr: 'a1',
    task: 'Describe your normal day to a colleague or new friend',
    context: 'Small talk about daily schedules — when you start work, eat, study.',
    outcome: 'The listener can picture your typical day and compare with theirs.',
    input: {
      title: 'B01 · Talk about your routine',
      text: [
        'Sara: What time do you usually start work?',
        'Minh: I usually start at nine. I work from home on Mondays.',
        'Sara: And when do you finish?',
        'Minh: Around six. Then I cook dinner and study English.',
        'Sara: Do you study every day?',
        'Minh: Almost every day, for thirty minutes.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Thì hiện tại đơn + trạng từ tần suất (usually, every day) cho thói quen.',
    },
    explanationVi:
      'Thói quen = thì hiện tại đơn + trạng từ tần suất. Nhớ "s/es" cho ngôi thứ 3: "he starts", "she works" — lỗi kinh điển của người Việt. "I usually start at nine" tự nhiên hơn "I start at nine usually".',
    targets: [
      {
        id: 'fd01.b01.t1',
        chunk: 'I usually start at nine',
        cueVi: 'tôi thường bắt đầu lúc 9 giờ',
        sourceSentence: 'Minh: I usually start at nine. I work from home on Mondays.',
        productionPattern: 'I usually <verb> at <time>',
        transferContext: 'describing your weekend routine — different activity and time',
      },
      {
        id: 'fd01.b01.t2',
        chunk: 'I work from home on Mondays',
        cueVi: 'thứ Hai tôi làm việc ở nhà',
        sourceSentence: 'Minh: I usually start at nine. I work from home on Mondays.',
        productionPattern: 'I work from home on <day(s)>',
        transferContext: 'a colleague works from home on Fridays — same pattern, new day',
      },
      {
        id: 'fd01.b01.t3',
        chunk: 'when do you finish',
        cueVi: 'bạn kết thúc lúc mấy giờ',
        sourceSentence: 'Sara: And when do you finish?',
        productionPattern: 'When do you <finish / start / have lunch>?',
        transferContext: 'asking a friend when their English class ends',
      },
      {
        id: 'fd01.b01.t4',
        chunk: 'I cook dinner and study English',
        cueVi: 'tôi nấu tối và học tiếng Anh',
        sourceSentence: 'Minh: Around six. Then I cook dinner and study English.',
        productionPattern: 'I <verb> and <verb> — two evening activities',
        transferContext: 'a student friend exercises and watches videos instead',
      },
      {
        id: 'fd01.b01.t5',
        chunk: 'for thirty minutes',
        cueVi: 'trong vòng 30 phút',
        sourceSentence: 'Minh: Almost every day, for thirty minutes.',
        productionPattern: 'for <number> minutes / for an hour',
        transferContext: 'telling a doctor how long you exercise each day',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'A host family asks about your normal Sunday. Describe three things you usually do, with times.',
      promptVi: 'Gia đình chủ nhà hỏi chủ nhật bạn thường làm gì. Kể 3 việc kèm thời gian.',
      changesDimension: 'the day (Sunday/weekend, not a workday)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-grammar-errors', 'oxford-5000'],
    researchRefs: ['lsrules-loop', 'vn-grammar-errors', 'lake-functions', 'vn-assembly', 'oxford-5k-prior'],
  },
  {
    id: 'b02',
    track: 'b',
    title: 'Talk about time and schedules',
    titleVi: 'Nói về giờ giấc và lịch trình',
    cefr: 'a1',
    task: 'Ask and confirm meeting times, deadlines and openings',
    context: 'Scheduling a call or asking when a place opens/closes.',
    outcome: 'Both sides agree on a time and nobody misses the appointment.',
    input: {
      title: 'B02 · Time and schedules',
      text: [
        'Sara: Can we meet on Thursday morning?',
        'Minh: What time works for you?',
        'Sara: Is ten thirty okay?',
        'Minh: A bit early for me. How about eleven?',
        'Sara: Eleven works. Does the office open at nine?',
        'Minh: Yes, it opens at nine and closes at six.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Hẹn giờ, đề xuất giờ khác, xác nhận giờ mở/đóng cửa.',
    },
    explanationVi:
      '"What time works for you?" mềm hơn "What time?". Từ chối giờ bằng "a bit early/late for me" rồi đề xuất "How about eleven?". Giờ mở cửa dùng hiện tại đơn (it opens at nine) vì là lịch cố định.',
    targets: [
      {
        id: 'fd01.b02.t1',
        chunk: 'What time works for you',
        cueVi: 'mấy giờ thì tiện cho bạn',
        sourceSentence: 'Minh: What time works for you?',
        productionPattern: 'What <time / day> works for you?',
        transferContext: 'scheduling a dentist appointment over the phone',
      },
      {
        id: 'fd01.b02.t2',
        chunk: 'A bit early for me',
        cueVi: 'hơi sớm với tôi',
        sourceSentence: 'Minh: A bit early for me. How about eleven?',
        productionPattern: 'A bit <early / late> for me.',
        transferContext: 'a dinner invite at 10pm — too late, not too early',
      },
      {
        id: 'fd01.b02.t3',
        chunk: 'How about eleven',
        cueVi: '11 giờ thì sao',
        sourceSentence: 'Minh: A bit early for me. How about eleven?',
        productionPattern: 'How about <eleven / Friday / next week>?',
        transferContext: 'counter-proposing a different day entirely',
      },
      {
        id: 'fd01.b02.t4',
        chunk: 'Does the office open at nine',
        cueVi: 'văn phòng mở cửa lúc 9 giờ phải không',
        sourceSentence: 'Sara: Eleven works. Does the office open at nine?',
        productionPattern: 'Does <the office / the shop / the gym> open at <time>?',
        transferContext: 'asking when the post office closes, not opens',
      },
      {
        id: 'fd01.b02.t5',
        chunk: 'it opens at nine and closes at six',
        cueVi: 'nó mở lúc 9 giờ và đóng lúc 6 giờ',
        sourceSentence: 'Minh: Yes, it opens at nine and closes at six.',
        productionPattern: 'It opens at <time> and closes at <time>',
        transferContext: 'describing a swimming pool schedule',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'A teammate proposes a call at 7am your time. Decline the hour politely and offer two alternatives.',
      promptVi: 'Đồng nghiệp đề nghị call lúc 7 giờ sáng. Từ chối khéo và đề xuất 2 giờ khác.',
      changesDimension: 'timezone problem (international call, not same-office meeting)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'en-to-meaning'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-dialogues'],
    researchRefs: ['lsrules-loop', 'lsrules-retrieval', 'lake-functions', 'lake-cando', 'vn-l1-support'],
  },
  {
    id: 'b03',
    track: 'b',
    title: 'Make plans',
    titleVi: 'Lên kế hoạch với người khác',
    cefr: 'a2',
    task: 'Propose, accept, or adjust a plan with someone',
    context: 'Arranging lunch, a call, or weekend activity with a colleague or friend.',
    outcome: 'A concrete plan exists: activity, time, place — or a clear raincheck.',
    input: {
      title: 'B03 · Make plans',
      text: [
        'Sara: Are you free this Saturday? Do you want to grab lunch?',
        'Minh: I would love to, but I have a class until two.',
        'Sara: No problem. We could meet at three instead.',
        'Minh: That works. Where do you want to go?',
        'Sara: How about the new place near the office?',
        'Minh: Sounds good. See you at three.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Đề nghị kế hoạch, từ chối mềm + đề xuất lại, chốt giờ và địa điểm.',
    },
    explanationVi:
      'Từ chối mềm: "I would love to, but + lý do". Đề xuất lại: "We could + V" hoặc "How about + địa điểm/giờ". Chốt: "That works" / "Sounds good. See you at <giờ>".',
    targets: [
      {
        id: 'fd01.b03.t1',
        chunk: 'Are you free this Saturday',
        cueVi: 'thứ Bảy này bạn có rảnh không',
        sourceSentence: 'Sara: Are you free this Saturday? Do you want to grab lunch?',
        productionPattern: 'Are you free <this Saturday / tomorrow / tonight>?',
        transferContext: 'inviting someone to a video call instead of lunch',
      },
      {
        id: 'fd01.b03.t2',
        chunk: 'Do you want to grab lunch',
        cueVi: 'bạn có muốn đi ăn trưa không',
        sourceSentence: 'Sara: Are you free this Saturday? Do you want to grab lunch?',
        productionPattern: 'Do you want to <grab lunch / get coffee / take a walk>?',
        transferContext: 'inviting a coworker for coffee instead of lunch',
      },
      {
        id: 'fd01.b03.t3',
        chunk: 'I would love to, but',
        cueVi: 'tôi rất muốn, nhưng ~',
        sourceSentence: 'Minh: I would love to, but I have a class until two.',
        productionPattern: 'I would love to, but <reason>',
        transferContext: 'declining a late-night event because of an early flight',
      },
      {
        id: 'fd01.b03.t4',
        chunk: 'We could meet at three instead',
        cueVi: 'ta có thể gặp lúc 3 giờ thay thế',
        sourceSentence: 'Sara: No problem. We could meet at three instead.',
        productionPattern: 'We could <meet / call / go> at <time> instead.',
        transferContext: 'rain cancels a picnic — meet online instead',
      },
      {
        id: 'fd01.b03.t5',
        chunk: 'Sounds good',
        cueVi: 'nghe được đấy / ổn',
        sourceSentence: 'Minh: Sounds good. See you at three.',
        productionPattern: 'Sounds good. / Sounds good to me.',
        transferContext: "accepting a teammate's proposed review time in chat",
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'A friend invites you to a movie at 8pm but you work late. Decline softly and propose a new time.',
      promptVi: 'Bạn bè rủ xem phim lúc 8 giờ tối nhưng bạn làm muộn. Từ chối mềm + đề xuất giờ khác.',
      changesDimension: 'activity (movie, not lunch) and blocker (work, not class)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-dialogues'],
    researchRefs: ['lsrules-loop', 'lake-functions', 'lsrules-transfer', 'vn-l1-support', 'a0-contract'],
  },
  {
    id: 'b04',
    track: 'b',
    title: 'Describe a simple problem',
    titleVi: 'Mô tả một vấn đề đơn giản',
    cefr: 'a2',
    task: 'Explain what is broken or wrong so someone can help',
    context: 'Your phone, an app, a room, an order — something is wrong and you need it fixed.',
    outcome: 'The helper understands what is wrong, when it started, and what you tried.',
    input: {
      title: 'B04 · Describe a simple problem',
      text: [
        'Minh: Hi, I have a problem with my phone. It does not charge.',
        'Staff: Okay. When did it start?',
        'Minh: It started yesterday. I tried a different cable, but it did not help.',
        'Staff: Does it turn on at all?',
        'Minh: Yes, it turns on, but the battery stays at zero.',
        'Staff: Let me take a look.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Mô tả vấn đề: cái gì hỏng, từ khi nào, bạn đã thử gì.',
    },
    explanationVi:
      'Công thức báo hỏng: "I have a problem with + X" → "It does not / it can not + V" → mốc thời gian "It started + thời điểm" → đã thử gì "I tried X, but it did not help". Người Việt hay quên "did not" rồi lại chia động từ quá khứ: đúng là "it did not help".',
    targets: [
      {
        id: 'fd01.b04.t1',
        chunk: 'I have a problem with my phone',
        cueVi: 'tôi gặp vấn đề với điện thoại',
        sourceSentence: 'Minh: Hi, I have a problem with my phone. It does not charge.',
        productionPattern: 'I have a problem with <my phone / the app / my order>',
        transferContext: 'a restaurant order arrives wrong — same opening frame',
      },
      {
        id: 'fd01.b04.t2',
        chunk: 'It does not charge',
        cueVi: 'nó không sạc (được)',
        sourceSentence: 'Minh: Hi, I have a problem with my phone. It does not charge.',
        productionPattern: 'It does not <charge / work / turn on>',
        transferContext: 'the office printer will not print — same negative frame',
      },
      {
        id: 'fd01.b04.t3',
        chunk: 'When did it start',
        cueVi: 'nó bắt đầu (bị) từ khi nào',
        sourceSentence: 'Staff: Okay. When did it start?',
        productionPattern: 'When did it <start / happen / break>?',
        transferContext: 'you are the helper — ask when the wifi went down',
      },
      {
        id: 'fd01.b04.t4',
        chunk: 'I tried a different cable, but it did not help',
        cueVi: 'tôi đã thử cáp khác nhưng không có tác dụng',
        sourceSentence: 'Minh: It started yesterday. I tried a different cable, but it did not help.',
        productionPattern: 'I tried <solution>, but it did not help.',
        transferContext: 'reporting to IT that restarting did not fix the issue',
      },
      {
        id: 'fd01.b04.t5',
        chunk: 'the battery stays at zero',
        cueVi: 'pin vẫn ở mức không',
        sourceSentence: 'Minh: Yes, it turns on, but the battery stays at zero.',
        productionPattern: '<X> stays at / remains at <state>',
        transferContext: 'an app stuck at a loading screen — "it stays on the logo"',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt:
        'At a hotel, the air conditioner in your room is broken. Report it: what is wrong, when it started, what you tried.',
      promptVi: 'Ở khách sạn, điều hòa hỏng. Báo lỗi: nó bị gì, từ khi nào, bạn đã thử gì.',
      changesDimension: 'the object and setting (hotel appliance, not a phone)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'en-to-meaning'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-grammar-errors', 'nep-painpoints'],
    researchRefs: ['lsrules-loop', 'vn-grammar-errors', 'lake-functions', 'lsrules-feedback', 'lake-painpoints'],
  },
  {
    id: 'b05',
    track: 'b',
    title: 'Talk about something that happened',
    titleVi: 'Kể một chuyện đã xảy ra',
    cefr: 'a2',
    task: 'Recount a short past event in order — what happened and how it ended',
    context: 'A colleague asks about your weekend, a meeting you attended, an incident.',
    outcome: 'The listener follows the sequence and understands the outcome.',
    input: {
      title: 'B05 · Something that happened',
      text: [
        'Sara: How was your presentation yesterday?',
        'Minh: It went well. I was nervous at first, but it got easier.',
        'Sara: Did anyone ask questions?',
        'Minh: Yes, the manager asked about the timeline. I answered with the roadmap.',
        'Sara: Nice. And then?',
        'Minh: After that, everyone relaxed and we discussed next steps.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Kể sự kiện quá khứ theo trình tự: diễn biến → cảm xúc → kết quả.',
    },
    explanationVi:
      'Quá khứ đơn cho sự kiện đã xong. Lối kể: đánh giá chung ("It went well") → cảm xúc/lúc đầu ("I was nervous at first") → chi tiết ("the manager asked...") → kết ("After that, ..."). "At first" và "after that" là keo nối.',
    targets: [
      {
        id: 'fd01.b05.t1',
        chunk: 'How was your presentation',
        cueVi: 'bài thuyết trình của bạn thế nào',
        sourceSentence: 'Sara: How was your presentation yesterday?',
        productionPattern: 'How was your <presentation / weekend / trip>?',
        transferContext: "asking about a friend's job interview",
      },
      {
        id: 'fd01.b05.t2',
        chunk: 'It went well',
        cueVi: 'nó đã diễn ra tốt',
        sourceSentence: 'Minh: It went well. I was nervous at first, but it got easier.',
        productionPattern: 'It went <well / badly / okay>.',
        transferContext: 'reporting how a difficult phone call ended',
      },
      {
        id: 'fd01.b05.t3',
        chunk: 'I was nervous at first',
        cueVi: 'lúc đầu tôi hồi hộp',
        sourceSentence: 'Minh: It went well. I was nervous at first, but it got easier.',
        productionPattern: 'I was <nervous / confused / worried> at first, but ~',
        transferContext: 'first day at a new job — nervous then comfortable',
      },
      {
        id: 'fd01.b05.t4',
        chunk: 'the manager asked about the timeline',
        cueVi: 'quản lý đã hỏi về tiến độ',
        sourceSentence: 'Minh: Yes, the manager asked about the timeline. I answered with the roadmap.',
        productionPattern: '<person> asked about <topic>',
        transferContext: 'a client asked about the price — different topic, same frame',
      },
      {
        id: 'fd01.b05.t5',
        chunk: 'we discussed next steps',
        cueVi: 'chúng tôi đã bàn các bước tiếp theo',
        sourceSentence: 'Minh: After that, everyone relaxed and we discussed next steps.',
        productionPattern: 'we discussed <next steps / the plan / the details>',
        transferContext: 'closing a project retrospective with your team',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'Tell a teammate about a bug you found yesterday: what happened, what you did, how it ended.',
      promptVi: 'Kể cho đồng nghiệp về con bug bạn phát hiện hôm qua: chuyện gì, bạn làm gì, kết quả ra sao.',
      changesDimension: 'event type (technical incident, not a presentation)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-grammar-errors'],
    researchRefs: ['lsrules-loop', 'lsrules-transfer', 'vn-grammar-errors', 'lake-functions', 'a0-evidence'],
  },
  {
    id: 'b06',
    track: 'b',
    title: 'Give an opinion and show uncertainty',
    titleVi: 'Nêu ý kiến và mức độ chắc chắn',
    cefr: 'a2',
    task: 'Say what you think while marking how sure you are',
    context: 'A teammate asks your view on a tool, a plan, a restaurant — and you are not always certain.',
    outcome: 'The listener gets your view AND your confidence level, so they can weigh it.',
    input: {
      title: 'B06 · Opinions and uncertainty',
      text: [
        'Sara: Should we switch to the new chat tool?',
        'Minh: I think it is better, but I am not sure yet.',
        'Sara: Why not?',
        'Minh: It is faster, but I guess the search is worse.',
        'Sara: Really? In my opinion the search is fine.',
        'Minh: Maybe. I need to try it more.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Ý kiến + mức chắc chắn: I think / I guess / I am not sure / Maybe.',
    },
    explanationVi:
      'Nêu ý kiến không cần chắc chắn tuyệt đối. Thang chắc chắn giảm dần: "I think" → "I guess" → "I am not sure" → "Maybe". Người Việt hay chỉ nói "Yes/No" hoặc "I think" cho mọi trường hợp.',
    targets: [
      {
        id: 'fd01.b06.t1',
        chunk: 'I think it is better',
        cueVi: 'tôi nghĩ nó tốt hơn',
        sourceSentence: 'Minh: I think it is better, but I am not sure yet.',
        productionPattern: 'I think it is <better / worse / fine>.',
        transferContext: 'comparing two restaurants a friend suggested',
      },
      {
        id: 'fd01.b06.t2',
        chunk: 'I am not sure yet',
        cueVi: 'tôi chưa chắc',
        sourceSentence: 'Minh: I think it is better, but I am not sure yet.',
        productionPattern: 'I am not sure <yet / about it / if it works>.',
        transferContext: 'asked if a new process will save time — hedge honestly',
      },
      {
        id: 'fd01.b06.t3',
        chunk: 'I guess the search is worse',
        cueVi: 'tôi đoán phần tìm kiếm tệ hơn',
        sourceSentence: 'Minh: It is faster, but I guess the search is worse.',
        productionPattern: 'I guess <clause>',
        transferContext: 'guessing why a meeting was cancelled',
      },
      {
        id: 'fd01.b06.t4',
        chunk: 'In my opinion',
        cueVi: 'theo ý kiến của tôi',
        sourceSentence: 'Sara: Really? In my opinion the search is fine.',
        productionPattern: 'In my opinion, <clause>.',
        transferContext: 'disagreeing politely about a design choice',
      },
      {
        id: 'fd01.b06.t5',
        chunk: 'I need to try it more',
        cueVi: 'tôi cần thử thêm',
        sourceSentence: 'Minh: Maybe. I need to try it more.',
        productionPattern: 'I need to <try it more / think about it / see>.',
        transferContext: 'a friend asks if you like a new game — you have only played once',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'Your team asks whether to adopt a new library. Give an opinion with your real confidence level.',
      promptVi: 'Team hỏi có nên dùng thư viện mới không. Nêu ý kiến kèm mức chắc chắn thật.',
      changesDimension: 'stakes and topic (a technical decision, not a chat tool preference)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-collocations'],
    researchRefs: ['lsrules-loop', 'lsrules-chunks', 'lake-functions', 'vn-assembly', 'a0-contract'],
  },
];
