/*
 * Track D — Listening & Pronunciation (4 lessons).
 * Perception is trained as perception (lsrules-hvpt): targets are things to
 * HEAR, not sounds to perfect. Language is recycled from Tracks A–C
 * (lake-microskills tier separation: decoding first, meaning second).
 * VN phonotactics drive the contrast choices (vn-phonology).
 */
import type { PackLesson } from './types';

export const TRACK_D: PackLesson[] = [
  {
    id: 'd01',
    track: 'd',
    title: 'Hear word boundaries in short phrases',
    titleVi: 'Nghe ranh giới từ trong cụm ngắn',
    cefr: 'a1',
    task: 'Split fast speech into individual words — catch where one word ends and the next starts',
    context:
      'Fluent speakers chain words together; Vietnamese monosyllabic habits make English sound like one long word.',
    outcome: 'You can tell "a nice to meet you" from "an ice to me chew" — the meaning lives in the boundaries.',
    input: {
      title: 'D01 · Word boundaries',
      text: [
        'Listen for the spaces inside these phrases from our earlier lessons:',
        'nice to meet you — not "nicetomeetyou"',
        'what do you do — often sounds like "whaddya" fast',
        "I am from Vietnam — in fast speech, I'm from is one beat",
        'let me check — "lemme" is the reduced form',
        'could you say that again — stress lands on SAY and AGAIN',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Nghe chỗ nối của các từ — tiếng Việt đơn âm tiết nên tai ta hay bẻ câu sai chỗ.',
    },
    explanationVi:
      "Tiếng Việt mỗi âm tiết rõ ràng; tiếng Anh nối âm và giảm âm (I am → I'm, let me → lemme). Bài này luyện NGHE chỗ nối — chưa yêu cầu nói y hệt. Nghe câu A01–C06 quen thuộc ở tốc độ nhanh.",
    targets: [
      {
        id: 'fd01.d01.t1',
        pronunciationNote: '"nicetomeetyou" — 4 từ nối một mạch, nhấn MEET',
        chunk: 'nice to meet you',
        cueVi: 'rất vui được gặp bạn (nghe: 4 từ nối nhau)',
        sourceSentence: 'nice to meet you — not "nicetomeetyou"',
        productionPattern: 'Nice to meet you <too / Name>',
        transferContext: 'hearing it fast in a noisy introduction',
      },
      {
        id: 'fd01.d01.t2',
        pronunciationNote: '"whaddya DO" — what-do-you co lại thành 2 âm',
        chunk: 'what do you do',
        cueVi: 'bạn làm nghề gì (nghe nhanh: "whaddya do")',
        sourceSentence: 'what do you do — often sounds like "whaddya" fast',
        productionPattern: 'What do you do? / What does <he / she> do?',
        transferContext: 'catching the question in a party conversation',
      },
      {
        id: 'fd01.d01.t3',
        pronunciationNote: '"I\'m-from-Vietnam" — I\'m from gộp một nhịp',
        chunk: 'I am from Vietnam',
        cueVi: "tôi đến từ Việt Nam (nghe nhanh: I'm from gộp một nhịp)",
        sourceSentence: "I am from Vietnam — in fast speech, I'm from is one beat",
        productionPattern: "I'm from <place>",
        transferContext: "hearing a stranger's origin answer in a group intro",
      },
      {
        id: 'fd01.d01.t4',
        pronunciationNote: '"LEM-me CHECK" — let me → lemme',
        chunk: 'let me check',
        cueVi: 'để tôi kiểm tra (nghe nhanh: "lemme check")',
        sourceSentence: 'let me check — "lemme" is the reduced form',
        productionPattern: 'Let me <check / see / think>.',
        transferContext: 'a colleague says it fast mid-meeting — catch the meaning',
      },
      {
        id: 'fd01.d01.t5',
        pronunciationNote: 'could you SAY that a-GAIN — nhấn SAY và GAIN',
        chunk: 'could you say that again',
        cueVi: 'bạn nói lại được không (trọng âm rơi vào SAY và AGAIN)',
        sourceSentence: 'could you say that again — stress lands on SAY and AGAIN',
        productionPattern: 'Could you <verb phrase> again?',
        transferContext: 'catching the request in a fast exchange',
      },
    ],
    supportLadder: ['context', 'audio', 'transcript', 'gloss-vi', 'full-answer'],
    transferTask: {
      prompt: 'Hear "did you eat yet" reduced in a TV clip — write down the three words and the meaning.',
      promptVi: 'Nghe "did you eat yet" nói nhanh trong phim — viết lại 3 từ + nghĩa.',
      changesDimension: 'a new reduced phrase outside the lesson set',
    },
    reviewVariants: ['audio-to-meaning', 'meaning-to-en', 'context-to-phrase'],
    sourceRefs: ['nep-phonetic-db', 'nep-collocations', 'fd-authored'],
    researchRefs: ['lsrules-hvpt', 'lake-microskills', 'vn-phonology', 'lsrules-captions', 'sla-final-consonants'],
  },
  {
    id: 'd02',
    track: 'd',
    title: 'Stress and reduced speech',
    titleVi: 'Trọng âm và âm giảm',
    cefr: 'a2',
    task: 'Find the stressed syllable — the word carrying the message in a sentence',
    context:
      'English meaning rides on stress; Vietnamese speakers often give every syllable equal weight and miss the signal.',
    outcome: 'You catch the key word even when the rest is blurred — and can place stress when you speak.',
    input: {
      title: 'D02 · Stress and reduced speech',
      text: [
        'In English, some words carry the message and others shrink:',
        'I NEED help with the password — NEED and PASS-word carry it',
        'the problem is that the app crashes — stress falls on PROB-lem and CRASH-es; verbs carry the news',
        'do you KNOW if the SHOP is open — KNOW and SHOP and O-pen',
        'listen for the strong beat, not every sound — "to", "the", "of" almost disappear',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Nghe nhịp mạnh. "to/the/of" bị giảm gần như mất — đó là bình thường, đừng cố nghe hết.',
    },
    explanationVi:
      'Tiếng Anh là ngôn ngữ nhấn nhịp: từ mang nghĩa dài và mạnh, từ nối (to, the, of, a) giảm còn /ə/. Người Việt hay đọc đều — nghe thì bỏ sót từ khóa vì chờ từng âm. Luyện: đánh dấu từ NHẤN trước, phần còn lại bỏ qua được.',
    targets: [
      {
        id: 'fd01.d02.t1',
        pronunciationNote: 'i-NEED-help-with-the-PASS-word — từ nối gần như mất',
        chunk: 'I need help with the password',
        cueVi: 'tôi cần giúp với mật khẩu (nhấn NEED, PASS-)',
        sourceSentence: 'I NEED help with the password — NEED and PASS-word carry it',
        productionPattern: 'I need help with <the password / this error / my code>',
        transferContext: 'a support call where the stressed word tells you the topic',
      },
      {
        id: 'fd01.d02.t2',
        pronunciationNote: 'the-PROB-lem-is-that-the-app-CRASH-es — nhấn PROB, CRASH',
        chunk: 'the problem is that the app crashes',
        cueVi: 'vấn đề là app bị crash (nhấn PROB-, CRASH-)',
        sourceSentence:
          'the problem is that the app crashes — stress falls on PROB-lem and CRASH-es; verbs carry the news',
        productionPattern: 'The problem is that <the app crashes / it fails / it freezes>.',
        transferContext: 'hearing a fast bug report — catch the two stressed words',
      },
      {
        id: 'fd01.d02.t3',
        pronunciationNote: 'də-yə-NOW-if-the-SHOP-is-O-pen — nhấn KNOW, SHOP, O-',
        chunk: 'do you know if the shop is open',
        cueVi: 'bạn có biết cửa hàng còn mở không (nhấn KNOW, SHOP, O-)',
        sourceSentence: 'do you KNOW if the SHOP is open — KNOW and SHOP and O-pen',
        productionPattern: 'Do you know if <the shop is open / it works / he is coming>?',
        transferContext: 'a quick yes/no question overheard in a queue',
      },
      {
        id: 'fd01.d02.t4',
        pronunciationNote: 'AL-most-dis-ap-PEAR — to/the/of gần như biến mất',
        chunk: 'almost disappear',
        cueVi: 'gần như biến mất (về âm thanh)',
        sourceSentence: 'listen for the strong beat, not every sound — "to", "the", "of" almost disappear',
        productionPattern: '<small words> almost disappear in fast speech',
        transferContext: 'recognizing why you missed "of" in a fast sentence',
      },
    ],
    supportLadder: ['context', 'audio', 'transcript', 'gloss-vi'],
    transferTask: {
      prompt:
        'Hear a fast sentence from a meeting recording — write only the stressed words, then reconstruct the message.',
      promptVi: 'Nghe một câu nói nhanh trong cuộc họp — viết chỉ các từ được nhấn, rồi dựng lại nội dung.',
      changesDimension: 'new sentence material; the skill (stress-hunting) transfers',
    },
    reviewVariants: ['audio-to-meaning', 'meaning-to-en'],
    sourceRefs: ['nep-phonetic-db', 'fd-authored'],
    researchRefs: ['lsrules-hvpt', 'lake-microskills', 'vn-phonology', 'sla-shadowing-vn', 'lsrules-captions'],
  },
  {
    id: 'd03',
    track: 'd',
    title: 'Common connected-speech patterns',
    titleVi: 'Các kiểu nối âm thường gặp',
    cefr: 'a2',
    task: 'Recognize the three main ways English words fuse: linking, dropping, blending',
    context: 'Fluent speech is not word-by-word; knowing the three fusion patterns turns mush into words.',
    outcome: 'You can predict what "going to", "want to", "did you" become at speed — and hear them anyway.',
    input: {
      title: 'D03 · Connected speech',
      text: [
        'Three patterns change how words sound together:',
        'linking — an apple: the "n" moves: a-NAP-ple',
        'dropping — I don\'t know: the "t" often goes silent: "I dunno"',
        'blending — did you: "d"+"y" becomes "j": "didja"',
        'going to and want to become gonna and wanna in casual speech',
        'these are normal, not lazy — your ear needs the pattern, not perfection',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Ba kiểu nối: nối âm cuối sang đầu từ sau, mất âm cuối (đặc biệt -t), trộn âm (d+y→j).',
    },
    explanationVi:
      'Ba kiểu nối: LINKING (an apple → "a-napple" — âm cuối chạy sang từ sau), DROPPING (don\'t know → "dunno" — mất âm /t/ cuối, lỗi ngược lại của người Việt hay nuốt âm cuối), BLENDING (did you → "didja", going to → "gonna"). Nghe nhận biết trước — nói thì không bắt buộc.',
    targets: [
      {
        id: 'fd01.d03.t1',
        pronunciationNote: '"a-NAP-ple" — âm n chạy sang từ sau',
        chunk: 'an apple',
        cueVi: 'một quả táo (nghe: "a-napple" — âm n nối sang)',
        sourceSentence: 'linking — an apple: the "n" moves: a-NAP-ple',
        productionPattern: 'an <vowel-word>: an apple, an idea, an hour',
        transferContext: 'hearing "an hour" as "a-nower" in directions',
      },
      {
        id: 'fd01.d03.t2',
        pronunciationNote: '"I-DUN-no" — mất âm t cuối',
        chunk: "I don't know",
        cueVi: 'tôi không biết (nghe nhanh: "I dunno")',
        sourceSentence: 'dropping — I don\'t know: the "t" often goes silent: "I dunno"',
        productionPattern: "I don't know. / I don't <know / think so>.",
        transferContext: 'catching "I dunno" shrugged in a hallway chat',
      },
      {
        id: 'fd01.d03.t3',
        pronunciationNote: '"DID-ja" — d+y trộn thành j',
        chunk: 'did you',
        cueVi: 'bạn đã ~ chưa (nghe nhanh: "didja")',
        sourceSentence: 'blending — did you: "d"+"y" becomes "j": "didja"',
        productionPattern: 'Did you <verb>?',
        transferContext: '"didja see it" in a casual question — same words',
      },
      {
        id: 'fd01.d03.t4',
        pronunciationNote: '"GON-na" — dạng nói nhanh của going to',
        chunk: 'going to',
        cueVi: 'sắp ~ (nói nhanh: "gonna")',
        sourceSentence: 'going to and want to become gonna and wanna in casual speech',
        productionPattern: 'I am going to <verb>. (write full form)',
        transferContext: 'hearing "gonna" in a movie and understanding the plan',
      },
      {
        id: 'fd01.d03.t5',
        pronunciationNote: '"WAN-na" — dạng nói nhanh của want to',
        chunk: 'want to',
        cueVi: 'muốn ~ (nói nhanh: "wanna")',
        sourceSentence: 'going to and want to become gonna and wanna in casual speech',
        productionPattern: 'I want to <verb>. (write full form)',
        transferContext: 'hearing "wanna grab lunch" as the B03 invitation',
      },
    ],
    supportLadder: ['context', 'audio', 'transcript', 'gloss-vi'],
    transferTask: {
      prompt:
        'In a video, someone says "haveta" and "shoulda". Map them to the written forms and use the full forms in a sentence.',
      promptVi: 'Trong phim nghe "haveta" và "shoulda". Đối chiếu về dạng viết + dùng dạng đầy đủ trong câu.',
      changesDimension: 'new reduced forms (have to, should have) beyond the lesson list',
    },
    reviewVariants: ['audio-to-meaning', 'en-to-meaning', 'meaning-to-en'],
    sourceRefs: ['nep-phonetic-db', 'fd-authored', 'community-guides'],
    researchRefs: ['lsrules-hvpt', 'lake-microskills', 'vn-phonology', 'lsrules-captions', 'a0-evidence'],
  },
  {
    id: 'd04',
    track: 'd',
    title: 'Listen for meaningful chunks',
    titleVi: 'Nghe theo cụm nghĩa',
    cefr: 'a2',
    task: 'Parse a fast sentence into meaning-groups instead of individual words',
    context: 'Understanding native speech means grouping sounds into chunks, not translating each word.',
    outcome: 'You hear "I would love to but" as one move, not six syllables.',
    input: {
      title: 'D04 · Meaningful chunks',
      text: [
        'Fluent listeners group sounds into meaning blocks:',
        'I would love to but I have a class — a soft-decline move, not six separate words',
        'the problem is that / the app crashes — frame + content',
        'it depends on / the cause — hedge + variable',
        'could you say that again — the polite request frame plus the action',
        'train your ear to grab the block first, then the detail',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-collocations',
      noteVi: 'Nghe theo khối nghĩa, không theo từng từ — chính là lý do học chunk ở Track C.',
    },
    explanationVi:
      'Đây là cầu nối giữa nghe và nói: cùng một chunk, tai nghe ra là một khối, miệng nói ra là một nhịp. Khi nghe, tìm đường cắt sau "is that", "to but", "on the" — chỗ ý chuyển tiếp.',
    targets: [
      {
        id: 'fd01.d04.t1',
        pronunciationNote: "ai'd-LUV-tə-BUT — nghe là một khối từ chối mềm",
        chunk: 'I would love to but',
        cueVi: 'tôi rất muốn nhưng ~ (khối từ chối mềm)',
        sourceSentence: 'I would love to but I have a class — a soft-decline move, not six separate words',
        productionPattern: 'I would love to, but <reason>.',
        transferContext: 'hearing a friend decline a trip invitation politely',
      },
      {
        id: 'fd01.d04.t2',
        pronunciationNote: 'the-PROB-lem-iz-that — khung chẩn đoán, nghe một nhịp',
        chunk: 'the problem is that',
        cueVi: 'vấn đề là ~ (khung chẩn đoán)',
        sourceSentence: 'the problem is that / the app crashes — frame + content',
        productionPattern: 'The problem is that <clause>.',
        transferContext: 'catching the frame in a fast support explanation',
      },
      {
        id: 'fd01.d04.t3',
        pronunciationNote: 'it-de-PEN-dzon — khung điều kiện một nhịp',
        chunk: 'it depends on',
        cueVi: 'còn tùy vào ~ (khung điều kiện)',
        sourceSentence: 'it depends on / the cause — hedge + variable',
        productionPattern: 'It depends on <the cause / the price / how>.',
        transferContext: 'a fast answer about cost — catch the hedge before the number',
      },
      {
        id: 'fd01.d04.t4',
        pronunciationNote: 'could-you-SAY-that-a-GAIN — khung yêu cầu + hành động',
        chunk: 'could you say that again',
        cueVi: 'bạn nói lại được không (khung yêu cầu + hành động)',
        sourceSentence: 'could you say that again — the polite request frame plus the action',
        productionPattern: 'Could you <verb phrase>?',
        transferContext: 'catching the request shape before the specific verb',
      },
    ],
    supportLadder: ['context', 'audio', 'transcript', 'gloss-vi'],
    transferTask: {
      prompt: 'Hear a fast voice message. Write the two meaning-blocks first, then the detail inside each.',
      promptVi: 'Nghe tin nhắn thoại nói nhanh. Viết 2 khối nghĩa trước, rồi chi tiết trong từng khối.',
      changesDimension: 'new message content; the chunking skill transfers',
    },
    reviewVariants: ['audio-to-meaning', 'context-to-phrase', 'meaning-to-en'],
    sourceRefs: ['nep-collocations', 'nep-phonetic-db', 'fd-authored'],
    researchRefs: ['lsrules-hvpt', 'lsrules-chunks', 'lake-microskills', 'lsrules-loop', 'vn-phonology'],
  },
];
