/*
 * Track C — Useful Chunks (6 lessons).
 * Formulaic sequences as first-class targets (lsrules-chunks): frames the
 * learner retrieves whole instead of assembling word-by-word — the direct
 * treatment for "biết từ nhưng không ghép thành câu".
 */
import type { PackLesson } from './types';

export const TRACK_C: PackLesson[] = [
  {
    id: 'c01',
    track: 'c',
    title: 'Trying and fixing',
    titleVi: 'Cụm khi đang thử và sửa',
    cefr: 'a1',
    task: 'Narrate an attempt that is not working yet, and keep going',
    context: 'You are fixing something — a form, an app, a device — and someone asks how it is going.',
    outcome: 'You report the attempt, the obstacle, and the next try without freezing.',
    input: {
      title: 'C01 · Trying and fixing',
      text: [
        'Sara: Is the form working?',
        'Minh: Not yet. I am trying to submit it, but it keeps rejecting my photo.',
        'Sara: Did you check the file size?',
        'Minh: Yes. I cannot figure out the real problem. Let me try again with a smaller file.',
        'Sara: Take your time.',
        'Minh: Okay — it worked this time!',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Cụm cho tình huống "đang thử mà chưa xong": trying to, keeps + V-ing, figure out, try again.',
    },
    explanationVi:
      '"I am trying to + V" = đang cố làm. "It keeps + V-ing" = nó cứ liên tục (lỗi). "I cannot figure out + X" = chưa hiểu ra vấn đề. "It worked" = thành công rồi (quá khứ, không phải hiện tại).',
    targets: [
      {
        id: 'fd01.c01.t1',
        chunk: 'I am trying to submit it',
        cueVi: 'tôi đang cố gửi nó',
        sourceSentence: 'Minh: Not yet. I am trying to submit it, but it keeps rejecting my photo.',
        productionPattern: 'I am trying to <verb> it/this',
        transferContext: 'trying to log in to a locked account',
      },
      {
        id: 'fd01.c01.t2',
        chunk: 'it keeps rejecting my photo',
        cueVi: 'nó cứ liên tục từ chối ảnh của tôi',
        sourceSentence: 'Minh: Not yet. I am trying to submit it, but it keeps rejecting my photo.',
        productionPattern: 'It keeps <verb-ing> <object> — a repeated failure',
        transferContext: 'an app keeps crashing every time you open it',
      },
      {
        id: 'fd01.c01.t3',
        chunk: 'I cannot figure out',
        cueVi: 'tôi không hiểu ra / tìm ra được',
        sourceSentence: 'Minh: Yes. I cannot figure out the real problem. Let me try again with a smaller file.',
        productionPattern: 'I cannot figure out <the problem / why it fails / how it works>',
        transferContext: 'a settings menu you cannot decode',
      },
      {
        id: 'fd01.c01.t4',
        chunk: 'Let me try again',
        cueVi: 'để tôi thử lại',
        sourceSentence: 'Minh: Yes. I cannot figure out the real problem. Let me try again with a smaller file.',
        productionPattern: 'Let me <try again / check / see>',
        transferContext: 'a phone call drops — redial and say this',
      },
      {
        id: 'fd01.c01.t5',
        chunk: 'it worked this time',
        cueVi: 'lần này nó hoạt động rồi',
        sourceSentence: 'Minh: Okay — it worked this time!',
        productionPattern: 'It worked <this time / finally>.',
        transferContext: 'a payment goes through after two failures',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'Your wifi drops during a video call. Narrate your fixing attempt in 2 sentences to the group chat.',
      promptVi: 'Wifi rớt giữa cuộc gọi. Kể 2 câu cho group chat: bạn đang thử gì + nó ra sao.',
      changesDimension: 'the failure (network during a call, not a web form)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'en-to-meaning'],
    sourceRefs: ['fd-authored', 'nep-collocations', 'nep-speaking-functions'],
    researchRefs: ['lsrules-chunks', 'lsrules-loop', 'vn-assembly', 'sla-l1-transfer', 'env-30min'],
  },
  {
    id: 'c02',
    track: 'c',
    title: 'Outcomes and small victories',
    titleVi: 'Cụm về kết quả và thành công nhỏ',
    cefr: 'a2',
    task: 'Report how something turned out — especially after difficulty',
    context: 'Telling a teammate the result after trying something hard.',
    outcome: 'The listener knows the outcome and the story shape behind it.',
    input: {
      title: 'C02 · Outcomes and small victories',
      text: [
        'Sara: Did you fix the login page?',
        'Minh: I ended up rewriting the whole form. It was faster than patching it.',
        'Sara: Smart. Did the tests pass?',
        'Minh: I was able to fix the main bug. One test still fails.',
        'Sara: Progress is progress.',
        'Minh: It turns out the problem was the date format, not the password.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Kể kết quả sau khi vật lộn: ended up, was able to, turns out.',
    },
    explanationVi:
      '"I ended up + V-ing" = cuối cùng lại làm X (khác dự định). "I was able to + V" = đã làm được (sau khó khăn — mạnh hơn "I could"). "It turns out + clause" = hóa ra sự thật là...',
    targets: [
      {
        id: 'fd01.c02.t1',
        chunk: 'I ended up rewriting the whole form',
        cueVi: 'cuối cùng tôi đã viết lại toàn bộ form',
        sourceSentence: 'Minh: I ended up rewriting the whole form. It was faster than patching it.',
        productionPattern: 'I ended up <verb-ing> <object>',
        transferContext: 'you planned to buy a book but ended up borrowing it',
      },
      {
        id: 'fd01.c02.t2',
        chunk: 'I was able to fix the main bug',
        cueVi: 'tôi đã sửa được con bug chính',
        sourceSentence: 'Minh: I was able to fix the main bug. One test still fails.',
        productionPattern: 'I was able to <verb> <object>',
        transferContext: 'you were able to catch an earlier train after all',
      },
      {
        id: 'fd01.c02.t3',
        chunk: 'It turns out',
        cueVi: 'hóa ra ~',
        sourceSentence: 'Minh: It turns out the problem was the date format, not the password.',
        productionPattern: 'It turns out <the real cause/situation>',
        transferContext: 'the meeting was not cancelled — it moved to another room',
      },
      {
        id: 'fd01.c02.t4',
        chunk: 'One test still fails',
        cueVi: 'một test vẫn còn fail',
        sourceSentence: 'Minh: I was able to fix the main bug. One test still fails.',
        productionPattern: '<X> still <fails / remains / is missing>',
        transferContext: "one item on your checklist is still open at day's end",
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt:
        'You spent the morning learning a new tool. Report to a friend what you ended up doing and what you were able to finish.',
      promptVi: 'Sáng nay bạn mày mò công cụ mới. Kể cho bạn bè: cuối cùng bạn đã làm gì + làm được gì.',
      changesDimension: 'domain (learning a tool, not fixing code)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-collocations', 'nep-grammar-errors'],
    researchRefs: ['lsrules-chunks', 'lsrules-transfer', 'vn-assembly', 'sla-l1-transfer', 'lsrules-loop'],
  },
  {
    id: 'c03',
    track: 'c',
    title: 'Hedging and depending',
    titleVi: 'Cụm nói điều kiện và không chắc chắn',
    cefr: 'a2',
    task: 'Answer without over-committing — say what things depend on',
    context: 'Questions where a flat yes/no would be wrong: cost, timing, feasibility.',
    outcome: 'You give an honest conditional answer instead of a false certainty.',
    input: {
      title: 'C03 · Hedging and depending',
      text: [
        'Sara: Will the fix take long?',
        'Minh: It depends on the cause. If it is the cache, ten minutes.',
        'Sara: Do you know what it is yet?',
        'Minh: It looks like a cache problem, but I am not sure if that is everything.',
        'Sara: Okay. Keep me posted.',
        'Minh: As far as I know, the server is fine — this is on our side.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Trả lời có điều kiện: it depends on, it looks like, as far as I know, not sure if.',
    },
    explanationVi:
      '"It depends on + X" = còn tùy vào X. "It looks like + clause" = có vẻ như (dựa trên bằng chứng). "As far as I know" = theo tôi biết (giới hạn thông tin của mình). "I am not sure if + clause" = chưa chắc liệu.',
    targets: [
      {
        id: 'fd01.c03.t1',
        chunk: 'It depends on the cause',
        cueVi: 'nó còn tùy vào nguyên nhân',
        sourceSentence: 'Minh: It depends on the cause. If it is the cache, ten minutes.',
        productionPattern: 'It depends on <the cause / the price / the weather>.',
        transferContext: 'asked how long a trip takes — depends on traffic',
      },
      {
        id: 'fd01.c03.t2',
        chunk: 'It looks like a cache problem',
        cueVi: 'có vẻ là vấn đề cache',
        sourceSentence: 'Minh: It looks like a cache problem, but I am not sure if that is everything.',
        productionPattern: 'It looks like <a problem / rain / it works>.',
        transferContext: 'judging weather from the window before going out',
      },
      {
        id: 'fd01.c03.t3',
        chunk: 'I am not sure if',
        cueVi: 'tôi không chắc liệu ~',
        sourceSentence: 'Minh: It looks like a cache problem, but I am not sure if that is everything.',
        productionPattern: 'I am not sure if <clause>',
        transferContext: 'a friend asks if the shop is still open — uncertain answer',
      },
      {
        id: 'fd01.c03.t4',
        chunk: 'As far as I know',
        cueVi: 'theo tôi được biết',
        sourceSentence: 'Minh: As far as I know, the server is fine — this is on our side.',
        productionPattern: 'As far as I know, <clause>',
        transferContext: 'answering a question about a policy you partly remember',
      },
      {
        id: 'fd01.c03.t5',
        chunk: 'Keep me posted',
        cueVi: 'cập nhật cho tôi nhé',
        sourceSentence: 'Sara: Okay. Keep me posted.',
        productionPattern: 'Keep me posted. / Keep me <posted / updated>.',
        transferContext: 'waiting on a delivery status — ask for updates',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt:
        'Your manager asks when a task will finish. Answer honestly: what it depends on and what you know so far.',
      promptVi: 'Sếp hỏi task xong khi nào. Trả lời thật: phụ thuộc vào gì + bạn biết gì đến giờ.',
      changesDimension: 'the unknown (timeline estimate, not a technical cause)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'en-to-meaning'],
    sourceRefs: ['fd-authored', 'nep-collocations', 'nep-speaking-functions'],
    researchRefs: ['lsrules-chunks', 'lsrules-loop', 'lsrules-retrieval', 'vn-assembly', 'a0-evidence'],
  },
  {
    id: 'c04',
    track: 'c',
    title: 'Naming the problem',
    titleVi: 'Cụm chỉ ra vấn đề',
    cefr: 'a2',
    task: 'Point at the cause of trouble precisely, without blaming',
    context: 'Explaining to support or a teammate where the failure actually is.',
    outcome: 'The listener knows the exact failing part, not just "it is broken".',
    input: {
      title: 'C04 · Naming the problem',
      text: [
        'Support: What seems to be the issue?',
        'Minh: The problem is that the app crashes on startup.',
        'Support: When did it begin?',
        'Minh: Since the update. I think the issue is the new login screen.',
        'Support: Possible. Anything else?',
        'Minh: It seems like it also freezes when I upload photos.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Chỉ đúng chỗ hỏng: the problem is that…, the issue is…, it seems like…',
    },
    explanationVi:
      '"The problem is that + clause" = vấn đề là... (chẩn đoán rõ). "I think the issue is + X" = đồn đoán nguyên nhân. "It seems like + clause" = có vẻ (cẩn trọng hơn). Tránh "have problem" không mạo từ — là "a problem" / "the problem".',
    targets: [
      {
        id: 'fd01.c04.t1',
        chunk: 'The problem is that the app crashes',
        cueVi: 'vấn đề là app bị crash',
        sourceSentence: 'Minh: The problem is that the app crashes on startup.',
        productionPattern: 'The problem is that <clause describing the failure>',
        transferContext: 'telling a mechanic the car makes noise when braking',
      },
      {
        id: 'fd01.c04.t2',
        chunk: 'on startup',
        cueVi: 'khi khởi động',
        sourceSentence: 'Minh: The problem is that the app crashes on startup.',
        productionPattern: 'on <startup / launch / first open>',
        transferContext: 'a laptop freezes on startup, not later',
      },
      {
        id: 'fd01.c04.t3',
        chunk: 'I think the issue is',
        cueVi: 'tôi nghĩ vấn đề là ~',
        sourceSentence: 'Minh: Since the update. I think the issue is the new login screen.',
        productionPattern: 'I think the issue is <the cause>',
        transferContext: 'guessing why a team process is slow — the issue is approvals',
      },
      {
        id: 'fd01.c04.t4',
        chunk: 'It seems like',
        cueVi: 'có vẻ như ~',
        sourceSentence: 'Minh: It seems like it also freezes when I upload photos.',
        productionPattern: 'It seems like <clause>',
        transferContext: 'a colleague seems unhappy — checking gently',
      },
      {
        id: 'fd01.c04.t5',
        chunk: 'What seems to be the issue',
        cueVi: 'có vẻ vấn đề là gì',
        sourceSentence: 'Support: What seems to be the issue?',
        productionPattern: 'What seems to be the <issue / problem>?',
        transferContext: 'you are the helper now — open a support call with this',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt: 'Your order arrives with a wrong item. Write to support: name the exact problem and when you noticed.',
      promptVi: 'Đơn hàng giao sai món. Viết cho support: nêu đúng vấn đề + khi nào bạn phát hiện.',
      changesDimension: 'domain (delivery order, not software) and modality (written report)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'context-to-production'],
    sourceRefs: ['fd-authored', 'nep-collocations', 'nep-grammar-errors', 'nep-painpoints'],
    researchRefs: ['lsrules-chunks', 'vn-grammar-errors', 'lsrules-loop', 'lake-painpoints', 'vn-assembly'],
  },
  {
    id: 'c05',
    track: 'c',
    title: 'Asking for explanation',
    titleVi: 'Cụm nhờ giải thích',
    cefr: 'a2',
    task: 'Ask someone to explain something step by step',
    context: 'A process, a code review comment, a form requirement is unclear.',
    outcome: 'You get an explanation you can follow — and can ask a pointed follow-up.',
    input: {
      title: 'C05 · Asking for explanation',
      text: [
        'Minh: Could you explain the review process? I am new here.',
        'Sara: Sure. First you open a PR, then two people review it.',
        'Minh: Do you know if design reviews it too?',
        'Sara: Only for UI changes. Is there a way to skip it for text fixes?',
        'Minh: Actually, for small text fixes it is automatic.',
        'Minh: Any idea why my build failed this morning?',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Nhờ giải thích quy trình + hỏi follow-up cụ thể.',
    },
    explanationVi:
      '"Could you explain + X?" lịch sự. "Do you know if + clause?" hỏi thông tin dạng yes/no (chú ý trật tự: "if design reviews", không đảo). "Is there a way to + V?" = có cách nào để... "Any idea why + clause?" = hỏi nguyên nhân thân mật.',
    targets: [
      {
        id: 'fd01.c05.t1',
        chunk: 'Could you explain the review process',
        cueVi: 'bạn có thể giải thích quy trình review không',
        sourceSentence: 'Minh: Could you explain the review process? I am new here.',
        productionPattern: 'Could you explain <the process / this error / how X works>?',
        transferContext: 'asking a bank clerk to explain a fee',
      },
      {
        id: 'fd01.c05.t2',
        chunk: 'Do you know if',
        cueVi: 'bạn có biết liệu ~ không',
        sourceSentence: 'Minh: Do you know if design reviews it too?',
        productionPattern: 'Do you know if <clause>?',
        transferContext: 'asking a receptionist if the gym is open on Sundays',
      },
      {
        id: 'fd01.c05.t3',
        chunk: 'Is there a way to',
        cueVi: 'có cách nào để ~ không',
        sourceSentence: 'Sara: Only for UI changes. Is there a way to skip it for text fixes?',
        productionPattern: 'Is there a way to <verb>?',
        transferContext: 'asking support if there is a way to change your seat online',
      },
      {
        id: 'fd01.c05.t4',
        chunk: 'Any idea why',
        cueVi: 'có ý kiến/ý niệm nào về lý do ~ không',
        sourceSentence: 'Minh: Any idea why my build failed this morning?',
        productionPattern: 'Any idea why <clause>?',
        transferContext: 'asking why the train is delayed, informally',
      },
      {
        id: 'fd01.c05.t5',
        chunk: 'I am new here',
        cueVi: 'tôi mới ở đây / mới tham gia',
        sourceSentence: 'Minh: Could you explain the review process? I am new here.',
        productionPattern: 'I am new <here / to this / to the team>.',
        transferContext: 'first day at a gym — ask how the lockers work',
      },
    ],
    supportLadder: ['context', 'lexical', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt:
        'A landlord explains the utility bill badly. Ask them to explain the calculation and ask a pointed follow-up.',
      promptVi: 'Chủ nhà giải thích tiền điện nước khó hiểu. Nhờ giải thích cách tính + hỏi thêm một câu cụ thể.',
      changesDimension: 'domain (housing paperwork, not engineering process)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'en-to-meaning'],
    sourceRefs: ['fd-authored', 'nep-speaking-functions', 'nep-collocations'],
    researchRefs: ['lsrules-chunks', 'lsrules-loop', 'lsrules-retrieval', 'vn-assembly', 'lake-functions'],
  },
  {
    id: 'c06',
    track: 'c',
    title: 'Buying time and checking',
    titleVi: 'Cụm câu giờ và kiểm chứng',
    cefr: 'a1',
    task: 'Hold a conversation slot while you think, look something up, or confirm',
    context: 'Live conversation does not wait while you think — you need fillers that do real work.',
    outcome: 'The exchange continues while you verify instead of stalling into silence.',
    input: {
      title: 'C06 · Buying time and checking',
      text: [
        'Sara: Can you send the file today?',
        'Minh: Let me see… I have it on my laptop. Let me check the version.',
        'Sara: Take your time.',
        'Minh: Okay, it is ready. Give me a second to upload it.',
        'Sara: No rush.',
        'Minh: Done. If I am not wrong, this is the final version.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Giữ nhịp hội thoại: let me see/check, give me a second, if I am not wrong.',
    },
    explanationVi:
      'Khoảng lặng làm người nghe lo. "Let me see/check" = để tôi xem/kiểm tra (mua vài giây). "Give me a second" = chờ tôi một chút. "If I am not wrong" = nếu tôi không nhầm (đánh dấu không chắc).',
    targets: [
      {
        id: 'fd01.c06.t1',
        chunk: 'Let me see',
        cueVi: 'để tôi xem / để tôi nghĩ đã',
        sourceSentence: 'Minh: Let me see… I have it on my laptop. Let me check the version.',
        productionPattern: 'Let me see. / Let me <check / think>.',
        transferContext: 'a customer asks if an item is in stock — check the shelf',
      },
      {
        id: 'fd01.c06.t2',
        chunk: 'Let me check the version',
        cueVi: 'để tôi kiểm tra phiên bản',
        sourceSentence: 'Minh: Let me see… I have it on my laptop. Let me check the version.',
        productionPattern: 'Let me check <the version / the date / my calendar>.',
        transferContext: 'checking your calendar before agreeing to a meeting time',
      },
      {
        id: 'fd01.c06.t3',
        chunk: 'Give me a second',
        cueVi: 'cho tôi một giây / một chút',
        sourceSentence: 'Minh: Okay, it is ready. Give me a second to upload it.',
        productionPattern: 'Give me a second to <verb>.',
        transferContext: 'at a counter, finding your card while the queue waits',
      },
      {
        id: 'fd01.c06.t4',
        chunk: 'If I am not wrong',
        cueVi: 'nếu tôi không nhầm',
        sourceSentence: 'Minh: Done. If I am not wrong, this is the final version.',
        productionPattern: 'If I am not wrong, <clause>.',
        transferContext: "recalling a colleague's name you heard once",
      },
      {
        id: 'fd01.c06.t5',
        chunk: 'Take your time',
        cueVi: 'cứ từ từ / không vội',
        sourceSentence: 'Sara: Take your time.',
        productionPattern: 'Take your time. / No rush.',
        transferContext: 'a nervous teammate rehearses a demo — reassure them',
      },
    ],
    supportLadder: ['context', 'gloss-vi', 'partial-model', 'full-answer'],
    transferTask: {
      prompt:
        'A client asks for a number you do not have memorized. Buy time, check, and report it with appropriate confidence.',
      promptVi: 'Khách hàng hỏi một con số bạn không nhớ. Câu giờ, kiểm tra, rồi báo kèm mức chắc chắn.',
      changesDimension: 'modality (voice call, not desk chat) and content (a number)',
    },
    reviewVariants: ['meaning-to-en', 'context-to-phrase', 'audio-to-meaning'],
    sourceRefs: ['fd-authored', 'nep-collocations', 'nep-painpoints'],
    researchRefs: ['lsrules-chunks', 'vn-assembly', 'lake-painpoints', 'lsrules-loop', 'env-30min'],
  },
];
