/*
 * Capability ontology (Part 3) — what learners can DO.
 * ids are stable; every LessonSpec.capabilities resolves here.
 */
export const CAPABILITIES: Record<string, { name: string; strand: string; fns?: string[] }> = {
  /* interaction */
  'greet-leave': { name: 'Greet and take leave', strand: 'interaction', fns: ['fn.01'] },
  'introduce-self': { name: 'Introduce yourself and others', strand: 'interaction', fns: ['fn.01', 'fn.02'] },
  'ask-personal-info': { name: 'Ask for names, origin, occupation', strand: 'interaction', fns: ['fn.02', 'fn.03'] },
  'clarify-meaning': { name: 'Ask for clarification', strand: 'interaction', fns: ['fn.03', 'fn.06'] },
  'ask-repetition': { name: 'Ask someone to repeat or slow down', strand: 'interaction', fns: ['fn.03', 'fn.06'] },
  'request-help': { name: 'Make polite requests', strand: 'interaction', fns: ['fn.06'] },
  'express-thanks': { name: 'Thank and respond to thanks', strand: 'interaction', fns: ['fn.01'] },
  apologize: { name: 'Apologize briefly', strand: 'interaction' },
  'handle-emergency': { name: 'Handle simple emergencies', strand: 'interaction', fns: ['fn.06'] },
  'small-talk': { name: 'Sustain light small talk', strand: 'interaction', fns: ['fn.01'] },
  /* everyday */
  'describe-routine': { name: 'Describe routines and habits', strand: 'everyday', fns: ['fn.07'] },
  'make-plans': { name: 'Make and discuss plans', strand: 'everyday', fns: ['fn.07'] },
  'narrate-past': { name: 'Talk about past events', strand: 'everyday', fns: ['fn.07'] },
  'express-opinion': { name: 'Give opinions and soft disagreement', strand: 'everyday', fns: ['fn.08'] },
  'ask-price': { name: 'Ask prices and shop basics', strand: 'everyday', fns: ['fn.03', 'fn.04'] },
  'order-food': { name: 'Order food and drinks', strand: 'everyday', fns: ['fn.04'] },
  'ask-directions': { name: 'Ask and follow directions', strand: 'everyday', fns: ['fn.05'] },
  'describe-problem': { name: 'Describe a problem and ask for a fix', strand: 'everyday', fns: ['fn.06'] },
  'schedule-appointment': { name: 'Schedule times and appointments', strand: 'everyday', fns: ['fn.07'] },
  'phone-basics': { name: 'Handle basic phone calls', strand: 'everyday', fns: ['fn.03', 'fn.06'] },
  'see-doctor': { name: 'Explain symptoms simply', strand: 'everyday', fns: ['fn.03', 'fn.06'] },
  'book-travel': { name: 'Book and discuss travel', strand: 'everyday', fns: ['fn.04', 'fn.07'] },
  'hotel-checkin': { name: 'Check in and request services', strand: 'everyday', fns: ['fn.04'] },
  'shop-return': { name: 'Return or exchange items', strand: 'everyday', fns: ['fn.04'] },
  'pay-bills': { name: 'Discuss money and payments', strand: 'everyday', fns: ['fn.04'] },
  'invite-respond': { name: 'Invite, accept, and decline', strand: 'everyday', fns: ['fn.01', 'fn.07'] },
  'compare-things': { name: 'Compare options simply', strand: 'everyday', fns: ['fn.08'] },
  'express-preference': { name: 'State preferences', strand: 'everyday', fns: ['fn.08'] },
  /* chunks */
  'hedge-statement': { name: 'Hedge and soften statements', strand: 'fluency', fns: ['fn.08', 'fn.10'] },
  'buy-time': { name: 'Buy thinking time naturally', strand: 'fluency', fns: ['fn.10'] },
  'agree-politely': { name: 'Agree and support', strand: 'fluency', fns: ['fn.10'] },
  'disagree-politely': { name: 'Disagree without friction', strand: 'fluency', fns: ['fn.10'] },
  'check-understanding': { name: 'Confirm you understood', strand: 'fluency', fns: ['fn.10'] },
  'change-topic': { name: 'Shift and return topics', strand: 'fluency', fns: ['fn.10'] },
  'close-conversation': { name: 'Close exchanges gracefully', strand: 'fluency', fns: ['fn.01', 'fn.10'] },
  'give-reason': { name: 'Give reasons and examples', strand: 'fluency', fns: ['fn.09'] },
  'tell-story': { name: 'Sequence a short story', strand: 'fluency', fns: ['fn.09'] },
  'make-offer': { name: 'Offer and accept help', strand: 'fluency', fns: ['fn.06', 'fn.10'] },
  'ask-favor': { name: 'Ask favors gently', strand: 'fluency', fns: ['fn.06'] },
  /* listening */
  'decode-boundaries': { name: 'Hear word boundaries', strand: 'listening' },
  'decode-weak-forms': { name: 'Hear weak forms of function words', strand: 'listening' },
  'decode-reductions': { name: 'Hear common reductions', strand: 'listening' },
  'decode-linking': { name: 'Hear consonant-vowel linking', strand: 'listening' },
  'decode-final-consonants': { name: 'Hear word-final consonants', strand: 'listening' },
  'decode-clusters': { name: 'Hear consonant clusters', strand: 'listening' },
  'decode-numbers': { name: 'Catch numbers, prices, times', strand: 'listening' },
  'decode-names': { name: 'Catch names and spelling', strand: 'listening' },
  'extract-detail': { name: 'Extract specific details', strand: 'listening' },
  'track-signposts': { name: 'Track discourse signposts', strand: 'listening' },
  'catch-gist': { name: 'Catch gist without every word', strand: 'listening' },
  'infer-tone': { name: 'Infer speaker tone', strand: 'listening' },
  'hear-fast-questions': { name: 'Decode fast question forms', strand: 'listening' },
  /* pronunciation */
  'perceive-final-consonants': { name: 'Perceive final consonants', strand: 'pronunciation' },
  'perceive-clusters': { name: 'Perceive consonant clusters', strand: 'pronunciation' },
  'perceive-th': { name: 'Perceive /θ ð/ vs /s t d z/', strand: 'pronunciation' },
  'perceive-tense-lax': { name: 'Perceive tense vs lax vowels', strand: 'pronunciation' },
  'perceive-rl': { name: 'Perceive /r/ vs /l/', strand: 'pronunciation' },
  'perceive-vb': { name: 'Perceive /v/ vs /b/', strand: 'pronunciation' },
  'perceive-ed-endings': { name: 'Perceive -ed endings', strand: 'pronunciation' },
  'place-word-stress': { name: 'Place word and sentence stress', strand: 'pronunciation' },
  'perceive-intonation': { name: 'Perceive question intonation', strand: 'pronunciation' },
  /* grammar-as-support */
  'use-be': { name: 'Use am/is/are correctly', strand: 'grammar' },
  'ask-yesno': { name: 'Form yes/no and wh- questions', strand: 'grammar' },
  'use-third-person-s': { name: 'Mark third-person -s', strand: 'grammar' },
  'use-past': { name: 'Use past forms for events', strand: 'grammar' },
  'use-going-to': { name: 'Use going to for plans', strand: 'grammar' },
  'use-continuous': { name: 'Use continuous for now', strand: 'grammar' },
  'use-modals': { name: 'Use can/could/should/have to', strand: 'grammar' },
  'use-articles': { name: 'Choose a/an/the', strand: 'grammar' },
  'use-prepositions': { name: 'Choose in/on/at/for', strand: 'grammar' },
  'use-plurals': { name: 'Mark plurals', strand: 'grammar' },
  'use-comparatives': { name: 'Use comparative forms', strand: 'grammar' },
  /* developer */
  'status-update': { name: 'Give a work status update', strand: 'developer' },
  'clarify-requirements': { name: 'Clarify requirements', strand: 'developer' },
  'report-bug': { name: 'Report a bug', strand: 'developer' },
  'reproduce-steps': { name: 'Write reproduction steps', strand: 'developer' },
  'ask-help': { name: 'Ask a colleague for help', strand: 'developer' },
  'explain-implementation': { name: 'Explain an implementation choice', strand: 'developer' },
  'review-code': { name: 'Give code review feedback', strand: 'developer' },
  'discuss-pr': { name: 'Discuss a pull request', strand: 'developer' },
  'notify-deploy': { name: 'Announce and track deployments', strand: 'developer' },
  'report-incident': { name: 'Report and update incidents', strand: 'developer' },
  'disagree-technical': { name: 'Disagree on technical direction', strand: 'developer' },
  'estimate-uncertainty': { name: 'Estimate with honest uncertainty', strand: 'developer' },
  'handoff-work': { name: 'Hand off work to a teammate', strand: 'developer' },
  'ask-documentation': { name: 'Ask for and write documentation', strand: 'developer' },
  'participate-meeting': { name: 'Participate in meetings', strand: 'developer' },
  'schedule-meeting': { name: 'Schedule and move meetings', strand: 'developer' },
  'message-async': { name: 'Write clear async messages', strand: 'developer' },
  'demo-feature': { name: 'Demo a feature', strand: 'developer' },
  'escalate-issue': { name: 'Escalate a blocked issue', strand: 'developer' },
  'postmortem-writeup': { name: 'Summarize an incident postmortem', strand: 'developer' },
};
