/*
 * Source manifest (Part 1) — every corpus family inspected, classified
 * fail-closed. Unknown rights never become reusable: anything not listed
 * here cannot be cited by a lesson spec at all.
 */
import type { SourceEntry } from './types.ts';

export const SOURCE_MANIFEST_VERSION = '2026-10-03';

const DERIVE = ['derive', 'link', 'cite', 'index', 'extract-facts'];
const NO_EMBED = ['no verbatim embedding', 'no prose copying', 'no learner-facing quotes'];
const REFERENCE = ['cite', 'inform-design', 'reference'];

export const SOURCE_MANIFEST: Record<string, SourceEntry> = {
  /* ---------- In-repo ---------- */
  'fd-authored': {
    id: 'fd-authored',
    name: 'Original FlashDay-authored lesson text',
    type: 'repo-artifact',
    location: 'this repository (src/lib/fd-content, src/lib/fd-content-v2)',
    language: 'en',
    domain: 'all',
    klass: 'REUSABLE_CONTENT',
    allowedOps: ['embed', 'derive', 'modify'],
    forbiddenOps: [],
    role: 'content-seed',
    confidence: 1,
    coverage: 'all authored lesson prose, dialogues, VN support',
    limitations: 'Authored for this pack; must still pass pedagogy + leakage validators.',
  },
  'fd01-pack': {
    id: 'fd01-pack',
    name: 'flashday-foundation-v1 shipped pack',
    type: 'repo-artifact',
    location: 'src/lib/fd-content/',
    language: 'en',
    domain: 'A0-A2 survival/everyday/chunks/listening/developer',
    klass: 'REUSABLE_CONTENT',
    allowedOps: ['embed', 'recycle', 'cite'],
    forbiddenOps: ['rewrite shipped learner IDs'],
    role: 'content-seed',
    confidence: 1,
    coverage: '30 lessons / 145 chunks — recycling source for V2',
    limitations: 'Frozen learner-facing ids; new content references it via recycling edges.',
  },

  /* ---------- NEP/01 research docs ---------- */
  'lsrules-docs': {
    id: 'lsrules-docs',
    name: 'Learning science product rules + A0 research dossier + content style guide',
    type: 'markdown-corpus',
    location: 'NEP/01_LEARNING_SCIENCE_AND_RESEARCH/learning_science_rules/',
    language: 'en',
    domain: 'learning-science methodology',
    klass: 'REFERENCE_ONLY',
    allowedOps: REFERENCE,
    forbiddenOps: NO_EMBED,
    role: 'methodology',
    confidence: 0.9,
    coverage: 'loop, retrieval, transfer, spacing, feedback, HVPT, chunks rules',
    limitations: 'Meta-analytic summaries; informs design, never learner text.',
  },
  'deep-research-reports': {
    id: 'deep-research-reports',
    name: 'NEP deep research reports (IELTS lexical, developer sources)',
    type: 'markdown-corpus',
    location: 'NEP/01_LEARNING_SCIENCE_AND_RESEARCH/deep_research_reports/',
    language: 'en',
    domain: 'research',
    klass: 'REFERENCE_ONLY',
    allowedOps: REFERENCE,
    forbiddenOps: NO_EMBED,
    role: 'methodology',
    confidence: 0.7,
    coverage: 'developer-English source inventory; IELTS lexical (excluded scope)',
    limitations: 'Variable provenance; treat as leads, not authority.',
  },
  'vn-linguistics': {
    id: 'vn-linguistics',
    name: 'BUILDING_FOR_VIETNAMESE_LEARNERS + LEARNER_AND_ENVIRONMENT',
    type: 'markdown-corpus',
    location: 'NEP/01_LEARNING_SCIENCE_AND_RESEARCH/vietnamese_learner_linguistics/',
    language: 'en',
    domain: 'VN learner linguistics + constraints',
    klass: 'REFERENCE_ONLY',
    allowedOps: REFERENCE,
    forbiddenOps: NO_EMBED,
    role: 'methodology',
    confidence: 0.9,
    coverage: 'L1 transfer classes, phonotactics, 30min phone-first budget, assembly bottleneck',
    limitations: 'Secondary synthesis; underlying citations checked where critical.',
  },
  'sla-papers': {
    id: 'sla-papers',
    name: 'SLA research papers (9, PDF+TXT): L1 transfer, shadowing, lexical threshold, gloss, L2TV, final consonants, extensive reading',
    type: 'pdf-corpus',
    location: 'NEP/01_LEARNING_SCIENCE_AND_RESEARCH/sla_research_papers/',
    language: 'en',
    domain: 'second-language acquisition research',
    klass: 'REFERENCE_ONLY',
    allowedOps: ['cite', 'inform-design'],
    forbiddenOps: [...NO_EMBED, 'republish PDFs'],
    role: 'methodology',
    confidence: 0.85,
    coverage: 'EJ/ED/W paper set cited by research manifest',
    limitations: 'Individual studies; effect sizes contextualized, not doctrine.',
  },
  'nep-benchmark': {
    id: 'nep-benchmark',
    name: 'NEP global benchmark & innovation study',
    type: 'markdown-corpus',
    location: 'NEP/01_LEARNING_SCIENCE_AND_RESEARCH/NEP_GLOBAL_BENCHMARK_AND_INNOVATION_STUDY.md',
    language: 'en',
    domain: 'product benchmarking',
    klass: 'REFERENCE_ONLY',
    allowedOps: REFERENCE,
    forbiddenOps: NO_EMBED,
    role: 'methodology',
    confidence: 0.6,
    coverage: 'competitive feature survey',
    limitations: 'Marketing-adjacent signals; never pedagogy authority.',
  },

  /* ---------- NEP/02 curriculum frameworks ---------- */
  'nep-phonetic-db': {
    id: 'nep-phonetic-db',
    name: 'vietnamese_english_phonetic_contrast.json — 44-phoneme VN-EN contrast DB',
    type: 'json',
    location: 'NEP/02_CURRICULUM_AND_FRAMEWORKS/vietnamese_english_phonetic_contrast.json',
    language: 'mixed',
    domain: 'pronunciation/listening contrasts',
    klass: 'LINK_AND_DERIVE',
    allowedOps: DERIVE,
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.9,
    coverage: 'vowel_pairs, consonant_pairs, minimal-pair confusions, VN error sites',
    limitations: 'Segmental only; suprasegmentals need other sources.',
  },
  'oxford-5000': {
    id: 'oxford-5000',
    name: 'oxford_5000_full.json — CEFR-graded headwords with IPA',
    type: 'json',
    location: 'NEP/02_CURRICULUM_AND_FRAMEWORKS/vocab_databases/oxford_5000_full.json',
    language: 'en',
    domain: 'core vocabulary',
    klass: 'LINK_AND_DERIVE',
    allowedOps: DERIVE,
    forbiddenOps: ['republish wordlist verbatim'],
    role: 'evidence',
    confidence: 0.95,
    coverage: '5944 headwords, CEFR levels, IPA — difficulty prior + vocab inventory',
    limitations: 'Word-level only; no chunk/phrasal entries.',
  },
  'stage-0-curriculum': {
    id: 'stage-0-curriculum',
    name: 'stage-0-curriculum.json — unit schema precedent',
    type: 'json',
    location: 'NEP/02_CURRICULUM_AND_FRAMEWORKS/stage_0_curriculum/',
    language: 'en',
    domain: 'curriculum schema',
    klass: 'LINK_AND_DERIVE',
    allowedOps: DERIVE,
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.8,
    coverage: 'canDo + cloze/sentence-builder activity precedent',
    limitations: 'Prototype schema; informs structure, not content.',
  },
  'day28-contract': {
    id: 'day28-contract',
    name: '28-day speaking journey contract (P3→P0 support scale)',
    type: 'markdown-corpus',
    location: 'NEP/02_CURRICULUM_AND_FRAMEWORKS/28-day-speaking-journey-contract.md',
    language: 'en',
    domain: 'support fading methodology',
    klass: 'REFERENCE_ONLY',
    allowedOps: REFERENCE,
    forbiddenOps: NO_EMBED,
    role: 'methodology',
    confidence: 0.85,
    coverage: 'support-fade scale per lesson',
    limitations: 'Speaking-course framing; adapted not adopted.',
  },
  'danh-muc-progression': {
    id: 'danh-muc-progression',
    name: 'DANH_MUC_PROGRESSION curriculum outline',
    type: 'markdown-corpus',
    location: 'NEP/02_CURRICULUM_AND_FRAMEWORKS/DANH_MUC_PROGRESSION.md',
    language: 'vi',
    domain: 'curriculum outline',
    klass: 'REFERENCE_ONLY',
    allowedOps: REFERENCE,
    forbiddenOps: NO_EMBED,
    role: 'methodology',
    confidence: 0.6,
    coverage: 'VN-oriented progression sketch',
    limitations: 'Draft outline; coverage signal only.',
  },
  'classic-textbooks': {
    id: 'classic-textbooks',
    name: 'Classic textbook PDFs (Ship or Sheep, Business Result, Cambridge, Pearson GSE kit…)',
    type: 'pdf-corpus',
    location: 'NEP/02_CURRICULUM_AND_FRAMEWORKS/classic_textbooks_pdfs/',
    language: 'en',
    domain: 'commercial textbooks',
    klass: 'REJECTED',
    allowedOps: [],
    forbiddenOps: ['ingest', 'embed', 'derive', 'link'],
    role: 'denylist',
    confidence: 0,
    coverage: 'none — commercial textbook mirrors',
    limitations: 'Copyright-restricted; listed to fail closed.',
  },

  /* ---------- NEP/03 community corpus ---------- */
  'community-guides': {
    id: 'community-guides',
    name: 'Vietnamese community learning guides (markdown corpus)',
    type: 'markdown-corpus',
    location: 'NEP/03_COMMUNITY_CORPUS_AND_DATASETS/learning_markdown_guides/',
    language: 'vi',
    domain: 'learner topic expectations',
    klass: 'REFERENCE_ONLY',
    allowedOps: ['cite', 'needs-analysis', 'inform-topics'],
    forbiddenOps: NO_EMBED,
    role: 'needs-analysis',
    confidence: 0.6,
    coverage: 'topics VN learners search/discuss; exam-heavy skew',
    limitations: 'UGC quality varies; signal not syllabus.',
  },
  'connected-speech-notes': {
    id: 'connected-speech-notes',
    name: 'Connected speech / phonology / IPA notes (community-compiled txt)',
    type: 'markdown-corpus',
    location: 'NEP/03_COMMUNITY_CORPUS_AND_DATASETS/*.txt',
    language: 'en',
    domain: 'phonology reference',
    klass: 'LINK_AND_DERIVE',
    allowedOps: ['derive', 'cite', 'index'],
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.7,
    coverage: 'linking/elision/weak-form inventories; IPA charts',
    limitations: 'Unattributed compilations; facts cross-checked against phonetic DB.',
  },
  'facebook-raw': {
    id: 'facebook-raw',
    name: 'Facebook raw learner posts dataset',
    type: 'dataset',
    location: 'NEP/03_COMMUNITY_CORPUS_AND_DATASETS/facebook_raw_dataset/',
    language: 'vi',
    domain: 'learner discourse',
    klass: 'REFERENCE_ONLY',
    allowedOps: ['needs-analysis', 'aggregate-counts'],
    forbiddenOps: [...NO_EMBED, 'quote individual posts'],
    role: 'needs-analysis',
    confidence: 0.5,
    coverage: 'raw painpoint source behind lakehouse fact_learner_painpoints',
    limitations: 'Personal posts; aggregate themes only, never quotes.',
  },
  'exam-prep': {
    id: 'exam-prep',
    name: 'IELTS/TOEIC collections + practice-test banks',
    type: 'markdown-corpus',
    location: 'NEP/03_.../ielts_toeic_master_collection/, practice_tests_and_exercise_banks/',
    language: 'en',
    domain: 'exam preparation',
    klass: 'REJECTED',
    allowedOps: [],
    forbiddenOps: ['ingest', 'embed', 'derive', 'link'],
    role: 'denylist',
    confidence: 0,
    coverage: 'none — commercial exam content',
    limitations: 'Copyright-restricted; V2 is not test prep.',
  },
  'scraped-centers': {
    id: 'scraped-centers',
    name: 'Scraped VN English-center materials, downloaded PDFs, playwright extracts',
    type: 'markdown-corpus',
    location: 'NEP/03_.../scraped_vn_english_centers/, downloaded_*, google_playwright_extracted/',
    language: 'vi',
    domain: 'mixed commercial/UGC',
    klass: 'REJECTED',
    allowedOps: [],
    forbiddenOps: ['ingest', 'embed', 'derive', 'link'],
    role: 'denylist',
    confidence: 0,
    coverage: 'none — unlicensed mirrors',
    limitations: 'Provenance unverifiable; denylist.',
  },

  /* ---------- NEP/05 lakehouse marts ---------- */
  'nep-speaking-functions': {
    id: 'nep-speaking-functions',
    name: 'dim_speaking_functions — A1-B1 speech-act inventory',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'en',
    domain: 'communicative functions',
    klass: 'LINK_AND_DERIVE',
    allowedOps: DERIVE,
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.85,
    coverage: '10 function groups with sample phrasing + situational context',
    limitations: 'Coarse groups; needs expansion for full coverage.',
  },
  'nep-collocations': {
    id: 'nep-collocations',
    name: 'fact_phrasal_collocations — chunk/collocation candidates with VN glosses',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'mixed',
    domain: 'formulaic language',
    klass: 'LINK_AND_DERIVE',
    allowedOps: DERIVE,
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.85,
    coverage: '10 curated collocation families',
    limitations: 'Small set; extended by authored chunk inventory.',
  },
  'nep-dialogues': {
    id: 'nep-dialogues',
    name: 'fact_functional_dialogues — scenario/key-expression inventory',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'en',
    domain: 'conversation situations',
    klass: 'LINK_AND_DERIVE',
    allowedOps: DERIVE,
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.8,
    coverage: '4 scripted scenario families',
    limitations: 'Informs scenario choices, not text.',
  },
  'nep-grammar-errors': {
    id: 'nep-grammar-errors',
    name: 'fact_grammar_mastery — VN common-mistake notes per topic',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'mixed',
    domain: 'grammar trouble spots',
    klass: 'LINK_AND_DERIVE',
    allowedOps: DERIVE,
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.85,
    coverage: '13 grammar topics with VN error notes + signal words',
    limitations: 'Support targets only — grammar is not the spine.',
  },
  'nep-painpoints': {
    id: 'nep-painpoints',
    name: 'fact_learner_painpoints — 10,515 community posts, categorized',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'vi',
    domain: 'needs analysis',
    klass: 'LINK_AND_DERIVE',
    allowedOps: ['derive', 'aggregate-counts', 'index'],
    forbiddenOps: ['quote individual posts', 'embed raw text'],
    role: 'needs-analysis',
    confidence: 0.8,
    coverage: 'skill distribution: General 3410, Grammar 1895, Speaking 1725, Listening 1387, Pronunciation 1247',
    limitations: 'Theme-level extraction only; no verbatim posts.',
  },
  'nep-phonemes': {
    id: 'nep-phonemes',
    name: 'dim_pronunciation_phonemes — 44 phonemes with VN minimal-pair confusions',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'en',
    domain: 'pronunciation',
    klass: 'LINK_AND_DERIVE',
    allowedOps: DERIVE,
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.85,
    coverage: 'phoneme inventory + confusion pairs',
    limitations: 'Pairs with nep-phonetic-db; not audio.',
  },
  'nep-microskills': {
    id: 'nep-microskills',
    name: 'dim_listening_microskills — 8 tiered microskills',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'en',
    domain: 'listening pedagogy',
    klass: 'LINK_AND_DERIVE',
    allowedOps: DERIVE,
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.85,
    coverage: 'bottom-up decoding (tier 1-2) vs top-down comprehension (tier 3-4)',
    limitations: 'Framework-level; lesson mapping is authored.',
  },
  'nep-cando': {
    id: 'nep-cando',
    name: 'fact_cefr_can_do + dim_cefr_levels — GSE-anchored descriptors',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'en',
    domain: 'level descriptors',
    klass: 'LINK_AND_DERIVE',
    allowedOps: ['derive', 'cite', 'index'],
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.85,
    coverage: '8 can-do anchors + 6 CEFR level descriptions',
    limitations: 'Descriptors inform labels, not teaching order.',
  },
  'nep-knowledge-chunks': {
    id: 'nep-knowledge-chunks',
    name: 'fact_knowledge_chunks — 6,137 crawled RAG chunks',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'en',
    domain: 'mixed web corpus',
    klass: 'REFERENCE_ONLY',
    allowedOps: ['cite', 'research-signal'],
    forbiddenOps: NO_EMBED,
    role: 'needs-analysis',
    confidence: 0.5,
    coverage: 'broad English-learning web corpus',
    limitations: 'Mixed provenance; research signal only, never content.',
  },
  'nep-crawled-corpus': {
    id: 'nep-crawled-corpus',
    name: 'fact_crawled_research_corpus — 34 crawled research pages',
    type: 'lakehouse-table',
    location: 'unified_english_lake.sqlite',
    language: 'en',
    domain: 'research pages',
    klass: 'REFERENCE_ONLY',
    allowedOps: REFERENCE,
    forbiddenOps: NO_EMBED,
    role: 'methodology',
    confidence: 0.6,
    coverage: 'lexical-count extracted pages',
    limitations: 'Small set; citation leads.',
  },

  /* ---------- External frameworks ---------- */
  'esl2-manifest': {
    id: 'esl2-manifest',
    name: 'ENGLISH_SOURCE_LIBRARY_V2 manifest + rights gate + core schema',
    type: 'framework',
    location: 'ENGLISH_SOURCE_LIBRARY_V2.zip (00_MANIFEST/)',
    language: 'en',
    domain: 'rights taxonomy + content schema',
    klass: 'REFERENCE_ONLY',
    allowedOps: REFERENCE,
    forbiddenOps: [],
    role: 'methodology',
    confidence: 0.9,
    coverage: 'rights classes, evidence levels, QA pipeline shape',
    limitations: 'Framework design only; its payloads were never ingested.',
  },
  'cefr-can-do': {
    id: 'cefr-can-do',
    name: 'CEFR Companion Volume descriptors (via lakehouse)',
    type: 'framework',
    location: 'coe.int; unified_english_lake.sqlite fact_cefr_can_do',
    language: 'en',
    domain: 'level descriptors',
    klass: 'REFERENCE_ONLY',
    allowedOps: ['cite', 'inform-levels'],
    forbiddenOps: NO_EMBED,
    role: 'evidence',
    confidence: 0.9,
    coverage: 'conservative level labels',
    limitations: 'Descriptors inform tasks, not order.',
  },
  'english-for-it': {
    id: 'english-for-it',
    name: 'Oxford English for IT + IT-English guides (corpus)',
    type: 'markdown-corpus',
    location: 'NEP/03_.../learning_markdown_guides/*CNTT*, IT guides',
    language: 'en',
    domain: 'developer/workplace English',
    klass: 'REFERENCE_ONLY',
    allowedOps: ['inform-topics', 'cite'],
    forbiddenOps: NO_EMBED,
    role: 'needs-analysis',
    confidence: 0.7,
    coverage: 'developer task scope: bugs, PRs, deploys, incidents',
    limitations: 'Commercial; informed scope, prose never embedded.',
  },

  /* ---------- Rejected ---------- */
  'pirate-mirrors': {
    id: 'pirate-mirrors',
    name: 'Pirated textbook mirrors (pdfcoffee/Scribd/Drive reposts)',
    type: 'pdf-corpus',
    location: 'download URLs inside corpus catalogs',
    language: 'en',
    domain: 'pirated materials',
    klass: 'REJECTED',
    allowedOps: [],
    forbiddenOps: ['ingest', 'embed', 'derive', 'link'],
    role: 'denylist',
    confidence: 0,
    coverage: 'none',
    limitations: 'Listed so the validator has an explicit denylist.',
  },

  /* ---------- VOA Learning English families (FD-VOA-CORPUS-01 §32) ----------
   * Rights are decided PER-ASSET by the corpus rights gate
   * (src/lib/voa-corpus/rights.ts). The klass below is the family-level
   * default: 'REUSABLE_CONTENT' entries may be embedded/derived ONLY
   * when the audit marks the specific asset VOA_ORIGINAL_PUBLIC_DOMAIN.
   * 'LINK_AND_DERIVE' families carry frequent third-party credits —
   * cite/derive only, never embed, unless an asset is individually
   * verified original. */
  'voa-lle-level1': {
    id: 'voa-lle-level1',
    name: "VOA Let's Learn English Level 1 (52 lessons)",
    type: 'dataset',
    location: 'learningenglish.voanews.com/p/5644.html → content-corpus/voa/',
    language: 'en',
    domain: 'beginner course — survival/everyday/listening',
    klass: 'REUSABLE_CONTENT',
    allowedOps: ['embed', 'derive', 'link', 'index', 'download', 'transcribe', 'segment'],
    forbiddenOps: ['reuse assets not audited VOA_ORIGINAL_PUBLIC_DOMAIN'],
    role: 'content-seed',
    confidence: 0.95,
    coverage: '52 lessons: conversation, speaking, pronunciation, writing, quiz, lesson plans',
    limitations: 'Per-asset audit required; attribution "Source: VOA Learning English" mandatory.',
  },
  'voa-lle-level2': {
    id: 'voa-lle-level2',
    name: "VOA Let's Learn English Level 2 (30 lessons)",
    type: 'dataset',
    location: 'learningenglish.voanews.com/p/6765.html → content-corpus/voa/',
    language: 'en',
    domain: 'intermediate course — everyday/chunks/grammar/listening',
    klass: 'REUSABLE_CONTENT',
    allowedOps: ['embed', 'derive', 'link', 'index', 'download', 'transcribe', 'segment'],
    forbiddenOps: ['reuse assets not audited VOA_ORIGINAL_PUBLIC_DOMAIN'],
    role: 'content-seed',
    confidence: 0.95,
    coverage: '30 lessons + review units + lesson plans',
    limitations: 'Per-asset audit required.',
  },
  'voa-anna': {
    id: 'voa-anna',
    name: "VOA Let's Learn English with Anna (+ Vietnamese variant)",
    type: 'dataset',
    location: 'learningenglish.voanews.com/p/8326.html → content-corpus/voa/',
    language: 'mixed',
    domain: 'beginner course — survival/everyday; VN comparison signal',
    klass: 'REUSABLE_CONTENT',
    allowedOps: ['embed', 'derive', 'link', 'index', 'download', 'transcribe', 'segment'],
    forbiddenOps: ['auto-merge VN text into FlashDay (§35 — comparison only)', 'reuse non-audited assets'],
    role: 'content-seed',
    confidence: 0.9,
    coverage: 'Anna series + 8 language variants incl. Vietnamese',
    limitations: 'VN localization = translation/reference signal, never auto-copied.',
  },
  'voa-everyday-grammar': {
    id: 'voa-everyday-grammar',
    name: 'VOA Everyday Grammar (+ TV)',
    type: 'dataset',
    location: 'learningenglish.voanews.com/z/4456 + z/4716 → content-corpus/voa/',
    language: 'en',
    domain: 'grammar knowledge/support',
    klass: 'REUSABLE_CONTENT',
    allowedOps: ['embed', 'derive', 'link', 'index'],
    forbiddenOps: ['grammar as curriculum spine', 'reuse non-audited assets'],
    role: 'evidence',
    confidence: 0.9,
    coverage: 'full grammar taxonomy; usage examples; learner-question corpus',
    limitations: 'Knowledge/support role only (§24).',
  },
  'voa-chunk-series': {
    id: 'voa-chunk-series',
    name: 'VOA English in a Minute / News Words / Words & Their Stories / Talk2Us',
    type: 'dataset',
    location: 'learningenglish.voanews.com/z/{3619,3620,987,6024} → content-corpus/voa/',
    language: 'en',
    domain: 'idioms, chunks, formulaic sequences, news vocabulary',
    klass: 'LINK_AND_DERIVE',
    allowedOps: ['derive', 'link', 'cite', 'index', 'embed-verified-original'],
    forbiddenOps: ['embed assets not audited original', 'force news vocab into A0/A1'],
    role: 'content-seed',
    confidence: 0.85,
    coverage: 'idiom/expression libraries with audio+video',
    limitations: 'Wire credits appear on some articles — per-asset audit required.',
  },
  'voa-pronunciation': {
    id: 'voa-pronunciation',
    name: 'VOA How to Pronounce',
    type: 'dataset',
    location: 'learningenglish.voanews.com/z/6042 → content-corpus/voa/',
    language: 'en',
    domain: 'pronunciation items (video+audio)',
    klass: 'REUSABLE_CONTENT',
    allowedOps: ['embed', 'derive', 'link', 'index'],
    forbiddenOps: ['infer learner pronunciation mastery', 'reuse non-audited assets'],
    role: 'content-seed',
    confidence: 0.9,
    coverage: 'phoneme-focused items with real audio',
    limitations: 'Cross-links to VN contrast DB; never evidence of learner ability.',
  },
  'voa-american-stories': {
    id: 'voa-american-stories',
    name: 'VOA American Stories (adapted literary works)',
    type: 'dataset',
    location: 'learningenglish.voanews.com/z/1581 → content-corpus/voa/',
    language: 'en',
    domain: 'graded extensive reading/listening narratives',
    klass: 'LINK_AND_DERIVE',
    allowedOps: ['derive', 'link', 'cite', 'index', 'embed-verified-original'],
    forbiddenOps: ['assume literary source rights from title', 'story completion as mastery'],
    role: 'content-seed',
    confidence: 0.8,
    coverage: 'long-form graded narratives with audio',
    limitations: '§6 — adaptation rights per-asset; sourceWork tracked separately.',
  },
  'voa-extensive-feeds': {
    id: 'voa-extensive-feeds',
    name: 'VOA topic feeds (As It Is, Arts & Culture, SciTech, Health, Education, Trending, VOA60, Podcast)',
    type: 'dataset',
    location: 'learningenglish.voanews.com/z/{3521,986,1579,955,7468,4652,3613,1689} → content-corpus/voa/',
    language: 'en',
    domain: 'authentic graded reading/listening',
    klass: 'LINK_AND_DERIVE',
    allowedOps: ['derive', 'link', 'cite', 'index', 'embed-verified-original'],
    forbiddenOps: ['news-as-curriculum', 'embed assets not audited original'],
    role: 'content-seed',
    confidence: 0.85,
    coverage: 'thousands of articles w/ audio — extensive input library',
    limitations: '§37 — carrier material, never curriculum spine. Wire credits common → per-asset audit.',
  },
  'voa-teacher-resources': {
    id: 'voa-teacher-resources',
    name: "VOA teacher resources (Let's Teach English, lesson plans, News Literacy)",
    type: 'dataset',
    location: 'learningenglish.voanews.com/p/{6764,6840}.html → content-corpus/voa/',
    language: 'en',
    domain: 'authoring reference / teacher guides',
    klass: 'LINK_AND_DERIVE',
    allowedOps: ['cite', 'inform-design', 'reference', 'index'],
    forbiddenOps: ['expose teacher instructions as learner lessons'],
    role: 'methodology',
    confidence: 0.85,
    coverage: 'course design, activity patterns, worksheets',
    limitations: 'AUTHORING_REFERENCE role (§8).',
  },
};
