/* Useful Chunks ch01–ch09 (A1–A2) — fluency glue: hedges, fillers, frames. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const CHUNKS_1: LessonSpec[] = [
  spec({
    id: 'ch01',
    level: 'a1',
    track: 'chunks',
    capabilities: ['hedge-statement'],
    title: 'I think and I guess',
    titleVi: 'I think và I guess',
    task: 'Soften an opinion with "I think" / "I guess"',
    context: 'Two friends picking a restaurant.',
    outcome: 'You can give opinions without sounding absolute.',
    input: {
      title: 'CH01 · Soft opinions',
      text: [
        'Mai: Should we eat here or find another place?',
        'Anh: I think this one is fine. The reviews look good.',
        'Mai: The menu is a bit pricey though.',
        'Anh: Yeah, I guess. But the portions are big.',
        'Mai: True. I think we should just stay.',
        'Anh: I think so too.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"I think" + ý kiến = giảm tuyệt đối; "I guess" thừa nhận có điều kiện.',
    },
    targets: [
      target({
        id: 'ch01.t1',
        chunk: 'I think this one is fine',
        cueVi: 'tôi nghĩ chỗ này ổn',
        sourceSentence: 'Anh: I think this one is fine. The reviews look good.',
        productionPattern: 'I think <this one is fine / it is okay>.',
        transferContext: 'giving a soft opinion on a movie',
      }),
      target({
        id: 'ch01.t2',
        chunk: 'The reviews look good',
        cueVi: 'đánh giá trông ổn',
        sourceSentence: 'Anh: I think this one is fine. The reviews look good.',
        productionPattern: 'The <reviews / photos / menu> look good.',
        transferContext: 'judging a hotel online',
      }),
      target({
        id: 'ch01.t3',
        chunk: 'a bit pricey',
        cueVi: 'hơi đắt',
        sourceSentence: 'Mai: The menu is a bit pricey though.',
        productionPattern: 'a bit <pricey / expensive / far>.',
        transferContext: 'commenting on a hotel rate',
      }),
      target({
        id: 'ch01.t4',
        chunk: 'I guess',
        cueVi: 'chắc vậy / tôi đoán',
        sourceSentence: 'Anh: Yeah, I guess. But the portions are big.',
        productionPattern: '<Yeah / I guess so>, I guess.',
        transferContext: 'half-agreeing about a long queue',
      }),
      target({
        id: 'ch01.t5',
        chunk: 'the portions are big',
        cueVi: 'phần ăn lớn',
        sourceSentence: 'Anh: Yeah, I guess. But the portions are big.',
        productionPattern: 'the <portions / rooms> are big.',
        transferContext: 'praising a diner',
      }),
      target({
        id: 'ch01.t6',
        chunk: 'I think so too',
        cueVi: 'tôi cũng nghĩ vậy',
        sourceSentence: 'Anh: I think so too.',
        productionPattern: 'I think <so / not>.',
        transferContext: "agreeing with a colleague's suggestion",
      }),
    ],
    transferTask: {
      prompt: 'Discuss a cafe choice — hedge two opinions with I think / I guess instead of stating facts.',
      promptVi: 'Bàn chọn quán cà phê — nói mềm hai ý kiến bằng I think / I guess thay vì khẳng định.',
      changesDimension: 'venue type + both speakers hedge',
    },
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch02',
    level: 'a2',
    track: 'chunks',
    capabilities: ['hedge-statement'],
    title: 'Actually and basically',
    titleVi: 'Actually và basically',
    task: 'Correct or simplify with "actually" / "basically"',
    context: 'Explaining a small misunderstanding about your job.',
    outcome: 'You can gently correct and summarize.',
    input: {
      title: 'CH02 · Correcting',
      text: [
        'Tom: So you are a programmer, right?',
        'Anh: Well, actually, I am more of a designer.',
        'Tom: Oh. So you draw things?',
        'Anh: Basically, yes — I design how apps look.',
        'Tom: Actually, that sounds more interesting.',
        'Anh: It is basically problem-solving with colors.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"actually" nhẹ nhàng sửa thông tin; "basically" gom ý phức tạp thành đơn giản.',
    },
    targets: [
      target({
        id: 'ch02.t1',
        chunk: 'Well, actually',
        cueVi: 'ừ thì thực ra',
        sourceSentence: 'Anh: Well, actually, I am more of a designer.',
        productionPattern: 'Well, actually, <I am more of a designer>.',
        transferContext: 'correcting a wrong assumption about your hometown',
      }),
      target({
        id: 'ch02.t2',
        chunk: 'more of a designer',
        cueVi: 'thiên về designer hơn',
        sourceSentence: 'Anh: Well, actually, I am more of a designer.',
        productionPattern: 'more of a <designer / backend person>.',
        transferContext: 'describing your role at a party',
      }),
      target({
        id: 'ch02.t3',
        chunk: 'Basically, yes',
        cueVi: 'nói gọn thì đúng',
        sourceSentence: 'Anh: Basically, yes — I design how apps look.',
        productionPattern: 'Basically, <yes / it is the same>.',
        transferContext: 'confirming a simplified description',
      }),
      target({
        id: 'ch02.t4',
        chunk: 'I design how apps look',
        cueVi: 'tôi thiết kế giao diện app',
        sourceSentence: 'Anh: Basically, yes — I design how apps look.',
        productionPattern: 'I design how <apps / websites> look.',
        transferContext: 'explaining your job to a child',
      }),
      target({
        id: 'ch02.t5',
        chunk: 'that sounds more interesting',
        cueVi: 'nghe thú vị hơn',
        sourceSentence: 'Tom: Actually, that sounds more interesting.',
        productionPattern: 'that sounds <more interesting / easier>.',
        transferContext: "reacting to someone's hobby",
      }),
      target({
        id: 'ch02.t6',
        chunk: 'problem-solving with colors',
        cueVi: 'giải quyết vấn đề bằng màu sắc',
        sourceSentence: 'Anh: It is basically problem-solving with colors.',
        productionPattern: 'basically <problem-solving> with <colors / data>.',
        transferContext: 'explaining a different creative job',
      }),
    ],
    transferTask: {
      prompt: 'Correct a wrong guess about your field and simplify your real job in one "basically" sentence.',
      promptVi: 'Sửa một phỏng đoán sai về lĩnh vực của bạn và gom nghề thật thành một câu "basically".',
      changesDimension: 'your field (not design) + same correction pattern',
    },
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch03',
    level: 'a2',
    track: 'chunks',
    capabilities: ['buy-time'],
    title: 'You know and I mean',
    titleVi: 'You know và I mean',
    task: 'Use fillers to keep your turn while thinking',
    context: 'Explaining a complicated weekend story.',
    outcome: 'You can hold the floor naturally while organizing thoughts.',
    input: {
      title: 'CH03 · The long story',
      text: [
        'Tom: How was the trip?',
        'Anh: It was, you know, kind of a disaster, honestly.',
        'Tom: What happened?',
        'Anh: I mean, first the bus broke down, then it rained all day.',
        'Tom: Oh no.',
        'Anh: But you know what? The food was amazing, so it was fine.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"you know" giữ nhịp khi đang nghĩ; "I mean" làm rõ ý vừa nói; "you know what" chuyển sang điểm sáng.',
    },
    targets: [
      target({
        id: 'ch03.t1',
        chunk: 'kind of a disaster',
        cueVi: 'kiểu như một thảm họa',
        sourceSentence: 'Anh: It was, you know, kind of a disaster, honestly.',
        productionPattern: 'kind of <a disaster / weird / fun>.',
        transferContext: 'describing a chaotic Monday',
      }),
      target({
        id: 'ch03.t2',
        chunk: 'What happened',
        cueVi: 'chuyện gì đã xảy ra',
        sourceSentence: 'Tom: What happened?',
        productionPattern: 'What <happened / went wrong>?',
        transferContext: 'asking about a canceled event',
      }),
      target({
        id: 'ch03.t3',
        chunk: 'the bus broke down',
        cueVi: 'xe buýt hỏng',
        sourceSentence: 'Anh: I mean, first the bus broke down, then it rained all day.',
        productionPattern: 'the <bus / car / bike> broke down.',
        transferContext: 'reporting a vehicle problem',
      }),
      target({
        id: 'ch03.t4',
        chunk: 'it rained all day',
        cueVi: 'mưa cả ngày',
        sourceSentence: 'Anh: I mean, first the bus broke down, then it rained all day.',
        productionPattern: 'it rained <all day / all night>.',
        transferContext: 'describing a ruined picnic',
      }),
      target({
        id: 'ch03.t5',
        chunk: 'you know what',
        cueVi: 'cậu biết không',
        sourceSentence: 'Anh: But you know what? The food was amazing, so it was fine.',
        productionPattern: 'But you know what? <It was fine>.',
        transferContext: 'pivoting to the good part of a bad day',
      }),
      target({
        id: 'ch03.t6',
        chunk: 'The food was amazing',
        cueVi: 'đồ ăn tuyệt',
        sourceSentence: 'Anh: But you know what? The food was amazing, so it was fine.',
        productionPattern: 'The <food / view / people> was amazing.',
        transferContext: 'highlighting one good thing about a trip',
      }),
    ],
    transferTask: {
      prompt: 'Tell a different bad-day story — delays and a wrong address — ending on a bright point.',
      promptVi: 'Kể một ngày tệ khác — trễ giờ và sai địa chỉ — kết thúc bằng điểm sáng.',
      changesDimension: 'problem types + same pivot-to-positive structure',
    },
    recyclingFrom: ['ev04'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch04',
    level: 'a1',
    track: 'chunks',
    capabilities: ['buy-time'],
    title: 'Let me see and hold on',
    titleVi: 'Let me see và hold on',
    task: 'Buy a few seconds to remember or check something',
    context: 'Answering a question you need to check your phone for.',
    outcome: 'You can pause a conversation politely.',
    input: {
      title: 'CH04 · Checking',
      text: [
        'Sara: When is your appointment again?',
        'Anh: Let me see... I think it is Thursday.',
        'Sara: Are you sure?',
        'Anh: Hold on, let me check my calendar.',
        'Anh: Yes — Thursday at three.',
        'Sara: Okay, see you there.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"Let me see" suy nghĩ vài giây; "Hold on" xin dừng để tra; hai bước rất tự nhiên.',
    },
    targets: [
      target({
        id: 'ch04.t1',
        chunk: 'Let me see',
        cueVi: 'để tôi xem nào',
        sourceSentence: 'Anh: Let me see... I think it is Thursday.',
        productionPattern: 'Let me <see / think>.',
        transferContext: 'recalling a name mid-conversation',
      }),
      target({
        id: 'ch04.t2',
        chunk: 'I think it is Thursday',
        cueVi: 'tôi nghĩ là thứ năm',
        sourceSentence: 'Anh: Let me see... I think it is Thursday.',
        productionPattern: 'I think it is <Thursday / at three>.',
        transferContext: 'guessing a date before checking',
      }),
      target({
        id: 'ch04.t3',
        chunk: 'Hold on',
        cueVi: 'khoan đã',
        sourceSentence: 'Anh: Hold on, let me check my calendar.',
        productionPattern: 'Hold on, let me <check / look>.',
        transferContext: 'pausing to find a photo',
      }),
      target({
        id: 'ch04.t4',
        chunk: 'let me check my calendar',
        cueVi: 'để tôi xem lịch',
        sourceSentence: 'Anh: Hold on, let me check my calendar.',
        productionPattern: 'let me check my <calendar / messages / notes>.',
        transferContext: 'verifying a price on your phone',
      }),
      target({
        id: 'ch04.t5',
        chunk: 'Thursday at three',
        cueVi: 'thứ năm lúc ba giờ',
        sourceSentence: 'Anh: Yes — Thursday at three.',
        productionPattern: '<Thursday / Friday> at <three / noon>.',
        transferContext: 'confirming an interview slot',
      }),
    ],
    transferTask: {
      prompt: 'Someone asks your booking reference — buy time, check an app, read it out.',
      promptVi: 'Người ta hỏi mã đặt chỗ của bạn — câu giờ, mở app tra, đọc ra.',
      changesDimension: 'checking an app not calendar + read-back task',
    },
    recyclingFrom: ['sv22'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch05',
    level: 'a2',
    track: 'chunks',
    capabilities: ['buy-time', 'hedge-statement'],
    title: 'That is a good question',
    titleVi: 'Câu hỏi hay đấy',
    task: 'Buy time for a hard question without dodging it',
    context: 'A colleague asks you something you need to think about.',
    outcome: 'You can acknowledge a question and think out loud.',
    input: {
      title: 'CH05 · Good question',
      text: [
        'Sara: Which city is better to live in, Hanoi or Saigon?',
        'Anh: Ooh, that is a good question. Let me think.',
        'Sara: For food, I mean.',
        'Anh: For food? Honestly, it depends on what you like.',
        'Sara: Noodle soup, mostly.',
        'Anh: Then probably Hanoi — but do not quote me on that.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"that is a good question" mua thời gian; "it depends" trả lời trung lập; "do not quote me" đùa/hedge.',
    },
    targets: [
      target({
        id: 'ch05.t1',
        chunk: 'that is a good question',
        cueVi: 'câu hỏi hay đấy',
        sourceSentence: 'Anh: Ooh, that is a good question. Let me think.',
        productionPattern: 'That is a <good / tough> question.',
        transferContext: 'responding to a tricky interview question',
      }),
      target({
        id: 'ch05.t2',
        chunk: 'Let me think',
        cueVi: 'để tôi nghĩ đã',
        sourceSentence: 'Anh: Ooh, that is a good question. Let me think.',
        productionPattern: 'Let me <think / see>.',
        transferContext: 'pausing before answering about salary',
      }),
      target({
        id: 'ch05.t3',
        chunk: 'it depends on',
        cueVi: 'tùy thuộc vào',
        sourceSentence: 'Anh: For food? Honestly, it depends on what you like.',
        productionPattern: 'it depends on <what you like / the weather>.',
        transferContext: 'answering "which phone should I buy"',
      }),
      target({
        id: 'ch05.t4',
        chunk: 'Noodle soup, mostly',
        cueVi: 'chủ yếu là phở',
        sourceSentence: 'Sara: Noodle soup, mostly.',
        productionPattern: '<Noodle soup>, mostly.',
        transferContext: 'specifying a preference quickly',
      }),
      target({
        id: 'ch05.t5',
        chunk: 'probably Hanoi',
        cueVi: 'chắc là Hà Nội',
        sourceSentence: 'Anh: Then probably Hanoi — but do not quote me on that.',
        productionPattern: 'probably <Hanoi / the red one>.',
        transferContext: 'giving a tentative recommendation',
      }),
      target({
        id: 'ch05.t6',
        chunk: 'do not quote me on that',
        cueVi: 'đừng lấy lời tôi làm chuẩn',
        sourceSentence: 'Anh: Then probably Hanoi — but do not quote me on that.',
        productionPattern: 'do not <quote me on that / hold me to it>.',
        transferContext: 'giving unofficial advice at work',
      }),
    ],
    transferTask: {
      prompt:
        'Field a different hard question — best way to learn a language — with hedge + depends + tentative answer.',
      promptVi: 'Xử lý câu hỏi khó khác — cách tốt nhất học ngoại ngữ — hedge + "tùy" + trả lời dè dặt.',
      changesDimension: 'advice question + conditional structure',
    },
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch06',
    level: 'a2',
    track: 'chunks',
    capabilities: ['hedge-statement'],
    title: 'Kind of and sort of',
    titleVi: 'Kind of và sort of',
    task: 'Soften descriptions that are not quite precise',
    context: 'Describing a weird dish to a friend.',
    outcome: 'You can describe vague things without committing.',
    input: {
      title: 'CH06 · Vague',
      text: [
        'Mai: What was that green thing at lunch?',
        'Anh: It was kind of a pancake, sort of.',
        'Mai: Was it sweet?',
        'Anh: Sort of — more savory, actually.',
        'Mai: Did you like it?',
        'Anh: Kind of. I would eat it again, probably.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"kind of / sort of" = hơi hơi, không rõ ràng; đặt trước tính từ/danh từ để mềm câu.',
    },
    targets: [
      target({
        id: 'ch06.t1',
        chunk: 'that green thing',
        cueVi: 'món xanh lá đó',
        sourceSentence: 'Mai: What was that green thing at lunch?',
        productionPattern: 'that <green thing / weird dish>.',
        transferContext: 'pointing at an unknown object',
      }),
      target({
        id: 'ch06.t2',
        chunk: 'kind of a pancake',
        cueVi: 'kiểu như bánh kếp',
        sourceSentence: 'Anh: It was kind of a pancake, sort of.',
        productionPattern: 'kind of <a pancake / a soup>.',
        transferContext: 'describing an unfamiliar snack',
      }),
      target({
        id: 'ch06.t3',
        chunk: 'Was it sweet',
        cueVi: 'có ngọt không',
        sourceSentence: 'Mai: Was it sweet?',
        productionPattern: 'Was it <sweet / spicy / good>?',
        transferContext: 'asking about a fruit you never tried',
      }),
      target({
        id: 'ch06.t4',
        chunk: 'more savory',
        cueVi: 'thiên mặn hơn',
        sourceSentence: 'Anh: Sort of — more savory, actually.',
        productionPattern: 'more <savory / bitter / salty>.',
        transferContext: 'describing a sauce flavor',
      }),
      target({
        id: 'ch06.t5',
        chunk: 'Did you like it',
        cueVi: 'bạn có thích không',
        sourceSentence: 'Mai: Did you like it?',
        productionPattern: 'Did you <like it / try it>?',
        transferContext: 'asking a friend about a new drink',
      }),
      target({
        id: 'ch06.t6',
        chunk: 'I would eat it again',
        cueVi: 'tôi sẽ ăn lại',
        sourceSentence: 'Anh: Kind of. I would eat it again, probably.',
        productionPattern: 'I would <eat it again / try it once>.',
        transferContext: 'rating an odd snack honestly',
      }),
    ],
    transferTask: {
      prompt: 'Describe a vague experience — a strange museum exhibit — with kind of/sort of hedges.',
      promptVi: 'Mô tả một trải nghiệm mơ hồ — một tác phẩm triển lãm lạ — với kind of/sort of.',
      changesDimension: 'art object not food + ambiguity about meaning',
    },
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch07',
    level: 'a2',
    track: 'chunks',
    capabilities: ['hedge-statement', 'express-opinion'],
    title: 'To be honest',
    titleVi: 'Nói thật thì',
    task: 'Preface an honest opinion that might disappoint',
    context: "Giving feedback on a friend's new haircut.",
    outcome: 'You can signal honesty before a mild negative.',
    input: {
      title: 'CH07 · Honest take',
      text: [
        'Linh: So, what do you think of my haircut?',
        'Anh: To be honest, I liked it longer.',
        'Linh: Really? You do not like it?',
        'Anh: It is not bad — just different. Honestly, give it a week.',
        'Linh: Fair. I am still getting used to it too.',
        'Anh: To be fair, it does suit your face.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"to be honest" báo trước ý kiến thật; "to be fair" cân bằng lại sau góp ý.',
    },
    targets: [
      target({
        id: 'ch07.t1',
        chunk: 'what do you think of my haircut',
        cueVi: 'bạn nghĩ sao về tóc tôi',
        sourceSentence: 'Linh: So, what do you think of my haircut?',
        productionPattern: 'what do you think of <my haircut / this outfit>?',
        transferContext: 'asking feedback on a presentation',
      }),
      target({
        id: 'ch07.t2',
        chunk: 'To be honest',
        cueVi: 'nói thật thì',
        sourceSentence: 'Anh: To be honest, I liked it longer.',
        productionPattern: 'To be honest, <I liked it longer / it is not great>.',
        transferContext: 'giving feedback on a drawing',
      }),
      target({
        id: 'ch07.t3',
        chunk: 'I liked it longer',
        cueVi: 'tôi thích khi nó dài hơn',
        sourceSentence: 'Anh: To be honest, I liked it longer.',
        productionPattern: 'I liked it <longer / before / differently>.',
        transferContext: 'preferring an earlier design version',
      }),
      target({
        id: 'ch07.t4',
        chunk: 'It is not bad',
        cueVi: 'không tệ đâu',
        sourceSentence: 'Anh: It is not bad — just different. Honestly, give it a week.',
        productionPattern: 'It is not <bad / terrible>.',
        transferContext: 'softening a negative review',
      }),
      target({
        id: 'ch07.t5',
        chunk: 'just different',
        cueVi: 'chỉ là khác thôi',
        sourceSentence: 'Anh: It is not bad — just different. Honestly, give it a week.',
        productionPattern: 'just <different / new / unusual>.',
        transferContext: 'describing an acquired taste',
      }),
      target({
        id: 'ch07.t6',
        chunk: 'getting used to it',
        cueVi: 'đang quen dần với nó',
        sourceSentence: 'Linh: Fair. I am still getting used to it too.',
        productionPattern: 'getting used to <it / the new place>.',
        transferContext: 'adjusting to a new phone',
      }),
      target({
        id: 'ch07.t7',
        chunk: 'To be fair',
        cueVi: 'công bằng mà nói',
        sourceSentence: 'Anh: To be fair, it does suit your face.',
        productionPattern: 'To be fair, <it does suit you>.',
        transferContext: "balancing criticism of a colleague's idea",
      }),
      target({
        id: 'ch07.t8',
        chunk: 'suit your face',
        cueVi: 'hợp với gương mặt',
        sourceSentence: 'Anh: To be fair, it does suit your face.',
        productionPattern: 'suit your <face / style>.',
        transferContext: 'complimenting glasses on a friend',
      }),
    ],
    transferTask: {
      prompt: "Give honest-but-kind feedback on a friend's cooking — one real critique, one balance point.",
      promptVi: 'Góp ý thật nhưng nhẹ về món bạn nấu — một điểm chê thật, một điểm cân bằng.',
      changesDimension: 'taste feedback + balance both directions',
    },
    recyclingFrom: ['ev18'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch08',
    level: 'a2',
    track: 'chunks',
    capabilities: ['check-understanding', 'buy-time'],
    title: 'As far as I know',
    titleVi: 'Theo tôi biết thì',
    task: 'Mark information as true-to-your-knowledge, not certain',
    context: "Answering about a store's hours you are not sure of.",
    outcome: 'You can share info while flagging uncertainty.',
    input: {
      title: 'CH08 · Not sure',
      text: [
        'Tom: Does the market close at six?',
        'Anh: As far as I know, yes. But I have not been there in a while.',
        'Tom: Should we check online?',
        'Anh: Good idea. If I remember correctly, they post hours on their page.',
        'Tom: It says seven, actually.',
        'Anh: Huh, they must have changed it. Good thing we checked.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"as far as I know" giới hạn độ chắc; "if I remember correctly" đánh dấu trí nhớ; "good thing" may mà.',
    },
    targets: [
      target({
        id: 'ch08.t1',
        chunk: 'Does the market close at six',
        cueVi: 'chợ đóng lúc sáu giờ à',
        sourceSentence: 'Tom: Does the market close at six?',
        productionPattern: 'Does the <market / pharmacy> close at <six>?',
        transferContext: 'asking closing hours of a bank',
      }),
      target({
        id: 'ch08.t2',
        chunk: 'As far as I know',
        cueVi: 'theo tôi biết',
        sourceSentence: 'Anh: As far as I know, yes. But I have not been there in a while.',
        productionPattern: 'As far as I know, <yes / it is open>.',
        transferContext: 'answering about office policy',
      }),
      target({
        id: 'ch08.t3',
        chunk: 'in a while',
        cueVi: 'đã lâu (không ~)',
        sourceSentence: 'Anh: As far as I know, yes. But I have not been there in a while.',
        productionPattern: 'in <a while / ages>.',
        transferContext: 'saying you have not visited a place recently',
      }),
      target({
        id: 'ch08.t4',
        chunk: 'check online',
        cueVi: 'tra trên mạng',
        sourceSentence: 'Tom: Should we check online?',
        productionPattern: 'check <online / their website / the app>.',
        transferContext: 'verifying a train schedule',
      }),
      target({
        id: 'ch08.t5',
        chunk: 'If I remember correctly',
        cueVi: 'nếu tôi nhớ không lầm',
        sourceSentence: 'Anh: Good idea. If I remember correctly, they post hours on their page.',
        productionPattern: 'If I remember correctly, <they post hours online>.',
        transferContext: 'recalling a detail about a service',
      }),
      target({
        id: 'ch08.t6',
        chunk: 'It says seven',
        cueVi: 'trên đó ghi bảy giờ',
        sourceSentence: 'Tom: It says seven, actually.',
        productionPattern: 'It says <seven / closed / sold out>.',
        transferContext: 'reading info off a sign or site',
      }),
      target({
        id: 'ch08.t7',
        chunk: 'Good thing we checked',
        cueVi: 'may mà mình tra',
        sourceSentence: 'Anh: Huh, they must have changed it. Good thing we checked.',
        productionPattern: 'Good thing we <checked / left early>.',
        transferContext: 'relief after verifying a detail',
      }),
    ],
    transferTask: {
      prompt: "Answer an unsure question — a restaurant's vegetarian options — flag uncertainty, verify, react.",
      promptVi: 'Trả lời câu không chắc — nhà hàng có đồ chay không — đánh dấu không chắc, kiểm tra, phản ứng.',
      changesDimension: 'menu info not hours + verification changes the answer',
    },
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch09',
    level: 'a2',
    track: 'chunks',
    capabilities: ['change-topic'],
    title: 'By the way and anyway',
    titleVi: 'By the way và anyway',
    task: 'Shift topics and return to the main thread',
    context: 'A chat that keeps drifting off-topic.',
    outcome: 'You can insert side notes and get back on track.',
    input: {
      title: 'CH09 · Topic shifts',
      text: [
        'Anh: So the meeting moved to Friday.',
        'Mai: Okay. By the way, did you see the new cafe downstairs?',
        'Anh: Not yet. Is it good?',
        'Mai: Really good croissants. Anyway — the Friday meeting, what time?',
        'Anh: Two thirty. Anyway, back to the report: it is due Thursday.',
        'Mai: Got it. Croissants after the deadline, then.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"by the way" đưa ý phụ vào; "anyway" kéo về mạch chính — cực kỳ tự nhiên trong hội thoại.',
    },
    targets: [
      target({
        id: 'ch09.t1',
        chunk: 'the meeting moved to Friday',
        cueVi: 'cuộc họp dời sang thứ sáu',
        sourceSentence: 'Anh: So the meeting moved to Friday.',
        productionPattern: 'the <meeting / deadline> moved to <Friday>.',
        transferContext: 'announcing a rescheduled class',
      }),
      target({
        id: 'ch09.t2',
        chunk: 'By the way',
        cueVi: 'nhân tiện',
        sourceSentence: 'Mai: Okay. By the way, did you see the new cafe downstairs?',
        productionPattern: 'By the way, <did you see / are you free>?',
        transferContext: 'adding a side question in a call',
      }),
      target({
        id: 'ch09.t3',
        chunk: 'the new cafe downstairs',
        cueVi: 'quán cà phê mới tầng dưới',
        sourceSentence: 'Mai: Okay. By the way, did you see the new cafe downstairs?',
        productionPattern: 'the new <cafe / gym> downstairs.',
        transferContext: 'mentioning a new shop at work',
      }),
      target({
        id: 'ch09.t4',
        chunk: 'Anyway',
        cueVi: 'dù sao thì/quay lại vấn đề',
        sourceSentence: 'Mai: Really good croissants. Anyway — the Friday meeting, what time?',
        productionPattern: 'Anyway — <the meeting / back to work>.',
        transferContext: 'returning to the agenda after small talk',
      }),
      target({
        id: 'ch09.t5',
        chunk: 'back to the report',
        cueVi: 'quay lại bản báo cáo',
        sourceSentence: 'Anh: Two thirty. Anyway, back to the report: it is due Thursday.',
        productionPattern: 'back to <the report / the plan>.',
        transferContext: 'refocusing a study group',
      }),
      target({
        id: 'ch09.t6',
        chunk: 'it is due Thursday',
        cueVi: 'hạn nộp thứ năm',
        sourceSentence: 'Anh: Two thirty. Anyway, back to the report: it is due Thursday.',
        productionPattern: 'it is due <Thursday / next week>.',
        transferContext: 'stating a homework deadline',
      }),
      target({
        id: 'ch09.t7',
        chunk: 'after the deadline',
        cueVi: 'sau hạn chót',
        sourceSentence: 'Mai: Got it. Croissants after the deadline, then.',
        productionPattern: 'after <the deadline / the meeting>.',
        transferContext: 'scheduling fun after work',
      }),
    ],
    transferTask: {
      prompt: 'Insert one side question into a work chat, then pull the conversation back to the task.',
      promptVi: 'Chèn một câu hỏi phụ vào chat công việc, rồi kéo hội thoại về lại nhiệm vụ.',
      changesDimension: 'written chat channel + you do both shifts',
    },
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
];
