/* Useful Chunks ch10–ch18 (A1–A2) — sequencing, signposts, closing. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const CHUNKS_2: LessonSpec[] = [
  spec({
    id: 'ch10',
    level: 'a1',
    track: 'chunks',
    capabilities: ['tell-story'],
    title: 'First, then, finally',
    titleVi: 'First, then, finally',
    task: 'Tell a simple sequence of events',
    context: 'Explaining how your day went badly.',
    outcome: 'You can order events with sequencers.',
    input: {
      title: 'CH10 · Bad morning',
      text: [
        'Sara: You look tired. What happened?',
        'Anh: Ugh. First, I missed the bus. Then it started raining.',
        'Sara: Oh no.',
        'Anh: Then I spilled coffee on my shirt. Finally, I arrived forty minutes late.',
        'Sara: What a morning. At least it is over.',
        'Anh: Right? I need a nap already.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Chuỗi sự kiện: First → Then → Then → Finally; "What a morning" câu cảm thán phản hồi.',
    },
    targets: [
      target({
        id: 'ch10.t1',
        chunk: 'You look tired',
        cueVi: 'trông bạn mệt quá',
        sourceSentence: 'Sara: You look tired. What happened?',
        productionPattern: 'You look <tired / happy / stressed>.',
        transferContext: 'noticing a friend looks unwell',
      }),
      target({
        id: 'ch10.t2',
        chunk: 'I missed the bus',
        cueVi: 'tôi lỡ xe buýt',
        sourceSentence: 'Anh: Ugh. First, I missed the bus. Then it started raining.',
        productionPattern: 'I missed <the bus / my train>.',
        transferContext: 'explaining why you were late to class',
      }),
      target({
        id: 'ch10.t3',
        chunk: 'it started raining',
        cueVi: 'trời bắt đầu mưa',
        sourceSentence: 'Anh: Ugh. First, I missed the bus. Then it started raining.',
        productionPattern: 'it started <raining / snowing>.',
        transferContext: 'describing weather ruining plans',
      }),
      target({
        id: 'ch10.t4',
        chunk: 'I spilled coffee on my shirt',
        cueVi: 'tôi đổ cà phê lên áo',
        sourceSentence: 'Anh: Then I spilled coffee on my shirt. Finally, I arrived forty minutes late.',
        productionPattern: 'I spilled <coffee / water> on my <shirt / bag>.',
        transferContext: 'describing a lunch accident',
      }),
      target({
        id: 'ch10.t5',
        chunk: 'forty minutes late',
        cueVi: 'trễ bốn mươi phút',
        sourceSentence: 'Anh: Then I spilled coffee on my shirt. Finally, I arrived forty minutes late.',
        productionPattern: '<forty minutes / an hour> late.',
        transferContext: 'reporting arrival delay to a host',
      }),
      target({
        id: 'ch10.t6',
        chunk: 'What a morning',
        cueVi: 'thật là một buổi sáng',
        sourceSentence: 'Sara: What a morning. At least it is over.',
        productionPattern: 'What a <morning / day / mess>.',
        transferContext: "reacting to someone's bad day",
      }),
      target({
        id: 'ch10.t7',
        chunk: 'At least it is over',
        cueVi: 'ít nhất cũng qua rồi',
        sourceSentence: 'Sara: What a morning. At least it is over.',
        productionPattern: 'At least <it is over / you are here>.',
        transferContext: 'comforting a friend after a bad exam',
      }),
      target({
        id: 'ch10.t8',
        chunk: 'I need a nap',
        cueVi: 'tôi cần ngủ trưa',
        sourceSentence: 'Anh: Right? I need a nap already.',
        productionPattern: 'I need a <nap / break / coffee>.',
        transferContext: 'saying you are exhausted after a trip',
      }),
    ],
    transferTask: {
      prompt: 'Sequence a different story — a cooking attempt that went wrong — with first/then/finally.',
      promptVi: 'Kể một câu chuyện khác — lần nấu ăn hỏng — với first/then/finally.',
      changesDimension: 'kitchen disaster + same sequencing spine',
    },
    recyclingFrom: ['ch03'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch11',
    level: 'a2',
    track: 'chunks',
    capabilities: ['give-reason'],
    title: 'For example and for instance',
    titleVi: 'For example và for instance',
    task: 'Support a point with a concrete example',
    context: 'Convincing a friend to try a new running route.',
    outcome: 'You can back opinions with examples.',
    input: {
      title: 'CH11 · For example',
      text: [
        'Anh: The park is great for running. It has everything.',
        'Mai: Like what?',
        'Anh: For example, there is a water fountain every kilometer.',
        'Mai: Okay, that is useful.',
        'Anh: And it is safe — for instance, there are lights everywhere.',
        'Mai: Alright, you convinced me. Saturday morning?',
        'Anh: Perfect.',
      ].join('\n'),
      origin: 'authored',
      noteVi:
        '"for example / for instance" đưa ví dụ cụ thể sau một claim chung; "you convinced me" = thuyết phục thành công.',
    },
    targets: [
      target({
        id: 'ch11.t1',
        chunk: 'great for running',
        cueVi: 'rất hợp để chạy bộ',
        sourceSentence: 'Anh: The park is great for running. It has everything.',
        productionPattern: 'great for <running / studying / families>.',
        transferContext: 'recommending a library for study',
      }),
      target({
        id: 'ch11.t2',
        chunk: 'Like what',
        cueVi: 'ví dụ như gì',
        sourceSentence: 'Mai: Like what?',
        productionPattern: 'Like <what / which ones>?',
        transferContext: 'asking for examples in any topic',
      }),
      target({
        id: 'ch11.t3',
        chunk: 'For example',
        cueVi: 'ví dụ',
        sourceSentence: 'Anh: For example, there is a water fountain every kilometer.',
        productionPattern: 'For example, <there is a fountain>.',
        transferContext: 'giving an example of good service',
      }),
      target({
        id: 'ch11.t4',
        chunk: 'a water fountain',
        cueVi: 'vòi nước uống',
        sourceSentence: 'Anh: For example, there is a water fountain every kilometer.',
        productionPattern: 'a <water fountain / rest stop> every kilometer.',
        transferContext: 'describing trail amenities',
      }),
      target({
        id: 'ch11.t5',
        chunk: 'for instance',
        cueVi: 'chẳng hạn',
        sourceSentence: 'Anh: And it is safe — for instance, there are lights everywhere.',
        productionPattern: 'for instance, <there are lights>.',
        transferContext: 'adding a second example about safety',
      }),
      target({
        id: 'ch11.t6',
        chunk: 'there are lights everywhere',
        cueVi: 'đèn khắp nơi',
        sourceSentence: 'Anh: And it is safe — for instance, there are lights everywhere.',
        productionPattern: 'there are <lights / cameras> everywhere.',
        transferContext: 'describing a well-lit campus',
      }),
      target({
        id: 'ch11.t7',
        chunk: 'you convinced me',
        cueVi: 'bạn thuyết phục tôi rồi',
        sourceSentence: 'Mai: Alright, you convinced me. Saturday morning?',
        productionPattern: 'you <convinced me / won me over>.',
        transferContext: 'accepting a restaurant suggestion',
      }),
    ],
    transferTask: {
      prompt: 'Convince someone of a different claim — your neighborhood is convenient — with two examples.',
      promptVi: 'Thuyết phục ai đó một claim khác — khu bạn sống tiện — với hai ví dụ.',
      changesDimension: 'different claim + example pair structure',
    },
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch12',
    level: 'a2',
    track: 'chunks',
    capabilities: ['express-opinion', 'hedge-statement'],
    title: 'The thing is',
    titleVi: 'The thing is',
    task: 'Lead into the real reason or problem',
    context: 'Explaining why you cannot lend money this month.',
    outcome: 'You can signal the core issue tactfully.',
    input: {
      title: 'CH12 · The real reason',
      text: [
        'Tom: Could you lend me fifty until Friday?',
        'Anh: Hmm. The thing is, I am a bit tight this month myself.',
        'Tom: Oh, no worries. I did not know.',
        'Anh: The thing is, rent just went up. Otherwise I would.',
        'Tom: Totally understand. Maybe ask Linh?',
        'Anh: Yeah, she might be able to. Sorry I cannot help this time.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"the thing is" giới thiệu lý do thật sau lưỡng lự; "a bit tight" = hơi thiếu tiền.',
    },
    targets: [
      target({
        id: 'ch12.t1',
        chunk: 'lend me fifty',
        cueVi: 'cho tôi mượn năm mươi',
        sourceSentence: 'Tom: Could you lend me fifty until Friday?',
        productionPattern: 'lend me <fifty / twenty> until <Friday / payday>.',
        transferContext: 'borrowing small cash from a roommate',
      }),
      target({
        id: 'ch12.t2',
        chunk: 'The thing is',
        cueVi: 'vấn đề là',
        sourceSentence: 'Anh: Hmm. The thing is, I am a bit tight this month myself.',
        productionPattern: 'The thing is, <I am tight this month / it is complicated>.',
        transferContext: 'explaining why you cannot join a trip',
      }),
      target({
        id: 'ch12.t3',
        chunk: 'a bit tight',
        cueVi: 'hơi eo hẹp (tiền)',
        sourceSentence: 'Anh: Hmm. The thing is, I am a bit tight this month myself.',
        productionPattern: 'a bit <tight / short> this month.',
        transferContext: 'explaining budget limits honestly',
      }),
      target({
        id: 'ch12.t4',
        chunk: 'rent just went up',
        cueVi: 'tiền nhà vừa tăng',
        sourceSentence: 'Anh: The thing is, rent just went up. Otherwise I would.',
        productionPattern: 'rent <just went up / is due>.',
        transferContext: 'explaining a sudden expense',
      }),
      target({
        id: 'ch12.t5',
        chunk: 'Otherwise I would',
        cueVi: 'nếu không thì tôi sẽ giúp',
        sourceSentence: 'Anh: The thing is, rent just went up. Otherwise I would.',
        productionPattern: 'Otherwise I <would / would help>.',
        transferContext: 'declining a favor with regret',
      }),
      target({
        id: 'ch12.t6',
        chunk: 'Totally understand',
        cueVi: 'hoàn toàn hiểu',
        sourceSentence: 'Tom: Totally understand. Maybe ask Linh?',
        productionPattern: 'Totally <understand / get it>.',
        transferContext: 'accepting a declined request graciously',
      }),
      target({
        id: 'ch12.t7',
        chunk: 'she might be able to',
        cueVi: 'cô ấy có thể giúp được',
        sourceSentence: 'Anh: Yeah, she might be able to. Sorry I cannot help this time.',
        productionPattern: 'she might <be able to / know>.',
        transferContext: 'suggesting an alternative helper',
      }),
    ],
    transferTask: {
      prompt: 'Decline a different request — covering a shift — with the thing is + real reason + alternative.',
      promptVi: 'Từ chối một yêu cầu khác — trực thay ca — với the thing is + lý do thật + gợi ý khác.',
      changesDimension: 'favor type + still warm decline',
    },
    recyclingFrom: ['ev17'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch13',
    level: 'a2',
    track: 'chunks',
    capabilities: ['express-opinion', 'disagree-politely'],
    title: 'On the other hand',
    titleVi: 'Mặt khác',
    task: 'Balance two sides of a decision',
    context: 'Deciding whether to move to a bigger apartment.',
    outcome: 'You can weigh two sides in one turn.',
    input: {
      title: 'CH13 · Weighing',
      text: [
        'Anh: The new place is bigger. On the other hand, it is farther from work.',
        'Mai: True. Bigger is nice though.',
        'Anh: On one hand, I want the space. On the other, the commute kills me.',
        'Mai: Can you work from home sometimes?',
        'Anh: Twice a week, yes. That changes things.',
        'Mai: So on balance, it is worth it.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"on (the) one hand … on the other (hand)" trình bày hai mặt; "on balance" tổng kết cân nhắc.',
    },
    targets: [
      target({
        id: 'ch13.t1',
        chunk: 'The new place is bigger',
        cueVi: 'chỗ mới rộng hơn',
        sourceSentence: 'Anh: The new place is bigger. On the other hand, it is farther from work.',
        productionPattern: 'The new <place / job> is <bigger / better>.',
        transferContext: 'starting a housing pros/cons talk',
      }),
      target({
        id: 'ch13.t2',
        chunk: 'On the other hand',
        cueVi: 'mặt khác',
        sourceSentence: 'Anh: The new place is bigger. On the other hand, it is farther from work.',
        productionPattern: 'On the other hand, <it is farther / it costs more>.',
        transferContext: 'weighing a job offer',
      }),
      target({
        id: 'ch13.t3',
        chunk: 'farther from work',
        cueVi: 'xa chỗ làm hơn',
        sourceSentence: 'Anh: The new place is bigger. On the other hand, it is farther from work.',
        productionPattern: 'farther from <work / the center>.',
        transferContext: 'comparing two schools',
      }),
      target({
        id: 'ch13.t4',
        chunk: 'I want the space',
        cueVi: 'tôi muốn có không gian',
        sourceSentence: 'Anh: On one hand, I want the space. On the other, the commute kills me.',
        productionPattern: 'I want the <space / quiet>.',
        transferContext: 'stating a housing priority',
      }),
      target({
        id: 'ch13.t5',
        chunk: 'the commute kills me',
        cueVi: 'quãng đường giết tôi',
        sourceSentence: 'Anh: On one hand, I want the space. On the other, the commute kills me.',
        productionPattern: 'the <commute / traffic / noise> kills me.',
        transferContext: 'complaining about a long drive',
      }),
      target({
        id: 'ch13.t6',
        chunk: 'work from home',
        cueVi: 'làm việc ở nhà',
        sourceSentence: 'Mai: Can you work from home sometimes?',
        productionPattern: 'work from <home / anywhere>.',
        transferContext: 'discussing remote days with a manager',
      }),
      target({
        id: 'ch13.t7',
        chunk: 'That changes things',
        cueVi: 'vậy thì khác rồi',
        sourceSentence: 'Anh: Twice a week, yes. That changes things.',
        productionPattern: 'That <changes things / is different>.',
        transferContext: 'revising a decision after new info',
      }),
      target({
        id: 'ch13.t8',
        chunk: 'on balance',
        cueVi: 'tổng thể xét',
        sourceSentence: 'Mai: So on balance, it is worth it.',
        productionPattern: 'on balance, <it is worth it / go for it>.',
        transferContext: 'concluding a difficult choice',
      }),
    ],
    transferTask: {
      prompt: 'Weigh a different decision — buying a motorbike vs staying with transit — both sides + verdict.',
      promptVi: 'Cân nhắc một quyết định khác — mua xe máy hay tiếp tục đi xe buýt — hai mặt + kết luận.',
      changesDimension: 'transport decision + full both-hands structure',
    },
    recyclingFrom: ['ev05'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch14',
    level: 'a2',
    track: 'chunks',
    capabilities: ['tell-story'],
    title: 'In the end',
    titleVi: 'Cuối cùng thì',
    task: 'Wrap up a story with the outcome',
    context: 'Telling how a stressful day turned out.',
    outcome: 'You can close a narrative with a resolution.',
    input: {
      title: 'CH14 · Resolution',
      text: [
        'Mai: Did you find your keys in the end?',
        'Anh: In the end, yes — they were in my jacket pocket all along.',
        'Mai: Classic. At least you found them.',
        'Anh: In the end, the day turned out okay.',
        'Mai: So no drama after all.',
        'Anh: None. I am buying a key hook this weekend.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"in the end" tổng kết sau chuỗi sự việc; "all along" = suốt từ đầu; "after all" sau cùng.',
    },
    targets: [
      target({
        id: 'ch14.t1',
        chunk: 'find your keys',
        cueVi: 'tìm thấy chìa khóa',
        sourceSentence: 'Mai: Did you find your keys in the end?',
        productionPattern: 'find your <keys / phone / wallet>.',
        transferContext: 'asking if someone found lost glasses',
      }),
      target({
        id: 'ch14.t2',
        chunk: 'In the end',
        cueVi: 'cuối cùng thì',
        sourceSentence: 'Anh: In the end, yes — they were in my jacket pocket all along.',
        productionPattern: 'In the end, <yes / it worked out>.',
        transferContext: 'concluding a long search story',
      }),
      target({
        id: 'ch14.t3',
        chunk: 'my jacket pocket',
        cueVi: 'túi áo khoác',
        sourceSentence: 'Anh: In the end, yes — they were in my jacket pocket all along.',
        productionPattern: 'in my <jacket pocket / bag>.',
        transferContext: 'finding something in an obvious place',
      }),
      target({
        id: 'ch14.t4',
        chunk: 'all along',
        cueVi: 'suốt từ đầu đến cuối',
        sourceSentence: 'Anh: In the end, yes — they were in my jacket pocket all along.',
        productionPattern: '<there / in my pocket> all along.',
        transferContext: 'realizing an answer was obvious',
      }),
      target({
        id: 'ch14.t5',
        chunk: 'the day turned out okay',
        cueVi: 'ngày hóa ra ổn',
        sourceSentence: 'Anh: In the end, the day turned out okay.',
        productionPattern: 'turned out <okay / fine / great>.',
        transferContext: 'summarizing a scary start that ended well',
      }),
      target({
        id: 'ch14.t6',
        chunk: 'after all',
        cueVi: 'sau cùng thì',
        sourceSentence: 'Mai: So no drama after all.',
        productionPattern: 'no <drama / problem> after all.',
        transferContext: 'relief that a worry was nothing',
      }),
      target({
        id: 'ch14.t7',
        chunk: 'a key hook',
        cueVi: 'móc treo chìa khóa',
        sourceSentence: 'Anh: None. I am buying a key hook this weekend.',
        productionPattern: 'a <key hook / spare key>.',
        transferContext: 'planning a small fix after a mishap',
      }),
    ],
    transferTask: {
      prompt: 'Tell a different resolution story — a lost delivery that finally arrived — with in the end + lesson.',
      promptVi: 'Kể một câu chuyện kết cục khác — gói hàng mất cuối cùng cũng đến — in the end + bài học.',
      changesDimension: 'delivery problem + lesson learned ending',
    },
    recyclingFrom: ['ch10'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch15',
    level: 'a1',
    track: 'chunks',
    capabilities: ['check-understanding'],
    title: 'So you mean',
    titleVi: 'Ý bạn là',
    task: 'Check you understood by paraphrasing back',
    context: 'Confirming meeting details you half-heard.',
    outcome: 'You can echo-check information.',
    input: {
      title: 'CH15 · Checking',
      text: [
        'Boss: Let us meet at the new office, not the old one.',
        'Anh: So you mean the one on Nguyen Hue street?',
        'Boss: Right, fourth floor.',
        'Anh: And we start at nine, not ten — is that right?',
        'Boss: Correct. Nine sharp.',
        'Anh: Okay, new office, fourth floor, nine sharp. Got it.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"So you mean X?" paraphrase để check; "is that right" xác nhận; "sharp" = đúng giờ.',
    },
    targets: [
      target({
        id: 'ch15.t1',
        chunk: 'the new office',
        cueVi: 'văn phòng mới',
        sourceSentence: 'Boss: Let us meet at the new office, not the old one.',
        productionPattern: 'the <new office / main branch>.',
        transferContext: 'clarifying which branch',
      }),
      target({
        id: 'ch15.t2',
        chunk: 'So you mean',
        cueVi: 'ý bạn là',
        sourceSentence: 'Anh: So you mean the one on Nguyen Hue street?',
        productionPattern: 'So you mean <the one on X street / tomorrow>?',
        transferContext: 'confirming a pickup point',
      }),
      target({
        id: 'ch15.t3',
        chunk: 'the one on Nguyen Hue street',
        cueVi: 'cái ở đường Nguyễn Huệ',
        sourceSentence: 'Anh: So you mean the one on Nguyen Hue street?',
        productionPattern: 'the one on <Nguyen Hue / the corner>.',
        transferContext: 'specifying a branch location',
      }),
      target({
        id: 'ch15.t4',
        chunk: 'is that right',
        cueVi: 'đúng không',
        sourceSentence: 'Anh: And we start at nine, not ten — is that right?',
        productionPattern: '<nine, not ten> — is that right?',
        transferContext: 'double-checking a gate number',
      }),
      target({
        id: 'ch15.t5',
        chunk: 'nine sharp',
        cueVi: 'chín giờ đúng',
        sourceSentence: 'Boss: Correct. Nine sharp.',
        productionPattern: '<nine / noon> sharp.',
        transferContext: 'stressing punctuality for a call',
      }),
      target({
        id: 'ch15.t6',
        chunk: 'Got it',
        cueVi: 'rõ rồi',
        sourceSentence: 'Anh: Okay, new office, fourth floor, nine sharp. Got it.',
        productionPattern: '<Okay / Right>, got it.',
        transferContext: 'summarizing instructions to confirm',
      }),
    ],
    transferTask: {
      prompt: 'Echo-check a different set of details — a delivery time, floor, and contact name.',
      promptVi: 'Kiểm tra lại một bộ chi tiết khác — giờ giao hàng, tầng, và tên người nhận.',
      changesDimension: 'delivery context + three-point echo summary',
    },
    recyclingFrom: ['sv06'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch16',
    level: 'a2',
    track: 'chunks',
    capabilities: ['close-conversation'],
    title: 'Wrap it up',
    titleVi: 'Kết thúc cuộc trò chuyện',
    task: 'Close a conversation naturally before leaving',
    context: 'Ending a long chat with a neighbor at the door.',
    outcome: 'You can signal goodbye without abruptness.',
    input: {
      title: 'CH16 · Wrapping up',
      text: [
        'Anh: Anyway, I should get going. It was nice catching up.',
        'Mrs. Chen: You too. Say hi to Lan for me.',
        'Anh: Will do. Let us have coffee sometime.',
        'Mrs. Chen: I would like that. Take care.',
        'Anh: You too. See you around.',
        'Mrs. Chen: Bye now.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Thoát êm: "I should get going" + "nice catching up" + lời hứa mơ hồ + take care.',
    },
    targets: [
      target({
        id: 'ch16.t1',
        chunk: 'I should get going',
        cueVi: 'tôi phải đi rồi',
        sourceSentence: 'Anh: Anyway, I should get going. It was nice catching up.',
        productionPattern: 'I should <get going / head out>.',
        transferContext: 'leaving a work lunch',
      }),
      target({
        id: 'ch16.t2',
        chunk: 'nice catching up',
        cueVi: 'vui được nghe chuyện của bạn',
        sourceSentence: 'Anh: Anyway, I should get going. It was nice catching up.',
        productionPattern: 'nice <catching up / talking>.',
        transferContext: 'closing a phone call with an old friend',
      }),
      target({
        id: 'ch16.t3',
        chunk: 'Say hi to Lan for me',
        cueVi: 'gửi lời hỏi thăm Lan giúp tôi',
        sourceSentence: 'Mrs. Chen: You too. Say hi to Lan for me.',
        productionPattern: 'Say hi to <Lan / your family> for me.',
        transferContext: 'asking a friend to greet their partner',
      }),
      target({
        id: 'ch16.t4',
        chunk: 'Will do',
        cueVi: 'sẽ làm/ngay đây',
        sourceSentence: 'Anh: Will do. Let us have coffee sometime.',
        productionPattern: '<Will do / Sure will>.',
        transferContext: 'agreeing to pass on a message',
      }),
      target({
        id: 'ch16.t5',
        chunk: 'have coffee sometime',
        cueVi: 'lúc nào đi uống cà phê',
        sourceSentence: 'Anh: Will do. Let us have coffee sometime.',
        productionPattern: 'have <coffee / lunch> sometime.',
        transferContext: 'leaving a vague plan with a colleague',
      }),
      target({
        id: 'ch16.t6',
        chunk: 'Take care',
        cueVi: 'giữ gìn sức khỏe',
        sourceSentence: 'Mrs. Chen: I would like that. Take care.',
        productionPattern: '<Take care / Stay safe>.',
        transferContext: 'ending a call with a relative',
      }),
      target({
        id: 'ch16.t7',
        chunk: 'See you around',
        cueVi: 'hẹn gặp lại (mơ hồ)',
        sourceSentence: 'Anh: You too. See you around.',
        productionPattern: 'See you <around / soon>.',
        transferContext: 'parting from a gym acquaintance',
      }),
    ],
    transferTask: {
      prompt: 'Close a different exchange — a work call — with exit line + warm closer + vague next plan.',
      promptVi: 'Kết thúc một cuộc trao đổi khác — cuộc gọi công việc — câu thoát + lời kết ấm + kế hoạch mơ hồ.',
      changesDimension: 'phone/work register + same three-beat close',
    },
    recyclingFrom: ['sv01'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch17',
    level: 'a2',
    track: 'chunks',
    capabilities: ['agree-politely', 'disagree-politely'],
    title: 'Agreeing and pushing back',
    titleVi: 'Đồng ý và phản đối',
    task: 'Agree or push back without hard "no"',
    context: 'Deciding on a team lunch spot.',
    outcome: 'You can agree, agree-with-but, and offer a counter.',
    input: {
      title: 'CH17 · Team lunch',
      text: [
        'Tom: Let us get burgers today.',
        'Anh: I am with you on that. Burgers sound good.',
        'Mai: Hmm, I see your point, but I had burgers yesterday.',
        'Tom: Fair. What are you thinking?',
        'Mai: How about the noodle place? Same price, faster.',
        'Anh: Good point. Noodles it is.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"I am with you" đồng thuận; "I see your point, but" phản bác êm; "X it is" chốt lựa chọn.',
    },
    targets: [
      target({
        id: 'ch17.t1',
        chunk: 'Let us get burgers',
        cueVi: 'ăn burger đi',
        sourceSentence: 'Tom: Let us get burgers today.',
        productionPattern: 'Let us get <burgers / noodles>.',
        transferContext: 'proposing a quick lunch',
      }),
      target({
        id: 'ch17.t2',
        chunk: 'I am with you',
        cueVi: 'tôi đồng ý/đi với bạn',
        sourceSentence: 'Anh: I am with you on that. Burgers sound good.',
        productionPattern: 'I am with <you / that>.',
        transferContext: "backing a colleague's idea in a meeting",
      }),
      target({
        id: 'ch17.t3',
        chunk: 'Burgers sound good',
        cueVi: 'burger nghe ổn',
        sourceSentence: 'Anh: I am with you on that. Burgers sound good.',
        productionPattern: '<Burgers / That> sounds good.',
        transferContext: 'approving a dinner suggestion',
      }),
      target({
        id: 'ch17.t4',
        chunk: 'I see your point',
        cueVi: 'tôi hiểu ý bạn',
        sourceSentence: 'Mai: Hmm, I see your point, but I had burgers yesterday.',
        productionPattern: 'I see your point, but <I had that yesterday>.',
        transferContext: 'disagreeing about a restaurant choice',
      }),
      target({
        id: 'ch17.t5',
        chunk: 'I had burgers yesterday',
        cueVi: 'hôm qua tôi ăn burger rồi',
        sourceSentence: 'Mai: Hmm, I see your point, but I had burgers yesterday.',
        productionPattern: 'I had <burgers / that> yesterday.',
        transferContext: 'explaining fatigue with a food',
      }),
      target({
        id: 'ch17.t6',
        chunk: 'What are you thinking',
        cueVi: 'bạn đang nghĩ gì',
        sourceSentence: 'Tom: Fair. What are you thinking?',
        productionPattern: 'What are you <thinking / feeling>?',
        transferContext: "asking a partner's preference",
      }),
      target({
        id: 'ch17.t7',
        chunk: 'Same price, faster',
        cueVi: 'cùng giá, nhanh hơn',
        sourceSentence: 'Mai: How about the noodle place? Same price, faster.',
        productionPattern: 'Same <price, faster / distance, better>.',
        transferContext: 'pitching an efficient option',
      }),
      target({
        id: 'ch17.t8',
        chunk: 'Noodles it is',
        cueVi: 'chốt mì nhé',
        sourceSentence: 'Anh: Good point. Noodles it is.',
        productionPattern: '<Noodles / Tuesday> it is.',
        transferContext: 'confirming a group decision',
      }),
    ],
    transferTask: {
      prompt: 'Push back on a different proposal — meeting time — with I see your point but + counter.',
      promptVi: 'Phản đối một đề xuất khác — giờ họp — với I see your point but + phương án khác.',
      changesDimension: 'schedule topic + counter-proposal structure',
    },
    recyclingFrom: ['ev18'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ch18',
    level: 'a2',
    track: 'chunks',
    capabilities: ['make-offer', 'request-help'],
    title: 'Offers and favors',
    titleVi: 'Đề nghị giúp và nhờ vả',
    task: 'Offer help and ask a small favor gracefully',
    context: 'Helping a colleague carry things and asking a favor back.',
    outcome: 'You can offer, accept, and request small helps.',
    input: {
      title: 'CH18 · Small favors',
      text: [
        'Anh: Those boxes look heavy. Want a hand?',
        'Tom: Thanks, that would be great.',
        'Anh: Where do they go?',
        'Tom: Just down the hall. Actually, could you do me a favor after this?',
        'Anh: Sure, what is it?',
        'Tom: Could you water my plant while I am away Friday?',
        'Anh: No problem at all. It is the least I can do.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"Want a hand" đề nghị giúp; "could you do me a favor" nhờ vả; "the least I can do" lịch sự.',
    },
    targets: [
      target({
        id: 'ch18.t1',
        chunk: 'look heavy',
        cueVi: 'trông nặng quá',
        sourceSentence: 'Anh: Those boxes look heavy. Want a hand?',
        productionPattern: 'look <heavy / full / busy>.',
        transferContext: 'noticing a stranger struggling with bags',
      }),
      target({
        id: 'ch18.t2',
        chunk: 'Want a hand',
        cueVi: 'cần giúp một tay không',
        sourceSentence: 'Anh: Those boxes look heavy. Want a hand?',
        productionPattern: 'Want a <hand / lift>?',
        transferContext: 'offering to help carry groceries',
      }),
      target({
        id: 'ch18.t3',
        chunk: 'that would be great',
        cueVi: 'vậy thì tốt quá',
        sourceSentence: 'Tom: Thanks, that would be great.',
        productionPattern: 'that would be <great / lovely / helpful>.',
        transferContext: 'accepting an offered ride',
      }),
      target({
        id: 'ch18.t4',
        chunk: 'down the hall',
        cueVi: 'xuống cuối hành lang',
        sourceSentence: 'Tom: Just down the hall. Actually, could you do me a favor after this?',
        productionPattern: 'down <the hall / the street>.',
        transferContext: 'directing someone to a room',
      }),
      target({
        id: 'ch18.t5',
        chunk: 'do me a favor',
        cueVi: 'giúp tôi một việc',
        sourceSentence: 'Tom: Just down the hall. Actually, could you do me a favor after this?',
        productionPattern: 'do me a <favor / solid>.',
        transferContext: 'asking a friend to check your mail',
      }),
      target({
        id: 'ch18.t6',
        chunk: 'water my plant',
        cueVi: 'tưới cây giúp tôi',
        sourceSentence: 'Tom: Could you water my plant while I am away Friday?',
        productionPattern: 'water my <plant / plants>.',
        transferContext: 'asking a neighbor to feed a cat',
      }),
      target({
        id: 'ch18.t7',
        chunk: 'while I am away',
        cueVi: 'trong lúc tôi đi vắng',
        sourceSentence: 'Tom: Could you water my plant while I am away Friday?',
        productionPattern: 'while I am <away / out of town>.',
        transferContext: 'asking someone to collect packages',
      }),
      target({
        id: 'ch18.t8',
        chunk: 'the least I can do',
        cueVi: 'chuyện nhỏ thôi mà',
        sourceSentence: 'Anh: No problem at all. It is the least I can do.',
        productionPattern: 'It is the <least I can do / least I can offer>.',
        transferContext: 'dismissing thanks after helping',
      }),
    ],
    transferTask: {
      prompt: 'Offer help with a different task — heavy luggage — then ask a small return favor.',
      promptVi: 'Đề nghị giúp một việc khác — vali nặng — rồi nhờ lại một việc nhỏ.',
      changesDimension: 'travel context + reciprocal favor flow',
    },
    recyclingFrom: ['sv08'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.functions],
  }),
];
