/* Developer English dv13–dv24 — meetings, async work, incidents, demos. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const DEVELOPER_2: LessonSpec[] = [
  spec({
    id: 'dv13',
    level: 'a2',
    track: 'developer',
    capabilities: ['estimate-uncertainty'],
    title: 'Estimate with honesty',
    titleVi: 'Ước lượng trung thực',
    task: 'Give an estimate that carries its uncertainty',
    context: 'PM asks how long a feature will take.',
    outcome: 'You can estimate with a range and flag unknowns.',
    input: {
      title: 'DV13 · Estimating',
      text: [
        'PM: How long will the search filter take?',
        'Minh: Rough guess — two to three days if the API cooperates.',
        'PM: If it does not?',
        'Minh: Then closer to a week. The unknown is the indexing side.',
        'PM: Can you give me a firmer date by tomorrow?',
        'Minh: Sure. I will spike it this afternoon and report back.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Ước lượng: range + unknown + spike trước khi chốt. "rough guess" = ước lượng thô.',
    },
    targets: [
      target({
        id: 'dv13.t1',
        chunk: 'How long will the search filter take',
        cueVi: 'filter search mất bao lâu',
        sourceSentence: 'PM: How long will the search filter take?',
        productionPattern: 'How long will <the filter / the fix> take?',
        transferContext: 'hearing an estimate question',
      }),
      target({
        id: 'dv13.t2',
        chunk: 'Rough guess',
        cueVi: 'ước chừng thô',
        sourceSentence: 'Minh: Rough guess — two to three days if the API cooperates.',
        productionPattern: 'Rough guess — <two to three / four> days.',
        transferContext: 'giving a preliminary estimate',
      }),
      target({
        id: 'dv13.t3',
        chunk: 'if the API cooperates',
        cueVi: 'nếu API hợp tác',
        sourceSentence: 'Minh: Rough guess — two to three days if the API cooperates.',
        productionPattern: 'if the <API / data> cooperates.',
        transferContext: 'flagging a dependency risk',
      }),
      target({
        id: 'dv13.t4',
        chunk: 'closer to a week',
        cueVi: 'gần một tuần hơn',
        sourceSentence: 'Minh: Then closer to a week. The unknown is the indexing side.',
        productionPattern: 'closer to <a week / two weeks>.',
        transferContext: 'revising an estimate upward',
      }),
      target({
        id: 'dv13.t5',
        chunk: 'The unknown is',
        cueVi: 'điều chưa biết là',
        sourceSentence: 'Minh: Then closer to a week. The unknown is the indexing side.',
        productionPattern: 'The unknown is <the indexing / the third-party>.',
        transferContext: 'naming the risk factor',
      }),
      target({
        id: 'dv13.t6',
        chunk: 'a firmer date',
        cueVi: 'ngày chắc hơn',
        sourceSentence: 'PM: Can you give me a firmer date by tomorrow?',
        productionPattern: 'a <firmer / harder> date.',
        transferContext: 'asking for a commitment',
      }),
      target({
        id: 'dv13.t7',
        chunk: 'spike it',
        cueVi: 'thử nghiệm nhanh (spike)',
        sourceSentence: 'Minh: Sure. I will spike it this afternoon and report back.',
        productionPattern: 'spike <it / the approach>.',
        transferContext: 'proposing a timeboxed investigation',
      }),
      target({
        id: 'dv13.t8',
        chunk: 'report back',
        cueVi: 'báo lại',
        sourceSentence: 'Minh: Sure. I will spike it this afternoon and report back.',
        productionPattern: 'report <back / tomorrow>.',
        transferContext: 'promising a follow-up answer',
      }),
    ],
    transferTask: {
      prompt: 'Estimate a different task — migrating the user table — range, unknown, spike plan.',
      promptVi: 'Ước lượng việc khác — migrate bảng users — range, unknown, kế hoạch spike.',
      changesDimension: 'data migration + same estimate frame',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv14',
    level: 'a2',
    track: 'developer',
    capabilities: ['handoff-work'],
    title: 'Hand off a task',
    titleVi: 'Bàn giao công việc',
    task: 'Hand a task to a teammate with context and gotchas',
    context: 'You are going on leave; someone takes your task.',
    outcome: 'You can hand off with status, risks, and pointers.',
    input: {
      title: 'DV14 · Handoff',
      text: [
        'Minh: Handing off the invoice feature while I am out.',
        'Sara: Where are things at?',
        'Minh: Core logic is done. The PDF export is half-finished.',
        'Sara: Any gotchas I should know?',
        'Minh: Watch out for timezone handling — it bit me twice.',
        'Sara: Docs anywhere?',
        'Minh: Notes are in the ticket, plus a short loom video.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Handoff: status → gotchas → pointers. "it bit me" = nó làm tôi vấp.',
    },
    targets: [
      target({
        id: 'dv14.t1',
        chunk: 'Handing off',
        cueVi: 'đang bàn giao',
        sourceSentence: 'Minh: Handing off the invoice feature while I am out.',
        productionPattern: 'Handing off <the invoice feature / this ticket>.',
        transferContext: 'announcing a handoff',
      }),
      target({
        id: 'dv14.t2',
        chunk: 'while I am out',
        cueVi: 'trong lúc tôi vắng',
        sourceSentence: 'Minh: Handing off the invoice feature while I am out.',
        productionPattern: 'while I am <out / away / on leave>.',
        transferContext: 'explaining an absence handoff',
      }),
      target({
        id: 'dv14.t3',
        chunk: 'Where are things at',
        cueVi: 'tiến độ đến đâu',
        sourceSentence: 'Sara: Where are things at?',
        productionPattern: 'Where are <things / we> at?',
        transferContext: 'asking status on a task',
      }),
      target({
        id: 'dv14.t4',
        chunk: 'half-finished',
        cueVi: 'làm dở nửa',
        sourceSentence: 'Minh: Core logic is done. The PDF export is half-finished.',
        productionPattern: '<half-finished / mostly done>.',
        transferContext: 'reporting partial completion',
      }),
      target({
        id: 'dv14.t5',
        chunk: 'Any gotchas',
        cueVi: 'có cạm bẫy gì không',
        sourceSentence: 'Sara: Any gotchas I should know?',
        productionPattern: 'Any <gotchas / landmines>?',
        transferContext: 'asking about hidden risks',
      }),
      target({
        id: 'dv14.t6',
        chunk: 'Watch out for',
        cueVi: 'coi chừng',
        sourceSentence: 'Minh: Watch out for timezone handling — it bit me twice.',
        productionPattern: 'Watch out for <timezone / edge cases>.',
        transferContext: 'warning about a tricky area',
      }),
      target({
        id: 'dv14.t7',
        chunk: 'it bit me twice',
        cueVi: 'nó làm tôi vấp hai lần',
        sourceSentence: 'Minh: Watch out for timezone handling — it bit me twice.',
        productionPattern: 'it <bit me / burned me> twice.',
        transferContext: 'admitting past mistakes on an area',
      }),
      target({
        id: 'dv14.t8',
        chunk: 'a short loom video',
        cueVi: 'một video loom ngắn',
        sourceSentence: 'Minh: Notes are in the ticket, plus a short loom video.',
        productionPattern: 'a <short loom / quick demo> video.',
        transferContext: 'pointing to a recorded walkthrough',
      }),
    ],
    transferTask: {
      prompt: 'Hand off a different task — a flaky integration — status, one gotcha, where docs live.',
      promptVi: 'Bàn giao việc khác — một integration hay lỗi — trạng thái, một gotcha, chỗ docs.',
      changesDimension: 'different task type + same handoff skeleton',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv15',
    level: 'a2',
    track: 'developer',
    capabilities: ['ask-documentation'],
    title: 'Ask for documentation',
    titleVi: 'Hỏi tài liệu',
    task: 'Ask where docs are and request what is missing',
    context: 'You cannot find docs for the auth service.',
    outcome: 'You can locate docs and flag gaps politely.',
    input: {
      title: 'DV15 · Missing docs',
      text: [
        'Minh: Is there a doc for the auth service somewhere?',
        'Sara: There is a README in the repo — a bit outdated though.',
        'Minh: It does not cover the token flow at all.',
        'Sara: Yeah, that part changed last sprint. Nobody wrote it up.',
        'Minh: Could you point me to whoever changed it?',
        'Sara: Talk to Linh. And feel free to add notes as you go.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Docs hunt: is there a doc → outdated → missing section → ask the person → write as you go.',
    },
    targets: [
      target({
        id: 'dv15.t1',
        chunk: 'Is there a doc for',
        cueVi: 'có tài liệu cho ~ không',
        sourceSentence: 'Minh: Is there a doc for the auth service somewhere?',
        productionPattern: 'Is there a doc for <the auth service / the API>?',
        transferContext: 'asking for API documentation',
      }),
      target({
        id: 'dv15.t2',
        chunk: 'a bit outdated',
        cueVi: 'hơi lỗi thời',
        sourceSentence: 'Sara: There is a README in the repo — a bit outdated though.',
        productionPattern: '<a bit / pretty> outdated.',
        transferContext: 'describing stale documentation',
      }),
      target({
        id: 'dv15.t3',
        chunk: 'the token flow',
        cueVi: 'luồng token',
        sourceSentence: 'Minh: It does not cover the token flow at all.',
        productionPattern: 'the <token / auth / deploy> flow.',
        transferContext: 'naming a missing doc section',
      }),
      target({
        id: 'dv15.t4',
        chunk: 'at all',
        cueVi: 'hoàn toàn không',
        sourceSentence: 'Minh: It does not cover the token flow at all.',
        productionPattern: 'at <all>.',
        transferContext: 'stressing total absence',
      }),
      target({
        id: 'dv15.t5',
        chunk: 'last sprint',
        cueVi: 'sprint trước',
        sourceSentence: 'Sara: Yeah, that part changed last sprint. Nobody wrote it up.',
        productionPattern: 'last <sprint / release / week>.',
        transferContext: 'placing a change in time',
      }),
      target({
        id: 'dv15.t6',
        chunk: 'Nobody wrote it up',
        cueVi: 'không ai viết lại',
        sourceSentence: 'Sara: Yeah, that part changed last sprint. Nobody wrote it up.',
        productionPattern: 'Nobody <wrote it up / documented it>.',
        transferContext: 'explaining a documentation gap',
      }),
      target({
        id: 'dv15.t7',
        chunk: 'point me to',
        cueVi: 'chỉ tôi đến',
        sourceSentence: 'Minh: Could you point me to whoever changed it?',
        productionPattern: 'point me to <whoever changed it / the owner>.',
        transferContext: 'finding the right person',
      }),
      target({
        id: 'dv15.t8',
        chunk: 'as you go',
        cueVi: 'trên đường làm',
        sourceSentence: 'Sara: Talk to Linh. And feel free to add notes as you go.',
        productionPattern: 'as you <go / learn / work>.',
        transferContext: 'encouraging docs contribution',
      }),
    ],
    transferTask: {
      prompt: 'Hunt docs for a different system — the deploy pipeline — and flag one missing section.',
      promptVi: 'Tìm docs cho hệ thống khác — deploy pipeline — và chỉ một phần còn thiếu.',
      changesDimension: 'different system + same doc-hunt flow',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv16',
    level: 'a2',
    track: 'developer',
    capabilities: ['participate-meeting'],
    title: 'Speak up in a meeting',
    titleVi: 'Phát biểu trong họp',
    task: 'Jump into a meeting without waiting forever',
    context: 'A planning meeting where your input is needed.',
    outcome: 'You can enter a conversation politely mid-flow.',
    input: {
      title: 'DV16 · Meetings',
      text: [
        'Lead: So we are leaning toward option B.',
        'Minh: Sorry to jump in — can I add something?',
        'Lead: Go ahead.',
        'Minh: Just a heads-up: option B doubles our API calls.',
        'Lead: Good catch. Any data on that?',
        'Minh: Rough numbers — I can pull the metrics today.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Vào cuộc họp: sorry to jump in → heads-up → good catch + offer data. "pull metrics" = lấy số liệu.',
    },
    targets: [
      target({
        id: 'dv16.t1',
        chunk: 'leaning toward option B',
        cueVi: 'nghiêng về phương án B',
        sourceSentence: 'Lead: So we are leaning toward option B.',
        productionPattern: 'leaning toward <option B / the simpler one>.',
        transferContext: 'hearing a group preference',
      }),
      target({
        id: 'dv16.t2',
        chunk: 'Sorry to jump in',
        cueVi: 'xin lỗi xen vào',
        sourceSentence: 'Minh: Sorry to jump in — can I add something?',
        productionPattern: 'Sorry to <jump in / interrupt>.',
        transferContext: 'entering any live discussion',
      }),
      target({
        id: 'dv16.t3',
        chunk: 'can I add something',
        cueVi: 'tôi có thể thêm ý không',
        sourceSentence: 'Minh: Sorry to jump in — can I add something?',
        productionPattern: 'can I <add something / chime in>?',
        transferContext: 'requesting the floor politely',
      }),
      target({
        id: 'dv16.t4',
        chunk: 'Go ahead',
        cueVi: 'cứ nói/tiếp đi',
        sourceSentence: 'Lead: Go ahead.',
        productionPattern: 'Go <ahead / on>.',
        transferContext: 'yielding the floor to someone',
      }),
      target({
        id: 'dv16.t5',
        chunk: 'Just a heads-up',
        cueVi: 'chỉ nhắc trước thôi',
        sourceSentence: 'Minh: Just a heads-up: option B doubles our API calls.',
        productionPattern: 'Just a <heads-up / quick note>.',
        transferContext: 'flagging info without blocking',
      }),
      target({
        id: 'dv16.t6',
        chunk: 'doubles our API calls',
        cueVi: 'tăng gấp đôi số call API',
        sourceSentence: 'Minh: Just a heads-up: option B doubles our API calls.',
        productionPattern: 'doubles <our API calls / the cost>.',
        transferContext: 'quantifying a downside',
      }),
      target({
        id: 'dv16.t7',
        chunk: 'Good catch',
        cueVi: 'phát hiện hay',
        sourceSentence: 'Lead: Good catch. Any data on that?',
        productionPattern: 'Good <catch / point / call>.',
        transferContext: 'praising a sharp observation',
      }),
      target({
        id: 'dv16.t8',
        chunk: 'pull the metrics',
        cueVi: 'lấy số liệu',
        sourceSentence: 'Minh: Rough numbers — I can pull the metrics today.',
        productionPattern: 'pull the <metrics / logs / data>.',
        transferContext: 'offering to fetch data',
      }),
    ],
    transferTask: {
      prompt: 'Enter a different meeting — budget review — jump in, flag a risk, offer data.',
      promptVi: 'Vào một cuộc họp khác — review ngân sách — xen vào, nêu rủi ro, đề nghị số liệu.',
      changesDimension: 'non-technical meeting + same entry moves',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv17',
    level: 'a2',
    track: 'developer',
    capabilities: ['schedule-meeting'],
    title: 'Schedule and move meetings',
    titleVi: 'Hẹn và dời lịch họp',
    task: 'Propose, confirm, and reschedule meeting times',
    context: 'Setting up a sync with a teammate in another timezone.',
    outcome: 'You can negotiate a time that works for both.',
    input: {
      title: 'DV17 · Scheduling',
      text: [
        'Minh: Can we find thirty minutes this week for a sync?',
        'Sara: Sure. Wednesday afternoon works for me.',
        'Minh: Afternoon your time or mine? You are two hours ahead.',
        'Sara: Good point. Let us say three your time, five mine.',
        'Minh: Works. Can we push it to Thursday though? Wednesday is stacked.',
        'Sara: Thursday is fine. Sending the invite now.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Hẹn xuyên timezone: hỏi rõ "your time or mine"; "stacked" = kín lịch; push it = dời.',
    },
    targets: [
      target({
        id: 'dv17.t1',
        chunk: 'find thirty minutes',
        cueVi: 'tìm 30 phút trống',
        sourceSentence: 'Minh: Can we find thirty minutes this week for a sync?',
        productionPattern: 'find <thirty / fifteen> minutes.',
        transferContext: 'requesting meeting time',
      }),
      target({
        id: 'dv17.t2',
        chunk: 'for a sync',
        cueVi: 'để sync/trò chuyện',
        sourceSentence: 'Minh: Can we find thirty minutes this week for a sync?',
        productionPattern: 'for a <sync / catch-up / review>.',
        transferContext: 'naming the meeting purpose',
      }),
      target({
        id: 'dv17.t3',
        chunk: 'Wednesday afternoon works',
        cueVi: 'chiều thứ tư được',
        sourceSentence: 'Sara: Sure. Wednesday afternoon works for me.',
        productionPattern: '<Wednesday / Friday> afternoon works.',
        transferContext: 'confirming a time block',
      }),
      target({
        id: 'dv17.t4',
        chunk: 'your time or mine',
        cueVi: 'giờ của bạn hay tôi',
        sourceSentence: 'Minh: Afternoon your time or mine? You are two hours ahead.',
        productionPattern: 'your <time / timezone> or mine?',
        transferContext: 'clarifying timezone confusion',
      }),
      target({
        id: 'dv17.t5',
        chunk: 'two hours ahead',
        cueVi: 'sớm hơn hai tiếng',
        sourceSentence: 'Minh: Afternoon your time or mine? You are two hours ahead.',
        productionPattern: '<two / three> hours ahead.',
        transferContext: 'stating a timezone offset',
      }),
      target({
        id: 'dv17.t6',
        chunk: 'push it to Thursday',
        cueVi: 'dời sang thứ năm',
        sourceSentence: 'Minh: Works. Can we push it to Thursday though? Wednesday is stacked.',
        productionPattern: 'push it to <Thursday / next week>.',
        transferContext: 'rescheduling a meeting',
      }),
      target({
        id: 'dv17.t7',
        chunk: 'is stacked',
        cueVi: 'kín lịch',
        sourceSentence: 'Minh: Works. Can we push it to Thursday though? Wednesday is stacked.',
        productionPattern: 'is <stacked / packed / full>.',
        transferContext: 'explaining a busy day',
      }),
      target({
        id: 'dv17.t8',
        chunk: 'Sending the invite',
        cueVi: 'đang gửi lời mời',
        sourceSentence: 'Sara: Thursday is fine. Sending the invite now.',
        productionPattern: 'Sending the <invite / calendar> now.',
        transferContext: 'confirming you sent the invite',
      }),
    ],
    transferTask: {
      prompt: 'Schedule a different sync — with someone three hours behind — propose, clarify, confirm.',
      promptVi: 'Hẹn sync khác — người chậm hơn ba tiếng — đề xuất, làm rõ, chốt.',
      changesDimension: 'different offset direction + same negotiation',
    },
    recyclingFrom: ['ev02', 'ev23'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv18',
    level: 'a2',
    track: 'developer',
    capabilities: ['message-async'],
    title: 'Write clear async messages',
    titleVi: 'Viết tin nhắn async rõ ràng',
    task: 'Write a Slack message that gets a fast answer',
    context: 'You need a decision from a busy lead.',
    outcome: 'You can front-load the ask and context.',
    input: {
      title: 'DV18 · Async ask',
      text: [
        'Hi Linh — need a decision on the search icon when you get a sec.',
        'Context: two options in Figma, A (magnifier) and B (sparkle).',
        'My rec: A — more standard, users will not miss it.',
        'No rush, but it blocks the nav PR.',
        'Thanks!',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Async message: ask up front → context → recommendation → deadline/blocking info → thanks.',
    },
    targets: [
      target({
        id: 'dv18.t1',
        chunk: 'when you get a sec',
        cueVi: 'khi nào rảnh một chút',
        sourceSentence: 'Hi Linh — need a decision on the search icon when you get a sec.',
        productionPattern: 'when you get a <sec / chance / minute>.',
        transferContext: 'softening an async ask',
      }),
      target({
        id: 'dv18.t2',
        chunk: 'need a decision on',
        cueVi: 'cần quyết định về',
        sourceSentence: 'Hi Linh — need a decision on the search icon when you get a sec.',
        productionPattern: 'need a decision on <the icon / the copy>.',
        transferContext: 'stating what is blocked on them',
      }),
      target({
        id: 'dv18.t3',
        chunk: 'two options in Figma',
        cueVi: 'hai phương án trong Figma',
        sourceSentence: 'Context: two options in Figma, A (magnifier) and B (sparkle).',
        productionPattern: 'two options in <Figma / the doc>.',
        transferContext: 'pointing to where options live',
      }),
      target({
        id: 'dv18.t4',
        chunk: 'My rec',
        cueVi: 'đề xuất của tôi',
        sourceSentence: 'My rec: A — more standard, users will not miss it.',
        productionPattern: 'My <rec / take>: <option>.',
        transferContext: 'offering your recommendation',
      }),
      target({
        id: 'dv18.t5',
        chunk: 'more standard',
        cueVi: 'chuẩn hơn/phổ biến hơn',
        sourceSentence: 'My rec: A — more standard, users will not miss it.',
        productionPattern: 'more <standard / common / intuitive>.',
        transferContext: 'justifying a UX choice',
      }),
      target({
        id: 'dv18.t6',
        chunk: 'No rush',
        cueVi: 'không gấp',
        sourceSentence: 'No rush, but it blocks the nav PR.',
        productionPattern: 'No <rush / hurry>, but <reason>.',
        transferContext: 'giving deadline context politely',
      }),
      target({
        id: 'dv18.t7',
        chunk: 'it blocks the nav PR',
        cueVi: 'nó chặn PR thanh nav',
        sourceSentence: 'No rush, but it blocks the nav PR.',
        productionPattern: 'it blocks <the nav PR / the release>.',
        transferContext: 'explaining why the ask matters',
      }),
    ],
    transferTask: {
      prompt: 'Write an async message for a different need — API key access — ask, context, deadline.',
      promptVi: 'Viết tin nhắn async cho nhu cầu khác — xin API key — ask, context, deadline.',
      changesDimension: 'access request not design decision + same structure',
    },
    recyclingFrom: ['dv02'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv19',
    level: 'a2',
    track: 'developer',
    capabilities: ['demo-feature'],
    title: 'Demo a feature',
    titleVi: 'Demo tính năng',
    task: 'Narrate a short demo of what you built',
    context: 'Showing your feature in the team demo meeting.',
    outcome: 'You can walk through a demo with signposts.',
    input: {
      title: 'DV19 · Demo',
      text: [
        'Minh: Okay, sharing my screen — can everyone see it?',
        'Team: Yes, we see it.',
        'Minh: This is the new filter. First, I open the dropdown.',
        'Minh: Then I pick a date range — notice the list updates live.',
        'Minh: And here is the edge case: empty results get a friendly message.',
        'Minh: Questions or should I keep going?',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Demo flow: screen check → what it is → steps → edge case → invite questions.',
    },
    targets: [
      target({
        id: 'dv19.t1',
        chunk: 'sharing my screen',
        cueVi: 'đang chia sẻ màn hình',
        sourceSentence: 'Minh: Okay, sharing my screen — can everyone see it?',
        productionPattern: 'sharing my <screen / window>.',
        transferContext: 'starting any screen-share demo',
      }),
      target({
        id: 'dv19.t2',
        chunk: 'can everyone see it',
        cueVi: 'mọi người thấy không',
        sourceSentence: 'Minh: Okay, sharing my screen — can everyone see it?',
        productionPattern: 'can <everyone / you all> see it?',
        transferContext: 'checking visibility before demo',
      }),
      target({
        id: 'dv19.t3',
        chunk: 'I open the dropdown',
        cueVi: 'tôi mở dropdown',
        sourceSentence: 'Minh: This is the new filter. First, I open the dropdown.',
        productionPattern: 'I <open / click / select> the dropdown.',
        transferContext: 'narrating a UI action',
      }),
      target({
        id: 'dv19.t5',
        chunk: 'a date range',
        cueVi: 'khoảng ngày',
        sourceSentence: 'Minh: Then I pick a date range — notice the list updates live.',
        productionPattern: 'a <date / price> range.',
        transferContext: 'describing a filter option',
      }),
      target({
        id: 'dv19.t6',
        chunk: 'updates live',
        cueVi: 'cập nhật trực tiếp',
        sourceSentence: 'Minh: Then I pick a date range — notice the list updates live.',
        productionPattern: 'updates <live / in real time>.',
        transferContext: 'highlighting reactive behavior',
      }),
      target({
        id: 'dv19.t7',
        chunk: 'the edge case',
        cueVi: 'trường hợp biên',
        sourceSentence: 'Minh: And here is the edge case: empty results get a friendly message.',
        productionPattern: 'the <edge case / error state>.',
        transferContext: 'showing boundary behavior',
      }),
      target({
        id: 'dv19.t8',
        chunk: 'a friendly message',
        cueVi: 'thông báo thân thiện',
        sourceSentence: 'Minh: And here is the edge case: empty results get a friendly message.',
        productionPattern: 'a <friendly / helpful> message.',
        transferContext: 'describing empty-state copy',
      }),
      target({
        id: 'dv19.t9',
        chunk: 'should I keep going',
        cueVi: 'tôi có nên tiếp tục không',
        sourceSentence: 'Minh: Questions or should I keep going?',
        productionPattern: 'should I <keep going / pause here>?',
        transferContext: 'checking audience engagement',
      }),
    ],
    transferTask: {
      prompt: 'Demo a different feature — an export button — screen check, steps, edge case.',
      promptVi: 'Demo tính năng khác — nút export — check màn hình, các bước, edge case.',
      changesDimension: 'different feature + same demo spine',
    },
    recyclingFrom: ['dv16'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv20',
    level: 'a2',
    track: 'developer',
    capabilities: ['postmortem-writeup'],
    title: 'Postmortem summary',
    titleVi: 'Tóm tắt postmortem',
    task: 'Summarize what broke and what you learned',
    context: "Writing the postmortem after yesterday's outage.",
    outcome: 'You can write a blameless incident summary.',
    input: {
      title: 'DV20 · Postmortem',
      text: [
        'Postmortem — outage on March twelfth.',
        'Summary: login broke for ninety minutes after a bad migration.',
        'Root cause: a missing index check slowed queries to timeout.',
        'What went well: rollback was fast — under ten minutes.',
        'What we learned: test migrations on a copy of prod data.',
        'Action items: add a migration checklist by Friday.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Postmortem không đổ lỗi: summary → root cause → went well → learned → action items.',
    },
    targets: [
      target({
        id: 'dv20.t2',
        chunk: 'for ninety minutes',
        cueVi: 'trong 90 phút',
        sourceSentence: 'Summary: login broke for ninety minutes after a bad migration.',
        productionPattern: 'for <ninety / sixty> minutes.',
        transferContext: 'stating incident duration',
      }),
      target({
        id: 'dv20.t3',
        chunk: 'a bad migration',
        cueVi: 'migration lỗi',
        sourceSentence: 'Summary: login broke for ninety minutes after a bad migration.',
        productionPattern: 'a <bad / failed> migration.',
        transferContext: 'naming the triggering change',
      }),
      target({
        id: 'dv20.t4',
        chunk: 'Root cause',
        cueVi: 'nguyên nhân gốc',
        sourceSentence: 'Root cause: a missing index check slowed queries to timeout.',
        productionPattern: 'Root <cause / reason>.',
        transferContext: 'labeling the cause section',
      }),
      target({
        id: 'dv20.t5',
        chunk: 'a missing index check',
        cueVi: 'thiếu kiểm tra index',
        sourceSentence: 'Root cause: a missing index check slowed queries to timeout.',
        productionPattern: 'a missing <index check / validation>.',
        transferContext: 'describing a different root cause',
      }),
      target({
        id: 'dv20.t6',
        chunk: 'slowed queries to timeout',
        cueVi: 'làm query chậm đến timeout',
        sourceSentence: 'Root cause: a missing index check slowed queries to timeout.',
        productionPattern: 'slowed <queries / requests> to timeout.',
        transferContext: 'describing a performance failure',
      }),
      target({
        id: 'dv20.t7',
        chunk: 'What went well',
        cueVi: 'điều đã tốt',
        sourceSentence: 'What went well: rollback was fast — under ten minutes.',
        productionPattern: 'What went <well / wrong>.',
        transferContext: 'opening the positives section',
      }),
      target({
        id: 'dv20.t8',
        chunk: 'What we learned',
        cueVi: 'điều học được',
        sourceSentence: 'What we learned: test migrations on a copy of prod data.',
        productionPattern: 'What we <learned / missed>.',
        transferContext: 'opening the lessons section',
      }),
      target({
        id: 'dv20.t10',
        chunk: 'Action items',
        cueVi: 'đầu việc cần làm',
        sourceSentence: 'Action items: add a migration checklist by Friday.',
        productionPattern: 'Action <items / steps>.',
        transferContext: 'opening the follow-ups section',
      }),
    ],
    transferTask: {
      prompt: 'Write a postmortem for a different incident — a deploy that broke images.',
      promptVi: 'Viết postmortem cho sự cố khác — deploy làm hỏng ảnh.',
      changesDimension: 'different failure + same blameless sections',
    },
    recyclingFrom: ['dv11'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv21',
    level: 'a2',
    track: 'developer',
    capabilities: ['clarify-requirements', 'estimate-uncertainty'],
    title: 'Flag a risk early',
    titleVi: 'Báo rủi ro sớm',
    task: 'Raise a project risk before it becomes a problem',
    context: 'You notice a deadline that will probably slip.',
    outcome: 'You can flag risk with evidence and options.',
    input: {
      title: 'DV21 · Flagging risk',
      text: [
        'Minh: Flagging something early — the April deadline looks tight.',
        'PM: How tight are we talking?',
        'Minh: We have three features left and only two weeks. Realistically we ship two.',
        'PM: Can we cut scope instead?',
        'Minh: Yes — the export feature could slip to May safely.',
        'PM: Good call. Let us update the plan today.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Flag risk: sớm + cụ thể (how tight) + con số thật + offer cắt scope thay vì trễ.',
    },
    targets: [
      target({
        id: 'dv21.t1',
        chunk: 'Flagging something early',
        cueVi: 'báo sớm một điều',
        sourceSentence: 'Minh: Flagging something early — the April deadline looks tight.',
        productionPattern: 'Flagging <something / a risk> early.',
        transferContext: 'raising a concern proactively',
      }),
      target({
        id: 'dv21.t2',
        chunk: 'looks tight',
        cueVi: 'trông căng',
        sourceSentence: 'Minh: Flagging something early — the April deadline looks tight.',
        productionPattern: 'looks <tight / risky / shaky>.',
        transferContext: 'describing schedule pressure',
      }),
      target({
        id: 'dv21.t3',
        chunk: 'How tight are we talking',
        cueVi: 'căng cỡ nào',
        sourceSentence: 'PM: How tight are we talking?',
        productionPattern: 'How <tight / bad> are we talking?',
        transferContext: 'asking severity of a concern',
      }),
      target({
        id: 'dv21.t4',
        chunk: 'three features left',
        cueVi: 'còn ba tính năng',
        sourceSentence: 'Minh: We have three features left and only two weeks.',
        productionPattern: '<three / four> features left.',
        transferContext: 'quantifying remaining work',
      }),
      target({
        id: 'dv21.t5',
        chunk: 'Realistically we ship two',
        cueVi: 'thực tế ta ship được hai',
        sourceSentence: 'Minh: We have three features left and only two weeks. Realistically we ship two.',
        productionPattern: 'Realistically we <ship two / finish half>.',
        transferContext: 'giving a grounded estimate',
      }),
      target({
        id: 'dv21.t6',
        chunk: 'cut scope',
        cueVi: 'cắt phạm vi',
        sourceSentence: 'PM: Can we cut scope instead?',
        productionPattern: 'cut <scope / features / a feature>.',
        transferContext: 'proposing to reduce work',
      }),
      target({
        id: 'dv21.t7',
        chunk: 'slip to May safely',
        cueVi: 'dời sang tháng 5 an toàn',
        sourceSentence: 'Minh: Yes — the export feature could slip to May safely.',
        productionPattern: 'slip to <May / next sprint> safely.',
        transferContext: 'moving a feature to a later release',
      }),
      target({
        id: 'dv21.t8',
        chunk: 'update the plan',
        cueVi: 'cập nhật kế hoạch',
        sourceSentence: 'PM: Good call. Let us update the plan today.',
        productionPattern: 'update the <plan / roadmap / ticket>.',
        transferContext: 'committing to a planning change',
      }),
    ],
    transferTask: {
      prompt: 'Flag a different risk — a dependency that is late — with evidence and a mitigation.',
      promptVi: 'Báo rủi ro khác — dependency trễ — với bằng chứng và phương án giảm thiểu.',
      changesDimension: 'external dependency risk + mitigation offered',
    },
    recyclingFrom: ['dv13'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv22',
    level: 'a2',
    track: 'developer',
    capabilities: ['escalate-issue'],
    title: 'Escalate a blocker',
    titleVi: 'Báo lên trên vấn đề bị kẹt',
    task: 'Escalate when you are blocked and cannot unblock alone',
    context: 'A vendor API has been broken for two days.',
    outcome: 'You can escalate with impact and what you need.',
    input: {
      title: 'DV22 · Escalation',
      text: [
        'Minh: I need to escalate something — the vendor API is still down.',
        'Lead: How long has it been?',
        'Minh: Two days. I opened a ticket, no response yet.',
        'Lead: What is the impact on our side?',
        'Minh: The sync job fails nightly — data is two days stale.',
        'Lead: I will email their account manager today.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Escalate: nêu cần escalate → duration → what you tried → impact → ask for higher-level action.',
    },
    targets: [
      target({
        id: 'dv22.t1',
        chunk: 'I need to escalate something',
        cueVi: 'tôi cần báo lên trên',
        sourceSentence: 'Minh: I need to escalate something — the vendor API is still down.',
        productionPattern: 'I need to escalate <something / this issue>.',
        transferContext: 'raising a blocked issue upward',
      }),
      target({
        id: 'dv22.t2',
        chunk: 'the vendor API',
        cueVi: 'API của đối tác',
        sourceSentence: 'Minh: I need to escalate something — the vendor API is still down.',
        productionPattern: 'the <vendor / payment / partner> API.',
        transferContext: 'naming a third-party dependency',
      }),
      target({
        id: 'dv22.t3',
        chunk: 'still down',
        cueVi: 'vẫn đang sập',
        sourceSentence: 'Minh: I need to escalate something — the vendor API is still down.',
        productionPattern: 'still <down / broken / failing>.',
        transferContext: 'reporting an ongoing outage',
      }),
      target({
        id: 'dv22.t4',
        chunk: 'I opened a ticket',
        cueVi: 'tôi đã mở ticket',
        sourceSentence: 'Minh: Two days. I opened a ticket, no response yet.',
        productionPattern: 'I opened a <ticket / support case>.',
        transferContext: 'documenting what you tried',
      }),
      target({
        id: 'dv22.t5',
        chunk: 'no response yet',
        cueVi: 'chưa có phản hồi',
        sourceSentence: 'Minh: Two days. I opened a ticket, no response yet.',
        productionPattern: 'no <response / reply> yet.',
        transferContext: 'reporting silence from support',
      }),
      target({
        id: 'dv22.t6',
        chunk: 'The sync job fails nightly',
        cueVi: 'job sync fail mỗi đêm',
        sourceSentence: 'Minh: The sync job fails nightly — data is two days stale.',
        productionPattern: 'The <sync / batch> job fails <nightly / hourly>.',
        transferContext: 'describing a recurring failure',
      }),
      target({
        id: 'dv22.t7',
        chunk: 'two days stale',
        cueVi: 'dữ liệu cũ hai ngày',
        sourceSentence: 'Minh: The sync job fails nightly — data is two days stale.',
        productionPattern: '<two days / a week> stale.',
        transferContext: 'quantifying data freshness',
      }),
      target({
        id: 'dv22.t8',
        chunk: 'their account manager',
        cueVi: 'account manager của họ',
        sourceSentence: 'Lead: I will email their account manager today.',
        productionPattern: 'their <account manager / support lead>.',
        transferContext: 'naming a higher-level contact',
      }),
    ],
    transferTask: {
      prompt: 'Escalate a different blocker — missing API credentials for a week — with impact.',
      promptVi: 'Báo lên trên một blocker khác — thiếu API credentials cả tuần — với impact.',
      changesDimension: 'access blocker not outage + same escalation frame',
    },
    recyclingFrom: ['dv06', 'dv21'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv23',
    level: 'a2',
    track: 'developer',
    capabilities: ['small-talk'],
    title: 'Remote small talk',
    titleVi: 'Nói chuyện phiếm remote',
    task: 'Do small talk on a remote team without awkwardness',
    context: 'First minutes of a video call while people join.',
    outcome: 'You can fill the pre-meeting silence naturally.',
    input: {
      title: 'DV23 · Pre-meeting',
      text: [
        'Sara: Morning, Minh. How are things in Da Nang?',
        'Minh: Hot, honestly. How is Berlin — still cold?',
        'Sara: Freezing. I am living on coffee.',
        'Minh: Same. By the way, did you see the game last night?',
        'Sara: I did not — worth watching?',
        'Minh: Skip it. Oh, Tom just joined. Hey Tom.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Remote small talk: weather → coffee → light topic → pivot when person joins.',
    },
    targets: [
      target({
        id: 'dv23.t1',
        chunk: 'How are things in Da Nang',
        cueVi: 'ở Đà Nẵng thế nào',
        sourceSentence: 'Sara: Morning, Minh. How are things in Da Nang?',
        productionPattern: 'How are things in <Da Nang / Berlin>?',
        transferContext: 'asking a remote colleague about their city',
      }),
      target({
        id: 'dv23.t2',
        chunk: 'Hot, honestly',
        cueVi: 'nóng lắm, thật đấy',
        sourceSentence: 'Minh: Hot, honestly. How is Berlin — still cold?',
        productionPattern: '<Hot / Busy / Fine>, honestly.',
        transferContext: 'giving an honest one-word answer',
      }),
      target({
        id: 'dv23.t3',
        chunk: 'still cold',
        cueVi: 'vẫn lạnh à',
        sourceSentence: 'Minh: Hot, honestly. How is Berlin — still cold?',
        productionPattern: 'still <cold / hot / raining>?',
        transferContext: 'checking ongoing weather',
      }),
      target({
        id: 'dv23.t4',
        chunk: 'living on coffee',
        cueVi: 'sống bằng cà phê',
        sourceSentence: 'Sara: Freezing. I am living on coffee.',
        productionPattern: 'living on <coffee / noodles / tea>.',
        transferContext: 'joking about a survival habit',
      }),
      target({
        id: 'dv23.t5',
        chunk: 'did you see the game',
        cueVi: 'có xem trận đấu không',
        sourceSentence: 'Minh: Same. By the way, did you see the game last night?',
        productionPattern: 'did you see <the game / the news>?',
        transferContext: 'opening a light topic',
      }),
      target({
        id: 'dv23.t6',
        chunk: 'worth watching',
        cueVi: 'đáng xem không',
        sourceSentence: 'Sara: I did not — worth watching?',
        productionPattern: 'worth <watching / reading / trying>?',
        transferContext: 'asking if content is good',
      }),
      target({
        id: 'dv23.t7',
        chunk: 'Skip it',
        cueVi: 'bỏ qua đi',
        sourceSentence: 'Minh: Skip it. Oh, Tom just joined. Hey Tom.',
        productionPattern: '<Skip it / Watch it>.',
        transferContext: 'giving a quick recommendation',
      }),
      target({
        id: 'dv23.t8',
        chunk: 'just joined',
        cueVi: 'vừa vào',
        sourceSentence: 'Minh: Skip it. Oh, Tom just joined. Hey Tom.',
        productionPattern: 'just <joined / arrived / logged on>.',
        transferContext: 'noticing someone entering the call',
      }),
    ],
    transferTask: {
      prompt: 'Small talk with a different remote colleague — different weather + a different light topic.',
      promptVi: 'Nói phiếm với đồng nghiệp remote khác — thời tiết khác + chủ đề nhẹ khác.',
      changesDimension: 'different colleague + new small-talk topic',
    },
    recyclingFrom: ['sv19', 'ch09'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv24',
    level: 'a2',
    track: 'developer',
    capabilities: ['explain-implementation', 'participate-meeting'],
    title: 'Explain a technical concept simply',
    titleVi: 'Giải thích kỹ thuật đơn giản',
    task: 'Explain caching to a non-technical PM',
    context: 'PM asks why the page feels faster today.',
    outcome: 'You can explain a technical idea with an analogy.',
    input: {
      title: 'DV24 · Simply technical',
      text: [
        'PM: Why is the dashboard faster today?',
        'Minh: We added caching — think of it like keeping a copy on your desk.',
        'PM: So instead of walking to the library every time?',
        'Minh: Exactly. The copy expires after a while, then we fetch fresh.',
        'PM: Does it ever show stale data?',
        'Minh: Briefly, yes — that is the trade-off for speed.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Giải thích cho non-tech: analogy (desk copy vs library) → trade-off → no jargon.',
    },
    targets: [
      target({
        id: 'dv24.t1',
        chunk: 'the dashboard faster',
        cueVi: 'dashboard nhanh hơn',
        sourceSentence: 'PM: Why is the dashboard faster today?',
        productionPattern: 'the <dashboard / page / app> faster.',
        transferContext: 'hearing a why-is-it-better question',
      }),
      target({
        id: 'dv24.t2',
        chunk: 'We added caching',
        cueVi: 'bọn tôi thêm cache',
        sourceSentence: 'Minh: We added caching — think of it like keeping a copy on your desk.',
        productionPattern: 'We added <caching / compression / a CDN>.',
        transferContext: 'naming the technical change',
      }),
      target({
        id: 'dv24.t3',
        chunk: 'keeping a copy on your desk',
        cueVi: 'giữ bản sao trên bàn',
        sourceSentence: 'Minh: We added caching — think of it like keeping a copy on your desk.',
        productionPattern: 'keeping a copy <on your desk / nearby>.',
        transferContext: 'using an everyday analogy',
      }),
      target({
        id: 'dv24.t4',
        chunk: 'walking to the library',
        cueVi: 'đi bộ ra thư viện',
        sourceSentence: 'PM: So instead of walking to the library every time?',
        productionPattern: 'walking to the <library / store> every time.',
        transferContext: 'extending a physical analogy',
      }),
      target({
        id: 'dv24.t5',
        chunk: 'expires after a while',
        cueVi: 'hết hạn sau một lúc',
        sourceSentence: 'Minh: Exactly. The copy expires after a while, then we fetch fresh.',
        productionPattern: 'expires after <a while / an hour>.',
        transferContext: 'explaining cache lifetime',
      }),
      target({
        id: 'dv24.t6',
        chunk: 'fetch fresh',
        cueVi: 'lấy mới',
        sourceSentence: 'Minh: Exactly. The copy expires after a while, then we fetch fresh.',
        productionPattern: 'fetch <fresh / new data>.',
        transferContext: 'explaining refresh behavior',
      }),
      target({
        id: 'dv24.t7',
        chunk: 'stale data',
        cueVi: 'dữ liệu cũ',
        sourceSentence: 'PM: Does it ever show stale data?',
        productionPattern: 'stale <data / info>.',
        transferContext: 'asking about data freshness',
      }),
      target({
        id: 'dv24.t8',
        chunk: 'the trade-off for speed',
        cueVi: 'đánh đổi để lấy tốc độ',
        sourceSentence: 'Minh: Briefly, yes — that is the trade-off for speed.',
        productionPattern: 'the trade-off for <speed / simplicity>.',
        transferContext: 'naming an engineering trade-off',
      }),
    ],
    transferTask: {
      prompt: 'Explain a different concept — why search is instant — with a simple analogy.',
      promptVi: 'Giải thích khái niệm khác — sao search nhanh tức thì — bằng một phép ẩn dụ đơn giản.',
      changesDimension: 'different concept + you build the analogy',
    },
    recyclingFrom: ['ch02'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
];
