/* Developer English dv01–dv12 — workplace English for software work.
 * english-for-it is REFERENCE_ONLY: informs design, never supplies prose —
 * every input here is original authored text. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const DEVELOPER_1: LessonSpec[] = [
  spec({
    id: 'dv01',
    level: 'a2',
    track: 'developer',
    capabilities: ['status-update'],
    title: 'Standup update',
    titleVi: 'Cập nhật standup',
    task: 'Give a 30-second standup: done, doing, blocked',
    context: 'Daily standup with your team.',
    outcome: 'You can report status in three short beats.',
    input: {
      title: 'DV01 · Standup',
      text: [
        'Lead: Minh, you are up. What is the status?',
        'Minh: Yesterday I finished the login form. Today I am wiring up the API.',
        'Lead: Any blockers?',
        'Minh: One — I am waiting on the auth token spec from backend.',
        'Lead: I will ping them. Anything else?',
        'Minh: That is it. I should be done by Friday.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Standup 3 beats: done → doing → blocked. "waiting on X" = đang chờ; "I am up" = đến lượt.',
    },
    targets: [
      target({
        id: 'dv01.t1',
        chunk: 'you are up',
        cueVi: 'đến lượt bạn',
        sourceSentence: 'Lead: Minh, you are up. What is the status?',
        productionPattern: '<you / he> are up.',
        transferContext: 'hearing your turn in a meeting',
      }),
      target({
        id: 'dv01.t2',
        chunk: 'I finished the login form',
        cueVi: 'tôi đã xong form đăng nhập',
        sourceSentence: 'Minh: Yesterday I finished the login form. Today I am wiring up the API.',
        productionPattern: 'I finished <the login form / the tests>.',
        transferContext: "reporting yesterday's task",
      }),
      target({
        id: 'dv01.t3',
        chunk: 'wiring up the API',
        cueVi: 'đang nối API',
        sourceSentence: 'Minh: Yesterday I finished the login form. Today I am wiring up the API.',
        productionPattern: 'wiring up <the API / the data>.',
        transferContext: 'describing integration work',
      }),
      target({
        id: 'dv01.t4',
        chunk: 'Any blockers',
        cueVi: 'có vướng gì không',
        sourceSentence: 'Lead: Any blockers?',
        productionPattern: 'Any <blockers / issues>?',
        transferContext: "checking a teammate's status",
      }),
      target({
        id: 'dv01.t5',
        chunk: 'waiting on the auth token spec',
        cueVi: 'đang chờ spec token auth',
        sourceSentence: 'Minh: One — I am waiting on the auth token spec from backend.',
        productionPattern: 'waiting on <the spec / a review>.',
        transferContext: 'reporting a dependency delay',
      }),
      target({
        id: 'dv01.t6',
        chunk: 'I will ping them',
        cueVi: 'tôi sẽ nhắc họ',
        sourceSentence: 'Lead: I will ping them. Anything else?',
        productionPattern: 'I will <ping / follow up with> them.',
        transferContext: 'offering to chase a dependency',
      }),
      target({
        id: 'dv01.t7',
        chunk: 'I should be done by Friday',
        cueVi: 'chắc thứ sáu xong',
        sourceSentence: 'Minh: That is it. I should be done by Friday.',
        productionPattern: 'I should be done by <Friday / tomorrow>.',
        transferContext: 'estimating completion',
      }),
    ],
    transferTask: {
      prompt: 'Give a standup for a different task — a bug fix — with done/doing/one blocker.',
      promptVi: 'Báo standup cho việc khác — sửa bug — với done/doing/một blocker.',
      changesDimension: 'task type + same three-beat structure',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv02',
    level: 'a2',
    track: 'developer',
    capabilities: ['status-update', 'message-async'],
    title: 'Written status update',
    titleVi: 'Update tiến độ bằng văn bản',
    task: 'Write a short async status message for your channel',
    context: 'Posting an end-of-day update in the team channel.',
    outcome: 'You can summarize progress in 3 written lines.',
    input: {
      title: 'DV02 · Async update',
      text: [
        'EOD update — auth flow:',
        'Done: password reset email template is merged.',
        'In progress: token refresh logic, about 70 percent.',
        'Blocked: staging env is down — flagged in infra channel.',
        'Next: finish refresh logic tomorrow morning.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Async update format: EOD + Done/In progress/Blocked/Next. Ngắn gọn, đủ ngữ cảnh.',
    },
    targets: [
      target({
        id: 'dv02.t1',
        chunk: 'EOD update',
        cueVi: 'update cuối ngày',
        sourceSentence: 'EOD update — auth flow:',
        productionPattern: '<EOD / morning> update.',
        transferContext: 'labeling an async check-in',
      }),
      target({
        id: 'dv02.t2',
        chunk: 'is merged',
        cueVi: 'đã được merge',
        sourceSentence: 'Done: password reset email template is merged.',
        productionPattern: 'is <merged / deployed / closed>.',
        transferContext: 'reporting a completed PR',
      }),
      target({
        id: 'dv02.t3',
        chunk: 'token refresh logic',
        cueVi: 'logic làm mới token',
        sourceSentence: 'In progress: token refresh logic, about 70 percent.',
        productionPattern: '<token refresh / retry> logic.',
        transferContext: 'naming a technical component',
      }),
      target({
        id: 'dv02.t4',
        chunk: 'about 70 percent',
        cueVi: 'khoảng 70%',
        sourceSentence: 'In progress: token refresh logic, about 70 percent.',
        productionPattern: 'about <70 / 80> percent.',
        transferContext: 'estimating progress on a task',
      }),
      target({
        id: 'dv02.t5',
        chunk: 'staging env is down',
        cueVi: 'môi trường staging đang sập',
        sourceSentence: 'Blocked: staging env is down — flagged in infra channel.',
        productionPattern: 'the <staging / test> env is down.',
        transferContext: 'reporting environment issues',
      }),
      target({
        id: 'dv02.t6',
        chunk: 'flagged in infra channel',
        cueVi: 'đã báo trong kênh infra',
        sourceSentence: 'Blocked: staging env is down — flagged in infra channel.',
        productionPattern: 'flagged in <the infra / a> channel.',
        transferContext: 'noting where you raised an issue',
      }),
      target({
        id: 'dv02.t7',
        chunk: 'finish refresh logic',
        cueVi: 'xong phần refresh',
        sourceSentence: 'Next: finish refresh logic tomorrow morning.',
        productionPattern: 'finish <the logic / the tests> tomorrow.',
        transferContext: "committing tomorrow's first task",
      }),
    ],
    transferTask: {
      prompt: 'Write a start-of-day update instead — plan for the day + any carry-over blocker.',
      promptVi: 'Viết update đầu ngày — kế hoạch hôm nay + blocker còn tồn.',
      changesDimension: 'start not end of day + forward-looking',
    },
    recyclingFrom: ['dv01'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv03',
    level: 'a2',
    track: 'developer',
    capabilities: ['clarify-requirements'],
    title: 'Clarify a requirement',
    titleVi: 'Làm rõ yêu cầu',
    task: 'Ask questions to pin down a vague ticket',
    context: 'A ticket says "make the button better" with no detail.',
    outcome: 'You can turn vague asks into specifics.',
    input: {
      title: 'DV03 · Vague ticket',
      text: [
        'Minh: Quick question on ticket four-one-two.',
        'PM: Sure, what is unclear?',
        'Minh: It says make the button better — what does better mean here?',
        'PM: Bigger and higher contrast. Users miss it now.',
        'Minh: Got it. Is there a design mock, or should I just style it?',
        'PM: No mock — go ahead and style it, send a screenshot.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Làm rõ ticket mơ hồ: hỏi "what does X mean" → hỏi có spec/mock không → xác nhận cách làm.',
    },
    targets: [
      target({
        id: 'dv03.t1',
        chunk: 'Quick question on ticket',
        cueVi: 'hỏi nhanh về ticket',
        sourceSentence: 'Minh: Quick question on ticket four-one-two.',
        productionPattern: 'Quick question on <ticket / the spec>.',
        transferContext: 'opening a clarification chat',
      }),
      target({
        id: 'dv03.t2',
        chunk: 'what is unclear',
        cueVi: 'chỗ nào chưa rõ',
        sourceSentence: 'PM: Sure, what is unclear?',
        productionPattern: 'What is <unclear / missing>?',
        transferContext: 'asking what confused someone',
      }),
      target({
        id: 'dv03.t3',
        chunk: 'make the button better',
        cueVi: 'làm nút tốt hơn (mơ hồ)',
        sourceSentence: 'Minh: It says make the button better — what does better mean here?',
        productionPattern: 'make the <button / page> better.',
        transferContext: 'quoting a vague requirement',
      }),
      target({
        id: 'dv03.t4',
        chunk: 'what does better mean',
        cueVi: '"tốt hơn" nghĩa là gì',
        sourceSentence: 'Minh: It says make the button better — what does better mean here?',
        productionPattern: 'what does <better / done / fixed> mean here?',
        transferContext: 'pinning down acceptance criteria',
      }),
      target({
        id: 'dv03.t5',
        chunk: 'higher contrast',
        cueVi: 'tương phản cao hơn',
        sourceSentence: 'PM: Bigger and higher contrast. Users miss it now.',
        productionPattern: '<higher contrast / more padding>.',
        transferContext: 'stating a UI requirement',
      }),
      target({
        id: 'dv03.t6',
        chunk: 'a design mock',
        cueVi: 'bản mockup thiết kế',
        sourceSentence: 'Minh: Got it. Is there a design mock, or should I just style it?',
        productionPattern: 'a <design mock / spec doc>.',
        transferContext: 'asking for reference materials',
      }),
      target({
        id: 'dv03.t7',
        chunk: 'send a screenshot',
        cueVi: 'gửi ảnh chụp màn hình',
        sourceSentence: 'PM: No mock — go ahead and style it, send a screenshot.',
        productionPattern: 'send a <screenshot / demo / link>.',
        transferContext: 'agreeing on proof of work',
      }),
    ],
    transferTask: {
      prompt: 'Clarify a different vague ticket — "speed up the page" — ask what metric and target.',
      promptVi: 'Làm rõ ticket mơ hồ khác — "speed up the page" — hỏi metric và mục tiêu.',
      changesDimension: 'performance requirement + measurable target',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv04',
    level: 'a2',
    track: 'developer',
    capabilities: ['report-bug'],
    title: 'Report a bug',
    titleVi: 'Báo cáo lỗi',
    task: 'File a clear bug report with expected vs actual',
    context: 'You found a crash on the checkout page.',
    outcome: 'You can report a bug someone else can act on.',
    input: {
      title: 'DV04 · Bug report',
      text: [
        'Bug: checkout crashes on submit.',
        'Expected: order confirmation page loads.',
        'Actual: blank screen, console shows a 500 error.',
        'Steps: add item, go to checkout, click submit.',
        'Environment: Chrome, staging build four-two.',
        'Happens every time, not intermittent.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Bug report: Expected vs Actual + steps to reproduce + environment + tần suất.',
    },
    targets: [
      target({
        id: 'dv04.t1',
        chunk: 'checkout crashes on submit',
        cueVi: 'checkout crash khi bấm gửi',
        sourceSentence: 'Bug: checkout crashes on submit.',
        productionPattern: '<crashes / freezes / fails> on <submit / load>.',
        transferContext: 'titling a different bug',
      }),
      target({
        id: 'dv04.t2',
        chunk: 'order confirmation page',
        cueVi: 'trang xác nhận đơn',
        sourceSentence: 'Expected: order confirmation page loads.',
        productionPattern: 'the <confirmation / success> page loads.',
        transferContext: 'stating expected behavior',
      }),
      target({
        id: 'dv04.t3',
        chunk: 'a 500 error',
        cueVi: 'lỗi 500',
        sourceSentence: 'Actual: blank screen, console shows a 500 error.',
        productionPattern: 'a <500 / 404 / 403> error.',
        transferContext: 'reporting a server error code',
      }),
      target({
        id: 'dv04.t4',
        chunk: 'go to checkout',
        cueVi: 'đến trang thanh toán',
        sourceSentence: 'Steps: add item, go to checkout, click submit.',
        productionPattern: 'go to <checkout / settings / the cart>.',
        transferContext: 'listing reproduction steps',
      }),
      target({
        id: 'dv04.t5',
        chunk: 'staging build',
        cueVi: 'bản build staging',
        sourceSentence: 'Environment: Chrome, staging build four-two.',
        productionPattern: '<staging / prod> build <four-two>.',
        transferContext: 'noting the environment',
      }),
      target({
        id: 'dv04.t6',
        chunk: 'every time',
        cueVi: 'lần nào cũng',
        sourceSentence: 'Happens every time, not intermittent.',
        productionPattern: '<every time / sometimes / rarely>.',
        transferContext: 'reporting bug frequency',
      }),
      target({
        id: 'dv04.t7',
        chunk: 'not intermittent',
        cueVi: 'không phải thỉnh thoảng',
        sourceSentence: 'Happens every time, not intermittent.',
        productionPattern: 'not <intermittent / random>.',
        transferContext: 'clarifying reproduction reliability',
      }),
    ],
    transferTask: {
      prompt: 'Report a different bug — search returns wrong results — expected/actual/steps/env.',
      promptVi: 'Báo một bug khác — search trả kết quả sai — expected/actual/steps/env.',
      changesDimension: 'logic bug not crash + same report frame',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv05',
    level: 'a2',
    track: 'developer',
    capabilities: ['reproduce-steps'],
    title: 'Write reproduction steps',
    titleVi: 'Viết các bước tái hiện',
    task: 'Write numbered steps so anyone can reproduce a bug',
    context: 'Adding repro steps to a bug you filed.',
    outcome: 'You can write minimal, ordered reproduction steps.',
    input: {
      title: 'DV05 · Repro steps',
      text: [
        'Steps to reproduce:',
        '1. Log in as a free-tier user.',
        '2. Go to Settings, then Billing.',
        '3. Click Upgrade Plan.',
        '4. Observe: the modal opens blank.',
        'Note: only repros on free tier, not pro.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Repro steps: user type → path → action → observe. Note điều kiện giới hạn (only free tier).',
    },
    targets: [
      target({
        id: 'dv05.t1',
        chunk: 'Steps to reproduce',
        cueVi: 'các bước tái hiện',
        sourceSentence: 'Steps to reproduce:',
        productionPattern: 'Steps to <reproduce / trigger>.',
        transferContext: 'labeling a bug report section',
      }),
      target({
        id: 'dv05.t2',
        chunk: 'Log in as',
        cueVi: 'đăng nhập với vai trò',
        sourceSentence: '1. Log in as a free-tier user.',
        productionPattern: 'Log in as <a free-tier / an admin> user.',
        transferContext: 'specifying the test user type',
      }),
      target({
        id: 'dv05.t3',
        chunk: 'a free-tier user',
        cueVi: 'user gói miễn phí',
        sourceSentence: '1. Log in as a free-tier user.',
        productionPattern: 'a <free-tier / pro / guest> user.',
        transferContext: 'describing account types',
      }),
      target({
        id: 'dv05.t4',
        chunk: 'then Billing',
        cueVi: 'rồi mục Thanh toán',
        sourceSentence: '2. Go to Settings, then Billing.',
        productionPattern: 'then <Billing / Profile / Security>.',
        transferContext: 'navigating a settings path',
      }),
      target({
        id: 'dv05.t5',
        chunk: 'Click Upgrade Plan',
        cueVi: 'bấm Nâng cấp gói',
        sourceSentence: '3. Click Upgrade Plan.',
        productionPattern: 'Click <Upgrade Plan / Save / Submit>.',
        transferContext: 'writing the trigger action',
      }),
      target({
        id: 'dv05.t6',
        chunk: 'the modal opens blank',
        cueVi: 'modal mở ra trắng',
        sourceSentence: '4. Observe: the modal opens blank.',
        productionPattern: 'the <modal / page / image> opens blank.',
        transferContext: 'describing the observed failure',
      }),
      target({
        id: 'dv05.t7',
        chunk: 'only repros on free tier',
        cueVi: 'chỉ tái hiện trên gói free',
        sourceSentence: 'Note: only repros on free tier, not pro.',
        productionPattern: 'only repros on <free tier / mobile>.',
        transferContext: 'scoping the bug condition',
      }),
    ],
    transferTask: {
      prompt: 'Write repro steps for a different bug — avatar upload fails on mobile Safari.',
      promptVi: 'Viết repro steps cho bug khác — upload avatar fail trên Safari mobile.',
      changesDimension: 'different feature + platform-specific condition',
    },
    recyclingFrom: ['dv04'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv06',
    level: 'a2',
    track: 'developer',
    capabilities: ['ask-help'],
    title: 'Ask for help when stuck',
    titleVi: 'Xin giúp khi bí',
    task: 'Ask a teammate for help without sounding helpless',
    context: 'You have been stuck on an error for an hour.',
    outcome: 'You can ask for help with context and what you tried.',
    input: {
      title: 'DV06 · Asking help',
      text: [
        'Minh: Hey Sara, got a minute? I am stuck on this import error.',
        'Sara: What have you tried so far?',
        'Minh: I restarted the server and cleared the cache — same error.',
        'Sara: Did you check the env variables?',
        'Minh: Not yet. Can you take a quick look?',
        'Sara: Sure, send me the stack trace.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Nhờ giúp đúng cách: got a minute → what you tried → specific ask (take a look / stack trace).',
    },
    targets: [
      target({
        id: 'dv06.t1',
        chunk: 'got a minute',
        cueVi: 'có rảnh một chút không',
        sourceSentence: 'Minh: Hey Sara, got a minute? I am stuck on this import error.',
        productionPattern: 'Got a <minute / sec>?',
        transferContext: 'interrupting a colleague politely',
      }),
      target({
        id: 'dv06.t2',
        chunk: 'I am stuck on',
        cueVi: 'tôi đang bí ở',
        sourceSentence: 'Minh: Hey Sara, got a minute? I am stuck on this import error.',
        productionPattern: 'I am stuck on <this error / this test>.',
        transferContext: 'admitting you are blocked',
      }),
      target({
        id: 'dv06.t3',
        chunk: 'this import error',
        cueVi: 'lỗi import này',
        sourceSentence: 'Minh: Hey Sara, got a minute? I am stuck on this import error.',
        productionPattern: 'this <import / build / type> error.',
        transferContext: 'naming the specific error',
      }),
      target({
        id: 'dv06.t4',
        chunk: 'What have you tried',
        cueVi: 'bạn đã thử gì',
        sourceSentence: 'Sara: What have you tried so far?',
        productionPattern: 'What have you <tried / checked>?',
        transferContext: "diagnosing a teammate's issue",
      }),
      target({
        id: 'dv06.t5',
        chunk: 'cleared the cache',
        cueVi: 'xóa cache',
        sourceSentence: 'Minh: I restarted the server and cleared the cache — same error.',
        productionPattern: 'cleared the <cache / cookies>.',
        transferContext: 'listing troubleshooting steps',
      }),
      target({
        id: 'dv06.t6',
        chunk: 'check the env variables',
        cueVi: 'kiểm tra biến môi trường',
        sourceSentence: 'Sara: Did you check the env variables?',
        productionPattern: 'check the <env variables / logs / config>.',
        transferContext: 'suggesting a diagnosis path',
      }),
      target({
        id: 'dv06.t7',
        chunk: 'take a quick look',
        cueVi: 'xem nhanh qua',
        sourceSentence: 'Minh: Not yet. Can you take a quick look?',
        productionPattern: 'take a <quick look / second look>.',
        transferContext: 'asking for a code review',
      }),
      target({
        id: 'dv06.t8',
        chunk: 'the stack trace',
        cueVi: 'stack trace',
        sourceSentence: 'Sara: Sure, send me the stack trace.',
        productionPattern: 'the <stack trace / error log>.',
        transferContext: 'sharing debug info',
      }),
    ],
    transferTask: {
      prompt: 'Ask for help with a different problem — a flaky test — include what you already tried.',
      promptVi: 'Nhờ giúp vấn đề khác — test flaky — kèm những gì đã thử.',
      changesDimension: 'flaky test not import error + same help structure',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv07',
    level: 'a2',
    track: 'developer',
    capabilities: ['explain-implementation'],
    title: 'Explain your approach',
    titleVi: 'Giải thích cách làm',
    task: 'Explain why you chose an implementation approach',
    context: 'A teammate asks why you used a map instead of a list.',
    outcome: 'You can justify a technical choice briefly.',
    input: {
      title: 'DV07 · Why a map',
      text: [
        'Sara: Why did you use a map here instead of a list?',
        'Minh: Lookups are faster — we check IDs thousands of times.',
        'Sara: But does order matter?',
        'Minh: Not for this. We only need to find by ID.',
        'Sara: Makes sense. Memory overhead is okay?',
        'Minh: It is small — maybe fifty entries max.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Giải thích approach: choice → reason (faster) → trade-off check (order? memory?) → size estimate.',
    },
    targets: [
      target({
        id: 'dv07.t1',
        chunk: 'Why did you use a map',
        cueVi: 'sao bạn dùng map',
        sourceSentence: 'Sara: Why did you use a map here instead of a list?',
        productionPattern: 'Why did you use <a map / async / caching>?',
        transferContext: 'asking about a design choice in review',
      }),
      target({
        id: 'dv07.t2',
        chunk: 'instead of a list',
        cueVi: 'thay vì list',
        sourceSentence: 'Sara: Why did you use a map here instead of a list?',
        productionPattern: 'instead of <a list / a loop / a library>.',
        transferContext: 'comparing two approaches',
      }),
      target({
        id: 'dv07.t3',
        chunk: 'Lookups are faster',
        cueVi: 'tra cứu nhanh hơn',
        sourceSentence: 'Minh: Lookups are faster — we check IDs thousands of times.',
        productionPattern: '<Lookups / Inserts> are faster.',
        transferContext: 'justifying a data structure',
      }),
      target({
        id: 'dv07.t4',
        chunk: 'thousands of times',
        cueVi: 'hàng nghìn lần',
        sourceSentence: 'Minh: Lookups are faster — we check IDs thousands of times.',
        productionPattern: '<thousands / millions> of times.',
        transferContext: 'quantifying usage scale',
      }),
      target({
        id: 'dv07.t5',
        chunk: 'does order matter',
        cueVi: 'thứ tự có quan trọng không',
        sourceSentence: 'Sara: But does order matter?',
        productionPattern: 'does <order / size / speed> matter?',
        transferContext: 'questioning a trade-off',
      }),
      target({
        id: 'dv07.t6',
        chunk: 'Makes sense',
        cueVi: 'hợp lý rồi',
        sourceSentence: 'Sara: Makes sense. Memory overhead is okay?',
        productionPattern: '<Makes sense / Fair enough>.',
        transferContext: 'accepting an explanation',
      }),
      target({
        id: 'dv07.t7',
        chunk: 'Memory overhead',
        cueVi: 'chi phí bộ nhớ',
        sourceSentence: 'Sara: Makes sense. Memory overhead is okay?',
        productionPattern: '<Memory / CPU> overhead.',
        transferContext: 'discussing resource costs',
      }),
      target({
        id: 'dv07.t8',
        chunk: 'fifty entries max',
        cueVi: 'tối đa 50 mục',
        sourceSentence: 'Minh: It is small — maybe fifty entries max.',
        productionPattern: '<fifty / a hundred> entries max.',
        transferContext: 'estimating data size',
      }),
    ],
    transferTask: {
      prompt: 'Explain a different choice — caching API results — with reason and trade-off.',
      promptVi: 'Giải thích lựa chọn khác — cache kết quả API — với lý do và trade-off.',
      changesDimension: 'caching decision + memory/freshness trade-off',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv08',
    level: 'a2',
    track: 'developer',
    capabilities: ['review-code'],
    title: 'Give code review feedback',
    titleVi: 'Góp ý code review',
    task: "Leave helpful review comments on a teammate's code",
    context: 'Reviewing a PR that has a couple of issues.',
    outcome: 'You can flag issues politely with suggestions.',
    input: {
      title: 'DV08 · Review comments',
      text: [
        'Comment 1: Nice work overall — a few small things.',
        'Comment 2: This loop could be a map lookup for clarity.',
        'Comment 3: Nit: variable name "data" is vague — maybe "userList"?',
        'Comment 4: This block looks duplicated — worth extracting?',
        'Comment 5: LGTM once the naming is fixed.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Review: mở tích cực → góp ý cụ thể → Nit cho chi tiết nhỏ → LGTM khi ổn.',
    },
    targets: [
      target({
        id: 'dv08.t1',
        chunk: 'Nice work overall',
        cueVi: 'nhìn chung làm tốt',
        sourceSentence: 'Comment 1: Nice work overall — a few small things.',
        productionPattern: 'Nice <work / job> overall.',
        transferContext: 'opening a review positively',
      }),
      target({
        id: 'dv08.t2',
        chunk: 'could be a map lookup',
        cueVi: 'có thể dùng map tra cứu',
        sourceSentence: 'Comment 2: This loop could be a map lookup for clarity.',
        productionPattern: 'could be a <map lookup / simpler call>.',
        transferContext: 'suggesting an alternative approach',
      }),
      target({
        id: 'dv08.t3',
        chunk: 'for clarity',
        cueVi: 'cho rõ ràng',
        sourceSentence: 'Comment 2: This loop could be a map lookup for clarity.',
        productionPattern: 'for <clarity / readability / safety>.',
        transferContext: 'justifying a style suggestion',
      }),
      target({
        id: 'dv08.t4',
        chunk: 'is vague',
        cueVi: 'mơ hồ/không rõ',
        sourceSentence: 'Comment 3: Nit: variable name "data" is vague — maybe "userList"?',
        productionPattern: 'is <vague / unclear>.',
        transferContext: 'flagging naming issues',
      }),
      target({
        id: 'dv08.t5',
        chunk: 'looks duplicated',
        cueVi: 'trông bị trùng',
        sourceSentence: 'Comment 4: This block looks duplicated — worth extracting?',
        productionPattern: 'looks <duplicated / repeated>.',
        transferContext: 'flagging repeated code',
      }),
      target({
        id: 'dv08.t6',
        chunk: 'worth extracting',
        cueVi: 'đáng tách ra không',
        sourceSentence: 'Comment 4: This block looks duplicated — worth extracting?',
        productionPattern: 'worth <extracting / refactoring>?',
        transferContext: 'suggesting a refactor',
      }),
      target({
        id: 'dv08.t7',
        chunk: 'LGTM',
        cueVi: 'looks good to me',
        sourceSentence: 'Comment 5: LGTM once the naming is fixed.',
        productionPattern: '<LGTM / Ship it> once <fixed>.',
        transferContext: 'approving a PR conditionally',
      }),
      target({
        id: 'dv08.t8',
        chunk: 'once the naming is fixed',
        cueVi: 'khi sửa xong tên',
        sourceSentence: 'Comment 5: LGTM once the naming is fixed.',
        productionPattern: 'once the <naming / tests> is fixed.',
        transferContext: 'conditioning approval',
      }),
    ],
    transferTask: {
      prompt: 'Review a different snippet — flag one perf issue, one naming nit, and approve conditionally.',
      promptVi: 'Review một đoạn khác — flag một vấn đề hiệu năng, một nit về tên, approve có điều kiện.',
      changesDimension: 'different code + review-comment format',
    },
    recyclingFrom: ['dv07'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv09',
    level: 'a2',
    track: 'developer',
    capabilities: ['discuss-pr'],
    title: 'Write a PR description',
    titleVi: 'Viết mô tả PR',
    task: 'Describe a pull request: what, why, how to test',
    context: 'Opening a PR for the dark mode feature.',
    outcome: 'You can write a PR description reviewers can use.',
    input: {
      title: 'DV09 · PR description',
      text: [
        'What: adds a dark mode toggle to settings.',
        'Why: users asked for it in feedback — reduces eye strain.',
        'How: theme stored in local storage, applied on load.',
        'Testing: toggle it on settings page — check all screens.',
        'Note: does not touch the print stylesheet.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'PR description: What/Why/How/Testing + Note cho phạm vi. Ngắn, để reviewer hiểu nhanh.',
    },
    targets: [
      target({
        id: 'dv09.t1',
        chunk: 'adds a dark mode toggle',
        cueVi: 'thêm nút bật dark mode',
        sourceSentence: 'What: adds a dark mode toggle to settings.',
        productionPattern: 'adds <a toggle / a filter / an export>.',
        transferContext: 'describing a new feature',
      }),
      target({
        id: 'dv09.t2',
        chunk: 'users asked for it',
        cueVi: 'user yêu cầu',
        sourceSentence: 'Why: users asked for it in feedback — reduces eye strain.',
        productionPattern: 'users <asked for it / reported it>.',
        transferContext: 'justifying a feature request',
      }),
      target({
        id: 'dv09.t3',
        chunk: 'reduces eye strain',
        cueVi: 'giảm mỏi mắt',
        sourceSentence: 'Why: users asked for it in feedback — reduces eye strain.',
        productionPattern: 'reduces <eye strain / load time>.',
        transferContext: 'stating a user benefit',
      }),
      target({
        id: 'dv09.t4',
        chunk: 'stored in local storage',
        cueVi: 'lưu trong local storage',
        sourceSentence: 'How: theme stored in local storage, applied on load.',
        productionPattern: 'stored in <local storage / the DB>.',
        transferContext: 'describing persistence approach',
      }),
      target({
        id: 'dv09.t5',
        chunk: 'applied on load',
        cueVi: 'áp dụng khi tải',
        sourceSentence: 'How: theme stored in local storage, applied on load.',
        productionPattern: 'applied on <load / mount / login>.',
        transferContext: 'describing when behavior kicks in',
      }),
      target({
        id: 'dv09.t6',
        chunk: 'toggle it on settings page',
        cueVi: 'bật tắt ở trang cài đặt',
        sourceSentence: 'Testing: toggle it on settings page — check all screens.',
        productionPattern: 'toggle it on <settings / the profile> page.',
        transferContext: 'giving manual test steps',
      }),
      target({
        id: 'dv09.t7',
        chunk: 'the print stylesheet',
        cueVi: 'stylesheet in ấn',
        sourceSentence: 'Note: does not touch the print stylesheet.',
        productionPattern: 'the <print / shared> stylesheet.',
        transferContext: 'scoping out unchanged areas',
      }),
    ],
    transferTask: {
      prompt: 'Write a PR description for a different change — a search filter fix — same four sections.',
      promptVi: 'Viết mô tả PR cho thay đổi khác — sửa filter search — cùng bốn phần.',
      changesDimension: 'bug fix not feature + same description frame',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv10',
    level: 'a2',
    track: 'developer',
    capabilities: ['notify-deploy'],
    title: 'Announce a deployment',
    titleVi: 'Thông báo deploy',
    task: 'Post a deploy notice with version and what changed',
    context: 'Shipping a release to production.',
    outcome: 'You can announce a deploy with rollback info.',
    input: {
      title: 'DV10 · Deploy notice',
      text: [
        'Deploy notice — v2.4.1 going out now.',
        'Changes: checkout crash fix + faster image loading.',
        'Expected downtime: none — rolling deploy.',
        'Watch: error rate on checkout for the next hour.',
        'Rollback: one command if anything looks off.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Deploy notice: version + changes + downtime + what to watch + rollback plan.',
    },
    targets: [
      target({
        id: 'dv10.t1',
        chunk: 'Deploy notice',
        cueVi: 'thông báo deploy',
        sourceSentence: 'Deploy notice — v2.4.1 going out now.',
        productionPattern: '<Deploy / Release> notice.',
        transferContext: 'labeling a release message',
      }),
      target({
        id: 'dv10.t2',
        chunk: 'going out now',
        cueVi: 'đang phát hành',
        sourceSentence: 'Deploy notice — v2.4.1 going out now.',
        productionPattern: 'going <out / live> now.',
        transferContext: 'announcing a release in progress',
      }),
      target({
        id: 'dv10.t3',
        chunk: 'checkout crash fix',
        cueVi: 'fix lỗi crash checkout',
        sourceSentence: 'Changes: checkout crash fix + faster image loading.',
        productionPattern: '<crash / login> fix.',
        transferContext: 'listing a bug fix in release notes',
      }),
      target({
        id: 'dv10.t4',
        chunk: 'faster image loading',
        cueVi: 'tải ảnh nhanh hơn',
        sourceSentence: 'Changes: checkout crash fix + faster image loading.',
        productionPattern: 'faster <image loading / search>.',
        transferContext: 'listing a perf improvement',
      }),
      target({
        id: 'dv10.t5',
        chunk: 'Expected downtime',
        cueVi: 'thời gian sập dự kiến',
        sourceSentence: 'Expected downtime: none — rolling deploy.',
        productionPattern: 'Expected <downtime / impact>: none.',
        transferContext: 'stating deploy impact',
      }),
      target({
        id: 'dv10.t6',
        chunk: 'rolling deploy',
        cueVi: 'deploy cuốn chiếu',
        sourceSentence: 'Expected downtime: none — rolling deploy.',
        productionPattern: 'a <rolling / blue-green> deploy.',
        transferContext: 'describing deploy strategy',
      }),
      target({
        id: 'dv10.t7',
        chunk: 'error rate on checkout',
        cueVi: 'tỉ lệ lỗi trên checkout',
        sourceSentence: 'Watch: error rate on checkout for the next hour.',
        productionPattern: 'error rate on <checkout / login>.',
        transferContext: 'naming a metric to monitor',
      }),
      target({
        id: 'dv10.t8',
        chunk: 'if anything looks off',
        cueVi: 'nếu có gì bất thường',
        sourceSentence: 'Rollback: one command if anything looks off.',
        productionPattern: 'if anything <looks off / breaks>.',
        transferContext: 'describing the abort condition',
      }),
    ],
    transferTask: {
      prompt: 'Announce a different deploy — hotfix only — with change, watch metric, rollback.',
      promptVi: 'Thông báo một deploy khác — chỉ hotfix — với thay đổi, metric theo dõi, rollback.',
      changesDimension: 'hotfix not feature release + same notice frame',
    },
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv11',
    level: 'a2',
    track: 'developer',
    capabilities: ['report-incident'],
    title: 'Report an incident',
    titleVi: 'Báo cáo sự cố',
    task: 'Give an incident update: what broke, impact, ETA',
    context: 'The API is returning 500s and users are affected.',
    outcome: 'You can post a clear incident status.',
    input: {
      title: 'DV11 · Incident',
      text: [
        'Incident update — 14:20 UTC.',
        'What: API returning five-hundreds on login.',
        'Impact: all users unable to sign in since 14:05.',
        'Cause: likely the database migration at 14:00.',
        'Action: rolling back the migration now.',
        'ETA: expect recovery within twenty minutes.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Incident update: timestamp + what + impact + cause + action + ETA. Ngắn, factual.',
    },
    targets: [
      target({
        id: 'dv11.t1',
        chunk: 'Incident update',
        cueVi: 'cập nhật sự cố',
        sourceSentence: 'Incident update — 14:20 UTC.',
        productionPattern: '<Incident / Status> update.',
        transferContext: 'labeling an outage post',
      }),
      target({
        id: 'dv11.t2',
        chunk: 'returning five-hundreds',
        cueVi: 'trả về lỗi 500',
        sourceSentence: 'What: API returning five-hundreds on login.',
        productionPattern: 'returning <five-hundreds / errors / timeouts>.',
        transferContext: 'describing a different failure mode',
      }),
      target({
        id: 'dv11.t3',
        chunk: 'unable to sign in',
        cueVi: 'không đăng nhập được',
        sourceSentence: 'Impact: all users unable to sign in since 14:05.',
        productionPattern: 'unable to <sign in / check out / load>.',
        transferContext: 'describing user impact',
      }),
      target({
        id: 'dv11.t4',
        chunk: 'since 14:05',
        cueVi: 'từ 14:05',
        sourceSentence: 'Impact: all users unable to sign in since 14:05.',
        productionPattern: 'since <14:05 / this morning>.',
        transferContext: 'reporting incident start time',
      }),
      target({
        id: 'dv11.t5',
        chunk: 'the database migration',
        cueVi: 'quá trình migrate database',
        sourceSentence: 'Cause: likely the database migration at 14:00.',
        productionPattern: 'the <database / schema> migration.',
        transferContext: 'naming a suspected cause',
      }),
      target({
        id: 'dv11.t6',
        chunk: 'rolling back the migration',
        cueVi: 'đang rollback migration',
        sourceSentence: 'Action: rolling back the migration now.',
        productionPattern: 'rolling back <the migration / the deploy>.',
        transferContext: 'describing a remediation action',
      }),
      target({
        id: 'dv11.t7',
        chunk: 'within twenty minutes',
        cueVi: 'trong vòng 20 phút',
        sourceSentence: 'ETA: expect recovery within twenty minutes.',
        productionPattern: 'within <twenty / thirty> minutes.',
        transferContext: 'giving a recovery estimate',
      }),
    ],
    transferTask: {
      prompt: 'Write an incident update for a different outage — payment gateway down.',
      promptVi: 'Viết incident update cho sự cố khác — cổng thanh toán sập.',
      changesDimension: 'different system + same update skeleton',
    },
    recyclingFrom: ['dv10'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'dv12',
    level: 'a2',
    track: 'developer',
    capabilities: ['disagree-technical'],
    title: 'Disagree on approach',
    titleVi: 'Không đồng ý về hướng làm',
    task: 'Push back on a technical decision respectfully',
    context: 'A teammate proposes rewriting a module from scratch.',
    outcome: 'You can disagree with reasons and an alternative.',
    input: {
      title: 'DV12 · Pushback',
      text: [
        'Sara: I think we should just rewrite this module.',
        'Minh: I see why, but I am not sure a rewrite is worth it.',
        'Sara: The code is a mess, though.',
        'Minh: Fair. But a rewrite breaks everything else depending on it.',
        'Sara: So what is your suggestion?',
        'Minh: Refactor it piece by piece — less risky, same outcome.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Disagree êm: I see why → but + lý do → offer alternative. Không nói "no" trực tiếp.',
    },
    targets: [
      target({
        id: 'dv12.t1',
        chunk: 'rewrite this module',
        cueVi: 'viết lại module này',
        sourceSentence: 'Sara: I think we should just rewrite this module.',
        productionPattern: 'rewrite <this module / the whole thing>.',
        transferContext: 'proposing a big refactor',
      }),
      target({
        id: 'dv12.t2',
        chunk: 'I see why',
        cueVi: 'tôi hiểu lý do',
        sourceSentence: 'Minh: I see why, but I am not sure a rewrite is worth it.',
        productionPattern: 'I see <why / your point>.',
        transferContext: 'acknowledging before disagreeing',
      }),
      target({
        id: 'dv12.t3',
        chunk: 'a rewrite is worth it',
        cueVi: 'viết lại có đáng không',
        sourceSentence: 'Minh: I see why, but I am not sure a rewrite is worth it.',
        productionPattern: 'a <rewrite / migration> is worth it.',
        transferContext: 'questioning effort vs benefit',
      }),
      target({
        id: 'dv12.t4',
        chunk: 'The code is a mess',
        cueVi: 'code rối',
        sourceSentence: 'Sara: The code is a mess, though.',
        productionPattern: 'The code is <a mess / outdated>.',
        transferContext: 'criticizing legacy code',
      }),
      target({
        id: 'dv12.t5',
        chunk: 'breaks everything else',
        cueVi: 'phá vỡ mọi thứ khác',
        sourceSentence: 'Minh: Fair. But a rewrite breaks everything else depending on it.',
        productionPattern: 'breaks <everything / the API>.',
        transferContext: 'warning about side effects',
      }),
      target({
        id: 'dv12.t6',
        chunk: 'depending on it',
        cueVi: 'phụ thuộc vào nó',
        sourceSentence: 'Minh: Fair. But a rewrite breaks everything else depending on it.',
        productionPattern: '<depending / relying> on it.',
        transferContext: 'describing downstream dependencies',
      }),
      target({
        id: 'dv12.t7',
        chunk: 'Refactor it piece by piece',
        cueVi: 'refactor từng phần',
        sourceSentence: 'Minh: Refactor it piece by piece — less risky, same outcome.',
        productionPattern: 'Refactor it <piece by piece / gradually>.',
        transferContext: 'proposing incremental change',
      }),
      target({
        id: 'dv12.t8',
        chunk: 'less risky',
        cueVi: 'ít rủi ro hơn',
        sourceSentence: 'Minh: Refactor it piece by piece — less risky, same outcome.',
        productionPattern: 'less <risky / costly / disruptive>.',
        transferContext: 'comparing risk levels',
      }),
    ],
    transferTask: {
      prompt: 'Push back on a different proposal — switching frameworks mid-project — with reason + alternative.',
      promptVi: 'Phản đối một đề xuất khác — đổi framework giữa dự án — lý do + phương án khác.',
      changesDimension: 'bigger proposal + same disagree pattern',
    },
    recyclingFrom: ['ch17', 'dv07'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
];
