/* Everyday English ev13–ev24 (A1–A2). */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const EVERYDAY_2: LessonSpec[] = [
  spec({
    id: 'ev13',
    level: 'a2',
    track: 'everyday',
    capabilities: ['book-travel'],
    title: 'At the airport',
    titleVi: 'Ở sân bay',
    task: 'Check in for a flight and get through basic questions',
    context: 'You are checking a bag for a domestic flight.',
    outcome: 'You can handle the check-in counter exchange.',
    input: {
      title: 'EV13 · Check-in counter',
      text: [
        'Agent: Passport, please. Are you checking any bags?',
        'Anh: Yes, one suitcase.',
        'Agent: Please put it on the scale. Window or aisle?',
        'Anh: Aisle, please.',
        'Agent: Here is your boarding pass. Boarding starts at nine forty-five, gate twelve.',
        'Anh: Where is security?',
        'Agent: Straight ahead, then up the escalator.',
      ].join('\n'),
      origin: 'authored',
      noteVi:
        'checking bags = ký gửi hành lý; window or aisle = ghế cửa sổ hay lối đi; boarding pass = thẻ lên máy bay.',
    },
    targets: [
      target({
        id: 'ev13.t1',
        chunk: 'checking any bags',
        cueVi: 'có ký gửi hành lý không',
        sourceSentence: 'Agent: Passport, please. Are you checking any bags?',
        productionPattern: 'checking <any bags / luggage>?',
        transferContext: 'hearing it at an international counter',
      }),
      target({
        id: 'ev13.t2',
        chunk: 'one suitcase',
        cueVi: 'một vali',
        sourceSentence: 'Anh: Yes, one suitcase.',
        productionPattern: 'one <suitcase / bag>.',
        transferContext: 'reporting luggage count at a bus station',
      }),
      target({
        id: 'ev13.t3',
        chunk: 'on the scale',
        cueVi: 'lên cân',
        sourceSentence: 'Agent: Please put it on the scale. Window or aisle?',
        productionPattern: 'put it on <the scale / the belt>.',
        transferContext: 'following bag-drop instructions',
      }),
      target({
        id: 'ev13.t4',
        chunk: 'Window or aisle',
        cueVi: 'cửa sổ hay lối đi',
        sourceSentence: 'Agent: Please put it on the scale. Window or aisle?',
        productionPattern: '<Window or aisle>?',
        transferContext: 'choosing a train seat',
      }),
      target({
        id: 'ev13.t5',
        chunk: 'Aisle, please',
        cueVi: 'cho tôi ghế lối đi',
        sourceSentence: 'Anh: Aisle, please.',
        productionPattern: '<Aisle / Window>, please.',
        transferContext: 'requesting a seat preference at booking',
      }),
      target({
        id: 'ev13.t6',
        chunk: 'boarding pass',
        cueVi: 'thẻ lên máy bay',
        sourceSentence: 'Agent: Here is your boarding pass. Boarding starts at nine forty-five, gate twelve.',
        productionPattern: 'your <boarding pass / ticket>.',
        transferContext: 'asking for a mobile boarding pass',
      }),
      target({
        id: 'ev13.t7',
        chunk: 'Boarding starts at',
        cueVi: 'bắt đầu lên máy bay lúc',
        sourceSentence: 'Agent: Here is your boarding pass. Boarding starts at nine forty-five, gate twelve.',
        productionPattern: 'Boarding starts at <nine forty-five / noon>.',
        transferContext: 'noting boarding time on a return flight',
      }),
      target({
        id: 'ev13.t8',
        chunk: 'gate twelve',
        cueVi: 'cổng mười hai',
        sourceSentence: 'Agent: Here is your boarding pass. Boarding starts at nine forty-five, gate twelve.',
        productionPattern: 'gate <twelve / B4>.',
        transferContext: 'finding a different gate number',
      }),
    ],
    transferTask: {
      prompt: 'Check in for an international flight — passport, two bags, seat choice, and asking about boarding time.',
      promptVi: 'Check-in chuyến quốc tế — hộ chiếu, hai kiện hành lý, chọn ghế, và hỏi giờ boarding.',
      changesDimension: 'international + different bag count + you ask the time',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev14',
    level: 'a1',
    track: 'everyday',
    capabilities: ['book-travel', 'ask-directions'],
    title: 'Taking a taxi',
    titleVi: 'Đi taxi',
    task: 'Tell a driver where to go and handle the fare',
    context: "Taking a taxi across town to a friend's place.",
    outcome: 'You can give a destination, follow the ride, and pay.',
    input: {
      title: 'EV14 · Taxi ride',
      text: [
        'Anh: Hi. To Riverside Apartments, please — near the big bridge.',
        'Driver: Riverside? That is about twenty minutes.',
        'Anh: Okay. Could you take the main road, not the highway?',
        'Driver: Sure. Meter is running.',
        'Anh: Can you drop me at the entrance?',
        'Driver: Here we are. That will be a hundred and twenty.',
        'Anh: Keep the change. Thank you.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"To + địa điểm, please" đưa đích; "drop me at" cho xuống tại; "Keep the change" giữ tiền thừa.',
    },
    targets: [
      target({
        id: 'ev14.t1',
        chunk: 'To Riverside Apartments',
        cueVi: 'đến chung cư Riverside',
        sourceSentence: 'Anh: Hi. To Riverside Apartments, please — near the big bridge.',
        productionPattern: 'To <Riverside Apartments / the station>, please.',
        transferContext: 'giving a hotel name to a driver',
      }),
      target({
        id: 'ev14.t2',
        chunk: 'about twenty minutes',
        cueVi: 'khoảng hai mươi phút',
        sourceSentence: 'Driver: Riverside? That is about twenty minutes.',
        productionPattern: 'about <twenty / thirty> minutes.',
        transferContext: 'estimating a ride duration',
      }),
      target({
        id: 'ev14.t3',
        chunk: 'the main road',
        cueVi: 'đường chính',
        sourceSentence: 'Anh: Okay. Could you take the main road, not the highway?',
        productionPattern: 'take the <main road / highway>.',
        transferContext: 'asking a driver to avoid tolls',
      }),
      target({
        id: 'ev14.t4',
        chunk: 'Meter is running',
        cueVi: 'đồng hồ đang chạy',
        sourceSentence: 'Driver: Sure. Meter is running.',
        productionPattern: 'The <meter / taximeter> is running.',
        transferContext: 'confirming fare basis',
      }),
      target({
        id: 'ev14.t5',
        chunk: 'drop me at the entrance',
        cueVi: 'cho tôi xuống ở cổng',
        sourceSentence: 'Anh: Can you drop me at the entrance?',
        productionPattern: 'drop me at <the entrance / the corner>.',
        transferContext: 'getting off near a shop',
      }),
      target({
        id: 'ev14.t6',
        chunk: 'Keep the change',
        cueVi: 'giữ lại tiền thừa',
        sourceSentence: 'Anh: Keep the change. Thank you.',
        productionPattern: 'Keep the <change>.',
        transferContext: 'tipping a delivery driver',
      }),
    ],
    transferTask: {
      prompt:
        'Give directions to a driver when they do not know your address — landmark, side of street, where to stop.',
      promptVi: 'Chỉ đường cho tài xế khi họ không biết địa chỉ — landmark, phía đường, điểm dừng.',
      changesDimension: 'driver needs guidance + you navigate',
    },
    recyclingFrom: ['ev07'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev15',
    level: 'a2',
    track: 'everyday',
    capabilities: ['describe-problem', 'request-help'],
    title: 'A problem with a neighbor',
    titleVi: 'Vấn đề với hàng xóm',
    task: 'Raise a noise problem politely and agree on a fix',
    context: 'Your upstairs neighbor plays loud music late at night.',
    outcome: 'You can raise an issue without starting a fight.',
    input: {
      title: 'EV15 · Noise',
      text: [
        'Anh: Hi, sorry to bother you. I am Anh, from downstairs.',
        'Neighbor: Oh, hi. Is everything okay?',
        'Anh: Mostly. But the music has been quite loud after midnight lately.',
        'Neighbor: I am sorry — I did not realize. I will keep it down.',
        'Anh: Thanks, I appreciate it. It is only on work nights, really.',
        'Neighbor: No problem. I will use headphones.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Mở mềm: "sorry to bother you"; nêu vấn đề gián tiếp "has been quite loud"; "keep it down" = nhỏ lại.',
    },
    targets: [
      target({
        id: 'ev15.t1',
        chunk: 'sorry to bother you',
        cueVi: 'xin lỗi làm phiền',
        sourceSentence: 'Anh: Hi, sorry to bother you. I am Anh, from downstairs.',
        productionPattern: 'Sorry to <bother you / disturb you>.',
        transferContext: "knocking on a landlord's door",
      }),
      target({
        id: 'ev15.t2',
        chunk: 'from downstairs',
        cueVi: 'ở tầng dưới',
        sourceSentence: 'Anh: Hi, sorry to bother you. I am Anh, from downstairs.',
        productionPattern: 'from <downstairs / next door / unit 5>.',
        transferContext: 'identifying yourself to a neighbor',
      }),
      target({
        id: 'ev15.t3',
        chunk: 'Is everything okay',
        cueVi: 'mọi thứ ổn chứ',
        sourceSentence: 'Neighbor: Oh, hi. Is everything okay?',
        productionPattern: 'Is everything <okay / alright>?',
        transferContext: 'checking on a colleague who looks stressed',
      }),
      target({
        id: 'ev15.t4',
        chunk: 'quite loud after midnight',
        cueVi: 'khá ồn sau nửa đêm',
        sourceSentence: 'Anh: Mostly. But the music has been quite loud after midnight lately.',
        productionPattern: 'quite <loud / late> after <midnight / ten>.',
        transferContext: 'complaining about construction noise',
      }),
      target({
        id: 'ev15.t5',
        chunk: 'I did not realize',
        cueVi: 'tôi không biết/tôi không để ý',
        sourceSentence: 'Neighbor: I am sorry — I did not realize. I will keep it down.',
        productionPattern: 'I did not <realize / notice>.',
        transferContext: 'apologizing for blocking a hallway',
      }),
      target({
        id: 'ev15.t6',
        chunk: 'keep it down',
        cueVi: 'nhỏ lại / giữ yên',
        sourceSentence: 'Neighbor: I am sorry — I did not realize. I will keep it down.',
        productionPattern: 'keep <it down / the noise down>.',
        transferContext: 'asking roommates to lower music',
      }),
      target({
        id: 'ev15.t7',
        chunk: 'I appreciate it',
        cueVi: 'tôi rất cảm kích',
        sourceSentence: 'Anh: Thanks, I appreciate it. It is only on work nights, really.',
        productionPattern: 'I <appreciate it / am grateful>.',
        transferContext: 'thanking a landlord for a repair',
      }),
    ],
    transferTask: {
      prompt: 'Raise a different shared-space issue — a bike blocking your door — and agree on a fix.',
      promptVi: 'Nêu vấn đề không gian chung khác — xe đạp chặn cửa — và thống nhất cách xử lý.',
      changesDimension: 'physical obstruction (not noise) + same soft-open script',
    },
    recyclingFrom: ['sv09', 'sv21'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev16',
    level: 'a1',
    track: 'everyday',
    capabilities: ['invite-respond'],
    title: 'Invite someone over',
    titleVi: 'Mời người khác',
    task: 'Invite a friend to dinner and handle the details',
    context: 'You want to cook for two friends on Saturday.',
    outcome: 'You can extend an invitation and confirm logistics.',
    input: {
      title: 'EV16 · Dinner invite',
      text: [
        'Anh: Hey Linh, do you want to come over for dinner on Saturday?',
        'Linh: I would love to! What time should I come?',
        'Anh: Around seven. Can you eat spicy food?',
        'Linh: A little, yes. Should I bring anything?',
        'Anh: Just yourself. Maybe some fruit if you want.',
        'Linh: Done. See you Saturday at seven.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"come over" = đến nhà chơi; "Should I bring anything" câu hỏi lễ phép của khách.',
    },
    targets: [
      target({
        id: 'ev16.t1',
        chunk: 'come over for dinner',
        cueVi: 'đến nhà ăn tối',
        sourceSentence: 'Anh: Hey Linh, do you want to come over for dinner on Saturday?',
        productionPattern: 'come over for <dinner / coffee / a movie>.',
        transferContext: 'inviting a classmate for a study session',
      }),
      target({
        id: 'ev16.t2',
        chunk: 'I would love to',
        cueVi: 'tôi rất muốn',
        sourceSentence: 'Linh: I would love to! What time should I come?',
        productionPattern: 'I would <love / like> to.',
        transferContext: 'accepting a barbecue invitation',
      }),
      target({
        id: 'ev16.t3',
        chunk: 'What time should I come',
        cueVi: 'tôi nên đến lúc mấy giờ',
        sourceSentence: 'Linh: I would love to! What time should I come?',
        productionPattern: 'What time should I <come / arrive>?',
        transferContext: 'confirming arrival at a party',
      }),
      target({
        id: 'ev16.t4',
        chunk: 'Can you eat spicy food',
        cueVi: 'bạn ăn được cay không',
        sourceSentence: 'Anh: Around seven. Can you eat spicy food?',
        productionPattern: 'Can you eat <spicy food / seafood>?',
        transferContext: 'checking dietary needs before cooking',
      }),
      target({
        id: 'ev16.t5',
        chunk: 'Should I bring anything',
        cueVi: 'tôi có nên mang gì không',
        sourceSentence: 'Linh: A little, yes. Should I bring anything?',
        productionPattern: 'Should I bring <anything / a dish>?',
        transferContext: 'asking a potluck host what to bring',
      }),
      target({
        id: 'ev16.t6',
        chunk: 'Just yourself',
        cueVi: 'không cần mang gì đâu',
        sourceSentence: 'Anh: Just yourself. Maybe some fruit if you want.',
        productionPattern: 'Just <yourself / bring nothing>.',
        transferContext: 'telling a guest not to bring gifts',
      }),
    ],
    transferTask: {
      prompt: 'Invite a coworker to a different event — a weekend hike — with meeting time and what to bring.',
      promptVi: 'Mời đồng nghiệp một sự kiện khác — đi leo núi cuối tuần — kèm giờ gặp và đồ cần mang.',
      changesDimension: 'outdoor activity + gear question instead of food',
    },
    recyclingFrom: ['sv24'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev17',
    level: 'a2',
    track: 'everyday',
    capabilities: ['invite-respond', 'disagree-politely'],
    title: 'Decline politely',
    titleVi: 'Từ chối lịch sự',
    task: 'Say no to an invitation without hurting the relationship',
    context: 'A colleague invites you to a party you cannot attend.',
    outcome: 'You can decline warmly and suggest an alternative.',
    input: {
      title: 'EV17 · Saying no',
      text: [
        'Mai: We are having a birthday dinner Friday. Can you come?',
        'Anh: Oh, I wish I could, but I already have plans that night.',
        'Mai: That is too bad. Another time?',
        'Anh: Definitely. How about lunch next week instead?',
        'Mai: Sure. Tuesday?',
        'Anh: Tuesday works. Happy birthday, by the way!',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Từ chối mềm: "I wish I could, but..." + lý do ngắn + đề xuất thay thế ("instead").',
    },
    targets: [
      target({
        id: 'ev17.t1',
        chunk: 'Can you come',
        cueVi: 'bạn đến được không',
        sourceSentence: 'Mai: We are having a birthday dinner Friday. Can you come?',
        productionPattern: 'Can you <come / make it>?',
        transferContext: 'hearing a wedding invitation',
      }),
      target({
        id: 'ev17.t2',
        chunk: 'I wish I could',
        cueVi: 'ước gì tôi có thể',
        sourceSentence: 'Anh: Oh, I wish I could, but I already have plans that night.',
        productionPattern: 'I wish I could, but <I have plans / I am busy>.',
        transferContext: 'declining a work happy hour',
      }),
      target({
        id: 'ev17.t3',
        chunk: 'I already have plans',
        cueVi: 'tôi đã có kế hoạch rồi',
        sourceSentence: 'Anh: Oh, I wish I could, but I already have plans that night.',
        productionPattern: 'I already have <plans / an appointment>.',
        transferContext: 'declining a second meeting invite',
      }),
      target({
        id: 'ev17.t4',
        chunk: 'That is too bad',
        cueVi: 'tiếc quá',
        sourceSentence: 'Mai: That is too bad. Another time?',
        productionPattern: 'That is <too bad / a shame>.',
        transferContext: 'reacting when a friend cancels',
      }),
      target({
        id: 'ev17.t5',
        chunk: 'Another time',
        cueVi: 'lần khác nhé',
        sourceSentence: 'Mai: That is too bad. Another time?',
        productionPattern: '<Another time / Next week>?',
        transferContext: 'offering a rain check for coffee',
      }),
      target({
        id: 'ev17.t6',
        chunk: 'instead',
        cueVi: 'thay vào đó',
        sourceSentence: 'Anh: Definitely. How about lunch next week instead?',
        productionPattern: 'How about <lunch / coffee> instead?',
        transferContext: 'suggesting a call instead of a visit',
      }),
      target({
        id: 'ev17.t7',
        chunk: 'by the way',
        cueVi: 'nhân tiện',
        sourceSentence: 'Anh: Tuesday works. Happy birthday, by the way!',
        productionPattern: '<Happy birthday / Congrats>, by the way.',
        transferContext: 'adding a side note in a chat',
      }),
    ],
    transferTask: {
      prompt: 'Decline a different invitation — a weekend trip — with a warm reason and a counter-offer.',
      promptVi: 'Từ chối lời mời khác — chuyến đi cuối tuần — với lý do ấm áp và đề xuất thay thế.',
      changesDimension: 'longer event + you propose a specific alternative',
    },
    recyclingFrom: ['ev16'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev18',
    level: 'a2',
    track: 'everyday',
    capabilities: ['express-opinion', 'disagree-politely'],
    title: 'Give your opinion',
    titleVi: 'Đưa ý kiến',
    task: 'Share an opinion about a film and disagree politely',
    context: 'Two friends discussing a movie they just watched.',
    outcome: 'You can give opinions with hedges and counter softly.',
    input: {
      title: 'EV18 · After the film',
      text: [
        'Tom: So, what did you think of the movie?',
        'Anh: Honestly, I thought it was a bit slow.',
        'Tom: Really? I loved it. The ending was great.',
        'Anh: The ending was good, I agree. But the middle dragged.',
        'Tom: Fair enough. I guess it is not for everyone.',
        'Anh: Exactly. Beautiful scenes, though.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Ý kiến có hedge: "Honestly / I thought / a bit"; đồng ý một phần rồi mới phản bác.',
    },
    targets: [
      target({
        id: 'ev18.t1',
        chunk: 'what did you think of',
        cueVi: 'bạn nghĩ gì về',
        sourceSentence: 'Tom: So, what did you think of the movie?',
        productionPattern: 'what did you think of <the movie / the talk>?',
        transferContext: 'asking a colleague about a workshop',
      }),
      target({
        id: 'ev18.t2',
        chunk: 'a bit slow',
        cueVi: 'hơi chậm',
        sourceSentence: 'Anh: Honestly, I thought it was a bit slow.',
        productionPattern: 'a bit <slow / long / boring>.',
        transferContext: 'reviewing a long meeting',
      }),
      target({
        id: 'ev18.t3',
        chunk: 'I thought it was',
        cueVi: 'tôi thấy nó',
        sourceSentence: 'Anh: Honestly, I thought it was a bit slow.',
        productionPattern: 'I thought it was <slow / great / okay>.',
        transferContext: 'sharing a book opinion',
      }),
      target({
        id: 'ev18.t4',
        chunk: 'The ending was great',
        cueVi: 'đoạn kết hay',
        sourceSentence: 'Tom: Really? I loved it. The ending was great.',
        productionPattern: 'The <ending / food / music> was great.',
        transferContext: 'praising part of a concert',
      }),
      target({
        id: 'ev18.t5',
        chunk: 'the middle dragged',
        cueVi: 'đoạn giữa dài dòng',
        sourceSentence: 'Anh: The ending was good, I agree. But the middle dragged.',
        productionPattern: 'the <middle / first half> dragged.',
        transferContext: 'critiquing a long presentation',
      }),
      target({
        id: 'ev18.t6',
        chunk: 'Fair enough',
        cueVi: 'cũng hợp lý',
        sourceSentence: 'Tom: Fair enough. I guess it is not for everyone.',
        productionPattern: '<Fair enough / That is fair>.',
        transferContext: 'accepting a different view at work',
      }),
      target({
        id: 'ev18.t7',
        chunk: 'not for everyone',
        cueVi: 'không phải ai cũng thích',
        sourceSentence: 'Tom: Fair enough. I guess it is not for everyone.',
        productionPattern: 'not for <everyone / me>.',
        transferContext: 'dismissing a taste difference about food',
      }),
      target({
        id: 'ev18.t8',
        chunk: 'though',
        cueVi: 'tuy nhiên (cuối câu)',
        sourceSentence: 'Anh: Exactly. Beautiful scenes, though.',
        productionPattern: '<Nice work / good effort>, though.',
        transferContext: 'softening criticism of a design',
      }),
    ],
    transferTask: {
      prompt: 'Debate a restaurant you both tried — agree on one point, disagree on another.',
      promptVi: 'Bàn về một nhà hàng hai người đã ăn — đồng ý một điểm, phản bác điểm khác.',
      changesDimension: 'food domain + partial-agreement structure',
    },
    recyclingFrom: ['sv12'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev19',
    level: 'a2',
    track: 'everyday',
    capabilities: ['describe-problem', 'request-help'],
    title: 'Something is broken at home',
    titleVi: 'Đồ hỏng trong nhà',
    task: 'Report a household problem to a landlord and arrange a repair',
    context: 'Your kitchen tap is leaking badly.',
    outcome: 'You can describe the fault and agree on a repair time.',
    input: {
      title: 'EV19 · Leaky tap',
      text: [
        'Anh: Hi Mr. Park, this is Anh from apartment 4B.',
        'Landlord: Hi Anh, what is up?',
        'Anh: The kitchen tap is leaking — it has been dripping all night.',
        'Landlord: Is it serious?',
        'Anh: There is a small puddle now. I turned the water off.',
        'Landlord: Good. I can send a plumber tomorrow morning.',
        'Anh: That works. Thank you.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Báo hỏng: what is broken → since when → severity → arrange fix; "What is up" cách hỏi thân mật.',
    },
    targets: [
      target({
        id: 'ev19.t1',
        chunk: 'this is Anh from apartment 4B',
        cueVi: 'tôi là Anh ở căn hộ 4B',
        sourceSentence: 'Anh: Hi Mr. Park, this is Anh from apartment 4B.',
        productionPattern: 'this is <Anh> from <apartment 4B / next door>.',
        transferContext: 'identifying yourself to a building manager',
      }),
      target({
        id: 'ev19.t2',
        chunk: 'what is up',
        cueVi: 'có chuyện gì',
        sourceSentence: 'Landlord: Hi Anh, what is up?',
        productionPattern: 'What is <up / going on>?',
        transferContext: 'greeting a teammate casually',
      }),
      target({
        id: 'ev19.t3',
        chunk: 'is leaking',
        cueVi: 'đang bị rò rỉ',
        sourceSentence: 'Anh: The kitchen tap is leaking — it has been dripping all night.',
        productionPattern: 'The <tap / pipe / roof> is leaking.',
        transferContext: 'reporting a dripping ceiling',
      }),
      target({
        id: 'ev19.t4',
        chunk: 'it has been dripping all night',
        cueVi: 'nó nhỏ giọt suốt đêm',
        sourceSentence: 'Anh: The kitchen tap is leaking — it has been dripping all night.',
        productionPattern: 'it has been <dripping / making noise> all night.',
        transferContext: 'describing a fridge that keeps buzzing',
      }),
      target({
        id: 'ev19.t5',
        chunk: 'Is it serious',
        cueVi: 'có nghiêm trọng không',
        sourceSentence: 'Landlord: Is it serious?',
        productionPattern: 'Is it <serious / urgent / fixable>?',
        transferContext: 'asking severity about a car noise',
      }),
      target({
        id: 'ev19.t6',
        chunk: 'a small puddle',
        cueVi: 'một vũng nước nhỏ',
        sourceSentence: 'Anh: There is a small puddle now. I turned the water off.',
        productionPattern: 'a <small puddle / big mess>.',
        transferContext: 'describing water damage to insurance',
      }),
      target({
        id: 'ev19.t7',
        chunk: 'I turned the water off',
        cueVi: 'tôi đã khóa nước',
        sourceSentence: 'Anh: There is a small puddle now. I turned the water off.',
        productionPattern: 'I turned <the water / it> off.',
        transferContext: 'explaining you unplugged a faulty appliance',
      }),
      target({
        id: 'ev19.t8',
        chunk: 'send a plumber',
        cueVi: 'cử thợ sửa ống nước',
        sourceSentence: 'Landlord: Good. I can send a plumber tomorrow morning.',
        productionPattern: 'send a <plumber / technician> tomorrow.',
        transferContext: 'asking when a repair person comes',
      }),
    ],
    transferTask: {
      prompt: 'Report a different fault — a broken AC in summer — with severity and a repair arrangement.',
      promptVi: 'Báo hỏng khác — điều hòa hỏng giữa hè — kèm mức độ và lịch sửa.',
      changesDimension: 'appliance type + urgency framing',
    },
    recyclingFrom: ['sv21'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev20',
    level: 'a2',
    track: 'everyday',
    capabilities: ['pay-bills'],
    title: 'Money and payments',
    titleVi: 'Tiền và thanh toán',
    task: 'Handle a payment conversation — split a bill and pay your share',
    context: 'Dinner with friends; the bill arrives.',
    outcome: 'You can ask to split, state your share, and confirm payment.',
    input: {
      title: 'EV20 · The bill',
      text: [
        'Waiter: Here is your bill.',
        'Anh: Can we split it, please?',
        'Waiter: Sure, three ways?',
        'Anh: Yes, please. How much is each?',
        'Waiter: Two hundred sixty each.',
        'Anh: I will pay by card. Do you add a tip?',
        'Waiter: It is already included.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"split it" chia bill; "each" mỗi người; "included" đã bao gồm tip.',
    },
    targets: [
      target({
        id: 'ev20.t1',
        chunk: 'Here is your bill',
        cueVi: 'đây là hóa đơn',
        sourceSentence: 'Waiter: Here is your bill.',
        productionPattern: 'Here is your <bill / change / receipt>.',
        transferContext: 'receiving a receipt at a café',
      }),
      target({
        id: 'ev20.t2',
        chunk: 'split it',
        cueVi: 'chia ra',
        sourceSentence: 'Anh: Can we split it, please?',
        productionPattern: 'split <it / the bill>.',
        transferContext: 'splitting a taxi fare with friends',
      }),
      target({
        id: 'ev20.t3',
        chunk: 'three ways',
        cueVi: 'chia ba',
        sourceSentence: 'Waiter: Sure, three ways?',
        productionPattern: '<two / three> ways.',
        transferContext: 'dividing a gift cost',
      }),
      target({
        id: 'ev20.t4',
        chunk: 'How much is each',
        cueVi: 'mỗi người bao nhiêu',
        sourceSentence: 'Anh: Yes, please. How much is each?',
        productionPattern: 'How much is <each / mine>?',
        transferContext: 'asking your share of a group ticket',
      }),
      target({
        id: 'ev20.t5',
        chunk: 'pay by card',
        cueVi: 'trả bằng thẻ',
        sourceSentence: 'Anh: I will pay by card. Do you add a tip?',
        productionPattern: 'pay by <card / cash / phone>.',
        transferContext: 'choosing payment at a market',
      }),
      target({
        id: 'ev20.t6',
        chunk: 'add a tip',
        cueVi: 'thêm tiền bo',
        sourceSentence: 'Anh: I will pay by card. Do you add a tip?',
        productionPattern: 'add a <tip / service charge>?',
        transferContext: 'asking about service charges abroad',
      }),
      target({
        id: 'ev20.t7',
        chunk: 'It is already included',
        cueVi: 'đã bao gồm rồi',
        sourceSentence: 'Waiter: It is already included.',
        productionPattern: 'It is already <included / paid>.',
        transferContext: 'confirming tax is in the price',
      }),
    ],
    transferTask: {
      prompt: 'Split a different cost — a shared taxi + snack — among four people and choose payment method.',
      promptVi: 'Chia một khoản khác — taxi + đồ ăn nhẹ — cho bốn người và chọn cách trả.',
      changesDimension: 'group of four + mixed cost type',
    },
    recyclingFrom: ['sv15'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev21',
    level: 'a2',
    track: 'everyday',
    capabilities: ['shop-return', 'describe-problem'],
    title: 'Return an online order',
    titleVi: 'Đổi/trả đơn online',
    task: 'Start a return for a wrong item and get a refund timeline',
    context: 'The shoes you ordered online are the wrong color.',
    outcome: 'You can open a return request and confirm the process.',
    input: {
      title: 'EV21 · Wrong item',
      text: [
        'Support: Thanks for calling. How can I help?',
        'Anh: I would like to return an order. They sent the wrong color.',
        'Support: Sorry about that. What is your order number?',
        'Anh: It is F-D-eight-four-two-one.',
        'Support: I see it. I will email you a return label now.',
        'Anh: When will I get the refund?',
        'Support: Within five business days after we receive it.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Trả hàng: lý do → order number → return label → refund timeline.',
    },
    targets: [
      target({
        id: 'ev21.t1',
        chunk: 'How can I help',
        cueVi: 'tôi có thể giúp gì',
        sourceSentence: 'Support: Thanks for calling. How can I help?',
        productionPattern: 'How can I <help / assist you>?',
        transferContext: 'hearing it on any support line',
      }),
      target({
        id: 'ev21.t2',
        chunk: 'return an order',
        cueVi: 'trả một đơn hàng',
        sourceSentence: 'Anh: I would like to return an order. They sent the wrong color.',
        productionPattern: 'return an <order / item>.',
        transferContext: 'starting a refund for damaged goods',
      }),
      target({
        id: 'ev21.t3',
        chunk: 'the wrong color',
        cueVi: 'sai màu',
        sourceSentence: 'Anh: I would like to return an order. They sent the wrong color.',
        productionPattern: 'the wrong <color / size / model>.',
        transferContext: 'reporting a wrong-size delivery',
      }),
      target({
        id: 'ev21.t4',
        chunk: 'your order number',
        cueVi: 'mã đơn của bạn',
        sourceSentence: 'Support: Sorry about that. What is your order number?',
        productionPattern: 'your <order / booking / reference> number.',
        transferContext: 'giving a flight confirmation code',
      }),
      target({
        id: 'ev21.t5',
        chunk: 'a return label',
        cueVi: 'nhãn trả hàng',
        sourceSentence: 'Support: I see it. I will email you a return label now.',
        productionPattern: 'a <return / shipping> label.',
        transferContext: 'asking where to print the label',
      }),
      target({
        id: 'ev21.t6',
        chunk: 'get the refund',
        cueVi: 'nhận lại tiền',
        sourceSentence: 'Anh: When will I get the refund?',
        productionPattern: 'get the <refund / replacement>.',
        transferContext: 'asking about a cancelled order refund',
      }),
      target({
        id: 'ev21.t7',
        chunk: 'five business days',
        cueVi: 'năm ngày làm việc',
        sourceSentence: 'Support: Within five business days after we receive it.',
        productionPattern: '<three / five> business days.',
        transferContext: 'asking a bank transfer timeline',
      }),
    ],
    transferTask: {
      prompt: 'Return a different item — a cracked phone screen protector — and ask for replacement instead of refund.',
      promptVi: 'Đổi món khác — miếng dán màn hình bị nứt — và xin thay thế thay vì hoàn tiền.',
      changesDimension: 'defect (not wrong variant) + replacement preferred',
    },
    recyclingFrom: ['sv23'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev22',
    level: 'a2',
    track: 'everyday',
    capabilities: ['phone-basics'],
    title: 'Leave a message',
    titleVi: 'Để lại lời nhắn',
    task: 'Handle a phone call and ask someone to call back',
    context: 'You call a clinic but the doctor is busy.',
    outcome: 'You can leave a callback request with your number.',
    input: {
      title: 'EV22 · Callback',
      text: [
        'Reception: City Clinic, good morning.',
        'Anh: Hello, could I speak to Dr. Tran, please?',
        'Reception: I am afraid she is with a patient right now.',
        'Anh: Could you ask her to call me back?',
        'Reception: Of course. Can I take your number?',
        'Anh: It is zero nine one, two three four, five six seven.',
        'Reception: Perfect. She will call you this afternoon.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"I am afraid" giới thiệu tin xấu nhẹ; "call me back" gọi lại; "take your number" xin số.',
    },
    targets: [
      target({
        id: 'ev22.t1',
        chunk: 'Could I speak to',
        cueVi: 'cho tôi nói chuyện với',
        sourceSentence: 'Anh: Hello, could I speak to Dr. Tran, please?',
        productionPattern: 'Could I speak to <Dr. Tran / the manager>?',
        transferContext: 'calling an office for a person',
      }),
      target({
        id: 'ev22.t2',
        chunk: 'I am afraid',
        cueVi: 'rất tiếc (tin không tốt)',
        sourceSentence: 'Reception: I am afraid she is with a patient right now.',
        productionPattern: 'I am afraid <she is busy / he is out>.',
        transferContext: 'hearing that someone is unavailable',
      }),
      target({
        id: 'ev22.t3',
        chunk: 'with a patient',
        cueVi: 'đang khám bệnh nhân',
        sourceSentence: 'Reception: I am afraid she is with a patient right now.',
        productionPattern: 'with a <patient / client / customer>.',
        transferContext: 'explaining why a colleague is busy',
      }),
      target({
        id: 'ev22.t4',
        chunk: 'call me back',
        cueVi: 'gọi lại cho tôi',
        sourceSentence: 'Anh: Could you ask her to call me back?',
        productionPattern: 'call me <back / later>.',
        transferContext: 'asking a shop to ring you back',
      }),
      target({
        id: 'ev22.t5',
        chunk: 'take your number',
        cueVi: 'xin số của bạn',
        sourceSentence: 'Reception: Of course. Can I take your number?',
        productionPattern: 'take your <number / name / details>.',
        transferContext: 'leaving details with a repair service',
      }),
      target({
        id: 'ev22.t6',
        chunk: 'this afternoon',
        cueVi: 'chiều nay',
        sourceSentence: 'Reception: Perfect. She will call you this afternoon.',
        productionPattern: '<this afternoon / later today>.',
        transferContext: 'confirming a callback window',
      }),
    ],
    transferTask: {
      prompt: "Call a landlord's office — person unavailable, leave callback + preferred time window.",
      promptVi: 'Gọi văn phòng chủ nhà — người cần gặp đang bận, để lại lời gọi lại + khung giờ mong muốn.',
      changesDimension: 'different office + you specify a time window',
    },
    recyclingFrom: ['sv05'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev23',
    level: 'a2',
    track: 'everyday',
    capabilities: ['make-plans', 'schedule-appointment'],
    title: 'Make arrangements by text',
    titleVi: 'Sắp xếp qua tin nhắn',
    task: 'Coordinate a meetup over messages with back-and-forth changes',
    context: 'Rescheduling coffee with a friend who is running late.',
    outcome: 'You can negotiate a plan in short written turns.',
    input: {
      title: 'EV23 · Texting',
      text: [
        'Linh: Running a bit late — can we push coffee to four?',
        'Anh: Four works. Same place?',
        'Linh: Yes, the corner cafe. I will be there at four ten, sorry!',
        'Anh: No worries. I will grab us a table.',
        'Linh: You are the best. See you soon.',
        'Anh: See you. Order you the usual?',
        'Linh: Yes please — iced latte, no sugar.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Hẹn qua tin nhắn: "push X to Y" dời; "Same place?" chốt địa điểm; "the usual" món quen thuộc.',
    },
    targets: [
      target({
        id: 'ev23.t1',
        chunk: 'Running a bit late',
        cueVi: 'đang hơi trễ',
        sourceSentence: 'Linh: Running a bit late — can we push coffee to four?',
        productionPattern: 'Running <a bit / ten minutes> late.',
        transferContext: 'warning a client you are behind',
      }),
      target({
        id: 'ev23.t2',
        chunk: 'push coffee to four',
        cueVi: 'dời cà phê sang bốn giờ',
        sourceSentence: 'Linh: Running a bit late — can we push coffee to four?',
        productionPattern: 'push <coffee / the meeting> to <four / Friday>.',
        transferContext: 'moving a call to next week',
      }),
      target({
        id: 'ev23.t3',
        chunk: 'Same place',
        cueVi: 'chỗ cũ không',
        sourceSentence: 'Anh: Four works. Same place?',
        productionPattern: 'Same <place / time>?',
        transferContext: 'confirming a regular meetup spot',
      }),
      target({
        id: 'ev23.t4',
        chunk: 'four ten',
        cueVi: 'bốn giờ mười',
        sourceSentence: 'Linh: Yes, the corner cafe. I will be there at four ten, sorry!',
        productionPattern: 'at <four ten / five-ish>.',
        transferContext: 'giving a precise arrival estimate',
      }),
      target({
        id: 'ev23.t5',
        chunk: 'No worries',
        cueVi: 'không sao đâu',
        sourceSentence: 'Anh: No worries. I will grab us a table.',
        productionPattern: 'No <worries / rush / problem>.',
        transferContext: 'reassuring someone running late to dinner',
      }),
      target({
        id: 'ev23.t6',
        chunk: 'grab us a table',
        cueVi: 'giữ bàn cho hai đứa',
        sourceSentence: 'Anh: No worries. I will grab us a table.',
        productionPattern: 'grab us a <table / seat>.',
        transferContext: 'holding seats at a cinema',
      }),
      target({
        id: 'ev23.t7',
        chunk: 'the usual',
        cueVi: 'món như mọi khi',
        sourceSentence: 'Anh: See you. Order you the usual?',
        productionPattern: 'the <usual / same as always>.',
        transferContext: "ordering a regular's drink",
      }),
      target({
        id: 'ev23.t8',
        chunk: 'no sugar',
        cueVi: 'không đường',
        sourceSentence: 'Linh: Yes please — iced latte, no sugar.',
        productionPattern: 'no <sugar / ice / onions>.',
        transferContext: 'customizing a sandwich order',
      }),
    ],
    transferTask: {
      prompt: 'Reschedule a different meetup — a gym session — by text: delay, confirm place, small favor.',
      promptVi: 'Dời lịch khác qua tin nhắn — buổi tập gym — trễ giờ, chốt địa điểm, nhờ vả nhỏ.',
      changesDimension: 'activity type + you are the one running late',
    },
    recyclingFrom: ['ev02', 'ev09'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev24',
    level: 'a2',
    track: 'everyday',
    capabilities: ['book-travel', 'make-plans'],
    title: 'Plan a weekend trip',
    titleVi: 'Lên kế hoạch đi cuối tuần',
    task: 'Plan a short trip — destination, transport, and a rough itinerary',
    context: 'Deciding on a two-day getaway with a friend.',
    outcome: 'You can propose options and agree on a simple plan.',
    input: {
      title: 'EV24 · Getaway',
      text: [
        'Anh: I want to get away next weekend. Any ideas?',
        'Linh: How about Da Lat? It is cooler there.',
        'Anh: Nice. Do we fly or take the bus?',
        'Linh: The sleeper bus is cheap — about eight hours overnight.',
        'Anh: Okay. What should we do there?',
        'Linh: The night market and maybe a coffee plantation tour.',
        'Anh: Book it. I will look at hotels tonight.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Lên trip: get away → how about X → fly or bus → itinerary; "Book it" = chốt luôn.',
    },
    targets: [
      target({
        id: 'ev24.t1',
        chunk: 'get away',
        cueVi: 'đi đâu đó nghỉ',
        sourceSentence: 'Anh: I want to get away next weekend. Any ideas?',
        productionPattern: 'get <away / out of town> for the weekend.',
        transferContext: 'planning a holiday break',
      }),
      target({
        id: 'ev24.t2',
        chunk: 'Any ideas',
        cueVi: 'có ý tưởng gì không',
        sourceSentence: 'Anh: I want to get away next weekend. Any ideas?',
        productionPattern: 'Any <ideas / suggestions>?',
        transferContext: 'brainstorming a birthday gift',
      }),
      target({
        id: 'ev24.t3',
        chunk: 'It is cooler there',
        cueVi: 'ở đó mát hơn',
        sourceSentence: 'Linh: How about Da Lat? It is cooler there.',
        productionPattern: 'It is <cooler / quieter / cheaper> there.',
        transferContext: 'recommending a beach town',
      }),
      target({
        id: 'ev24.t4',
        chunk: 'fly or take the bus',
        cueVi: 'bay hay đi xe khách',
        sourceSentence: 'Anh: Nice. Do we fly or take the bus?',
        productionPattern: '<fly / drive> or take the <bus / train>?',
        transferContext: 'comparing transport to a conference',
      }),
      target({
        id: 'ev24.t5',
        chunk: 'the sleeper bus',
        cueVi: 'xe giường nằm',
        sourceSentence: 'Linh: The sleeper bus is cheap — about eight hours overnight.',
        productionPattern: 'the <sleeper bus / night train>.',
        transferContext: 'choosing overnight transport',
      }),
      target({
        id: 'ev24.t6',
        chunk: 'eight hours overnight',
        cueVi: 'tám tiếng qua đêm',
        sourceSentence: 'Linh: The sleeper bus is cheap — about eight hours overnight.',
        productionPattern: '<eight hours / two days> overnight.',
        transferContext: 'describing a long train ride',
      }),
      target({
        id: 'ev24.t7',
        chunk: 'What should we do there',
        cueVi: 'ta nên làm gì ở đó',
        sourceSentence: 'Anh: Okay. What should we do there?',
        productionPattern: 'What should we <do / see / eat> there?',
        transferContext: 'planning activities in a new city',
      }),
      target({
        id: 'ev24.t8',
        chunk: 'Book it',
        cueVi: 'đặt luôn đi',
        sourceSentence: 'Anh: Book it. I will look at hotels tonight.',
        productionPattern: '<Book it / Go for it>.',
        transferContext: 'committing to a chosen flight',
      }),
    ],
    transferTask: {
      prompt: 'Plan a different trip — a beach weekend — transport choice, one activity, who books what.',
      promptVi: 'Lên một chuyến khác — cuối tuần biển — chọn phương tiện, một hoạt động, phân chia ai đặt gì.',
      changesDimension: 'destination type + task splitting between people',
    },
    recyclingFrom: ['ev03', 'ev13'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
];
