/* Everyday English ev01–ev12 (A1–A2) — life situations beyond survival. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const EVERYDAY_1: LessonSpec[] = [
  spec({
    id: 'ev01',
    level: 'a1',
    track: 'everyday',
    capabilities: ['describe-routine'],
    title: 'Your morning routine',
    titleVi: 'Buổi sáng của bạn',
    task: 'Describe what you do every morning and ask about theirs',
    context: 'Comparing mornings with a new roommate.',
    outcome: 'You can sequence a routine with time markers.',
    input: {
      title: 'EV01 · Mornings',
      text: [
        'Ben: What time do you usually wake up?',
        'Anh: I usually get up around six thirty.',
        'Ben: That is early. What do you do first?',
        'Anh: First I make coffee, then I check my messages.',
        'Ben: Do you eat breakfast at home?',
        'Anh: Usually, yes. Then I leave for work at eight.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Kể thói quen: usually + verb; nối ý bằng First / then; "get up" khác "wake up".',
    },
    targets: [
      target({
        id: 'ev01.t1',
        chunk: 'What time do you usually',
        cueVi: 'bạn thường ~ lúc mấy giờ',
        sourceSentence: 'Ben: What time do you usually wake up?',
        productionPattern: 'What time do you usually <wake up / leave>?',
        transferContext: 'asking a colleague about their commute',
      }),
      target({
        id: 'ev01.t2',
        chunk: 'I usually get up',
        cueVi: 'tôi thường thức dậy',
        sourceSentence: 'Anh: I usually get up around six thirty.',
        productionPattern: 'I usually <get up / start work> around seven.',
        transferContext: 'describing a weekend routine',
      }),
      target({
        id: 'ev01.t3',
        chunk: 'around six thirty',
        cueVi: 'khoảng sáu rưỡi',
        sourceSentence: 'Anh: I usually get up around six thirty.',
        productionPattern: 'around <six thirty / noon>.',
        transferContext: 'giving a loose arrival time',
      }),
      target({
        id: 'ev01.t4',
        chunk: 'What do you do first',
        cueVi: 'bạn làm gì đầu tiên',
        sourceSentence: 'Ben: That is early. What do you do first?',
        productionPattern: 'What do you do <first / next>?',
        transferContext: 'asking how someone starts a project',
      }),
      target({
        id: 'ev01.t5',
        chunk: 'First I make coffee',
        cueVi: 'đầu tiên tôi pha cà phê',
        sourceSentence: 'Anh: First I make coffee, then I check my messages.',
        productionPattern: 'First I <make coffee / shower>.',
        transferContext: 'describing the first step of a recipe',
      }),
      target({
        id: 'ev01.t6',
        chunk: 'then I check my messages',
        cueVi: 'rồi tôi xem tin nhắn',
        sourceSentence: 'Anh: First I make coffee, then I check my messages.',
        productionPattern: 'then I <check my messages / get dressed>.',
        transferContext: 'listing evening steps',
      }),
      target({
        id: 'ev01.t7',
        chunk: 'I leave for work',
        cueVi: 'tôi đi làm',
        sourceSentence: 'Anh: Usually, yes. Then I leave for work at eight.',
        productionPattern: 'I leave for <work / school> at eight.',
        transferContext: 'telling a friend when you are free',
      }),
    ],
    transferTask: {
      prompt: 'Describe your evening routine instead — three steps with first/then and approximate times.',
      promptVi: 'Kể thói quen buổi tối của bạn — ba bước với first/then và giờ gần đúng.',
      changesDimension: 'time of day + reversed sequence direction',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev02',
    level: 'a1',
    track: 'everyday',
    capabilities: ['describe-routine', 'schedule-appointment'],
    title: 'Your weekly schedule',
    titleVi: 'Lịch tuần của bạn',
    task: 'Describe which days you do things and find a free day',
    context: 'Planning a regular study session with a classmate.',
    outcome: 'You can say busy/free days and agree on a slot.',
    input: {
      title: 'EV02 · The week',
      text: [
        'Linh: Are you free on Tuesdays?',
        'Anh: Tuesdays are busy. I have a late meeting.',
        'Linh: How about Thursdays?',
        'Anh: Thursdays work. I finish at five.',
        'Linh: Great. Every Thursday then, at six?',
        'Anh: Perfect. See you Thursday.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"On + thứ" cho ngày trong tuần; "X works" = ngày đó ổn; "every Thursday" lịch định kỳ.',
    },
    targets: [
      target({
        id: 'ev02.t1',
        chunk: 'Are you free on',
        cueVi: 'bạn rảnh vào ~ không',
        sourceSentence: 'Linh: Are you free on Tuesdays?',
        productionPattern: 'Are you free on <Tuesday / Friday>?',
        transferContext: 'asking a tutor for a slot',
      }),
      target({
        id: 'ev02.t2',
        chunk: 'are busy',
        cueVi: 'bận',
        sourceSentence: 'Anh: Tuesdays are busy. I have a late meeting.',
        productionPattern: '<Mondays / Weekdays> are busy.',
        transferContext: 'explaining why weekends are better',
      }),
      target({
        id: 'ev02.t3',
        chunk: 'a late meeting',
        cueVi: 'cuộc họp muộn',
        sourceSentence: 'Anh: Tuesdays are busy. I have a late meeting.',
        productionPattern: 'a <late / early> <meeting / class>.',
        transferContext: 'excusing yourself from an event',
      }),
      target({
        id: 'ev02.t4',
        chunk: 'Thursdays work',
        cueVi: 'thứ năm được',
        sourceSentence: 'Anh: Thursdays work. I finish at five.',
        productionPattern: '<Thursdays / Mornings> work.',
        transferContext: 'confirming a gym schedule',
      }),
      target({
        id: 'ev02.t5',
        chunk: 'I finish at five',
        cueVi: 'tôi xong lúc năm giờ',
        sourceSentence: 'Anh: Thursdays work. I finish at five.',
        productionPattern: 'I finish <at five / late>.',
        transferContext: 'telling a friend pickup time',
      }),
      target({
        id: 'ev02.t6',
        chunk: 'Every Thursday then',
        cueVi: 'vậy thì mỗi thứ năm nhé',
        sourceSentence: 'Linh: Great. Every Thursday then, at six?',
        productionPattern: 'Every <Thursday / week> then.',
        transferContext: 'setting a recurring call',
      }),
    ],
    transferTask: {
      prompt: 'Find a weekly slot for language exchange — reject one day, accept another, set recurrence.',
      promptVi: 'Tìm khung giờ hàng tuần cho trao đổi ngôn ngữ — từ chối một ngày, nhận ngày khác, đặt lặp lại.',
      changesDimension: 'recurring commitment + negotiation both ways',
    },
    recyclingFrom: ['sv14', 'sv22'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev03',
    level: 'a1',
    track: 'everyday',
    capabilities: ['make-plans'],
    title: 'Make concrete plans',
    titleVi: 'Lên kế hoạch cụ thể',
    task: 'Turn a vague idea into a plan with time and place',
    context: 'Two friends deciding on a Saturday activity.',
    outcome: 'You can propose, adjust, and fix a plan.',
    input: {
      title: 'EV03 · Saturday plan',
      text: [
        'Tom: Want to do something this Saturday?',
        'Anh: Sure. How about hiking?',
        'Tom: It might rain. Maybe the museum instead?',
        'Anh: Good idea. Let us meet at ten.',
        'Tom: Where exactly?',
        'Anh: At the main entrance. I will text you the pin.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"It might rain" đưa lý do đổi plan; "Where exactly" hỏi chốt địa điểm.',
    },
    targets: [
      target({
        id: 'ev03.t1',
        chunk: 'Want to do something',
        cueVi: 'muốn đi chơi gì không',
        sourceSentence: 'Tom: Want to do something this Saturday?',
        productionPattern: 'Want to <do something / grab lunch>?',
        transferContext: 'inviting a coworker after work',
      }),
      target({
        id: 'ev03.t2',
        chunk: 'It might rain',
        cueVi: 'trời có thể mưa',
        sourceSentence: 'Tom: It might rain. Maybe the museum instead?',
        productionPattern: 'It might <rain / be crowded>.',
        transferContext: 'warning about a beach plan',
      }),
      target({
        id: 'ev03.t3',
        chunk: 'instead',
        cueVi: 'thay vào đó',
        sourceSentence: 'Tom: It might rain. Maybe the museum instead?',
        productionPattern: 'Maybe <the museum / coffee> instead?',
        transferContext: 'suggesting delivery instead of eating out',
      }),
      target({
        id: 'ev03.t4',
        chunk: 'Let us meet at ten',
        cueVi: 'hẹn mười giờ nhé',
        sourceSentence: 'Anh: Good idea. Let us meet at ten.',
        productionPattern: 'Let us meet at <ten / the station>.',
        transferContext: 'setting a call time with a client',
      }),
      target({
        id: 'ev03.t5',
        chunk: 'Where exactly',
        cueVi: 'chính xác ở đâu',
        sourceSentence: 'Tom: Where exactly?',
        productionPattern: 'Where <exactly / should we meet>?',
        transferContext: 'confirming a pickup point',
      }),
      target({
        id: 'ev03.t6',
        chunk: 'the main entrance',
        cueVi: 'cổng chính',
        sourceSentence: 'Anh: At the main entrance. I will text you the pin.',
        productionPattern: 'at the <main entrance / back gate>.',
        transferContext: 'describing where to meet at a mall',
      }),
      target({
        id: 'ev03.t7',
        chunk: 'I will text you',
        cueVi: 'tôi sẽ nhắn cho bạn',
        sourceSentence: 'Anh: At the main entrance. I will text you the pin.',
        productionPattern: 'I will <text / send> you the pin.',
        transferContext: 'sharing a document link later',
      }),
    ],
    transferTask: {
      prompt: 'Change an outdoor plan to indoor because of weather — propose, fix time and exact spot.',
      promptVi: 'Đổi kế hoạch ngoài trời sang trong nhà vì thời tiết — đề xuất, chốt giờ và điểm hẹn cụ thể.',
      changesDimension: 'same swap logic, different activity pair',
    },
    recyclingFrom: ['sv24'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev04',
    level: 'a1',
    track: 'everyday',
    capabilities: ['narrate-past'],
    title: 'Talk about yesterday',
    titleVi: 'Kể chuyện hôm qua',
    task: 'Say what you did yesterday in a few sentences',
    context: 'Monday small talk at work.',
    outcome: 'You can narrate a simple past sequence.',
    input: {
      title: 'EV04 · Yesterday',
      text: [
        'Sara: How was your Sunday, Minh?',
        'Minh: Pretty good. I slept in, then I went to the market.',
        'Sara: Did you buy anything interesting?',
        'Minh: Just vegetables. Then I cooked lunch and watched a film.',
        'Sara: Sounds relaxing.',
        'Minh: It was. I did not leave the house after three.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Quá khứ đơn: slept in → went → cooked → watched; "did not leave" phủ định.',
    },
    targets: [
      target({
        id: 'ev04.t1',
        chunk: 'How was your Sunday',
        cueVi: 'chủ nhật thế nào',
        sourceSentence: 'Sara: How was your Sunday, Minh?',
        productionPattern: 'How was your <Sunday / trip>?',
        transferContext: "asking about a colleague's holiday",
      }),
      target({
        id: 'ev04.t2',
        chunk: 'I slept in',
        cueVi: 'tôi ngủ nướng',
        sourceSentence: 'Minh: Pretty good. I slept in, then I went to the market.',
        productionPattern: 'I <slept in / stayed home>.',
        transferContext: 'describing a lazy Saturday',
      }),
      target({
        id: 'ev04.t3',
        chunk: 'I went to the market',
        cueVi: 'tôi đi chợ',
        sourceSentence: 'Minh: Pretty good. I slept in, then I went to the market.',
        productionPattern: 'I went to <the market / the gym>.',
        transferContext: 'saying where you went this morning',
      }),
      target({
        id: 'ev04.t4',
        chunk: 'Did you buy anything',
        cueVi: 'bạn có mua gì không',
        sourceSentence: 'Sara: Did you buy anything interesting?',
        productionPattern: 'Did you <buy / see / eat> anything?',
        transferContext: 'asking about a fair someone visited',
      }),
      target({
        id: 'ev04.t5',
        chunk: 'I cooked lunch',
        cueVi: 'tôi nấu bữa trưa',
        sourceSentence: 'Minh: Just vegetables. Then I cooked lunch and watched a film.',
        productionPattern: 'I cooked <lunch / dinner>.',
        transferContext: "describing last night's meal prep",
      }),
      target({
        id: 'ev04.t6',
        chunk: 'Sounds relaxing',
        cueVi: 'nghe thư giãn đấy',
        sourceSentence: 'Sara: Sounds relaxing.',
        productionPattern: 'Sounds <relaxing / fun / tiring>.',
        transferContext: "reacting to a friend's quiet weekend",
      }),
      target({
        id: 'ev04.t7',
        chunk: 'I did not leave the house',
        cueVi: 'tôi không ra khỏi nhà',
        sourceSentence: 'Minh: It was. I did not leave the house after three.',
        productionPattern: 'I did not <leave the house / go out>.',
        transferContext: 'explaining a missed message',
      }),
    ],
    transferTask: {
      prompt: 'Tell a different past sequence — a bad day this time (two problems, one fix).',
      promptVi: 'Kể một chuỗi quá khứ khác — lần này là một ngày tệ (hai vấn đề, một cách xử lý).',
      changesDimension: 'emotional valence + problem-solution structure',
    },
    recyclingFrom: ['sv19'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev05',
    level: 'a2',
    track: 'everyday',
    capabilities: ['compare-things', 'express-preference'],
    title: 'Compare two options',
    titleVi: 'So sánh hai lựa chọn',
    task: 'Compare two choices and justify your pick',
    context: 'Choosing between two apartments with a friend.',
    outcome: 'You can weigh pros/cons in simple comparative frames.',
    input: {
      title: 'EV05 · Which one',
      text: [
        'Linh: So, apartment A or B?',
        'Anh: A is cheaper, but B is closer to work.',
        'Linh: Which matters more to you?',
        'Anh: Honestly, the commute. A short ride saves an hour a day.',
        'Linh: But A is bigger, right?',
        'Anh: True. Still, I would rather pay more and live closer.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'So sánh: X is cheaper/closer/bigger; "I would rather" + chọn; "still" nhượng bộ.',
    },
    targets: [
      target({
        id: 'ev05.t1',
        chunk: 'A or B',
        cueVi: 'A hay B',
        sourceSentence: 'Linh: So, apartment A or B?',
        productionPattern: '<A or B / this or that>?',
        transferContext: 'asking a friend to pick between dishes',
      }),
      target({
        id: 'ev05.t2',
        chunk: 'is cheaper',
        cueVi: 'rẻ hơn',
        sourceSentence: 'Anh: A is cheaper, but B is closer to work.',
        productionPattern: '<A> is <cheaper / bigger / faster>.',
        transferContext: 'comparing two laptops',
      }),
      target({
        id: 'ev05.t3',
        chunk: 'closer to work',
        cueVi: 'gần chỗ làm hơn',
        sourceSentence: 'Anh: A is cheaper, but B is closer to work.',
        productionPattern: 'closer to <work / the station>.',
        transferContext: 'comparing two gyms',
      }),
      target({
        id: 'ev05.t4',
        chunk: 'Which matters more',
        cueVi: 'cái nào quan trọng hơn',
        sourceSentence: 'Linh: Which matters more to you?',
        productionPattern: 'Which matters <more / most>?',
        transferContext: 'comparing job offers',
      }),
      target({
        id: 'ev05.t5',
        chunk: 'the commute',
        cueVi: 'quãng đường đi làm',
        sourceSentence: 'Anh: Honestly, the commute. A short ride saves an hour a day.',
        productionPattern: 'the <commute / price / location>.',
        transferContext: 'explaining a housing decision',
      }),
      target({
        id: 'ev05.t6',
        chunk: 'I would rather',
        cueVi: 'tôi thà ~ hơn',
        sourceSentence: 'Anh: True. Still, I would rather pay more and live closer.',
        productionPattern: 'I would rather <pay more / stay home>.',
        transferContext: 'choosing a window seat over aisle',
      }),
    ],
    transferTask: {
      prompt: 'Compare two phone plans — price vs data — and justify your choice in two sentences.',
      promptVi: 'So sánh hai gói cước điện thoại — giá vs dung lượng — và giải thích lựa chọn trong hai câu.',
      changesDimension: 'different domain + numeric tradeoff',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev06',
    level: 'a1',
    track: 'everyday',
    capabilities: ['ask-price', 'express-preference'],
    title: 'Shop for clothes',
    titleVi: 'Mua quần áo',
    task: 'Ask for a different size or color while shopping',
    context: 'You found a shirt you like but not in your size.',
    outcome: 'You can ask sizes/colors and decide to try or buy.',
    input: {
      title: 'EV06 · Wrong size',
      text: [
        'Anh: Excuse me, do you have this in a medium?',
        'Clerk: Let me check. We have it in blue and black.',
        'Anh: Can I try the blue one on?',
        'Clerk: Sure, the fitting room is over there.',
        'Anh: It fits well. Is it on sale?',
        'Clerk: Yes, twenty percent off this week.',
        'Anh: Great, I will take it.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: '"in a medium" hỏi size; "try on" mặc thử; "on sale / X% off" giảm giá.',
    },
    targets: [
      target({
        id: 'ev06.t1',
        chunk: 'do you have this in a medium',
        cueVi: 'có cái này size M không',
        sourceSentence: 'Anh: Excuse me, do you have this in a medium?',
        productionPattern: 'do you have this in <a medium / another color>?',
        transferContext: 'asking for a shoe size',
      }),
      target({
        id: 'ev06.t2',
        chunk: 'Let me check',
        cueVi: 'để tôi kiểm tra',
        sourceSentence: 'Clerk: Let me check. We have it in blue and black.',
        productionPattern: 'Let me <check / see>.',
        transferContext: 'pausing to verify stock online',
      }),
      target({
        id: 'ev06.t3',
        chunk: 'try the blue one on',
        cueVi: 'mặc thử cái xanh',
        sourceSentence: 'Anh: Can I try the blue one on?',
        productionPattern: 'try <the blue one / these> on.',
        transferContext: 'trying shoes at a store',
      }),
      target({
        id: 'ev06.t4',
        chunk: 'the fitting room',
        cueVi: 'phòng thử đồ',
        sourceSentence: 'Clerk: Sure, the fitting room is over there.',
        productionPattern: 'the <fitting room / counter> is over there.',
        transferContext: 'asking where to try clothes',
      }),
      target({
        id: 'ev06.t5',
        chunk: 'It fits well',
        cueVi: 'vừa khít',
        sourceSentence: 'Anh: It fits well. Is it on sale?',
        productionPattern: 'It <fits well / is too tight>.',
        transferContext: 'describing a jacket to a friend',
      }),
      target({
        id: 'ev06.t6',
        chunk: 'on sale',
        cueVi: 'đang giảm giá',
        sourceSentence: 'Anh: It fits well. Is it on sale?',
        productionPattern: 'on <sale / discount>.',
        transferContext: 'asking about a promo at checkout',
      }),
      target({
        id: 'ev06.t7',
        chunk: 'twenty percent off',
        cueVi: 'giảm hai mươi phần trăm',
        sourceSentence: 'Clerk: Yes, twenty percent off this week.',
        productionPattern: '<twenty / fifty> percent off.',
        transferContext: 'explaining a store promo',
      }),
    ],
    transferTask: {
      prompt: 'Buy shoes — ask for your size, try them, ask about discount, decide.',
      promptVi: 'Mua giày — hỏi size, thử, hỏi giảm giá, quyết định.',
      changesDimension: 'footwear sizing + same shop script',
    },
    recyclingFrom: ['sv11', 'sv23'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev07',
    level: 'a1',
    track: 'everyday',
    capabilities: ['ask-directions'],
    title: 'Directions across town',
    titleVi: 'Chỉ đường trong thành phố',
    task: 'Follow longer directions with landmarks and transport',
    context: 'A local explains how to get to the museum from here.',
    outcome: 'You can follow multi-step directions with landmarks.',
    input: {
      title: 'EV07 · To the museum',
      text: [
        'Anh: How do I get to the city museum from here?',
        'Local: Take bus nine from that stop over there.',
        'Anh: Where do I get off?',
        'Local: At the post office — it takes about fifteen minutes.',
        'Anh: Is it far from the stop?',
        'Local: No, it is right across the street. You cannot miss it.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: '"How do I get to" hỏi đường; "get off" xuống xe; "You cannot miss it" = rất dễ thấy.',
    },
    targets: [
      target({
        id: 'ev07.t1',
        chunk: 'How do I get to',
        cueVi: 'đi đến ~ bằng cách nào',
        sourceSentence: 'Anh: How do I get to the city museum from here?',
        productionPattern: 'How do I get to <the museum / the airport>?',
        transferContext: 'asking transit to a stadium',
      }),
      target({
        id: 'ev07.t2',
        chunk: 'Take bus nine',
        cueVi: 'đi xe buýt số 9',
        sourceSentence: 'Local: Take bus nine from that stop over there.',
        productionPattern: 'Take <bus nine / the metro> from here.',
        transferContext: 'telling a friend which train to board',
      }),
      target({
        id: 'ev07.t3',
        chunk: 'Where do I get off',
        cueVi: 'tôi xuống ở đâu',
        sourceSentence: 'Anh: Where do I get off?',
        productionPattern: 'Where do I <get off / transfer>?',
        transferContext: 'asking a metro connection',
      }),
      target({
        id: 'ev07.t4',
        chunk: 'the post office',
        cueVi: 'bưu điện',
        sourceSentence: 'Local: At the post office — it takes about fifteen minutes.',
        productionPattern: 'at the <post office / next stop>.',
        transferContext: 'naming a landmark stop',
      }),
      target({
        id: 'ev07.t5',
        chunk: 'it takes about fifteen minutes',
        cueVi: 'mất khoảng mười lăm phút',
        sourceSentence: 'Local: At the post office — it takes about fifteen minutes.',
        productionPattern: 'it takes about <fifteen / twenty> minutes.',
        transferContext: 'estimating walk time for a visitor',
      }),
      target({
        id: 'ev07.t6',
        chunk: 'across the street',
        cueVi: 'bên kia đường',
        sourceSentence: 'Local: No, it is right across the street. You cannot miss it.',
        productionPattern: 'across <the street / the park>.',
        transferContext: 'pointing out a bank to a tourist',
      }),
      target({
        id: 'ev07.t7',
        chunk: 'You cannot miss it',
        cueVi: 'không thể không thấy',
        sourceSentence: 'Local: No, it is right across the street. You cannot miss it.',
        productionPattern: 'You cannot <miss it / go wrong>.',
        transferContext: 'assuring someone a venue is obvious',
      }),
    ],
    transferTask: {
      prompt: 'Explain how to reach your home from the station — transport, stop, landmark.',
      promptVi: 'Chỉ cách đến nhà bạn từ ga — phương tiện, điểm xuống, landmark.',
      changesDimension: 'you give directions (role reversal)',
    },
    recyclingFrom: ['sv17'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev08',
    level: 'a1',
    track: 'everyday',
    capabilities: ['order-food'],
    title: 'At the restaurant',
    titleVi: 'Ở nhà hàng',
    task: 'Order at a sit-down restaurant and ask about the menu',
    context: 'Dinner with a friend at a small restaurant.',
    outcome: 'You can order courses and handle the bill.',
    input: {
      title: 'EV08 · Dinner out',
      text: [
        'Waiter: Are you ready to order?',
        'Anh: Yes. What do you recommend?',
        'Waiter: The grilled fish is very popular.',
        'Anh: I will have that, with rice. And water, please.',
        'Waiter: Anything for dessert?',
        'Anh: Not now, thank you. Could we have the bill later?',
        'Waiter: Of course.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: '"I will have" gọi món trang trọng hơn "Can I have"; "the bill" = tính tiền.',
    },
    targets: [
      target({
        id: 'ev08.t1',
        chunk: 'Are you ready to order',
        cueVi: 'bạn gọi món chưa',
        sourceSentence: 'Waiter: Are you ready to order?',
        productionPattern: 'ready to <order / go>?',
        transferContext: 'hearing the question at a café',
      }),
      target({
        id: 'ev08.t2',
        chunk: 'What do you recommend',
        cueVi: 'bạn gợi ý món gì',
        sourceSentence: 'Anh: Yes. What do you recommend?',
        productionPattern: 'What do you <recommend / suggest>?',
        transferContext: 'asking a barista for a drink pick',
      }),
      target({
        id: 'ev08.t3',
        chunk: 'very popular',
        cueVi: 'rất được ưa chuộng',
        sourceSentence: 'Waiter: The grilled fish is very popular.',
        productionPattern: '<The grilled fish / This dish> is very popular.',
        transferContext: 'recommending a dish to a guest',
      }),
      target({
        id: 'ev08.t4',
        chunk: 'I will have that',
        cueVi: 'tôi lấy món đó',
        sourceSentence: 'Anh: I will have that, with rice. And water, please.',
        productionPattern: 'I will have <that / the chicken>, with rice.',
        transferContext: 'ordering at a lunch counter',
      }),
      target({
        id: 'ev08.t5',
        chunk: 'with rice',
        cueVi: 'kèm cơm',
        sourceSentence: 'Anh: I will have that, with rice. And water, please.',
        productionPattern: 'with <rice / no ice / extra sauce>.',
        transferContext: 'customizing a fast-food order',
      }),
      target({
        id: 'ev08.t6',
        chunk: 'Anything for dessert',
        cueVi: 'có dùng tráng miệng không',
        sourceSentence: 'Waiter: Anything for dessert?',
        productionPattern: 'Anything for <dessert / to start>?',
        transferContext: 'offering a guest fruit after dinner',
      }),
      target({
        id: 'ev08.t7',
        chunk: 'the bill',
        cueVi: 'hóa đơn',
        sourceSentence: 'Anh: Not now, thank you. Could we have the bill later?',
        productionPattern: 'Could we have <the bill / the check>?',
        transferContext: 'closing out at a café',
      }),
    ],
    transferTask: {
      prompt: 'Order for two people — recommend question, two different dishes, and split the bill at the end.',
      promptVi: 'Gọi món cho hai người — hỏi gợi ý, hai món khác nhau, và tách bill cuối bữa.',
      changesDimension: 'ordering for two + bill splitting',
    },
    recyclingFrom: ['sv16'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev09',
    level: 'a2',
    track: 'everyday',
    capabilities: ['order-food', 'express-preference'],
    title: 'Order it your way',
    titleVi: 'Gọi theo cách của bạn',
    task: 'Customize a drink order with size, milk, and extras',
    context: 'A busy coffee chain with a long customization menu.',
    outcome: 'You can specify exactly what you want.',
    input: {
      title: 'EV09 · Coffee run',
      text: [
        'Barista: Next! What can I make for you?',
        'Anh: A medium latte, please. With oat milk.',
        'Barista: Hot or iced?',
        'Anh: Iced, please. Not too sweet — maybe half the syrup.',
        'Barista: No problem. Anything to eat?',
        'Anh: That is everything, thanks.',
        'Barista: It will be ready at the end of the counter.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Tùy chỉnh: size + sữa + đá/nóng + độ ngọt; "That is everything" = hết order.',
    },
    targets: [
      target({
        id: 'ev09.t1',
        chunk: 'What can I make for you',
        cueVi: 'tôi pha gì cho bạn',
        sourceSentence: 'Barista: Next! What can I make for you?',
        productionPattern: 'What can I <make / get> for you?',
        transferContext: 'hearing it at a juice bar',
      }),
      target({
        id: 'ev09.t2',
        chunk: 'a medium latte',
        cueVi: 'một ly latte vừa',
        sourceSentence: 'Anh: A medium latte, please. With oat milk.',
        productionPattern: 'a <medium / large> <latte / americano>.',
        transferContext: 'ordering a different drink size',
      }),
      target({
        id: 'ev09.t3',
        chunk: 'with oat milk',
        cueVi: 'với sữa yến mạch',
        sourceSentence: 'Anh: A medium latte, please. With oat milk.',
        productionPattern: 'with <oat milk / no sugar / extra shot>.',
        transferContext: 'asking for almond milk instead',
      }),
      target({
        id: 'ev09.t4',
        chunk: 'Hot or iced',
        cueVi: 'nóng hay đá',
        sourceSentence: 'Barista: Hot or iced?',
        productionPattern: '<Hot or iced / Small or large>?',
        transferContext: 'hearing the question at a tea shop',
      }),
      target({
        id: 'ev09.t5',
        chunk: 'Not too sweet',
        cueVi: 'đừng quá ngọt',
        sourceSentence: 'Anh: Iced, please. Not too sweet — maybe half the syrup.',
        productionPattern: 'Not too <sweet / strong / spicy>.',
        transferContext: 'asking for mild curry',
      }),
      target({
        id: 'ev09.t6',
        chunk: 'half the syrup',
        cueVi: 'một nửa syrup',
        sourceSentence: 'Anh: Iced, please. Not too sweet — maybe half the syrup.',
        productionPattern: 'half the <syrup / sugar>.',
        transferContext: 'cutting sugar in a smoothie',
      }),
      target({
        id: 'ev09.t7',
        chunk: 'That is everything',
        cueVi: 'vậy là đủ rồi',
        sourceSentence: 'Anh: That is everything, thanks.',
        productionPattern: 'That is <everything / all>, thanks.',
        transferContext: 'finishing a grocery order',
      }),
    ],
    transferTask: {
      prompt: 'Order the same drink for a friend with different preferences — change two customizations.',
      promptVi: 'Gọi cùng món cho một người bạn thích khác — đổi hai tùy chỉnh.',
      changesDimension: 'ordering on behalf + swapped specs',
    },
    recyclingFrom: ['ev08'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev10',
    level: 'a2',
    track: 'everyday',
    capabilities: ['see-doctor'],
    title: 'At the doctor',
    titleVi: 'Ở phòng khám',
    task: 'Describe symptoms and understand simple advice',
    context: 'You have had a headache and sore throat for two days.',
    outcome: 'You can name symptoms, duration, and follow instructions.',
    input: {
      title: 'EV10 · Clinic visit',
      text: [
        'Doctor: What brings you in today?',
        'Anh: I have had a headache and a sore throat since Monday.',
        'Doctor: Any fever?',
        'Anh: A small one last night — about thirty-eight degrees.',
        'Doctor: Probably a cold. Drink plenty of water and rest.',
        'Anh: Should I take any medicine?',
        'Doctor: Just painkillers if it gets worse. Come back if it lasts a week.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Triệu chứng + thời gian (since Monday); "What brings you in" = lý do đến khám.',
    },
    targets: [
      target({
        id: 'ev10.t1',
        chunk: 'What brings you in',
        cueVi: 'bạn đến khám vì lý do gì',
        sourceSentence: 'Doctor: What brings you in today?',
        productionPattern: 'What brings you in <today>?',
        transferContext: 'hearing the intake question at a dentist',
      }),
      target({
        id: 'ev10.t2',
        chunk: 'I have had a headache',
        cueVi: 'tôi bị đau đầu',
        sourceSentence: 'Anh: I have had a headache and a sore throat since Monday.',
        productionPattern: 'I have had a <headache / cough / fever>.',
        transferContext: 'describing a backache to a pharmacist',
      }),
      target({
        id: 'ev10.t3',
        chunk: 'a sore throat',
        cueVi: 'đau họng',
        sourceSentence: 'Anh: I have had a headache and a sore throat since Monday.',
        productionPattern: 'a <sore throat / runny nose / bad cough>.',
        transferContext: 'telling a school nurse your symptoms',
      }),
      target({
        id: 'ev10.t4',
        chunk: 'since Monday',
        cueVi: 'từ thứ hai',
        sourceSentence: 'Anh: I have had a headache and a sore throat since Monday.',
        productionPattern: 'since <Monday / yesterday / last week>.',
        transferContext: 'reporting how long pain lasted',
      }),
      target({
        id: 'ev10.t5',
        chunk: 'Any fever',
        cueVi: 'có sốt không',
        sourceSentence: 'Doctor: Any fever?',
        productionPattern: 'Any <fever / pain / allergies>?',
        transferContext: 'answering screening questions at a pharmacy',
      }),
      target({
        id: 'ev10.t6',
        chunk: 'plenty of water',
        cueVi: 'nhiều nước',
        sourceSentence: 'Doctor: Probably a cold. Drink plenty of water and rest.',
        productionPattern: 'plenty of <water / rest / sleep>.',
        transferContext: 'advising a sick colleague',
      }),
      target({
        id: 'ev10.t7',
        chunk: 'painkillers',
        cueVi: 'thuốc giảm đau',
        sourceSentence: 'Doctor: Just painkillers if it gets worse.',
        productionPattern: '<painkillers / this medicine> twice a day.',
        transferContext: 'asking dosage at a pharmacy',
      }),
      target({
        id: 'ev10.t8',
        chunk: 'if it gets worse',
        cueVi: 'nếu nó nặng hơn',
        sourceSentence: 'Doctor: Just painkillers if it gets worse. Come back if it lasts a week.',
        productionPattern: 'if it gets <worse / better>.',
        transferContext: 'describing when to return to a clinic',
      }),
    ],
    transferTask: {
      prompt: 'Describe a different issue — stomachache after food — with duration and a question about medicine.',
      promptVi: 'Mô tả vấn đề khác — đau bụng sau khi ăn — kèm thời gian và câu hỏi về thuốc.',
      changesDimension: 'symptom domain + cause suspicion',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev11',
    level: 'a2',
    track: 'everyday',
    capabilities: ['see-doctor', 'describe-problem'],
    title: 'At the pharmacy',
    titleVi: 'Ở hiệu thuốc',
    task: 'Ask for over-the-counter medicine and check dosage',
    context: 'You need something for allergies at a pharmacy.',
    outcome: 'You can describe a minor issue and confirm how to take medicine.',
    input: {
      title: 'EV11 · Pharmacy',
      text: [
        'Anh: Hi, do you have anything for allergies?',
        'Pharmacist: Sneezing or itchy eyes?',
        'Anh: Both, mostly in the morning.',
        'Pharmacist: This one works well. Take one tablet a day.',
        'Anh: With food or without?',
        'Pharmacist: Either is fine. Do not take more than one.',
        'Anh: Got it. How much is it?',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"anything for X" hỏi thuốc; liều: one tablet a day; "with food or without" hỏi cách uống.',
    },
    targets: [
      target({
        id: 'ev11.t1',
        chunk: 'anything for allergies',
        cueVi: 'có thuốc gì cho dị ứng không',
        sourceSentence: 'Anh: Hi, do you have anything for allergies?',
        productionPattern: 'anything for <allergies / a cold / pain>?',
        transferContext: 'asking for motion-sickness pills',
      }),
      target({
        id: 'ev11.t2',
        chunk: 'itchy eyes',
        cueVi: 'mắt ngứa',
        sourceSentence: 'Pharmacist: Sneezing or itchy eyes?',
        productionPattern: '<itchy eyes / runny nose / dry skin>.',
        transferContext: 'describing symptoms at a different pharmacy',
      }),
      target({
        id: 'ev11.t3',
        chunk: 'one tablet a day',
        cueVi: 'một viên mỗi ngày',
        sourceSentence: 'Pharmacist: This one works well. Take one tablet a day.',
        productionPattern: '<one / two> tablets a day.',
        transferContext: 'confirming vitamin dosage',
      }),
      target({
        id: 'ev11.t4',
        chunk: 'With food or without',
        cueVi: 'uống cùng bữa ăn hay không',
        sourceSentence: 'Anh: With food or without?',
        productionPattern: 'With <food or without / water>?',
        transferContext: 'checking antibiotic instructions',
      }),
      target({
        id: 'ev11.t5',
        chunk: 'Do not take more than one',
        cueVi: 'đừng uống quá một viên',
        sourceSentence: 'Pharmacist: Either is fine. Do not take more than one.',
        productionPattern: 'Do not take more than <one / two>.',
        transferContext: 'warning a friend about dosage',
      }),
      target({
        id: 'ev11.t6',
        chunk: 'Either is fine',
        cueVi: 'cách nào cũng được',
        sourceSentence: 'Pharmacist: Either is fine. Do not take more than one.',
        productionPattern: 'Either <is fine / works>.',
        transferContext: 'saying two options both work',
      }),
    ],
    transferTask: {
      prompt: 'Ask for something for a different issue — insect bites — and confirm usage instructions.',
      promptVi: 'Hỏi thuốc cho vấn đề khác — muỗi/côn trùng cắn — và xác nhận cách dùng.',
      changesDimension: 'topical treatment + different dosing question',
    },
    recyclingFrom: ['ev10'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'ev12',
    level: 'a2',
    track: 'everyday',
    capabilities: ['hotel-checkin'],
    title: 'Hotel check-in',
    titleVi: 'Nhận phòng khách sạn',
    task: 'Check in, give your booking name, and ask about breakfast and wifi',
    context: 'Arriving at a small hotel after a long trip.',
    outcome: 'You can complete check-in and get key information.',
    input: {
      title: 'EV12 · Check-in',
      text: [
        'Receptionist: Good evening. Checking in?',
        'Anh: Yes, I have a reservation under Nguyen.',
        'Receptionist: Two nights, a double room — correct?',
        'Anh: That is right. Is breakfast included?',
        'Receptionist: Yes, seven to ten in the lobby. Here is your key card.',
        'Anh: And what is the wifi password?',
        'Receptionist: It is on the card sleeve. Checkout is at noon.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"reservation under + tên" cho booking; "included" đã bao gồm; checkout time phải nghe kỹ.',
    },
    targets: [
      target({
        id: 'ev12.t1',
        chunk: 'Checking in',
        cueVi: 'nhận phòng',
        sourceSentence: 'Receptionist: Good evening. Checking in?',
        productionPattern: '<Checking in / checking out>?',
        transferContext: 'hearing the question at a hostel desk',
      }),
      target({
        id: 'ev12.t2',
        chunk: 'a reservation under',
        cueVi: 'đặt phòng dưới tên',
        sourceSentence: 'Anh: Yes, I have a reservation under Nguyen.',
        productionPattern: 'a reservation under <Nguyen / my name>.',
        transferContext: 'claiming a restaurant booking',
      }),
      target({
        id: 'ev12.t3',
        chunk: 'a double room',
        cueVi: 'phòng đôi',
        sourceSentence: 'Receptionist: Two nights, a double room — correct?',
        productionPattern: 'a <double / single / twin> room.',
        transferContext: 'confirming room type by phone',
      }),
      target({
        id: 'ev12.t4',
        chunk: 'Is breakfast included',
        cueVi: 'có bao gồm bữa sáng không',
        sourceSentence: 'Anh: That is right. Is breakfast included?',
        productionPattern: 'Is <breakfast / parking> included?',
        transferContext: 'asking about included amenities at a resort',
      }),
      target({
        id: 'ev12.t5',
        chunk: 'the wifi password',
        cueVi: 'mật khẩu wifi',
        sourceSentence: 'Anh: And what is the wifi password?',
        productionPattern: 'the <wifi password / gym hours>.',
        transferContext: 'asking at an airport lounge',
      }),
      target({
        id: 'ev12.t6',
        chunk: 'on the card sleeve',
        cueVi: 'trên bao thẻ',
        sourceSentence: 'Receptionist: It is on the card sleeve. Checkout is at noon.',
        productionPattern: 'on the <card sleeve / desk card>.',
        transferContext: 'finding info printed on materials',
      }),
      target({
        id: 'ev12.t7',
        chunk: 'Checkout is at noon',
        cueVi: 'trả phòng lúc trưa',
        sourceSentence: 'Receptionist: It is on the card sleeve. Checkout is at noon.',
        productionPattern: 'Checkout is at <noon / eleven>.',
        transferContext: 'confirming departure time at a hostel',
      }),
    ],
    transferTask: {
      prompt: 'Check into an Airbnb-style guesthouse — confirm booking, ask for door code and quiet hours.',
      promptVi: 'Nhận phòng kiểu guesthouse — xác nhận booking, hỏi mã cửa và giờ yên tĩnh.',
      changesDimension: 'self-check-in setting + different facility questions',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
];
