/* Grammar-support gr01–gr12 — grammar serving a functional task, not rules for
 * rules' sake. Each lesson ties a form to an everyday job. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const GRAMMAR: LessonSpec[] = [
  spec({
    id: 'gr01',
    level: 'a0',
    track: 'grammar-support',
    capabilities: ['use-be'],
    title: 'Am, is, are',
    titleVi: 'Am, is, are',
    task: 'Introduce people and things with the right "be" form',
    context: 'Introducing yourself and a friend.',
    outcome: 'You can match I/you/he-she/it/we-they with be.',
    input: {
      title: 'GR01 · Be',
      text: [
        'Anh: I am Anh. This is my friend Tom.',
        'Tom: Hi. Tom is a student here.',
        'Anh: We are in the same class.',
        'Tom: Are you new to the city?',
        'Anh: Yes, I am. It is my first month.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'I am / he-she-it is / you-we-they are. Câu hỏi đảo "be" lên đầu.',
    },
    targets: [
      target({
        id: 'gr01.t1',
        chunk: 'I am Anh',
        cueVi: 'tôi là Anh',
        sourceSentence: 'Anh: I am Anh. This is my friend Tom.',
        productionPattern: 'I am <name / a student / new>.',
        transferContext: 'introducing yourself in class',
      }),
      target({
        id: 'gr01.t2',
        chunk: 'This is my friend',
        cueVi: 'đây là bạn tôi',
        sourceSentence: 'Anh: I am Anh. This is my friend Tom.',
        productionPattern: 'This is my <friend / wife / colleague>.',
        transferContext: 'introducing a colleague at work',
      }),
      target({
        id: 'gr01.t3',
        chunk: 'is a student',
        cueVi: 'là sinh viên',
        sourceSentence: 'Tom: Hi. Tom is a student here.',
        productionPattern: '<He / She> is a <student / teacher>.',
        transferContext: "describing a sibling's job",
      }),
      target({
        id: 'gr01.t4',
        chunk: 'We are in the same class',
        cueVi: 'chúng tôi cùng lớp',
        sourceSentence: 'Anh: We are in the same class.',
        productionPattern: 'We are <in the same class / coworkers / neighbors>.',
        transferContext: 'explaining how you know someone',
      }),
      target({
        id: 'gr01.t5',
        chunk: 'Are you new',
        cueVi: 'bạn mới đến à',
        sourceSentence: 'Tom: Are you new to the city?',
        productionPattern: 'Are you <new / ready / sure>?',
        transferContext: 'asking if someone just moved',
      }),
      target({
        id: 'gr01.t6',
        chunk: 'my first month',
        cueVi: 'tháng đầu của tôi',
        sourceSentence: 'Anh: Yes, I am. It is my first month.',
        productionPattern: 'my <first / second> month.',
        transferContext: 'saying how long you have been somewhere',
      }),
    ],
    transferTask: {
      prompt: 'Introduce a different pair — a spouse and a coworker — with correct be-forms.',
      promptVi: 'Giới thiệu một cặp khác — vợ/chồng và đồng nghiệp — với be đúng.',
      changesDimension: 'relationship types + more he/she mixing',
    },
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr02',
    level: 'a1',
    track: 'grammar-support',
    capabilities: ['ask-yesno'],
    title: 'Do and does questions',
    titleVi: 'Câu hỏi với do/does',
    task: 'Ask everyday yes/no questions with do and does',
    context: 'Interviewing a new classmate about their life.',
    outcome: 'You can choose do vs does correctly.',
    input: {
      title: 'GR02 · Do/Does',
      text: [
        'Anh: Do you live near here?',
        'Linh: Yes, I do. And you?',
        'Anh: I live downtown. Does your family live here too?',
        'Linh: No, they do not. They are in Hue.',
        'Anh: Do you visit them often?',
        'Linh: Not really — maybe twice a year.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'do cho I/you/we/they; does cho he/she/it. Trả lời ngắn: Yes I do / No they do not.',
    },
    targets: [
      target({
        id: 'gr02.t1',
        chunk: 'Do you live near here',
        cueVi: 'bạn sống gần đây không',
        sourceSentence: 'Anh: Do you live near here?',
        productionPattern: 'Do you <live / work / study> near here?',
        transferContext: 'asking a neighbor about their commute',
      }),
      target({
        id: 'gr02.t2',
        chunk: 'Yes, I do',
        cueVi: 'có (đúng)',
        sourceSentence: 'Linh: Yes, I do. And you?',
        productionPattern: 'Yes, I <do / am / can>.',
        transferContext: 'short answers in any interview',
      }),
      target({
        id: 'gr02.t3',
        chunk: 'I live downtown',
        cueVi: 'tôi sống ở trung tâm',
        sourceSentence: 'Anh: I live downtown. Does your family live here too?',
        productionPattern: 'I live <downtown / nearby / alone>.',
        transferContext: 'saying where you live to a colleague',
      }),
      target({
        id: 'gr02.t4',
        chunk: 'Does your family live here',
        cueVi: 'gia đình bạn sống đây không',
        sourceSentence: 'Anh: I live downtown. Does your family live here too?',
        productionPattern: 'Does your <family / roommate> live here?',
        transferContext: "asking about a friend's household",
      }),
      target({
        id: 'gr02.t5',
        chunk: 'they do not',
        cueVi: 'họ không',
        sourceSentence: 'Linh: No, they do not. They are in Hue.',
        productionPattern: "they do <not / n't>.",
        transferContext: 'denying a guess about someone',
      }),
      target({
        id: 'gr02.t6',
        chunk: 'Do you visit them often',
        cueVi: 'bạn có thường thăm họ không',
        sourceSentence: 'Anh: Do you visit them often?',
        productionPattern: 'Do you visit <them / home> often?',
        transferContext: 'asking about hometown visits',
      }),
      target({
        id: 'gr02.t7',
        chunk: 'twice a year',
        cueVi: 'hai lần một năm',
        sourceSentence: 'Linh: Not really — maybe twice a year.',
        productionPattern: '<twice / once / three times> a year.',
        transferContext: 'reporting frequency of a habit',
      }),
    ],
    transferTask: {
      prompt: 'Interview a teammate about their routine — three do/does questions + short answers.',
      promptVi: 'Phỏng vấn đồng đội về thói quen — ba câu do/does + trả lời ngắn.',
      changesDimension: 'routine topic + question-only focus',
    },
    recyclingFrom: ['sv10'],
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr03',
    level: 'a1',
    track: 'grammar-support',
    capabilities: ['use-third-person-s'],
    title: 'The -s on he and she',
    titleVi: 'Đuôi -s cho ngôi ba',
    task: "Describe another person's routine with correct -s",
    context: "Talking about your sister's typical day.",
    outcome: 'You can add -s to he/she/it verbs.',
    input: {
      title: 'GR03 · She works',
      text: [
        'Anh: My sister works at a hospital.',
        'Tom: What does she do there?',
        'Anh: She checks patients in. She starts at seven.',
        'Tom: Does she like it?',
        'Anh: She loves it. She finishes at three, then she studies.',
        'Tom: Busy. Does she ever rest?',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'he/she/it + verb-s: works, checks, starts, loves, finishes. Câu hỏi dùng does → bỏ s ở động từ.',
    },
    targets: [
      target({
        id: 'gr03.t1',
        chunk: 'works at a hospital',
        cueVi: 'làm việc ở bệnh viện',
        sourceSentence: 'Anh: My sister works at a hospital.',
        productionPattern: '<She / He> works at a <hospital / bank>.',
        transferContext: "describing a parent's job",
      }),
      target({
        id: 'gr03.t2',
        chunk: 'What does she do',
        cueVi: 'cô ấy làm gì',
        sourceSentence: 'Tom: What does she do there?',
        productionPattern: 'What does <she / he> do?',
        transferContext: "asking about someone's role",
      }),
      target({
        id: 'gr03.t3',
        chunk: 'checks patients in',
        cueVi: 'tiếp nhận bệnh nhân',
        sourceSentence: 'Anh: She checks patients in. She starts at seven.',
        productionPattern: '<checks in / signs in> patients.',
        transferContext: "describing a receptionist's job",
      }),
      target({
        id: 'gr03.t4',
        chunk: 'starts at seven',
        cueVi: 'bắt đầu lúc bảy giờ',
        sourceSentence: 'Anh: She checks patients in. She starts at seven.',
        productionPattern: '<starts / finishes> at <seven / three>.',
        transferContext: "reporting someone's shift",
      }),
      target({
        id: 'gr03.t5',
        chunk: 'Does she like it',
        cueVi: 'cô ấy có thích không',
        sourceSentence: 'Tom: Does she like it?',
        productionPattern: 'Does <she / he> like it?',
        transferContext: "asking about someone's hobby",
      }),
      target({
        id: 'gr03.t6',
        chunk: 'She loves it',
        cueVi: 'cô ấy rất thích',
        sourceSentence: 'Anh: She loves it. She finishes at three, then she studies.',
        productionPattern: 'She <loves / hates> it.',
        transferContext: "reacting to someone's enthusiasm",
      }),
      target({
        id: 'gr03.t7',
        chunk: 'finishes at three',
        cueVi: 'kết thúc lúc ba giờ',
        sourceSentence: 'Anh: She loves it. She finishes at three, then she studies.',
        productionPattern: 'finishes at <three / five>.',
        transferContext: 'reporting end-of-shift time',
      }),
    ],
    transferTask: {
      prompt: "Describe a different person's routine — a roommate — three facts with -s endings.",
      promptVi: 'Tả thói quen người khác — bạn cùng phòng — ba sự thật với đuôi -s.',
      changesDimension: 'different person + only third-person facts',
    },
    recyclingFrom: ['ev01'],
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr04',
    level: 'a1',
    track: 'grammar-support',
    capabilities: ['use-past'],
    title: 'Was and were',
    titleVi: 'Was và were',
    task: 'Describe past states and feelings',
    context: 'Reviewing a trip that ended yesterday.',
    outcome: 'You can use was/were for past descriptions.',
    input: {
      title: 'GR04 · The trip',
      text: [
        'Sara: How was the trip?',
        'Anh: It was great. The hotel was right on the beach.',
        'Sara: Were the people friendly?',
        'Anh: They were lovely. The food was amazing too.',
        'Sara: Was it expensive?',
        'Anh: It was not bad — cheaper than I expected.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'was cho I/he/she/it; were cho you/we/they. Phủ định: was not/were not.',
    },
    targets: [
      target({
        id: 'gr04.t1',
        chunk: 'How was the trip',
        cueVi: 'chuyến đi thế nào',
        sourceSentence: 'Sara: How was the trip?',
        productionPattern: 'How was <the trip / the food / your day>?',
        transferContext: "asking about a friend's weekend",
      }),
      target({
        id: 'gr04.t2',
        chunk: 'It was great',
        cueVi: 'tuyệt lắm',
        sourceSentence: 'Anh: It was great. The hotel was right on the beach.',
        productionPattern: 'It was <great / okay / terrible>.',
        transferContext: 'reviewing a restaurant',
      }),
      target({
        id: 'gr04.t3',
        chunk: 'right on the beach',
        cueVi: 'ngay trên bãi biển',
        sourceSentence: 'Anh: It was great. The hotel was right on the beach.',
        productionPattern: 'right on the <beach / corner>.',
        transferContext: 'describing a great location',
      }),
      target({
        id: 'gr04.t4',
        chunk: 'Were the people friendly',
        cueVi: 'người dân có thân thiện không',
        sourceSentence: 'Sara: Were the people friendly?',
        productionPattern: 'Were the <people / staff / rooms> friendly?',
        transferContext: 'asking about service quality',
      }),
      target({
        id: 'gr04.t5',
        chunk: 'They were lovely',
        cueVi: 'họ rất đáng yêu',
        sourceSentence: 'Anh: They were lovely. The food was amazing too.',
        productionPattern: 'They were <lovely / helpful / rude>.',
        transferContext: 'describing hosts at a guesthouse',
      }),
      target({
        id: 'gr04.t6',
        chunk: 'Was it expensive',
        cueVi: 'có đắt không',
        sourceSentence: 'Sara: Was it expensive?',
        productionPattern: 'Was it <expensive / crowded / far>?',
        transferContext: 'asking about a concert ticket',
      }),
      target({
        id: 'gr04.t7',
        chunk: 'cheaper than I expected',
        cueVi: 'rẻ hơn tôi tưởng',
        sourceSentence: 'Anh: It was not bad — cheaper than I expected.',
        productionPattern: '<cheaper / better / worse> than I expected.',
        transferContext: 'reviewing a purchase',
      }),
    ],
    transferTask: {
      prompt: 'Review a different past experience — a concert — with was/were descriptions.',
      promptVi: 'Đánh giá một trải nghiệm quá khứ khác — buổi hòa nhạc — với was/were.',
      changesDimension: 'event type + mixed was/were',
    },
    recyclingFrom: ['ev04'],
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr05',
    level: 'a1',
    track: 'grammar-support',
    capabilities: ['use-going-to', 'make-plans'],
    title: 'Going to for plans',
    titleVi: 'Going to cho kế hoạch',
    task: 'Talk about decided future plans',
    context: "Discussing next month's moves with a friend.",
    outcome: 'You can state intentions with going to.',
    input: {
      title: 'GR05 · Plans',
      text: [
        'Tom: What are you going to do this summer?',
        'Anh: I am going to take an English course.',
        'Tom: Nice. Are you going to study online?',
        'Anh: Partly. I am going to a center two days a week.',
        'Tom: Are you going to take a test after?',
        'Anh: Yes, I am going to try the B1 exam.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'be + going to + verb = kế hoạch đã quyết. Hỏi: Are you going to...?',
    },
    targets: [
      target({
        id: 'gr05.t1',
        chunk: 'What are you going to do',
        cueVi: 'bạn định làm gì',
        sourceSentence: 'Tom: What are you going to do this summer?',
        productionPattern: 'What are you going to <do / eat / watch>?',
        transferContext: 'asking weekend plans',
      }),
      target({
        id: 'gr05.t2',
        chunk: 'take an English course',
        cueVi: 'học một khóa tiếng Anh',
        sourceSentence: 'Anh: I am going to take an English course.',
        productionPattern: 'take an <English / cooking> course.',
        transferContext: 'describing a learning goal',
      }),
      target({
        id: 'gr05.t3',
        chunk: 'study online',
        cueVi: 'học online',
        sourceSentence: 'Tom: Nice. Are you going to study online?',
        productionPattern: '<study / work / shop> online.',
        transferContext: 'asking about learning format',
      }),
      target({
        id: 'gr05.t4',
        chunk: 'two days a week',
        cueVi: 'hai ngày một tuần',
        sourceSentence: 'Anh: Partly. I am going to a center two days a week.',
        productionPattern: '<two / three> days a week.',
        transferContext: 'describing gym frequency',
      }),
      target({
        id: 'gr05.t5',
        chunk: 'take a test',
        cueVi: 'thi một bài',
        sourceSentence: 'Tom: Are you going to take a test after?',
        productionPattern: 'take a <test / exam / class>.',
        transferContext: 'asking about certification',
      }),
      target({
        id: 'gr05.t6',
        chunk: 'the B1 exam',
        cueVi: 'kỳ thi B1',
        sourceSentence: 'Anh: Yes, I am going to try the B1 exam.',
        productionPattern: 'the <B1 / driving> exam.',
        transferContext: 'stating a certification goal',
      }),
    ],
    transferTask: {
      prompt: 'State three going-to plans for next month — study, health, social.',
      promptVi: 'Nêu ba kế hoạch going to cho tháng sau — học tập, sức khỏe, xã giao.',
      changesDimension: 'three life areas + no input text',
    },
    recyclingFrom: ['sv24'],
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr06',
    level: 'a1',
    track: 'grammar-support',
    capabilities: ['use-continuous'],
    title: 'Happening right now',
    titleVi: 'Đang diễn ra',
    task: 'Describe what people are doing now',
    context: 'Describing a busy café scene to a friend on the phone.',
    outcome: 'You can use -ing for actions in progress.',
    input: {
      title: 'GR06 · Café scene',
      text: [
        'Tom: What is happening there? It is loud.',
        'Anh: A band is setting up. People are taking photos.',
        'Tom: Are you studying or just watching?',
        'Anh: I am pretending to study, honestly.',
        'Tom: Is anyone dancing?',
        'Anh: Not yet. A waiter is handing out free coffee though.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'be + V-ing = đang diễn ra ngay lúc nói. "pretending to" = giả vờ.',
    },
    targets: [
      target({
        id: 'gr06.t1',
        chunk: 'What is happening',
        cueVi: 'chuyện gì đang xảy ra',
        sourceSentence: 'Tom: What is happening there? It is loud.',
        productionPattern: 'What is <happening / going on>?',
        transferContext: 'asking about noise in a call',
      }),
      target({
        id: 'gr06.t2',
        chunk: 'A band is setting up',
        cueVi: 'ban nhạc đang chuẩn bị',
        sourceSentence: 'Anh: A band is setting up. People are taking photos.',
        productionPattern: 'is <setting up / starting>.',
        transferContext: 'describing event prep',
      }),
      target({
        id: 'gr06.t3',
        chunk: 'taking photos',
        cueVi: 'đang chụp ảnh',
        sourceSentence: 'Anh: A band is setting up. People are taking photos.',
        productionPattern: 'taking <photos / videos>.',
        transferContext: 'describing a crowd at an event',
      }),
      target({
        id: 'gr06.t4',
        chunk: 'studying or just watching',
        cueVi: 'học hay chỉ ngồi xem',
        sourceSentence: 'Tom: Are you studying or just watching?',
        productionPattern: '<studying / working> or just <watching>?',
        transferContext: 'teasing a friend at a café',
      }),
      target({
        id: 'gr06.t5',
        chunk: 'pretending to study',
        cueVi: 'giả vờ học',
        sourceSentence: 'Anh: I am pretending to study, honestly.',
        productionPattern: 'pretending to <study / work / read>.',
        transferContext: 'admitting you are distracted',
      }),
      target({
        id: 'gr06.t6',
        chunk: 'Is anyone dancing',
        cueVi: 'có ai đang nhảy không',
        sourceSentence: 'Tom: Is anyone dancing?',
        productionPattern: 'Is anyone <dancing / singing / leaving>?',
        transferContext: 'asking about a party atmosphere',
      }),
      target({
        id: 'gr06.t7',
        chunk: 'handing out free coffee',
        cueVi: 'đang phát cà phê miễn phí',
        sourceSentence: 'Anh: Not yet. A waiter is handing out free coffee though.',
        productionPattern: 'handing out <free coffee / samples>.',
        transferContext: 'describing a promo at a mall',
      }),
    ],
    transferTask: {
      prompt: 'Describe a different live scene — a market — three things happening right now.',
      promptVi: 'Tả một cảnh trực tiếp khác — khu chợ — ba điều đang diễn ra.',
      changesDimension: 'market scene + three -ing observations',
    },
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr07',
    level: 'a1',
    track: 'grammar-support',
    capabilities: ['use-modals', 'request-help'],
    title: 'Can and could',
    titleVi: 'Can và could',
    task: 'Ask for things with can and could politely',
    context: 'Asking favors at work.',
    outcome: 'You can pick can vs could for politeness.',
    input: {
      title: 'GR07 · Asking',
      text: [
        'Anh: Can I use your charger?',
        'Tom: Sure, here.',
        'Anh: Could you show me how this app works?',
        'Tom: Of course. Could you hold this for a second?',
        'Anh: Sure. Can you send me the file later?',
        'Tom: No problem, I will send it tonight.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'can = bình thường; could = lịch sự hơn. Cả hai đều cho phép/nhờ vả nhẹ.',
    },
    targets: [
      target({
        id: 'gr07.t1',
        chunk: 'Can I use your charger',
        cueVi: 'cho tôi dùng sạc của bạn',
        sourceSentence: 'Anh: Can I use your charger?',
        productionPattern: 'Can I use your <charger / pen / wifi>?',
        transferContext: 'asking to borrow at a café',
      }),
      target({
        id: 'gr07.t2',
        chunk: 'Could you show me',
        cueVi: 'bạn chỉ tôi được không',
        sourceSentence: 'Anh: Could you show me how this app works?',
        productionPattern: 'Could you show me <how this works / the way>?',
        transferContext: 'asking a demo from a colleague',
      }),
      target({
        id: 'gr07.t3',
        chunk: 'how this app works',
        cueVi: 'app này dùng thế nào',
        sourceSentence: 'Anh: Could you show me how this app works?',
        productionPattern: 'how this <app / machine / form> works.',
        transferContext: 'learning a new tool',
      }),
      target({
        id: 'gr07.t4',
        chunk: 'hold this for a second',
        cueVi: 'giữ cái này một chút',
        sourceSentence: 'Tom: Of course. Could you hold this for a second?',
        productionPattern: 'hold this for <a second / a minute>.',
        transferContext: 'asking someone to hold your bag',
      }),
      target({
        id: 'gr07.t5',
        chunk: 'send me the file',
        cueVi: 'gửi file cho tôi',
        sourceSentence: 'Anh: Sure. Can you send me the file later?',
        productionPattern: 'send me the <file / link / photo>.',
        transferContext: 'asking for a document by chat',
      }),
      target({
        id: 'gr07.t6',
        chunk: 'I will send it tonight',
        cueVi: 'tôi sẽ gửi tối nay',
        sourceSentence: 'Tom: No problem, I will send it tonight.',
        productionPattern: 'I will send <it / you> tonight.',
        transferContext: 'promising a follow-up email',
      }),
    ],
    transferTask: {
      prompt: 'Ask three favors at a hotel — can (casual) and could (formal) mixed.',
      promptVi: 'Nhờ ba việc ở khách sạn — trộn can (thân mật) và could (trang trọng).',
      changesDimension: 'hotel setting + politeness-level choice',
    },
    recyclingFrom: ['sv08'],
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr08',
    level: 'a2',
    track: 'grammar-support',
    capabilities: ['use-modals'],
    title: 'Have to and should',
    titleVi: 'Have to và should',
    task: 'Distinguish must-do from good-idea',
    context: 'Discussing what is required vs recommended at work.',
    outcome: 'You can mark obligation vs advice.',
    input: {
      title: 'GR08 · Obligation',
      text: [
        'Tom: Do we have to wear badges here?',
        'Anh: Yes, we have to. Security checks them.',
        'Tom: Should I get one at the desk?',
        'Anh: You should — they will ask for ID anyway.',
        'Tom: Do I have to pay for parking too?',
        'Anh: You do not have to. It is free for guests.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'have to = bắt buộc; should = nên (khuyên). Phủ định: do not have to = không bắt buộc.',
    },
    targets: [
      target({
        id: 'gr08.t1',
        chunk: 'have to wear badges',
        cueVi: 'phải đeo thẻ',
        sourceSentence: 'Tom: Do we have to wear badges here?',
        productionPattern: 'have to <wear badges / sign in>.',
        transferContext: 'asking rules at a new office',
      }),
      target({
        id: 'gr08.t2',
        chunk: 'Security checks them',
        cueVi: 'bảo vệ kiểm tra',
        sourceSentence: 'Anh: Yes, we have to. Security checks them.',
        productionPattern: 'Security <checks / asks for> them.',
        transferContext: 'explaining a badge policy',
      }),
      target({
        id: 'gr08.t3',
        chunk: 'Should I get one',
        cueVi: 'tôi có nên lấy một cái không',
        sourceSentence: 'Tom: Should I get one at the desk?',
        productionPattern: 'Should I <get one / ask first>?',
        transferContext: 'asking what to do first',
      }),
      target({
        id: 'gr08.t4',
        chunk: 'You should',
        cueVi: 'bạn nên',
        sourceSentence: 'Anh: You should — they will ask for ID anyway.',
        productionPattern: 'You <should / should not>.',
        transferContext: 'advising a visitor',
      }),
      target({
        id: 'gr08.t5',
        chunk: 'ask for ID',
        cueVi: 'hỏi giấy tờ',
        sourceSentence: 'Anh: You should — they will ask for ID anyway.',
        productionPattern: 'ask for <ID / a ticket>.',
        transferContext: 'hearing an entry requirement',
      }),
      target({
        id: 'gr08.t6',
        chunk: 'pay for parking',
        cueVi: 'trả tiền đỗ xe',
        sourceSentence: 'Tom: Do I have to pay for parking too?',
        productionPattern: 'pay for <parking / tickets>.',
        transferContext: 'asking about costs at a venue',
      }),
      target({
        id: 'gr08.t7',
        chunk: 'free for guests',
        cueVi: 'miễn phí cho khách',
        sourceSentence: 'Anh: You do not have to. It is free for guests.',
        productionPattern: 'free for <guests / members>.',
        transferContext: 'explaining a perk',
      }),
    ],
    transferTask: {
      prompt: 'Explain rules at a gym — one have-to, one should, one do-not-have-to.',
      promptVi: 'Giải thích nội quy phòng gym — một have to, một should, một không bắt buộc.',
      changesDimension: 'gym rules + all three obligation levels',
    },
    recyclingFrom: ['gr07'],
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr09',
    level: 'a1',
    track: 'grammar-support',
    capabilities: ['use-articles'],
    title: 'A, an, the',
    titleVi: 'A, an, the',
    task: 'Choose a/an/the when talking about things',
    context: 'Describing objects in your room.',
    outcome: 'You can pick the right article for new vs known things.',
    input: {
      title: 'GR09 · Articles',
      text: [
        'Anh: I got a new lamp yesterday.',
        'Tom: Nice. Where did you put it?',
        'Anh: On the desk, next to an old photo.',
        'Tom: The photo of your family?',
        'Anh: Yes, the one from last summer.',
        'Tom: Does the lamp work well?',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'a/an = lần đầu nhắc; the = đã biết rõ cái nào. an trước nguyên âm.',
    },
    targets: [
      target({
        id: 'gr09.t1',
        chunk: 'a new lamp',
        cueVi: 'một cái đèn mới',
        sourceSentence: 'Anh: I got a new lamp yesterday.',
        productionPattern: 'a <new lamp / good deal>.',
        transferContext: 'mentioning a new purchase',
      }),
      target({
        id: 'gr09.t2',
        chunk: 'Where did you put it',
        cueVi: 'bạn để nó ở đâu',
        sourceSentence: 'Tom: Nice. Where did you put it?',
        productionPattern: 'Where did you <put / leave> it?',
        transferContext: 'asking about a shared item',
      }),
      target({
        id: 'gr09.t3',
        chunk: 'On the desk',
        cueVi: 'trên bàn',
        sourceSentence: 'Anh: On the desk, next to an old photo.',
        productionPattern: 'On the <desk / shelf / table>.',
        transferContext: 'describing where something sits',
      }),
      target({
        id: 'gr09.t4',
        chunk: 'an old photo',
        cueVi: 'một tấm ảnh cũ',
        sourceSentence: 'Anh: On the desk, next to an old photo.',
        productionPattern: 'an <old photo / old book>.',
        transferContext: 'describing a keepsake',
      }),
      target({
        id: 'gr09.t5',
        chunk: 'The photo of your family',
        cueVi: 'tấm ảnh gia đình bạn',
        sourceSentence: 'Tom: The photo of your family?',
        productionPattern: 'The <photo / one> of your <family>.',
        transferContext: 'confirming which item',
      }),
      target({
        id: 'gr09.t6',
        chunk: 'the one from last summer',
        cueVi: 'cái từ mùa hè năm ngoái',
        sourceSentence: 'Anh: Yes, the one from last summer.',
        productionPattern: 'the one from <last summer / the trip>.',
        transferContext: 'specifying which item you mean',
      }),
      target({
        id: 'gr09.t7',
        chunk: 'work well',
        cueVi: 'hoạt động tốt',
        sourceSentence: 'Tom: Does the lamp work well?',
        productionPattern: 'work <well / fine>.',
        transferContext: 'asking about a device',
      }),
    ],
    transferTask: {
      prompt: 'Describe three objects in a new room — first mention with a/an, second with the.',
      promptVi: 'Tả ba đồ vật trong phòng mới — lần đầu dùng a/an, lần sau dùng the.',
      changesDimension: 'new objects + article-shift discipline',
    },
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr10',
    level: 'a1',
    track: 'grammar-support',
    capabilities: ['use-prepositions'],
    title: 'In, on, at for time',
    titleVi: 'In, on, at cho thời gian',
    task: 'Use the right time preposition',
    context: 'Scheduling and remembering dates.',
    outcome: 'You can pick in/on/at for times and dates.',
    input: {
      title: 'GR10 · Time preps',
      text: [
        'Tom: When is your birthday?',
        'Anh: In July. Yours?',
        'Tom: On the fifth. What are you doing on the weekend?',
        'Anh: I am meeting friends at noon on Saturday.',
        'Tom: At noon? I am free at three.',
        'Anh: Okay, three it is — in the afternoon.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'in + tháng/năm/buổi; on + ngày/thứ; at + giờ cụ thể. at noon/night ngoại lệ.',
    },
    targets: [
      target({
        id: 'gr10.t1',
        chunk: 'In July',
        cueVi: 'vào tháng bảy',
        sourceSentence: 'Anh: In July. Yours?',
        productionPattern: 'In <July / May / the summer>.',
        transferContext: 'saying when a project ends',
      }),
      target({
        id: 'gr10.t2',
        chunk: 'On the fifth',
        cueVi: 'vào ngày mùng 5',
        sourceSentence: 'Tom: On the fifth. What are you doing on the weekend?',
        productionPattern: 'On <the fifth / Monday / my day off>.',
        transferContext: 'giving a date for a party',
      }),
      target({
        id: 'gr10.t3',
        chunk: 'on the weekend',
        cueVi: 'vào cuối tuần',
        sourceSentence: 'Tom: On the fifth. What are you doing on the weekend?',
        productionPattern: 'on <the weekend / Saturday>.',
        transferContext: 'asking about free time',
      }),
      target({
        id: 'gr10.t4',
        chunk: 'at noon',
        cueVi: 'lúc trưa',
        sourceSentence: 'Anh: I am meeting friends at noon on Saturday.',
        productionPattern: 'at <noon / night / three>.',
        transferContext: 'setting a lunch time',
      }),
      target({
        id: 'gr10.t5',
        chunk: 'on Saturday',
        cueVi: 'vào thứ bảy',
        sourceSentence: 'Anh: I am meeting friends at noon on Saturday.',
        productionPattern: 'on <Saturday / the tenth>.',
        transferContext: 'naming a meetup day',
      }),
      target({
        id: 'gr10.t6',
        chunk: 'at three',
        cueVi: 'lúc ba giờ',
        sourceSentence: 'Tom: At noon? I am free at three.',
        productionPattern: 'at <three / seven thirty>.',
        transferContext: 'proposing a different time',
      }),
      target({
        id: 'gr10.t7',
        chunk: 'in the afternoon',
        cueVi: 'vào buổi chiều',
        sourceSentence: 'Anh: Okay, three it is — in the afternoon.',
        productionPattern: 'in the <afternoon / morning / evening>.',
        transferContext: 'describing when a class runs',
      }),
    ],
    transferTask: {
      prompt: 'Plan a call — state the month, the day, and the exact hour with correct prepositions.',
      promptVi: 'Lên lịch cuộc gọi — nêu tháng, ngày, và giờ chính xác với giới từ đúng.',
      changesDimension: 'three granularities in one plan',
    },
    recyclingFrom: ['sv22', 'sv14'],
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr11',
    level: 'a1',
    track: 'grammar-support',
    capabilities: ['use-plurals'],
    title: 'Plurals',
    titleVi: 'Số nhiều',
    task: 'Form and hear plural endings',
    context: 'Counting things at a shop.',
    outcome: 'You can add -s/-es and spot irregular plurals.',
    input: {
      title: 'GR11 · Plurals',
      text: [
        'Anh: I need two boxes, three brushes, and some dishes.',
        'Clerk: We have boxes on aisle two.',
        "Anh: And do you have children's toothbrushes?",
        "Clerk: Yes, next to the men's section.",
        'Anh: I also need two knives for the kitchen.',
        'Clerk: The knives are on the top shelf.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Phần lớn +s; -es sau s/x/ch/sh; bất quy tắc: children, men, knives (f→ves).',
    },
    targets: [
      target({
        id: 'gr11.t1',
        chunk: 'two boxes',
        cueVi: 'hai cái hộp',
        sourceSentence: 'Anh: I need two boxes, three brushes, and some dishes.',
        productionPattern: 'two <boxes / brushes / dishes>.',
        transferContext: 'listing supplies to buy',
      }),
      target({
        id: 'gr11.t2',
        chunk: 'three brushes',
        cueVi: 'ba cái bàn chải',
        sourceSentence: 'Anh: I need two boxes, three brushes, and some dishes.',
        productionPattern: 'three <brushes / watches / buses>.',
        transferContext: 'counting cleaning supplies',
      }),
      target({
        id: 'gr11.t3',
        chunk: "children's toothbrushes",
        cueVi: 'bàn chải trẻ em',
        sourceSentence: "Anh: And do you have children's toothbrushes?",
        productionPattern: "children's <toothbrushes / clothes / books>.",
        transferContext: "asking for kids' items",
      }),
      target({
        id: 'gr11.t4',
        chunk: "the men's section",
        cueVi: 'khu đồ nam',
        sourceSentence: "Clerk: Yes, next to the men's section.",
        productionPattern: "the <men's / women's> section.",
        transferContext: 'navigating a department store',
      }),
      target({
        id: 'gr11.t5',
        chunk: 'two knives',
        cueVi: 'hai con dao',
        sourceSentence: 'Anh: I also need two knives for the kitchen.',
        productionPattern: 'two <knives / shelves / lives>.',
        transferContext: 'listing kitchen tools',
      }),
      target({
        id: 'gr11.t6',
        chunk: 'the top shelf',
        cueVi: 'kệ trên cùng',
        sourceSentence: 'Clerk: The knives are on the top shelf.',
        productionPattern: 'the <top / bottom> shelf.',
        transferContext: 'asking where items sit',
      }),
    ],
    transferTask: {
      prompt: 'List five items to buy for a kitchen — include two -es plurals and one irregular.',
      promptVi: 'Liệt kê năm món cần mua cho bếp — gồm hai số nhiều -es và một bất quy tắc.',
      changesDimension: 'new domain list + plural-form check',
    },
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
  spec({
    id: 'gr12',
    level: 'a2',
    track: 'grammar-support',
    capabilities: ['use-comparatives', 'compare-things'],
    title: 'Bigger and more',
    titleVi: 'Bigger và more',
    task: 'Compare things with -er and more',
    context: 'Comparing two jobs you could take.',
    outcome: 'You can use -er for short words, more for long.',
    input: {
      title: 'GR12 · Comparing',
      text: [
        'Anh: Job A pays better, but the hours are longer.',
        'Tom: Which one is closer?',
        'Anh: B is closer and more flexible.',
        'Tom: Is the work more interesting there?',
        'Anh: Slightly. But A is more stable.',
        'Tom: Tough call. Which matters more?',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Tính ngắn + -er (better, longer, closer); tính dài dùng more (more flexible).',
    },
    targets: [
      target({
        id: 'gr12.t1',
        chunk: 'pays better',
        cueVi: 'trả lương cao hơn',
        sourceSentence: 'Anh: Job A pays better, but the hours are longer.',
        productionPattern: 'pays <better / more / worse>.',
        transferContext: 'comparing two freelance gigs',
      }),
      target({
        id: 'gr12.t2',
        chunk: 'the hours are longer',
        cueVi: 'giờ làm dài hơn',
        sourceSentence: 'Anh: Job A pays better, but the hours are longer.',
        productionPattern: 'the <hours / days> are <longer / shorter>.',
        transferContext: 'comparing shift schedules',
      }),
      target({
        id: 'gr12.t3',
        chunk: 'Which one is closer',
        cueVi: 'cái nào gần hơn',
        sourceSentence: 'Tom: Which one is closer?',
        productionPattern: 'Which one is <closer / cheaper / better>?',
        transferContext: 'comparing two gyms',
      }),
      target({
        id: 'gr12.t4',
        chunk: 'more flexible',
        cueVi: 'linh hoạt hơn',
        sourceSentence: 'Anh: B is closer and more flexible.',
        productionPattern: 'more <flexible / interesting / difficult>.',
        transferContext: 'comparing class options',
      }),
      target({
        id: 'gr12.t5',
        chunk: 'more interesting',
        cueVi: 'thú vị hơn',
        sourceSentence: 'Tom: Is the work more interesting there?',
        productionPattern: 'more <interesting / boring / stressful>.',
        transferContext: 'asking about course content',
      }),
      target({
        id: 'gr12.t6',
        chunk: 'more stable',
        cueVi: 'ổn định hơn',
        sourceSentence: 'Anh: Slightly. But A is more stable.',
        productionPattern: 'more <stable / secure / risky>.',
        transferContext: 'comparing contract types',
      }),
      target({
        id: 'gr12.t7',
        chunk: 'Tough call',
        cueVi: 'khó quyết',
        sourceSentence: 'Tom: Tough call. Which matters more?',
        productionPattern: 'Tough <call / choice>.',
        transferContext: 'admitting a hard decision',
      }),
      target({
        id: 'gr12.t8',
        chunk: 'Which matters more',
        cueVi: 'cái nào quan trọng hơn',
        sourceSentence: 'Tom: Tough call. Which matters more?',
        productionPattern: 'Which <matters / costs> more?',
        transferContext: 'prioritizing criteria in a choice',
      }),
    ],
    transferTask: {
      prompt: 'Compare two cities to live in — cost, distance, lifestyle — with -er and more.',
      promptVi: 'So sánh hai thành phố để sống — giá, khoảng cách, lối sống — với -er và more.',
      changesDimension: 'city comparison + mixed comparative forms',
    },
    recyclingFrom: ['ev05', 'ch13'],
    sourceRefs: [...SRC.grammar],
    researchRefs: [...RES.grammar],
  }),
];
