/* Listening li01–li08 — perception microskills (boundary, weak forms, linking).
 * Scaffolds start with audio+transcript; targets carry heard-form notes. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { LADDER_LISTEN, RES, SRC, spec, target, VARIANTS_LISTEN } from './helpers.ts';

export const LISTENING_1: LessonSpec[] = [
  spec({
    id: 'li01',
    level: 'a1',
    track: 'listening',
    capabilities: ['decode-boundaries'],
    title: 'Where words end',
    titleVi: 'Ran giới từ',
    task: 'Hear where one word ends and the next begins',
    context: 'Fast English smears words together — train your ear on boundaries.',
    outcome: 'You can segment a stream into words.',
    input: {
      title: 'LI01 · Boundaries',
      text: [
        'Listen for where words split in fast speech.',
        'an apple / a napple — the sounds are the same.',
        'Practice: "I need it" sounds like "I nee dit".',
        'Boundary trick: hear the rhythm, not the gaps.',
        'Chunk: "a cup of tea" → "a cuppa tea".',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Tiếng Anh nói nhanh không có "khoảng trống" giữa từ — nghe theo nhịp, không chờ gap.',
    },
    targets: [
      target({
        id: 'li01.t1',
        chunk: 'an apple',
        cueVi: 'một quả táo',
        sourceSentence: 'an apple / a napple — the sounds are the same.',
        productionPattern: 'an <apple / egg / orange>.',
        transferContext: 'ordering fruit at a market',
        pronunciationNote: '"a-NAP-pəl" — n trôi sang vần sau',
      }),
      target({
        id: 'li01.t2',
        chunk: 'a cup of tea',
        cueVi: 'một tách trà',
        sourceSentence: 'Chunk: "a cup of tea" → "a cuppa tea".',
        productionPattern: 'a cup of <tea / coffee>.',
        transferContext: 'offering a drink at home',
        pronunciationNote: 'of → /ə/: "a CUP-ə tea"',
      }),
      target({
        id: 'li01.t3',
        chunk: 'I need it',
        cueVi: 'tôi cần nó',
        sourceSentence: 'Practice: "I need it" sounds like "I nee dit".',
        productionPattern: 'I <need / want> it.',
        transferContext: 'asking for a tool at work',
        pronunciationNote: '"I NEE-dit" — d nối vào it',
      }),
      target({
        id: 'li01.t4',
        chunk: 'the rhythm',
        cueVi: 'nhịp điệu',
        sourceSentence: 'Boundary trick: hear the rhythm, not the gaps.',
        productionPattern: 'the <rhythm / stress pattern>.',
        transferContext: 'describing music vs speech flow',
        pronunciationNote: 'RHY-thm — nhấn âm đầu',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Transcribe 3 phrases a friend says fast at home — mark where the words actually split.',
      promptVi: 'Chép 3 cụm bạn bè nói nhanh — đánh dấu ran giới từ thật.',
      changesDimension: 'new phrases + write boundaries yourself',
    },
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li02',
    level: 'a1',
    track: 'listening',
    capabilities: ['decode-weak-forms'],
    title: 'Little words shrink',
    titleVi: 'Từ nhỏ bị co lại',
    task: 'Catch the weak forms of to/of/a/the',
    context: 'Function words almost disappear in fluent speech.',
    outcome: 'You can hear "to" as /tə/ and "of" as /əv~ə/.',
    input: {
      title: 'LI02 · Weak forms',
      text: [
        'Function words shrink when unstressed.',
        '"to the store" → "tə thə store".',
        '"a glass of water" → "ə glass ə water".',
        '"going to" often becomes "gonna".',
        'Hear the weak forms, then guess the full word.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'to/of/a/the/a → schwa /ə/ khi không nhấn; gonna/wanna là dạng rút gọn phổ biến.',
    },
    targets: [
      target({
        id: 'li02.t1',
        chunk: 'to the store',
        cueVi: 'đến cửa hàng',
        sourceSentence: '"to the store" → "tə thə store".',
        productionPattern: 'to the <store / bank / office>.',
        transferContext: 'giving quick directions',
        pronunciationNote: 'to→/tə/, the→/thə/',
      }),
      target({
        id: 'li02.t2',
        chunk: 'a glass of water',
        cueVi: 'một ly nước',
        sourceSentence: '"a glass of water" → "ə glass ə water".',
        productionPattern: 'a glass of <water / juice>.',
        transferContext: 'asking for a drink politely',
        pronunciationNote: 'a→/ə/, of→/ə/: "ə GLASS ə WAD-ər"',
      }),
      target({
        id: 'li02.t3',
        chunk: 'going to',
        cueVi: 'sắp/định',
        sourceSentence: '"going to" often becomes "gonna".',
        productionPattern: 'going to <leave / go>.',
        transferContext: 'hearing casual future plans',
        pronunciationNote: '"GON-na"',
      }),
      target({
        id: 'li02.t4',
        chunk: 'the full word',
        cueVi: 'từ đầy đủ',
        sourceSentence: 'Hear the weak forms, then guess the full word.',
        productionPattern: 'the <full / weak> form.',
        transferContext: 'comparing dictionary vs spoken forms',
        pronunciationNote: 'unstressed "the" = /thə/',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Catch weak forms in a song line or podcast clip — write the "full" sentence.',
      promptVi: 'Bắt weak forms trong một câu nhạc/podcast — viết lại câu đầy đủ.',
      changesDimension: 'real audio source + restore full forms',
    },
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li03',
    level: 'a2',
    track: 'listening',
    capabilities: ['decode-linking'],
    title: 'Sounds link together',
    titleVi: 'Nối âm',
    task: 'Hear consonant-vowel linking across words',
    context: 'Final consonants jump onto the next vowel.',
    outcome: 'You can decode "an egg" vs "a nag" style linking.',
    input: {
      title: 'LI03 · Linking',
      text: [
        'Final consonants flow into the next vowel.',
        '"turn it off" → "tur-ni-toff".',
        '"check it out" → "che-ki-tout".',
        '"not at all" → "no-ta-tall".',
        'Linking makes phrases sound like one long word.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Phụ âm cuối nối vào nguyên âm đầu từ sau — "not at all" nghe như một từ dài.',
    },
    targets: [
      target({
        id: 'li03.t1',
        chunk: 'turn it off',
        cueVi: 'tắt nó đi',
        sourceSentence: '"turn it off" → "tur-ni-toff".',
        productionPattern: 'turn <it / them> off.',
        transferContext: 'telling someone to shut a device',
        pronunciationNote: '"tur-NI-toff"',
      }),
      target({
        id: 'li03.t2',
        chunk: 'check it out',
        cueVi: 'xem thử đi',
        sourceSentence: '"check it out" → "che-ki-tout".',
        productionPattern: 'check <it / this> out.',
        transferContext: 'showing a friend a video',
        pronunciationNote: '"CHE-ki-tout"',
      }),
      target({
        id: 'li03.t3',
        chunk: 'not at all',
        cueVi: 'không sao / hoàn toàn không',
        sourceSentence: '"not at all" → "no-ta-tall".',
        productionPattern: 'not at <all>.',
        transferContext: 'replying to an apology',
        pronunciationNote: '"no-ta-TALL"',
      }),
      target({
        id: 'li03.t4',
        chunk: 'one long word',
        cueVi: 'một từ dài',
        sourceSentence: 'Linking makes phrases sound like one long word.',
        productionPattern: 'one <long word / smooth stream>.',
        transferContext: 'describing how natives chain speech',
        pronunciationNote: 'linking keeps rhythm flowing',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Find 2 linked phrases in a movie line — write them as they sound (tur-ni-toff style).',
      promptVi: 'Tìm 2 cụm nối âm trong một câu phim — viết theo âm nghe được.',
      changesDimension: 'film audio + you write the linked form',
    },
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li04',
    level: 'a2',
    track: 'listening',
    capabilities: ['decode-reductions'],
    title: 'Gonna, wanna, gotta',
    titleVi: 'Gonna, wanna, gotta',
    task: 'Recognize the three big reductions in casual speech',
    context: 'Fast informal English compresses verb phrases.',
    outcome: 'You can map gonna→going to, wanna→want to, gotta→got to.',
    input: {
      title: 'LI04 · Reductions',
      text: [
        'Casual speech reduces common verb phrases.',
        '"I am gonna go" = I am going to go.',
        '"Do you wanna come?" = Do you want to come?',
        '"I gotta run" = I have got to run (I must go).',
        'Hear the reduction, expand it in your head.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'gonna = going to; wanna = want to; gotta = (have) got to. Nghe hiểu, không bắt buộc nói.',
    },
    targets: [
      target({
        id: 'li04.t1',
        chunk: 'gonna go',
        cueVi: 'sắp đi',
        sourceSentence: '"I am gonna go" = I am going to go.',
        productionPattern: 'gonna <go / try / call>.',
        transferContext: 'hearing weekend plans',
        pronunciationNote: '"GON-na"',
      }),
      target({
        id: 'li04.t2',
        chunk: 'wanna come',
        cueVi: 'muốn đi không',
        sourceSentence: '"Do you wanna come?" = Do you want to come?',
        productionPattern: 'wanna <come / eat / watch>?',
        transferContext: 'hearing a casual invite',
        pronunciationNote: '"WON-na"',
      }),
      target({
        id: 'li04.t3',
        chunk: 'gotta run',
        cueVi: 'phải chạy/đi rồi',
        sourceSentence: '"I gotta run" = I have got to run (I must go).',
        productionPattern: 'gotta <run / go / leave>.',
        transferContext: 'hearing someone excuse themselves',
        pronunciationNote: '"GOD-uh"',
      }),
      target({
        id: 'li04.t4',
        chunk: 'the reduction',
        cueVi: 'dạng rút gọn',
        sourceSentence: 'Hear the reduction, expand it in your head.',
        productionPattern: 'the <reduction / full form>.',
        transferContext: 'translating casual speech in your head',
        pronunciationNote: 'expand back to full form mentally',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: "Hear a friend's casual message — expand 3 reductions into full forms on paper.",
      promptVi: 'Nghe tin nhắn thoại — viết lại 3 dạng rút gọn thành dạng đầy đủ.',
      changesDimension: 'real message + expand not just recognize',
    },
    recyclingFrom: ['li02'],
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li05',
    level: 'a2',
    track: 'listening',
    capabilities: ['decode-final-consonants'],
    title: 'Final consonants disappear',
    titleVi: 'Phụ âm đuôi biến mất',
    task: 'Detect when word-final t/d/s are dropped',
    context: 'Vietnamese ears often miss endings — and so do natives when they drop them.',
    outcome: 'You can hear which finals survive and which vanish.',
    input: {
      title: 'LI05 · Dropped finals',
      text: [
        'English also drops endings in fast speech.',
        '"last night" → "las night" (t often gone).',
        '"next day" → "nex day".',
        '"most people" → "mos people".',
        'But grammar still marks time — hear the context, not just the letter.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 't/d cuối trước phụ âm thường rơi — phải đoán qua ngữ cảnh; đây là lý do nghe khó cho người Việt.',
    },
    targets: [
      target({
        id: 'li05.t1',
        chunk: 'last night',
        cueVi: 'tối qua',
        sourceSentence: '"last night" → "las night" (t often gone).',
        productionPattern: 'last <night / week / year>.',
        transferContext: 'talking about last evening',
        pronunciationNote: '"las-NIGHT" — t rơi',
      }),
      target({
        id: 'li05.t2',
        chunk: 'next day',
        cueVi: 'hôm sau',
        sourceSentence: '"next day" → "nex day".',
        productionPattern: 'next <day / week / time>.',
        transferContext: 'scheduling a follow-up',
        pronunciationNote: '"nex-DAY" — t rơi',
      }),
      target({
        id: 'li05.t3',
        chunk: 'most people',
        cueVi: 'đa số người',
        sourceSentence: '"most people" → "mos people".',
        productionPattern: 'most <people / students>.',
        transferContext: 'citing a general fact',
        pronunciationNote: '"mos-PEE-pul" — t rơi',
      }),
      target({
        id: 'li05.t4',
        chunk: 'the context',
        cueVi: 'ngữ cảnh',
        sourceSentence: 'But grammar still marks time — hear the context, not just the letter.',
        productionPattern: 'the <context / surrounding words>.',
        transferContext: 'guessing meaning from surrounding words',
        pronunciationNote: 'stress on CON-text',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Dictate a fast news clip — mark every dropped final you caught and what context told you.',
      promptVi: 'Chính tả một đoạn tin nhanh — đánh dấu phụ âm đuôi bị rơi và ngữ cảnh báo gì.',
      changesDimension: 'real broadcast + context-inference report',
    },
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li06',
    level: 'a2',
    track: 'listening',
    capabilities: ['decode-numbers'],
    title: 'Numbers at speed',
    titleVi: 'Bắt số nhanh',
    task: 'Catch prices, times, and phone digits in real speech',
    context: 'Numbers blur together — especially teen/ty pairs.',
    outcome: 'You can distinguish thirteen/thirty by stress.',
    input: {
      title: 'LI06 · Fast numbers',
      text: [
        'Thirteen vs thirty — hear the stress.',
        'The word thirteen is thir-TEEN — stress on teen.',
        'The word thirty is THIR-ty — stress on the first syllable.',
        'Price: "fifteen fifty" could be 15.50 or 50/15.',
        'Phone numbers read digit by digit or in pairs.',
        'Practice: 0905 213 876 → oh-nine-oh-five, two-one-three, eight-seven-six.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Teen nhấn âm sau, ty nhấn âm đầu — quy luật stress quyết định bạn nghe đúng số.',
    },
    targets: [
      target({
        id: 'li06.t1',
        chunk: 'thirteen',
        cueVi: 'mười ba',
        sourceSentence: 'The word thirteen is thir-TEEN — stress on teen.',
        productionPattern: '<thirteen / fourteen / fifteen>.',
        transferContext: 'hearing a room number at a hotel',
        pronunciationNote: 'thir-TEEN — nhấn âm sau',
      }),
      target({
        id: 'li06.t2',
        chunk: 'thirty',
        cueVi: 'ba mươi',
        sourceSentence: 'The word thirty is THIR-ty — stress on the first syllable.',
        productionPattern: '<thirty / forty / fifty>.',
        transferContext: 'hearing a price at a counter',
        pronunciationNote: 'THIR-ty — nhấn âm đầu',
      }),
      target({
        id: 'li06.t3',
        chunk: 'fifteen fifty',
        cueVi: '15.50 (giá)',
        sourceSentence: 'Price: "fifteen fifty" could be 15.50 or 50/15.',
        productionPattern: '<fifteen fifty / twelve thirty>.',
        transferContext: 'hearing a total at a café',
        pronunciationNote: 'ambiguous — ask if unsure',
      }),
      target({
        id: 'li06.t4',
        chunk: 'digit by digit',
        cueVi: 'từng chữ số',
        sourceSentence: 'Phone numbers read digit by digit or in pairs.',
        productionPattern: 'digit by <digit / pair>.',
        transferContext: 'dictating your number slowly',
        pronunciationNote: 'digits get equal stress',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Write down 5 numbers someone dictates — check teen/ty stress on each.',
      promptVi: 'Viết 5 số được đọc — kiểm stress teen/ty từng số.',
      changesDimension: 'dictation task + rule application',
    },
    recyclingFrom: ['sv05'],
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li07',
    level: 'a2',
    track: 'listening',
    capabilities: ['decode-names'],
    title: 'Names and spelled letters',
    titleVi: 'Tên và đánh vần',
    task: 'Catch names and spelled-out letters at speed',
    context: 'Booking desks spell names fast — catch every letter.',
    outcome: 'You can follow letter-by-letter spelling.',
    input: {
      title: 'LI07 · Spelling catch',
      text: [
        'English letters blur: B or D, M or N, G or J, E or I.',
        'Clarify with "as in": "G as in green".',
        'Names: Smith → S-M-I-T-H.',
        'Slow letters get equal stress; fast ones blur.',
        'Practice: N-G-U-Y-E-N — say each letter clearly.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Cặp chữ dễ nhầm: B/D, M/N, G/J — dùng "X as in word" để tách khi cần.',
    },
    targets: [
      target({
        id: 'li07.t1',
        chunk: 'B or D',
        cueVi: 'B hay D',
        sourceSentence: 'English letters blur: B or D, M or N, G or J, E or I.',
        productionPattern: '<B or D / M or N / G or J>.',
        transferContext: 'clarifying a letter over the phone',
        pronunciationNote: '"BEE or DEE"',
      }),
      target({
        id: 'li07.t2',
        chunk: 'G as in green',
        cueVi: 'chữ G như green',
        sourceSentence: 'Clarify with "as in": "G as in green".',
        productionPattern: '<letter> as in <word>.',
        transferContext: 'spelling your name for a form',
        pronunciationNote: 'steady letter-by-letter pace',
      }),
      target({
        id: 'li07.t3',
        chunk: 'S-M-I-T-H',
        cueVi: 'đánh vần Smith',
        sourceSentence: 'Names: Smith → S-M-I-T-H.',
        productionPattern: '<S-M-I-T-H / your name>.',
        transferContext: 'confirming a booking name',
        pronunciationNote: 'each letter equal stress',
      }),
      target({
        id: 'li07.t4',
        chunk: 'each letter clearly',
        cueVi: 'từng chữ rõ ràng',
        sourceSentence: 'Practice: N-G-U-Y-E-N — say each letter clearly.',
        productionPattern: 'each <letter / digit> clearly.',
        transferContext: 'reading a code slowly',
        pronunciationNote: 'slow, even spacing',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Transcribe a fast-spelled name in a podcast or video — write the letters you heard.',
      promptVi: 'Chép tên được đánh vần nhanh trong podcast/video — ghi lại các chữ nghe được.',
      changesDimension: 'real speed + transcription output',
    },
    recyclingFrom: ['sv20'],
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li08',
    level: 'a2',
    track: 'listening',
    capabilities: ['track-signposts'],
    title: 'Follow the signposts',
    titleVi: 'Theo dấu hiệu chuyển ý',
    task: 'Track discourse markers that tell you what comes next',
    context: 'Long answers get easier when you hear the signals.',
    outcome: 'You can predict structure from signpost words.',
    input: {
      title: 'LI08 · Signposts',
      text: [
        'Signposts tell you what kind of info comes next.',
        '"First" = a list is starting.',
        '"But" = a contrast is coming.',
        '"So" = a result or summary.',
        '"Anyway" = back to the main point.',
        'Hear the signal, predict the move.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'But = ngược lại; So = kết quả; Anyway = quay về ý chính; nghe trước để đoán sau.',
    },
    targets: [
      target({
        id: 'li08.t1',
        chunk: 'First',
        cueVi: 'đầu tiên (bắt đầu liệt kê)',
        sourceSentence: '"First" = a list is starting.',
        productionPattern: 'First, <point one>.',
        transferContext: 'hearing the start of instructions',
        pronunciationNote: 'FIRST — nhấn mạnh',
      }),
      target({
        id: 'li08.t2',
        chunk: 'But',
        cueVi: 'nhưng (báo ngược ý)',
        sourceSentence: '"But" = a contrast is coming.',
        productionPattern: 'But, <opposite point>.',
        transferContext: 'hearing a critique after praise',
        pronunciationNote: 'BUT — pause after it',
      }),
      target({
        id: 'li08.t3',
        chunk: 'So',
        cueVi: 'vậy thì (kết quả)',
        sourceSentence: '"So" = a result or summary.',
        productionPattern: 'So, <conclusion>.',
        transferContext: 'hearing the point of a long story',
        pronunciationNote: 'SO — often lengthened',
      }),
      target({
        id: 'li08.t4',
        chunk: 'Anyway',
        cueVi: 'dù sao thì (về ý chính)',
        sourceSentence: '"Anyway" = back to the main point.',
        productionPattern: 'Anyway, <main point>.',
        transferContext: 'returning to topic after a tangent',
        pronunciationNote: 'AN-y-way',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Listen to a short talk — write the signposts and predict what each one introduced.',
      promptVi: 'Nghe một bài nói ngắn — ghi signposts và đoán mỗi cái dẫn gì.',
      changesDimension: 'extended audio + prediction task',
    },
    recyclingFrom: ['ch09'],
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
];
