/* Listening li09–li16 — extraction skills: gist, detail, tone, fast questions. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { LADDER_LISTEN, RES, SRC, spec, target, VARIANTS_LISTEN } from './helpers.ts';

export const LISTENING_2: LessonSpec[] = [
  spec({
    id: 'li09',
    level: 'a2',
    track: 'listening',
    capabilities: ['catch-gist'],
    title: 'Get the gist',
    titleVi: 'Nắm ý chính',
    task: 'Catch the main idea without every word',
    context: 'Announcements give key info buried in noise.',
    outcome: 'You can pull the one thing that matters.',
    input: {
      title: 'LI09 · Gist',
      text: [
        'Announcement: "Attention passengers on the 9:15 service to Da Nang."',
        '"Due to track work, this service will depart from platform three."',
        '"Please check the boards for your connecting services."',
        'Gist question: what do YOU need to do?',
        'Answer: go to platform three. The rest is context.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Nghe thông báo: tìm ACTION cần làm (go to platform 3), bỏ qua lý do và chi tiết phụ.',
    },
    targets: [
      target({
        id: 'li09.t1',
        chunk: 'Attention passengers',
        cueVi: 'xin chú ý hành khách',
        sourceSentence: 'Announcement: "Attention passengers on the 9:15 service to Da Nang."',
        productionPattern: 'Attention <passengers / customers>.',
        transferContext: 'hearing a store announcement',
        pronunciationNote: 'at-TEN-tion — nhấn âm giữa',
      }),
      target({
        id: 'li09.t2',
        chunk: 'the 9:15 service',
        cueVi: 'chuyến 9 giờ 15',
        sourceSentence: 'Announcement: "Attention passengers on the 9:15 service to Da Nang."',
        productionPattern: 'the <9:15 / next> service to <Da Nang>.',
        transferContext: 'hearing a bus departure call',
        pronunciationNote: '"the nine-fifteen SER-vis"',
      }),
      target({
        id: 'li09.t3',
        chunk: 'Due to track work',
        cueVi: 'do sửa đường ray',
        sourceSentence: '"Due to track work, this service will depart from platform three."',
        productionPattern: 'Due to <track work / weather>.',
        transferContext: 'hearing a delay explanation',
        pronunciationNote: 'DUE-to — reason marker',
      }),
      target({
        id: 'li09.t4',
        chunk: 'depart from platform three',
        cueVi: 'khởi hành từ sân ba',
        sourceSentence: '"Due to track work, this service will depart from platform three."',
        productionPattern: 'depart from <platform three / gate five>.',
        transferContext: 'hearing gate info at a bus terminal',
        pronunciationNote: 'plat-FORM three',
      }),
      target({
        id: 'li09.t5',
        chunk: 'check the boards',
        cueVi: 'xem bảng thông tin',
        sourceSentence: '"Please check the boards for your connecting services."',
        productionPattern: 'check the <boards / screens>.',
        transferContext: 'hearing advice at an airport',
        pronunciationNote: 'CHECK the boards — action',
      }),
      target({
        id: 'li09.t6',
        chunk: 'your connecting services',
        cueVi: 'chuyến nối tiếp của bạn',
        sourceSentence: '"Please check the boards for your connecting services."',
        productionPattern: 'your <connecting / onward> services.',
        transferContext: 'following a transfer instruction',
        pronunciationNote: 'con-NECT-ing',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Hear a different announcement — gate change at an airport — write the ONE action you must take.',
      promptVi: 'Nghe thông báo khác — đổi cổng ở sân bay — viết HÀNH ĐỘNG duy nhất phải làm.',
      changesDimension: 'airport not rail + extract action only',
    },
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li10',
    level: 'a2',
    track: 'listening',
    capabilities: ['extract-detail'],
    title: 'Pick out the details',
    titleVi: 'Bắt chi tiết',
    task: 'Extract specific facts from a short monologue',
    context: 'A voicemail gives a time, a place, and a name.',
    outcome: 'You can note the three key details.',
    input: {
      title: 'LI10 · Voicemail',
      text: [
        'Voicemail: "Hi Anh, this is Dr. Tran\'s office calling."',
        '"We are moving your appointment to Friday, May ninth, at two thirty."',
        '"Please ask for Nurse Kelly when you arrive at the fourth floor."',
        'Details to catch: who? when? where? who to ask for?',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Chi tiết: who called → new time → where → who to find. Nghe voicemail là bắt 4W.',
    },
    targets: [
      target({
        id: 'li10.t1',
        chunk: "this is Dr. Tran's office",
        cueVi: 'đây là phòng khám bác Trần',
        sourceSentence: 'Voicemail: "Hi Anh, this is Dr. Tran\'s office calling."',
        productionPattern: "this is <Dr. Tran's / the> office calling.",
        transferContext: 'identifying a caller on voicemail',
        pronunciationNote: '"this-is doc-tor TRAN\'s office"',
      }),
      target({
        id: 'li10.t2',
        chunk: 'moving your appointment',
        cueVi: 'dời lịch hẹn của bạn',
        sourceSentence: '"We are moving your appointment to Friday, May ninth, at two thirty."',
        productionPattern: 'moving your <appointment / booking> to <Friday>.',
        transferContext: 'hearing a rescheduled delivery',
        pronunciationNote: 'MOV-ing your ap-POINT-ment',
      }),
      target({
        id: 'li10.t3',
        chunk: 'Friday, May ninth',
        cueVi: 'thứ sáu, ngày 9/5',
        sourceSentence: '"We are moving your appointment to Friday, May ninth, at two thirty."',
        productionPattern: '<Friday, May ninth>.',
        transferContext: 'noting a date from a message',
        pronunciationNote: 'FRI-day May NINTH',
      }),
      target({
        id: 'li10.t4',
        chunk: 'at two thirty',
        cueVi: 'lúc hai giờ ba mươi',
        sourceSentence: '"We are moving your appointment to Friday, May ninth, at two thirty."',
        productionPattern: 'at <two thirty / three>.',
        transferContext: 'confirming a time from a message',
        pronunciationNote: 'at two-THIR-ty',
      }),
      target({
        id: 'li10.t5',
        chunk: 'ask for Nurse Kelly',
        cueVi: 'hỏi y tá Kelly',
        sourceSentence: '"Please ask for Nurse Kelly when you arrive at the fourth floor."',
        productionPattern: 'ask for <Nurse Kelly / the manager>.',
        transferContext: 'knowing who to find at a desk',
        pronunciationNote: 'ASK-for NURSE KEL-ly',
      }),
      target({
        id: 'li10.t6',
        chunk: 'the fourth floor',
        cueVi: 'tầng bốn',
        sourceSentence: '"Please ask for Nurse Kelly when you arrive at the fourth floor."',
        productionPattern: 'the <fourth / third> floor.',
        transferContext: 'navigating to an office',
        pronunciationNote: 'fourth FLOOR',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Extract 4 details from a different message — package delivery: who, when, where, what to bring.',
      promptVi: 'Bắt 4 chi tiết từ tin nhắn khác — giao hàng: ai, khi nào, ở đâu, mang gì.',
      changesDimension: 'delivery not clinic + same 4W extraction',
    },
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li11',
    level: 'a2',
    track: 'listening',
    capabilities: ['hear-fast-questions'],
    title: 'Questions at full speed',
    titleVi: 'Câu hỏi tốc độ thật',
    task: 'Decode fast spoken questions',
    context: 'Natives compress questions into two syllables.',
    outcome: 'You can map "dya wanna" → "do you want to".',
    input: {
      title: 'LI11 · Fast questions',
      text: [
        '"Whaddya doin?" = What are you doing?',
        '"Dya wanna go?" = Do you want to go?',
        '"Havya eaten?" = Have you eaten?',
        '"Wherya goin?" = Where are you going?',
        'Fast questions shrink the helper verbs.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'What are you → whaddya; do you → dya; have you → havya. Nghe tổng âm, đừng tìm từng từ.',
    },
    targets: [
      target({
        id: 'li11.t1',
        chunk: 'What are you doing',
        cueVi: 'bạn đang làm gì',
        sourceSentence: '"Whaddya doin?" = What are you doing?',
        productionPattern: 'What are you <doing / saying>?',
        transferContext: 'hearing a casual check-in',
        pronunciationNote: '"whaddya DO-in"',
      }),
      target({
        id: 'li11.t2',
        chunk: 'Do you want to go',
        cueVi: 'bạn có muốn đi không',
        sourceSentence: '"Dya wanna go?" = Do you want to go?',
        productionPattern: 'Do you want to <go / eat>?',
        transferContext: 'hearing a fast invite',
        pronunciationNote: '"dya-WON-na go"',
      }),
      target({
        id: 'li11.t3',
        chunk: 'Have you eaten',
        cueVi: 'bạn ăn chưa',
        sourceSentence: '"Havya eaten?" = Have you eaten?',
        productionPattern: 'Have you <eaten / seen / heard>?',
        transferContext: 'hearing a host check on you',
        pronunciationNote: '"HAV-ya eat-n"',
      }),
      target({
        id: 'li11.t4',
        chunk: 'Where are you going',
        cueVi: 'bạn đang đi đâu',
        sourceSentence: '"Wherya goin?" = Where are you going?',
        productionPattern: 'Where are you <going / staying>?',
        transferContext: 'hearing someone ask your destination',
        pronunciationNote: '"wher-ya GO-in"',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Expand 3 fast questions a friend says into their full forms on paper.',
      promptVi: 'Viết lại 3 câu hỏi nhanh của bạn bè thành dạng đầy đủ.',
      changesDimension: 'spoken input + expansion output',
    },
    recyclingFrom: ['li04'],
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li12',
    level: 'a2',
    track: 'listening',
    capabilities: ['infer-tone'],
    title: 'Hear the tone',
    titleVi: 'Nghe thái độ',
    task: 'Detect politeness vs annoyance from sound alone',
    context: 'Same words, different feelings — tone tells the real message.',
    outcome: "You can guess the speaker's attitude.",
    input: {
      title: 'LI12 · Tone',
      text: [
        '"That is fine" flat = annoyed; warm rise = genuine.',
        '"Whatever" falling = dismissive.',
        '"Really?" rising = surprise; falling = doubt.',
        'Tone carries the feeling; words carry the content.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Cùng câu nói, ngữ điệu khác = ý khác. Nghe tone trước, nghĩ ý sau.',
    },
    targets: [
      target({
        id: 'li12.t1',
        chunk: 'That is fine',
        cueVi: 'không sao (thật sự)',
        sourceSentence: '"That is fine" flat = annoyed; warm rise = genuine.',
        productionPattern: 'That is <fine / okay>.',
        transferContext: 'judging if a friend is really okay',
        pronunciationNote: 'flat = annoyed; warm = genuine',
      }),
      target({
        id: 'li12.t2',
        chunk: 'Whatever',
        cueVi: 'kệ đi / sao cũng được',
        sourceSentence: '"Whatever" falling = dismissive.',
        productionPattern: '<Whatever / Suit yourself>.',
        transferContext: 'hearing someone give up arguing',
        pronunciationNote: 'falling = dismissive',
      }),
      target({
        id: 'li12.t3',
        chunk: 'Really',
        cueVi: 'thật không (ngạc nhiên/nghi ngờ)',
        sourceSentence: '"Really?" rising = surprise; falling = doubt.',
        productionPattern: '<Really / Seriously>?',
        transferContext: 'expressing surprise at news',
        pronunciationNote: 'rising = surprise, falling = doubt',
      }),
      target({
        id: 'li12.t4',
        chunk: 'the feeling',
        cueVi: 'cảm xúc',
        sourceSentence: 'Tone carries the feeling; words carry the content.',
        productionPattern: 'the <feeling / attitude / mood>.',
        transferContext: 'reading mood from a short reply',
        pronunciationNote: 'FEEL-ing',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Guess the attitude in 3 replies from a show — mark each as warm/flat/dismissive.',
      promptVi: 'Đoán thái độ trong 3 câu trả lời từ phim — đánh dấu warm/flat/dismissive.',
      changesDimension: 'media audio + attitude labels',
    },
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li13',
    level: 'a1',
    track: 'listening',
    capabilities: ['decode-boundaries'],
    title: 'Sentences in chunks',
    titleVi: 'Câu theo cụm nghĩa',
    task: 'Hear speech as thought-groups, not word-by-word',
    context: 'Fluent speakers pause between meaning-groups.',
    outcome: 'You can segment by sense units.',
    input: {
      title: 'LI13 · Thought groups',
      text: [
        'Fluent speech comes in chunks, not words.',
        '"After work today / I am going to the gym / with my friend Sara."',
        'The pauses mark the meaning-groups.',
        'Hear the chunk, get the chunk of meaning.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-microskills',
      noteVi: 'Chia câu theo cụm nghĩa — pause nằm giữa các cụm, nghe trọn cụm để hiểu nhanh.',
    },
    targets: [
      target({
        id: 'li13.t1',
        chunk: 'After work today',
        cueVi: 'chiều nay sau giờ làm',
        sourceSentence: '"After work today / I am going to the gym / with my friend Sara."',
        productionPattern: 'After <work / class> today.',
        transferContext: 'hearing plans for later',
        pronunciationNote: 'pause after "today"',
      }),
      target({
        id: 'li13.t2',
        chunk: 'I am going to the gym',
        cueVi: 'tôi định đi gym',
        sourceSentence: '"After work today / I am going to the gym / with my friend Sara."',
        productionPattern: 'I am going to the <gym / store>.',
        transferContext: 'hearing a destination',
        pronunciationNote: '"I\'m-gonna-the-GYM"',
      }),
      target({
        id: 'li13.t3',
        chunk: 'with my friend Sara',
        cueVi: 'với bạn Sara',
        sourceSentence: '"After work today / I am going to the gym / with my friend Sara."',
        productionPattern: 'with my <friend / sister> Sara.',
        transferContext: 'hearing who they are with',
        pronunciationNote: 'with my FRIEND SA-ra',
      }),
      target({
        id: 'li13.t4',
        chunk: 'the meaning-groups',
        cueVi: 'các cụm nghĩa',
        sourceSentence: 'The pauses mark the meaning-groups.',
        productionPattern: 'the <meaning-groups / sense units>.',
        transferContext: 'explaining prosody to a classmate',
        pronunciationNote: 'MEAN-ing groups',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Mark the thought-groups in a sentence someone says — draw slashes where the pauses fall.',
      promptVi: 'Đánh dấu cụm nghĩa trong câu ai đó nói — gạch chéo chỗ pause.',
      changesDimension: 'different sentence + you mark the chunks',
    },
    recyclingFrom: ['li01'],
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li14',
    level: 'a2',
    track: 'listening',
    capabilities: ['decode-clusters'],
    title: 'Consonant clusters',
    titleVi: 'Cụm phụ âm',
    task: 'Hear words with two or three consonants in a row',
    context: 'Vietnamese syllables rarely cluster — English piles them up.',
    outcome: 'You can catch str/spr/st/sk endings and starts.',
    input: {
      title: 'LI14 · Clusters',
      text: [
        'English stacks consonants Vietnamese rarely does.',
        '"street" = s-t-r-eet (three consonants).',
        '"texts" = teks-ts (final cluster).',
        '"asked" = ask-t (two finals).',
        'Slow the cluster down in your head, then speed it up.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Người Việt hay thêm nguyên âm vào cụm ("sə-treet") — nghe cụm như một khối, không tách.',
    },
    targets: [
      target({
        id: 'li14.t1',
        chunk: 'street',
        cueVi: 'đường phố',
        sourceSentence: '"street" = s-t-r-eet (three consonants).',
        productionPattern: '<street / stream / strong>.',
        transferContext: 'hearing a street name in directions',
        pronunciationNote: 'str- là một khối: "STREET"',
      }),
      target({
        id: 'li14.t2',
        chunk: 'texts',
        cueVi: 'tin nhắn (số nhiều)',
        sourceSentence: '"texts" = teks-ts (final cluster).',
        productionPattern: '<texts / tests / lists>.',
        transferContext: 'hearing a message count',
        pronunciationNote: '"TEKSTS" — two finals',
      }),
      target({
        id: 'li14.t3',
        chunk: 'asked',
        cueVi: 'đã hỏi',
        sourceSentence: '"asked" = ask-t (two finals).',
        productionPattern: '<asked / helped / talked>.',
        transferContext: 'hearing past-tense questions',
        pronunciationNote: '"ASKT" — no vowel between',
      }),
      target({
        id: 'li14.t4',
        chunk: 'speed it up',
        cueVi: 'tăng tốc lại',
        sourceSentence: 'Slow the cluster down in your head, then speed it up.',
        productionPattern: 'speed <it / the word> up.',
        transferContext: 'drilling a hard word aloud',
        pronunciationNote: 'SPEED-it-UP',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Dictate 4 cluster-words from a clip — write each cluster as one unit.',
      promptVi: 'Chính tả 4 từ có cụm từ clip — viết mỗi cụm thành một khối.',
      changesDimension: 'dictation + cluster-units output',
    },
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li15',
    level: 'a2',
    track: 'listening',
    capabilities: ['extract-detail', 'catch-gist'],
    title: 'Following instructions',
    titleVi: 'Theo hướng dẫn',
    task: 'Catch steps in a spoken how-to',
    context: 'Someone explains how to use a machine.',
    outcome: 'You can hold the steps in order.',
    input: {
      title: 'LI15 · How-to',
      text: [
        'Staff: "Okay, so first you tap your card here."',
        '"Then you select your ticket type on the screen."',
        '"After that, you pay by card or cash."',
        '"Finally, take your ticket and the receipt below."',
        'Order of actions: tap → select → pay → take.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Hướng dẫn máy: bắt động từ hành động + thứ tự sequencers. Tap → select → pay → take.',
    },
    targets: [
      target({
        id: 'li15.t1',
        chunk: 'tap your card',
        cueVi: 'quẹt thẻ',
        sourceSentence: 'Staff: "Okay, so first you tap your card here."',
        productionPattern: 'tap your <card / phone>.',
        transferContext: 'hearing payment instructions',
        pronunciationNote: 'TAP your card',
      }),
      target({
        id: 'li15.t2',
        chunk: 'select your ticket type',
        cueVi: 'chọn loại vé',
        sourceSentence: '"Then you select your ticket type on the screen."',
        productionPattern: 'select your <ticket type / option>.',
        transferContext: 'using a self-checkout',
        pronunciationNote: 'se-LECT your TICK-et type',
      }),
      target({
        id: 'li15.t3',
        chunk: 'on the screen',
        cueVi: 'trên màn hình',
        sourceSentence: '"Then you select your ticket type on the screen."',
        productionPattern: 'on the <screen / display>.',
        transferContext: 'finding a button on an ATM',
        pronunciationNote: 'on the SCREEN',
      }),
      target({
        id: 'li15.t4',
        chunk: 'pay by card or cash',
        cueVi: 'trả bằng thẻ hoặc tiền mặt',
        sourceSentence: '"After that, you pay by card or cash."',
        productionPattern: 'pay by <card / cash / phone>.',
        transferContext: 'choosing payment method at a kiosk',
        pronunciationNote: 'pay by CARD or CASH',
      }),
      target({
        id: 'li15.t5',
        chunk: 'take your ticket',
        cueVi: 'lấy vé',
        sourceSentence: '"Finally, take your ticket and the receipt below."',
        productionPattern: 'take your <ticket / receipt>.',
        transferContext: 'finishing a parking payment',
        pronunciationNote: 'TAKE your TICK-et',
      }),
      target({
        id: 'li15.t6',
        chunk: 'the receipt',
        cueVi: 'hóa đơn/biên lai',
        sourceSentence: '"Finally, take your ticket and the receipt below."',
        productionPattern: 'the <receipt / change>.',
        transferContext: 'collecting items after payment',
        pronunciationNote: 're-CEIPT — p câm',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Extract the step order from a different how-to — using an ATM.',
      promptVi: 'Bắt thứ tự bước từ hướng dẫn khác — dùng ATM.',
      changesDimension: 'different machine + action-order output',
    },
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
  spec({
    id: 'li16',
    level: 'a2',
    track: 'listening',
    capabilities: ['catch-gist', 'infer-tone'],
    title: 'The point of the story',
    titleVi: 'Ý chính của câu chuyện',
    task: 'Catch why a speaker is telling a story',
    context: 'A friend tells a long story — what is the takeaway?',
    outcome: "You can find the speaker's point, not just facts.",
    input: {
      title: 'LI16 · The point',
      text: [
        'Tom: "So I waited an hour for this interview."',
        '"The manager finally comes out, looks at me, and says the role was filled last week."',
        '"No email, no call. I just took the day off for nothing."',
        'Point: not the facts — the frustration about wasted effort.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Nghe point = cảm xúc + lý do kể (wasted effort), không chỉ sự kiện. "for nothing" = uổng công.',
    },
    targets: [
      target({
        id: 'li16.t1',
        chunk: 'waited an hour',
        cueVi: 'đã đợi một tiếng',
        sourceSentence: 'Tom: "So I waited an hour for this interview."',
        productionPattern: 'waited <an hour / forever>.',
        transferContext: 'hearing a complaint about delays',
        pronunciationNote: 'WAIT-ed an HOUR',
      }),
      target({
        id: 'li16.t2',
        chunk: 'the role was filled',
        cueVi: 'vị trí đã có người',
        sourceSentence: '"The manager finally comes out, looks at me, and says the role was filled last week."',
        productionPattern: 'the <role / position> was filled.',
        transferContext: 'hearing a job rejection reason',
        pronunciationNote: 'the role was FILLED',
      }),
      target({
        id: 'li16.t3',
        chunk: 'last week',
        cueVi: 'tuần trước',
        sourceSentence: '"The manager finally comes out, looks at me, and says the role was filled last week."',
        productionPattern: '<last / this> week.',
        transferContext: 'placing an event in time',
        pronunciationNote: 'las-WEEK — t rơi',
      }),
      target({
        id: 'li16.t4',
        chunk: 'No email, no call',
        cueVi: 'không email, không gọi',
        sourceSentence: '"No email, no call. I just took the day off for nothing."',
        productionPattern: 'No <email / warning / heads-up>.',
        transferContext: 'listing what did not happen',
        pronunciationNote: 'NO email, NO call — parallel stress',
      }),
      target({
        id: 'li16.t5',
        chunk: 'took the day off',
        cueVi: 'đã nghỉ một ngày',
        sourceSentence: '"No email, no call. I just took the day off for nothing."',
        productionPattern: 'took the <day / afternoon> off.',
        transferContext: 'explaining an absence',
        pronunciationNote: 'took the DAY-off',
      }),
      target({
        id: 'li16.t6',
        chunk: 'for nothing',
        cueVi: 'uổng công',
        sourceSentence: '"No email, no call. I just took the day off for nothing."',
        productionPattern: 'for <nothing / no reason>.',
        transferContext: 'expressing wasted effort',
        pronunciationNote: 'for NUTH-ing',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: "Hear a different rant — a canceled flight — write the speaker's real point in one line.",
      promptVi: 'Nghe một lời phàn nàn khác — chuyến bay bị hủy — viết ý thật trong một dòng.',
      changesDimension: 'travel complaint + point-in-one-line output',
    },
    recyclingFrom: ['ch10'],
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
];
