/* Pronunciation pr09–pr16 — more VN contrasts + stress/intonation. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { LADDER_LISTEN, RES, SRC, spec, target, VARIANTS_LISTEN } from './helpers.ts';

export const PRONUNCIATION_2: LessonSpec[] = [
  spec({
    id: 'pr09',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt không phân /e/ và /æ/ — hai âm đều nghe gần nhau nên cặp từ hay trùng.',
    capabilities: ['perceive-tense-lax'],
    title: 'Pen vs pan',
    titleVi: 'Pen vs pan',
    task: 'Distinguish /e/ from /æ/',
    context: 'bad/bed, man/men — the vowel opens differently.',
    outcome: 'You can hear the jaw drop on /æ/.',
    input: {
      title: 'PR09 · /e/ vs /æ/',
      text: [
        'bed has /e/ — jaw half-open, relaxed.',
        'bad has /æ/ — jaw drops wider, a bit of whine.',
        'pen vs pan, men vs man, set vs sat.',
        'Hear the jaw: /e/ small, /æ/ wide.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: '/e/ miệng hé nhỏ; /æ/ hàm hạ rộng hơn, hơi kéo dài. "man" không đọc như "men".',
    },
    targets: [
      target({
        id: 'pr09.t1',
        kind: 'pronunciation',
        chunk: 'bed',
        cueVi: 'giường — /e/',
        sourceSentence: 'bed has /e/ — jaw half-open, relaxed.',
        productionPattern: '<bed / pen / men> → /e/.',
        transferContext: 'hearing furniture words',
        pronunciationNote: 'jaw half-open — /e/',
      }),
      target({
        id: 'pr09.t2',
        kind: 'pronunciation',
        chunk: 'bad',
        cueVi: 'tệ — /æ/',
        sourceSentence: 'bad has /æ/ — jaw drops wider, a bit of whine.',
        productionPattern: '<bad / pan / man> → /æ/.',
        transferContext: 'hearing descriptions',
        pronunciationNote: 'jaw wide — /æ/',
      }),
      target({
        id: 'pr09.t3',
        kind: 'pronunciation',
        chunk: 'pen',
        cueVi: 'bút — /e/',
        sourceSentence: 'pen vs pan, men vs man, set vs sat.',
        productionPattern: '<pen / ten / send> → /e/.',
        transferContext: 'hearing office words',
        pronunciationNote: '/e/',
      }),
      target({
        id: 'pr09.t4',
        kind: 'pronunciation',
        chunk: 'pan',
        cueVi: 'chảo — /æ/',
        sourceSentence: 'pen vs pan, men vs man, set vs sat.',
        productionPattern: '<pan / can / hand> → /æ/.',
        transferContext: 'hearing kitchen words',
        pronunciationNote: '/æ/',
      }),
      target({
        id: 'pr09.t5',
        kind: 'pronunciation',
        chunk: 'men',
        cueVi: 'đàn ông (số nhiều) — /e/',
        sourceSentence: 'pen vs pan, men vs man, set vs sat.',
        productionPattern: '<men / them / said> → /e/.',
        transferContext: 'hearing plural people',
        pronunciationNote: '/e/',
      }),
      target({
        id: 'pr09.t6',
        kind: 'pronunciation',
        chunk: 'man',
        cueVi: 'đàn ông (số ít) — /æ/',
        sourceSentence: 'pen vs pan, men vs man, set vs sat.',
        productionPattern: '<man / stand / bag> → /æ/.',
        transferContext: 'hearing singular people',
        pronunciationNote: '/æ/',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Sort 8 words by ear into /e/ vs /æ/ — then say one pair yourself.',
      promptVi: 'Phân loại 8 từ theo tai thành /e/ vs /æ/ — rồi đọc một cặp.',
      changesDimension: 'sorting + light production',
    },
    recyclingFrom: ['pr05'],
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr10',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt không phân độ dài nguyên âm sau — u dài và ngắn nghe ngang nhau.',
    capabilities: ['perceive-tense-lax'],
    title: 'Full vs fool',
    titleVi: 'Full vs fool',
    task: 'Distinguish short /ʊ/ from long /uː/',
    context: 'look/Luke, pull/pool — length shifts meaning.',
    outcome: 'You can hear the long round /uː/ vs short /ʊ/.',
    input: {
      title: 'PR10 · /ʊ/ vs /uː/',
      text: [
        'fool has long /uː/ — lips round, hold it.',
        'full has short /ʊ/ — lips less round, quick.',
        'Luke vs look, pool vs pull.',
        'Same length rule as sheep/ship, different vowel.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: '/uː/ môi tròn kéo dài; /ʊ/ ngắn, môi lỏng hơn. Nhớ: "fool" dài, "full" ngắn.',
    },
    targets: [
      target({
        id: 'pr10.t1',
        kind: 'pronunciation',
        chunk: 'fool',
        cueVi: 'kẻ ngốc — /uː/ dài',
        sourceSentence: 'fool has long /uː/ — lips round, hold it.',
        productionPattern: '<fool / pool / tool> → /uː/.',
        transferContext: 'hearing long-u words',
        pronunciationNote: 'long round /uː/',
      }),
      target({
        id: 'pr10.t2',
        kind: 'pronunciation',
        chunk: 'full',
        cueVi: 'đầy — /ʊ/ ngắn',
        sourceSentence: 'full has short /ʊ/ — lips less round, quick.',
        productionPattern: '<full / pull / put> → /ʊ/.',
        transferContext: 'hearing container words',
        pronunciationNote: 'short /ʊ/',
      }),
      target({
        id: 'pr10.t3',
        kind: 'pronunciation',
        chunk: 'Luke',
        cueVi: 'một cái tên — /uː/',
        sourceSentence: 'Luke vs look, pool vs pull.',
        productionPattern: '<Luke / choose / food> → /uː/.',
        transferContext: 'hearing names',
        pronunciationNote: '/uː/',
      }),
      target({
        id: 'pr10.t4',
        kind: 'pronunciation',
        chunk: 'look',
        cueVi: 'nhìn — /ʊ/',
        sourceSentence: 'Luke vs look, pool vs pull.',
        productionPattern: '<look / book / good> → /ʊ/.',
        transferContext: 'hearing action words',
        pronunciationNote: '/ʊ/',
      }),
      target({
        id: 'pr10.t5',
        kind: 'pronunciation',
        chunk: 'pool',
        cueVi: 'hồ bơi — /uː/',
        sourceSentence: 'Luke vs look, pool vs pull.',
        productionPattern: '<pool / school / cool> → /uː/.',
        transferContext: 'hearing place words',
        pronunciationNote: '/uː/',
      }),
      target({
        id: 'pr10.t6',
        kind: 'pronunciation',
        chunk: 'pull',
        cueVi: 'kéo — /ʊ/',
        sourceSentence: 'Luke vs look, pool vs pull.',
        productionPattern: '<pull / push / bull> → /ʊ/.',
        transferContext: 'hearing door instructions',
        pronunciationNote: '/ʊ/',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Sort 8 words by ear into /uː/ vs /ʊ/ — flag the hardest pair.',
      promptVi: 'Phân loại 8 từ theo tai thành /uː/ vs /ʊ/ — đánh dấu cặp khó nhất.',
      changesDimension: 'sorting + difficulty flag',
    },
    recyclingFrom: ['pr05'],
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr11',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt có /s/ nhưng /ʃ/ (sh) ở vị trí lưỡi khác — hai âm hay lẫn.',
    capabilities: ['perceive-th', 'perceive-tense-lax'],
    title: 'S vs SH',
    titleVi: 'S vs SH',
    task: 'Distinguish /s/ from /ʃ/',
    context: 'see/she, sip/ship, sort/short — hissing vs hushing.',
    outcome: 'You can hear the tongue pull back for /ʃ/.',
    input: {
      title: 'PR11 · S/SH',
      text: [
        'see has /s/ — thin hiss, tongue forward.',
        'she has /ʃ/ — fat hush, tongue pulls back.',
        'sip vs ship, sort vs short, save vs shave.',
        'For /ʃ/ the tongue arches like saying "shhh".',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: '/s/ xì mỏng (lưỡi sát răng); /ʃ/ xì dày (lưỡi cong lên). "she" không đọc "see".',
    },
    targets: [
      target({
        id: 'pr11.t1',
        kind: 'pronunciation',
        chunk: 'see',
        cueVi: 'nhìn thấy — /s/',
        sourceSentence: 'see has /s/ — thin hiss, tongue forward.',
        productionPattern: '<see / sip / sort> → /s/.',
        transferContext: 'hearing sight words',
        pronunciationNote: 'thin hiss — /s/',
      }),
      target({
        id: 'pr11.t2',
        kind: 'pronunciation',
        chunk: 'she',
        cueVi: 'cô ấy — /ʃ/',
        sourceSentence: 'she has /ʃ/ — fat hush, tongue pulls back.',
        productionPattern: '<she / ship / short> → /ʃ/.',
        transferContext: 'hearing pronouns',
        pronunciationNote: 'fat hush — /ʃ/',
      }),
      target({
        id: 'pr11.t3',
        kind: 'pronunciation',
        chunk: 'sip',
        cueVi: 'hớp — /s/',
        sourceSentence: 'sip vs ship, sort vs short, save vs shave.',
        productionPattern: '<sip / sit / sell> → /s/.',
        transferContext: 'hearing drink words',
        pronunciationNote: '/s/',
      }),
      target({
        id: 'pr11.t4',
        kind: 'pronunciation',
        chunk: 'ship',
        cueVi: 'tàu — /ʃ/',
        sourceSentence: 'sip vs ship, sort vs short, save vs shave.',
        productionPattern: '<ship / shoe / shop> → /ʃ/.',
        transferContext: 'hearing boat words',
        pronunciationNote: '/ʃ/',
      }),
      target({
        id: 'pr11.t5',
        kind: 'pronunciation',
        chunk: 'sort',
        cueVi: 'phân loại — /s/',
        sourceSentence: 'sip vs ship, sort vs short, save vs shave.',
        productionPattern: '<sort / sour / safe> → /s/.',
        transferContext: 'hearing organize words',
        pronunciationNote: '/s/',
      }),
      target({
        id: 'pr11.t6',
        kind: 'pronunciation',
        chunk: 'short',
        cueVi: 'ngắn — /ʃ/',
        sourceSentence: 'sip vs ship, sort vs short, save vs shave.',
        productionPattern: '<short / sure / show> → /ʃ/.',
        transferContext: 'hearing length words',
        pronunciationNote: '/ʃ/',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Sort 8 words by ear into /s/ vs /ʃ/ — then try "she sells seashells".',
      promptVi: 'Phân loại 8 từ theo tai thành /s/ vs /ʃ/ — rồi thử "she sells seashells".',
      changesDimension: 'sorting + tongue twister production',
    },
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr12',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt có tr gần giống /tʃ/ — hai âm tắc-trượt này rất dễ nhầm cho tai VN.',
    capabilities: ['perceive-clusters'],
    title: 'CH vs TR',
    titleVi: 'CH vs TR',
    task: 'Distinguish /tʃ/ from /tr/ and /ts/',
    context: 'cheap/trip, choose/true — the tongue curls differently.',
    outcome: 'You can hear the stop-then-slide of /tʃ/.',
    input: {
      title: 'PR12 · CH/TR',
      text: [
        'cheap has /tʃ/ — a stop that slides into sh.',
        'trip has /tr/ — a stop that rolls into r.',
        'choose vs truce — same contrast.',
        'Practice pairs: cheap/trip, choose/truce, chair/tree.',
        'Vietnamese has /tr/ in some dialects — /tʃ/ is different.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: '/tʃ/: tắc rồi trượt sang /ʃ/. /tr/: tắc rồi trượt sang /r/. "cheap" ≠ "trip".',
    },
    targets: [
      target({
        id: 'pr12.t1',
        kind: 'pronunciation',
        chunk: 'cheap',
        cueVi: 'rẻ — /tʃ/',
        sourceSentence: 'cheap has /tʃ/ — a stop that slides into sh.',
        productionPattern: '<cheap / choose / chair> → /tʃ/.',
        transferContext: 'hearing price words',
        pronunciationNote: 'stop → slide sh',
      }),
      target({
        id: 'pr12.t2',
        kind: 'pronunciation',
        chunk: 'trip',
        cueVi: 'chuyến đi — /tr/',
        sourceSentence: 'trip has /tr/ — a stop that rolls into r.',
        productionPattern: '<trip / true / try> → /tr/.',
        transferContext: 'hearing travel words',
        pronunciationNote: 'stop → roll r',
      }),
      target({
        id: 'pr12.t3',
        kind: 'pronunciation',
        chunk: 'choose',
        cueVi: 'chọn — /tʃ/',
        sourceSentence: 'choose vs truce — same contrast.',
        productionPattern: '<choose / chop / check> → /tʃ/.',
        transferContext: 'hearing decision words',
        pronunciationNote: '/tʃ/',
      }),
      target({
        id: 'pr12.t4',
        kind: 'pronunciation',
        chunk: 'truce',
        cueVi: 'đình chiến — /tr/',
        sourceSentence: 'choose vs truce — same contrast.',
        productionPattern: '<truce / trust / train> → /tr/.',
        transferContext: 'hearing peace words',
        pronunciationNote: '/tr/',
      }),
      target({
        id: 'pr12.t5',
        kind: 'pronunciation',
        chunk: 'chair',
        cueVi: 'ghế — /tʃ/',
        sourceSentence: 'Practice pairs: cheap/trip, choose/truce, chair/tree.',
        productionPattern: '<chair / much / rich> → /tʃ/.',
        transferContext: 'hearing furniture words',
        pronunciationNote: '/tʃ/',
      }),
      target({
        id: 'pr12.t6',
        kind: 'pronunciation',
        chunk: 'tree',
        cueVi: 'cây — /tr/',
        sourceSentence: 'Practice pairs: cheap/trip, choose/truce, chair/tree.',
        productionPattern: '<tree / truck / treat> → /tr/.',
        transferContext: 'hearing nature words',
        pronunciationNote: '/tr/',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Sort 8 words by ear into /tʃ/ vs /tr/ — note which side you default to.',
      promptVi: 'Phân loại 8 từ theo tai thành /tʃ/ vs /tr/ — ghi lại bạn hay nghe nhầm sang bên nào.',
      changesDimension: 'sorting + error-pattern self-report',
    },
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr13',
    level: 'a1',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt là ngôn ngữ thanh điệu — nhấn âm (stress) đổi nghĩa mà tai VN chưa quen bắt.',
    capabilities: ['place-word-stress'],
    title: 'Word stress',
    titleVi: 'Nhấn âm từ',
    task: 'Hear which syllable is stressed in two-syllable words',
    context: 'PROblem vs proJECT — stress moves meaning.',
    outcome: 'You can hear the loud syllable.',
    input: {
      title: 'PR13 · Stress',
      text: [
        'TAble — first syllable loud.',
        'beGIN — second syllable loud.',
        'Nouns often stress first: TAble, PICture, WINdow.',
        'Verbs often stress last: beGIN, forGET, deCIDE.',
        'Hear the loud beat, not the spelling.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Danh từ 2 âm thường nhấn âm đầu (TAble); động từ nhấn âm sau (beGIN). Nghe beat, không đoán.',
    },
    targets: [
      target({
        id: 'pr13.t1',
        chunk: 'TAble',
        cueVi: 'cái bàn — nhấn âm đầu',
        sourceSentence: 'TAble — first syllable loud.',
        productionPattern: '<TAble / WINdow / PICture>.',
        transferContext: 'hearing object names',
        pronunciationNote: 'TA-ble — first beat loud',
      }),
      target({
        id: 'pr13.t2',
        chunk: 'beGIN',
        cueVi: 'bắt đầu — nhấn âm sau',
        sourceSentence: 'beGIN — second syllable loud.',
        productionPattern: '<beGIN / forGET / deCIDE>.',
        transferContext: 'hearing action verbs',
        pronunciationNote: 'be-GIN — second beat loud',
      }),
      target({
        id: 'pr13.t3',
        chunk: 'PICture',
        cueVi: 'bức tranh — nhấn âm đầu',
        sourceSentence: 'Nouns often stress first: TAble, PICture, WINdow.',
        productionPattern: '<PICture / PARty / DOCtor>.',
        transferContext: 'hearing noun patterns',
        pronunciationNote: 'PIC-ture',
      }),
      target({
        id: 'pr13.t4',
        chunk: 'forGET',
        cueVi: 'quên — nhấn âm sau',
        sourceSentence: 'Verbs often stress last: beGIN, forGET, deCIDE.',
        productionPattern: '<forGET / arRIVE / rePEAT>.',
        transferContext: 'hearing verb patterns',
        pronunciationNote: 'for-GET',
      }),
      target({
        id: 'pr13.t5',
        chunk: 'the loud beat',
        cueVi: 'nhịp mạnh',
        sourceSentence: 'Hear the loud beat, not the spelling.',
        productionPattern: 'the <loud beat / strong syllable>.',
        transferContext: 'explaining stress to a learner',
        pronunciationNote: 'stress = loud + long',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Mark the stressed syllable in 8 two-syllable words you hear.',
      promptVi: 'Đánh dấu âm được nhấn trong 8 từ hai âm tiết bạn nghe.',
      changesDimension: 'stress-marking output on new words',
    },
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr14',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Từ chức năng bị giảm âm trong lời nói thật — tai Việt quen phát âm đầy nên mất từ nhỏ.',
    capabilities: ['place-word-stress'],
    title: 'Sentence stress',
    titleVi: 'Nhấn trọng âm câu',
    task: 'Hear which words carry the beat in a sentence',
    context: 'English stresses content words, skips function words.',
    outcome: 'You can hear the sentence rhythm.',
    input: {
      title: 'PR14 · Rhythm',
      text: [
        'English beats on content words, not grammar words.',
        '"I WANT to GO to the STORE" — want, go, store loud.',
        'Small words shrink: to, the, a, of.',
        'The beat lands on nouns, verbs, adjectives.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Tiếng Anh nhấn từ mang nghĩa (noun/verb/adj), không nhấn từ chức năng — tạo nhịp đều đều.',
    },
    targets: [
      target({
        id: 'pr14.t1',
        chunk: 'I WANT to GO',
        cueVi: 'tôi MUỐN ĐI (nhấn)',
        sourceSentence: '"I WANT to GO to the STORE" — want, go, store loud.',
        productionPattern: 'I WANT to GO to the STORE.',
        transferContext: 'hearing desires in speech',
        pronunciationNote: 'beat on WANT GO STORE',
      }),
      target({
        id: 'pr14.t2',
        chunk: 'to the STORE',
        cueVi: 'đến CỬA HÀNG',
        sourceSentence: '"I WANT to GO to the STORE" — want, go, store loud.',
        productionPattern: 'to the <STORE / BANK / GYM>.',
        transferContext: 'hearing destinations',
        pronunciationNote: 'weak to-the, strong STORE',
      }),
      target({
        id: 'pr14.t3',
        chunk: 'Small words shrink',
        cueVi: 'từ nhỏ bị co',
        sourceSentence: 'Small words shrink: to, the, a, of.',
        productionPattern: 'Small words <shrink / weaken>.',
        transferContext: 'explaining rhythm to a learner',
        pronunciationNote: 'function words go fast',
      }),
      target({
        id: 'pr14.t4',
        chunk: 'nouns, verbs, adjectives',
        cueVi: 'danh/động/tính từ',
        sourceSentence: 'The beat lands on nouns, verbs, adjectives.',
        productionPattern: '<nouns / verbs / adjectives>.',
        transferContext: 'identifying stressed word classes',
        pronunciationNote: 'content words get beat',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Mark the stressed words in a spoken sentence — check they are content words.',
      promptVi: 'Đánh dấu các từ được nhấn trong một câu nói — kiểm tra đó là content words.',
      changesDimension: 'stress-marking + word-class check',
    },
    recyclingFrom: ['li02', 'li13'],
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr15',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Tiếng Anh dùng ngữ điệu lên/xuống để phân loại câu hỏi — khác hệ thống thanh điệu tiếng Việt.',
    capabilities: ['perceive-intonation'],
    title: 'Questions rise',
    titleVi: 'Ngữ điệu câu hỏi',
    task: 'Hear rising vs falling intonation on questions',
    context: 'yes/no questions rise; wh- questions fall.',
    outcome: 'You can tell question type by pitch alone.',
    input: {
      title: 'PR15 · Intonation',
      text: [
        '"Are you ready?" rises at the end — yes/no question.',
        '"Where are you going?" falls — wh- question.',
        'Rising = checking; falling = asking for info.',
        "Hear the last word's pitch direction.",
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Câu yes/no lên giọng cuối; câu wh- xuống giọng. Nghe hướng pitch ở từ cuối.',
    },
    targets: [
      target({
        id: 'pr15.t1',
        chunk: 'Are you ready',
        cueVi: 'bạn sẵn sàng chưa (lên giọng)',
        sourceSentence: '"Are you ready?" rises at the end — yes/no question.',
        productionPattern: 'Are you <ready / sure / coming>?',
        transferContext: 'hearing check questions',
        pronunciationNote: 'rising tail — yes/no',
      }),
      target({
        id: 'pr15.t2',
        chunk: 'Where are you going',
        cueVi: 'bạn đi đâu (xuống giọng)',
        sourceSentence: '"Where are you going?" falls — wh- question.',
        productionPattern: 'Where are you <going / staying>?',
        transferContext: 'hearing info questions',
        pronunciationNote: 'falling tail — wh-',
      }),
      target({
        id: 'pr15.t3',
        chunk: 'Rising = checking',
        cueVi: 'lên giọng = hỏi kiểm',
        sourceSentence: 'Rising = checking; falling = asking for info.',
        productionPattern: 'Rising = <checking / confirming>.',
        transferContext: 'explaining question intonation',
        pronunciationNote: 'rise = yes/no',
      }),
      target({
        id: 'pr15.t4',
        chunk: 'asking for info',
        cueVi: 'hỏi thông tin',
        sourceSentence: 'Rising = checking; falling = asking for info.',
        productionPattern: 'asking for <info / help / details>.',
        transferContext: 'explaining wh- intonation',
        pronunciationNote: 'fall = wh-',
      }),
      target({
        id: 'pr15.t5',
        chunk: 'the last word',
        cueVi: 'từ cuối câu',
        sourceSentence: "Hear the last word's pitch direction.",
        productionPattern: 'the <last word / final syllable>.',
        transferContext: 'training pitch listening',
        pronunciationNote: 'focus on the tail',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Label 6 questions as rise or fall — predict if each wants yes/no or info.',
      promptVi: 'Gắn nhãn 6 câu hỏi là lên hay xuống giọng — đoán mỗi câu muốn yes/no hay thông tin.',
      changesDimension: 'labeling + type prediction',
    },
    recyclingFrom: ['li11', 'li12'],
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr16',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Đường cao độ đổi = thái độ đổi — tiếng Việt dùng thanh cho nghĩa từ, không phải thái độ câu.',
    capabilities: ['perceive-intonation'],
    title: 'Surprise and doubt',
    titleVi: 'Ngạc nhiên và nghi ngờ',
    task: 'Hear emotional pitch on short replies',
    context: '"Really?" can mean wow or prove-it.',
    outcome: 'You can read feeling from pitch.',
    input: {
      title: 'PR16 · Pitch feelings',
      text: [
        '"Really?" rising high = surprise.',
        '"Really." falling flat = doubt or sarcasm.',
        '"Fine." short drop = annoyed.',
        'Pitch direction + length = the emotion.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Pitch cao + kéo dài = ngạc nhiên; xuống nhanh = nghi ngờ/chán. Nghe cảm xúc qua đường cao độ.',
    },
    targets: [
      target({
        id: 'pr16.t1',
        chunk: 'Really',
        cueVi: 'thật không (ngạc nhiên)',
        sourceSentence: '"Really?" rising high = surprise.',
        productionPattern: '<Really / Wow / No way>?',
        transferContext: 'reacting to surprising news',
        pronunciationNote: 'high rise = surprise',
      }),
      target({
        id: 'pr16.t2',
        chunk: 'falling flat',
        cueVi: 'ngữ điệu tụt xuống (nghi ngờ)',
        sourceSentence: '"Really." falling flat = doubt or sarcasm.',
        productionPattern: 'falling <flat / low>.',
        transferContext: 'expressing doubt politely',
        pronunciationNote: 'flat fall = doubt',
      }),
      target({
        id: 'pr16.t3',
        chunk: 'Fine',
        cueVi: 'được rồi (chán)',
        sourceSentence: '"Fine." short drop = annoyed.',
        productionPattern: '<Fine / Whatever / Okay>.',
        transferContext: 'giving in during an argument',
        pronunciationNote: 'short drop = annoyed',
      }),
      target({
        id: 'pr16.t4',
        chunk: 'the emotion',
        cueVi: 'cảm xúc',
        sourceSentence: 'Pitch direction + length = the emotion.',
        productionPattern: 'the <emotion / attitude / tone>.',
        transferContext: 'reading mood from replies',
        pronunciationNote: 'pitch + length = feeling',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Label 4 short replies by emotion — surprise/doubt/annoyance/genuine.',
      promptVi: 'Gắn nhãn 4 câu trả lời ngắn theo cảm xúc — ngạc nhiên/nghi ngờ/chán/chân thành.',
      changesDimension: 'emotion labeling on new replies',
    },
    recyclingFrom: ['li12'],
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
];
