/* Pronunciation pr01–pr08 — Vietnamese-specific contrasts, perception-first.
 * No ASR, no accent targets — only perception + optional mouth notes. */

import type { LessonSpec } from '../../content-factory/types.ts';
import { LADDER_LISTEN, RES, SRC, spec, target, VARIANTS_LISTEN } from './helpers.ts';

export const PRONUNCIATION_1: LessonSpec[] = [
  spec({
    id: 'pr01',
    level: 'a1',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt không có phụ âm cuối /s/ hay /z/ — hay nuốt hoặc đọc ngang nhau.',
    capabilities: ['perceive-final-consonants'],
    title: 'Final -s: cats vs dogs',
    titleVi: 'Âm -s cuối: cats vs dogs',
    task: 'Hear the difference between plural /s/ and /z/',
    context: 'Plural and verb endings carry meaning — hear them.',
    outcome: 'You can tell /s/ from /z/ at word end.',
    input: {
      title: 'PR01 · Final s',
      text: [
        'cats ends in a sharp /s/ — unvoiced.',
        'dogs ends in a buzzing /z/ — voiced.',
        'days uses /z/; it is voiced after a vowel.',
        'books uses /s/; it is unvoiced after /k/.',
        'Rule: match the voicing of the sound before it.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Âm đuôi -s đọc /s/ hay /z/ theo âm trước: hữu thanh → /z/, vô thanh → /s/. Người Việt hay nuốt âm này.',
    },
    targets: [
      target({
        id: 'pr01.t1',
        kind: 'pronunciation',
        chunk: 'cats',
        cueVi: 'những con mèo — /s/ sắc',
        sourceSentence: 'cats ends in a sharp /s/ — unvoiced.',
        productionPattern: '<cats / books / hats> → /s/.',
        transferContext: 'hearing plural lists',
        pronunciationNote: 'sharp /s/ after /t/',
      }),
      target({
        id: 'pr01.t2',
        kind: 'pronunciation',
        chunk: 'dogs',
        cueVi: 'những con chó — /z/ ù',
        sourceSentence: 'dogs ends in a buzzing /z/ — voiced.',
        productionPattern: '<dogs / days / pens> → /z/.',
        transferContext: 'hearing plural nouns in speech',
        pronunciationNote: 'buzzing /z/ after /g/',
      }),
      target({
        id: 'pr01.t3',
        chunk: 'days',
        cueVi: 'những ngày — /z/',
        sourceSentence: 'days uses /z/; it is voiced after a vowel.',
        productionPattern: '<days / plays / goes> → /z/.',
        transferContext: 'hearing -s after vowel sounds',
        pronunciationNote: '/z/ after vowels',
      }),
      target({
        id: 'pr01.t4',
        chunk: 'books',
        cueVi: 'những cuốn sách — /s/',
        sourceSentence: 'books uses /s/; it is unvoiced after /k/.',
        productionPattern: '<books / cups / maps> → /s/.',
        transferContext: 'hearing -s after /k, p, t/',
        pronunciationNote: '/s/ after /k/',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Sort 8 plural words by ear into /s/ vs /z/ ending columns.',
      promptVi: 'Phân loại 8 từ số nhiều theo tai thành cột đuôi /s/ vs /z/.',
      changesDimension: 'new word set + sorting output',
    },
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr02',
    level: 'a1',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt không có đuôi -ed — hay đọc thành âm tiết riêng hoặc bỏ luôn.',
    capabilities: ['perceive-ed-endings'],
    title: 'The -ed ending',
    titleVi: 'Đuôi -ed',
    task: 'Hear the three ways -ed is pronounced',
    context: 'walked vs played vs wanted — three different sounds.',
    outcome: 'You can tell /t/, /d/, and /ɪd/ apart.',
    input: {
      title: 'PR02 · -ed',
      text: [
        'walked ends in /t/ — quick, unvoiced.',
        'played ends in /d/ — voiced, soft.',
        'wanted ends in /ɪd/ — a full extra syllable.',
        'The -ed adds a syllable only after /t/ or /d/.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi:
        '-ed chỉ thành âm tiết riêng sau /t,d/ (wanted). Còn lại chỉ là /t/ hoặc /d/ ngắn — người Việt hay đọc "ed" to.',
    },
    targets: [
      target({
        id: 'pr02.t1',
        kind: 'pronunciation',
        chunk: 'walked',
        cueVi: 'đã đi bộ — /t/',
        sourceSentence: 'walked ends in /t/ — quick, unvoiced.',
        productionPattern: '<walked / stopped / helped> → /t/.',
        transferContext: 'hearing past actions in stories',
        pronunciationNote: '"WALKT" — one syllable',
      }),
      target({
        id: 'pr02.t2',
        kind: 'pronunciation',
        chunk: 'played',
        cueVi: 'đã chơi — /d/',
        sourceSentence: 'played ends in /d/ — voiced, soft.',
        productionPattern: '<played / called / used> → /d/.',
        transferContext: 'hearing past hobbies',
        pronunciationNote: '"PLAYD" — one syllable',
      }),
      target({
        id: 'pr02.t3',
        kind: 'pronunciation',
        chunk: 'wanted',
        cueVi: 'đã muốn — /ɪd/ thêm âm tiết',
        sourceSentence: 'wanted ends in /ɪd/ — a full extra syllable.',
        productionPattern: '<wanted / needed / waited> → /ɪd/.',
        transferContext: 'hearing -ed after t/d',
        pronunciationNote: '"WON-tid" — two syllables',
      }),
      target({
        id: 'pr02.t4',
        chunk: 'a full extra syllable',
        cueVi: 'thêm một âm tiết',
        sourceSentence: 'wanted ends in /ɪd/ — a full extra syllable.',
        productionPattern: 'a full <extra syllable / beat>.',
        transferContext: 'counting syllables in a word',
        pronunciationNote: 'extra beat only after t/d',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Sort 10 past verbs by ear into /t/, /d/, /ɪd/ ending columns.',
      promptVi: 'Phân loại 10 động từ quá khứ theo tai thành ba cột /t/, /d/, /ɪd/.',
      changesDimension: 'new verb set + three-way sort',
    },
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr03',
    level: 'a1',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt không có âm lưỡi-giữa-răng — tai VN hay nghe thành /s/ hoặc /t/.',
    capabilities: ['perceive-th'],
    title: 'TH: think vs sink',
    titleVi: 'Âm TH: think vs sink',
    task: 'Distinguish /θ/ from /s/ and /t/',
    context: 'Vietnamese has no /θ/ — it becomes /s/ or /t/ by habit.',
    outcome: 'You can hear think/sink and three/tree apart.',
    input: {
      title: 'PR03 · /θ/',
      text: [
        'think has /θ/ — tongue between teeth, air flows.',
        'sink has /s/ — tongue behind teeth.',
        'three has /θ/; tree has /t/ — tongue stops the air.',
        'Minimal pair practice: think/sink, three/tree, bath/bass.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: '/θ/: lưỡi giữa hai hàm răng, thổi khí ra. Nghe khác /s/ (lưỡi sau răng) và /t/ (chặn hơi).',
    },
    targets: [
      target({
        id: 'pr03.t1',
        kind: 'pronunciation',
        chunk: 'think',
        cueVi: 'nghĩ — /θ/',
        sourceSentence: 'think has /θ/ — tongue between teeth, air flows.',
        productionPattern: '<think / thank / thin> → /θ/.',
        transferContext: 'hearing opinion words',
        pronunciationNote: 'tongue between teeth — /θ/',
      }),
      target({
        id: 'pr03.t2',
        kind: 'pronunciation',
        chunk: 'sink',
        cueVi: 'chìm/bồn rửa — /s/',
        sourceSentence: 'sink has /s/ — tongue behind teeth.',
        productionPattern: '<sink / sing / pass> → /s/.',
        transferContext: 'hearing kitchen words',
        pronunciationNote: 'tongue behind teeth — /s/',
      }),
      target({
        id: 'pr03.t3',
        kind: 'pronunciation',
        chunk: 'three',
        cueVi: 'số ba — /θ/',
        sourceSentence: 'three has /θ/; tree has /t/ — tongue stops the air.',
        productionPattern: '<three / throw / thumb> → /θ/.',
        transferContext: 'hearing numbers at a store',
        pronunciationNote: '/θ/ + r — air flows',
      }),
      target({
        id: 'pr03.t4',
        kind: 'pronunciation',
        chunk: 'tree',
        cueVi: 'cây — /t/',
        sourceSentence: 'three has /θ/; tree has /t/ — tongue stops the air.',
        productionPattern: '<tree / true / try> → /t/.',
        transferContext: 'hearing nature words',
        pronunciationNote: '/t/ stops air then releases',
      }),
      target({
        id: 'pr03.t5',
        chunk: 'bath',
        cueVi: 'tắm — /θ/',
        sourceSentence: 'Minimal pair practice: think/sink, three/tree, bath/bass.',
        productionPattern: '<bath / path / math> → /θ/.',
        transferContext: 'hearing bathroom words',
        pronunciationNote: 'final /θ/ — soft hiss',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Sort 8 words by ear into /θ/ vs /s/ vs /t/ — then try a few yourself.',
      promptVi: 'Phân loại 8 từ theo tai thành /θ/ vs /s/ vs /t/ — rồi thử đọc vài từ.',
      changesDimension: 'three-way sort + optional light production',
    },
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr04',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Âm /ð/ rung không tồn tại trong tiếng Việt — hay chuyển thành /d/ hoặc /z/.',
    capabilities: ['perceive-th'],
    title: 'This and that',
    titleVi: 'Âm ð: this, that',
    task: 'Hear voiced /ð/ in function words',
    context: 'the/this/that all start with buzzing /ð/.',
    outcome: 'You can hear /ð/ vs /d/ and /z/.',
    input: {
      title: 'PR04 · /ð/',
      text: [
        'this and that start with voiced /ð/.',
        'Same position as /θ/, but the throat vibrates.',
        'breathe has /ð/ at the end; breath has /θ/.',
        'Common words: the, this, that, there, mother, father.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: '/ð/ là /θ/ có rung thanh — xuất hiện ở the/this/that/there. Người Việt hay thành /d/ hoặc /z/.',
    },
    targets: [
      target({
        id: 'pr04.t1',
        kind: 'pronunciation',
        chunk: 'this',
        cueVi: 'cái này — /ð/',
        sourceSentence: 'this and that start with voiced /ð/.',
        productionPattern: '<this / that / there> → /ð/.',
        transferContext: 'hearing demonstratives',
        pronunciationNote: 'voiced buzz — /ð/',
      }),
      target({
        id: 'pr04.t2',
        kind: 'pronunciation',
        chunk: 'that',
        cueVi: 'cái kia — /ð/',
        sourceSentence: 'this and that start with voiced /ð/.',
        productionPattern: '<that / those / they> → /ð/.',
        transferContext: 'pointing at things in speech',
        pronunciationNote: '/ð/ in function words',
      }),
      target({
        id: 'pr04.t3',
        kind: 'pronunciation',
        chunk: 'breathe',
        cueVi: 'thở (động từ) — /ð/',
        sourceSentence: 'breathe has /ð/ at the end; breath has /θ/.',
        productionPattern: '<breathe / bathe / clothe> → /ð/.',
        transferContext: 'hearing verb vs noun pairs',
        pronunciationNote: 'final voiced /ð/',
      }),
      target({
        id: 'pr04.t4',
        kind: 'pronunciation',
        chunk: 'breath',
        cueVi: 'hơi thở (danh từ) — /θ/',
        sourceSentence: 'breathe has /ð/ at the end; breath has /θ/.',
        productionPattern: '<breath / bath / cloth> → /θ/.',
        transferContext: 'hearing noun endings',
        pronunciationNote: 'final unvoiced /θ/',
      }),
      target({
        id: 'pr04.t5',
        chunk: 'mother',
        cueVi: 'mẹ — /ð/ giữa từ',
        sourceSentence: 'Common words: the, this, that, there, mother, father.',
        productionPattern: '<mother / father / brother> → /ð/.',
        transferContext: 'hearing family words',
        pronunciationNote: 'mid-word /ð/',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Mark every /ð/ you hear in a spoken sentence about family.',
      promptVi: 'Đánh dấu mọi âm /ð/ nghe được trong một câu nói về gia đình.',
      changesDimension: 'continuous speech + phoneme spotting',
    },
    recyclingFrom: ['pr03'],
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr05',
    level: 'a1',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt không phân biệt nguyên âm dài/ngắn kiểu này — hai âm hay nghe ngang nhau.',
    capabilities: ['perceive-tense-lax'],
    title: 'Sheep vs ship',
    titleVi: 'Sheep vs ship',
    task: 'Distinguish long /iː/ from short /ɪ/',
    context: 'Vietnamese ears merge these — but meaning changes.',
    outcome: 'You can hear sheep/ship, leave/live apart.',
    input: {
      title: 'PR05 · /iː/ vs /ɪ/',
      text: [
        'sheep has long /iː/ — smile wider, hold it.',
        'ship has short /ɪ/ — relax, release fast.',
        'leave vs live: same contrast.',
        'eat vs it — the length changes the word.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi:
        '/iː/ dài vs /ɪ/ ngắn — người Việt hay nói ngang nhau → "I live here" nghe như "leave". Kéo dài hoặc cắt ngắn.',
    },
    targets: [
      target({
        id: 'pr05.t1',
        kind: 'pronunciation',
        chunk: 'sheep',
        cueVi: 'con cừu — /iː/ dài',
        sourceSentence: 'sheep has long /iː/ — smile wider, hold it.',
        productionPattern: '<sheep / sleep / green> → /iː/.',
        transferContext: 'hearing animal names',
        pronunciationNote: 'long smile /iː/',
      }),
      target({
        id: 'pr05.t2',
        kind: 'pronunciation',
        chunk: 'ship',
        cueVi: 'con tàu — /ɪ/ ngắn',
        sourceSentence: 'ship has short /ɪ/ — relax, release fast.',
        productionPattern: '<ship / sit / list> → /ɪ/.',
        transferContext: 'hearing boat words',
        pronunciationNote: 'short relaxed /ɪ/',
      }),
      target({
        id: 'pr05.t3',
        kind: 'pronunciation',
        chunk: 'leave',
        cueVi: 'rời đi — /iː/',
        sourceSentence: 'leave vs live: same contrast.',
        productionPattern: '<leave / these / beach> → /iː/.',
        transferContext: 'hearing verb pairs',
        pronunciationNote: 'hold the /iː/',
      }),
      target({
        id: 'pr05.t4',
        kind: 'pronunciation',
        chunk: 'live',
        cueVi: 'sống — /ɪ/',
        sourceSentence: 'leave vs live: same contrast.',
        productionPattern: '<live / this / bit> → /ɪ/.',
        transferContext: 'hearing where someone lives',
        pronunciationNote: 'short /ɪ/',
      }),
      target({
        id: 'pr05.t5',
        kind: 'pronunciation',
        chunk: 'eat',
        cueVi: 'ăn — /iː/',
        sourceSentence: 'eat vs it — the length changes the word.',
        productionPattern: '<eat / seat / beat> → /iː/.',
        transferContext: 'hearing food words',
        pronunciationNote: 'long /iː/',
      }),
      target({
        id: 'pr05.t6',
        kind: 'pronunciation',
        chunk: 'it',
        cueVi: 'nó — /ɪ/',
        sourceSentence: 'eat vs it — the length changes the word.',
        productionPattern: '<it / in / is> → /ɪ/.',
        transferContext: 'hearing function words',
        pronunciationNote: 'tiny /ɪ/',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Hear 6 words — sort into long /iː/ vs short /ɪ/ — then say 2 pairs yourself.',
      promptVi: 'Nghe 6 từ — chia thành /iː/ dài vs /ɪ/ ngắn — rồi nói 2 cặp.',
      changesDimension: 'sorting + optional light production',
    },
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr06',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Hai âm khác vị trí lưỡi rõ — tiếng Việt ở một số vùng trộn chúng, tai cần luyện tách.',
    capabilities: ['perceive-rl'],
    title: 'R vs L',
    titleVi: 'R vs L',
    task: 'Distinguish /r/ from /l/ in common words',
    context: 'right/light, road/load — meaning flips on one sound.',
    outcome: 'You can hear /r/ (curled, no touch) vs /l/ (tongue touch).',
    input: {
      title: 'PR06 · R/L',
      text: [
        'right vs light — hear the tongue position.',
        'For /r/: tongue curls back, does not touch.',
        'For /l/: tongue tip touches the ridge behind teeth.',
        'Practice pairs: right/light, road/load, pray/play.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: '/r/: lưỡi cong lên không chạm; /l/: đầu lưỡi chạm ngạc cứng. Nghe khác nhau rõ trong cặp đối lập.',
    },
    targets: [
      target({
        id: 'pr06.t1',
        kind: 'pronunciation',
        chunk: 'right',
        cueVi: 'đúng/phải — /r/',
        sourceSentence: 'right vs light — hear the tongue position.',
        productionPattern: '<right / road / red> → /r/.',
        transferContext: 'hearing directions',
        pronunciationNote: 'tongue curls back — no touch',
      }),
      target({
        id: 'pr06.t2',
        kind: 'pronunciation',
        chunk: 'light',
        cueVi: 'ánh sáng/nhẹ — /l/',
        sourceSentence: 'right vs light — hear the tongue position.',
        productionPattern: '<light / load / let> → /l/.',
        transferContext: 'hearing color and weight words',
        pronunciationNote: 'tongue tip touches ridge',
      }),
      target({
        id: 'pr06.t3',
        kind: 'pronunciation',
        chunk: 'road',
        cueVi: 'đường — /r/',
        sourceSentence: 'Practice pairs: right/light, road/load, pray/play.',
        productionPattern: '<road / run / rain> → /r/.',
        transferContext: 'hearing travel words',
        pronunciationNote: '/r/ — curled',
      }),
      target({
        id: 'pr06.t4',
        kind: 'pronunciation',
        chunk: 'load',
        cueVi: 'tải — /l/',
        sourceSentence: 'Practice pairs: right/light, road/load, pray/play.',
        productionPattern: '<load / long / love> → /l/.',
        transferContext: 'hearing cargo words',
        pronunciationNote: '/l/ — tip touches',
      }),
      target({
        id: 'pr06.t5',
        kind: 'pronunciation',
        chunk: 'pray',
        cueVi: 'cầu nguyện — /r/',
        sourceSentence: 'Practice pairs: right/light, road/load, pray/play.',
        productionPattern: '<pray / free / three> → /r/.',
        transferContext: 'hearing words with r-clusters',
        pronunciationNote: 'pr- cluster',
      }),
      target({
        id: 'pr06.t6',
        kind: 'pronunciation',
        chunk: 'play',
        cueVi: 'chơi — /l/',
        sourceSentence: 'Practice pairs: right/light, road/load, pray/play.',
        productionPattern: '<play / please / fly> → /l/.',
        transferContext: 'hearing words with l-clusters',
        pronunciationNote: 'pl- cluster',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Sort 8 words by ear into /r/ vs /l/ — then try the pairs aloud.',
      promptVi: 'Phân loại 8 từ theo tai thành /r/ vs /l/ — rồi đọc thử các cặp.',
      changesDimension: 'sorting + light production',
    },
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr07',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt không có /v/ kiểu Anh (môi-răng rung) — hay thành /b/ hoặc /w/.',
    capabilities: ['perceive-vb'],
    title: 'V vs B',
    titleVi: 'V vs B',
    task: 'Distinguish /v/ from /b/ and /p/',
    context: 'very/berry, van/ban — one lip position apart.',
    outcome: 'You can hear the buzzing /v/ vs the pop of /b/.',
    input: {
      title: 'PR07 · V/B',
      text: [
        'very has /v/ — lower lip touches upper teeth.',
        'berry has /b/ — both lips pop open.',
        'van vs ban, vest vs best — same contrast.',
        'Vietnamese has no /v/ — it often becomes /b/.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: '/v/: môi dưới chạm răng trên, rung nhẹ. /b/: hai môi khép rồi bật. Người Việt hay nói /v/ thành /b/.',
    },
    targets: [
      target({
        id: 'pr07.t1',
        kind: 'pronunciation',
        chunk: 'very',
        cueVi: 'rất — /v/',
        sourceSentence: 'very has /v/ — lower lip touches upper teeth.',
        productionPattern: '<very / van / vest> → /v/.',
        transferContext: 'hearing degree words',
        pronunciationNote: 'lip-teeth buzz — /v/',
      }),
      target({
        id: 'pr07.t2',
        kind: 'pronunciation',
        chunk: 'berry',
        cueVi: 'quả mọng — /b/',
        sourceSentence: 'berry has /b/ — both lips pop open.',
        productionPattern: '<berry / ban / best> → /b/.',
        transferContext: 'hearing food words',
        pronunciationNote: 'both lips pop — /b/',
      }),
      target({
        id: 'pr07.t3',
        kind: 'pronunciation',
        chunk: 'van',
        cueVi: 'xe tải nhỏ — /v/',
        sourceSentence: 'van vs ban, vest vs best — same contrast.',
        productionPattern: '<van / vote / vine> → /v/.',
        transferContext: 'hearing vehicle words',
        pronunciationNote: '/v/ — soft buzz',
      }),
      target({
        id: 'pr07.t4',
        kind: 'pronunciation',
        chunk: 'ban',
        cueVi: 'cấm — /b/',
        sourceSentence: 'van vs ban, vest vs best — same contrast.',
        productionPattern: '<ban / boat / buy> → /b/.',
        transferContext: 'hearing rule words',
        pronunciationNote: '/b/ — sudden pop',
      }),
      target({
        id: 'pr07.t5',
        kind: 'pronunciation',
        chunk: 'vest',
        cueVi: 'áo ghi lê — /v/',
        sourceSentence: 'van vs ban, vest vs best — same contrast.',
        productionPattern: '<vest / voice / move> → /v/.',
        transferContext: 'hearing clothing words',
        pronunciationNote: '/v/',
      }),
      target({
        id: 'pr07.t6',
        kind: 'pronunciation',
        chunk: 'best',
        cueVi: 'tốt nhất — /b/',
        sourceSentence: 'van vs ban, vest vs best — same contrast.',
        productionPattern: '<best / big / book> → /b/.',
        transferContext: 'hearing superlatives',
        pronunciationNote: '/b/',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Sort 8 words by ear into /v/ vs /b/ — flag any you could not tell apart.',
      promptVi: 'Phân loại 8 từ theo tai thành /v/ vs /b/ — đánh dấu từ không phân biệt được.',
      changesDimension: 'sorting + uncertainty flagging',
    },
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
  spec({
    id: 'pr08',
    level: 'a2',
    track: 'pronunciation',
    contrastVi: 'Tiếng Việt không có cụm phụ âm cuối — hay nuốt âm hoặc thêm nguyên âm vào cuối.',
    capabilities: ['perceive-clusters'],
    title: 'Clusters at the end',
    titleVi: 'Cụm phụ âm đuôi',
    task: 'Perceive final clusters that Vietnamese drops',
    context: 'words like "test", "hand", "work" end in two sounds.',
    outcome: 'You can hear both consonants in -st, -nd, -rk.',
    input: {
      title: 'PR08 · Final clusters',
      text: [
        'test ends in /st/ — two sounds, one beat.',
        'hand ends in /nd/ — nose air then stop.',
        'work ends in /rk/ — the r colors the vowel.',
        'Vietnamese drops the second consonant by habit.',
        'Practice: test, hand, work, help, last.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Người Việt hay nuốt phụ âm đuôi thứ hai ("tes" thay "test"). Nghe cả hai âm trong một nhịp.',
    },
    targets: [
      target({
        id: 'pr08.t1',
        kind: 'pronunciation',
        chunk: 'test',
        cueVi: 'bài kiểm tra — /st/',
        sourceSentence: 'test ends in /st/ — two sounds, one beat.',
        productionPattern: '<test / last / best> → /st/.',
        transferContext: 'hearing exam words',
        pronunciationNote: 'both /s/ and /t/ survive',
      }),
      target({
        id: 'pr08.t2',
        kind: 'pronunciation',
        chunk: 'hand',
        cueVi: 'bàn tay — /nd/',
        sourceSentence: 'hand ends in /nd/ — nose air then stop.',
        productionPattern: '<hand / find / friend> → /nd/.',
        transferContext: 'hearing body words',
        pronunciationNote: 'nasal + stop /nd/',
      }),
      target({
        id: 'pr08.t3',
        kind: 'pronunciation',
        chunk: 'work',
        cueVi: 'công việc — /rk/',
        sourceSentence: 'work ends in /rk/ — the r colors the vowel.',
        productionPattern: '<work / park / mark> → /rk/.',
        transferContext: 'hearing job words',
        pronunciationNote: 'r-colored vowel + /k/',
      }),
      target({
        id: 'pr08.t4',
        kind: 'pronunciation',
        chunk: 'help',
        cueVi: 'giúp — /lp/',
        sourceSentence: 'Practice: test, hand, work, help, last.',
        productionPattern: '<help / milk / shelf> → /lp lk lf/.',
        transferContext: 'hearing request words',
        pronunciationNote: '/lp/ — tongue stays for l',
      }),
      target({
        id: 'pr08.t5',
        kind: 'pronunciation',
        chunk: 'last',
        cueVi: 'cuối cùng — /st/',
        sourceSentence: 'Practice: test, hand, work, help, last.',
        productionPattern: '<last / most / past> → /st/.',
        transferContext: 'hearing sequence words',
        pronunciationNote: '/st/ cluster',
      }),
    ],
    supportLadder: LADDER_LISTEN,
    reviewVariants: VARIANTS_LISTEN,
    transferTask: {
      prompt: 'Dictate 6 cluster-ending words from a clip — write every final consonant.',
      promptVi: 'Chính tả 6 từ đuôi cụm từ clip — viết đủ mọi phụ âm cuối.',
      changesDimension: 'dictation + full-final output',
    },
    recyclingFrom: ['li05', 'li14'],
    sourceRefs: [...SRC.phonetic],
    researchRefs: [...RES.pronunciation],
  }),
];
