/* Review rv01–rv08 — consolidation lessons that recycle earlier chunks in
 * changed contexts (spaced reuse, per the recycling strand). */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const REVIEW: LessonSpec[] = [
  spec({
    id: 'rv01',
    level: 'a1',
    track: 'review',
    capabilities: ['greet-leave', 'introduce-self', 'small-talk'],
    title: 'Review: meeting someone new',
    titleVi: 'Ôn tập: gặp người mới',
    task: 'Run a full first-meeting exchange from memory',
    context: 'A new neighbor knocks on your door to say hi.',
    outcome: 'You can chain greeting → intro → small talk → close.',
    input: {
      title: 'RV01 · New neighbor',
      text: [
        'Neighbor: Hi! I am Dana — just moved in next door.',
        'You: Good morning, Dana. I am Anh. Nice to meet you.',
        'Neighbor: Nice to meet you too. Are you from here?',
        'You: I am from Da Nang, actually. And you?',
        'Neighbor: I am from Hue. Well, see you around!',
        'You: You too — welcome to the building.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Chuỗi full: greeting → tự giới thiệu → hỏi quê quán → kết thúc. Tái dùng chunks từ sv01-sv03.',
    },
    targets: [
      target({
        id: 'rv01.t1',
        chunk: 'just moved in next door',
        cueVi: 'vừa chuyển đến nhà kế bên',
        sourceSentence: 'Neighbor: Hi! I am Dana — just moved in next door.',
        productionPattern: 'just moved in <next door / upstairs>.',
        transferContext: 'introducing yourself to a new flatmate',
      }),
      target({
        id: 'rv01.t2',
        chunk: 'Are you from here',
        cueVi: 'bạn là người đây à',
        sourceSentence: 'Neighbor: Nice to meet you too. Are you from here?',
        productionPattern: 'Are you from <here / this city>?',
        transferContext: 'asking about origin more casually',
      }),
      target({
        id: 'rv01.t3',
        chunk: 'I am from Da Nang, actually',
        cueVi: 'tôi đến từ Đà Nẵng',
        sourceSentence: 'You: I am from Da Nang, actually. And you?',
        productionPattern: 'I am from <Da Nang / Hue>, actually.',
        transferContext: 'correcting an assumption about origin',
      }),
      target({
        id: 'rv01.t4',
        chunk: 'welcome to the building',
        cueVi: 'chào mừng đến tòa nhà',
        sourceSentence: 'You: You too — welcome to the building.',
        productionPattern: 'welcome to <the building / the team / the city>.',
        transferContext: 'welcoming a new colleague',
      }),
    ],
    transferTask: {
      prompt: "Role-play a different first meeting — a coworker's first day — greeting to close.",
      promptVi: 'Đóng vai một cuộc gặp đầu khác — ngày đầu của đồng nghiệp — chào đến kết.',
      changesDimension: 'workplace first-day + whole arc',
    },
    recyclingFrom: ['sv01', 'sv02', 'sv03', 'sv19', 'ch16'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.transfer],
  }),
  spec({
    id: 'rv02',
    level: 'a1',
    track: 'review',
    capabilities: ['ask-repetition', 'clarify-meaning', 'check-understanding'],
    title: 'Review: getting clarity',
    titleVi: 'Ôn tập: hỏi cho rõ',
    task: 'Combine every clarification move in one exchange',
    context: 'Instructions come too fast at a new gym.',
    outcome: 'You can stack clarify moves until you understand.',
    input: {
      title: 'RV02 · Too fast',
      text: [
        'Staff: Grab a towel, scan your band, the lockers are through there.',
        'You: Sorry, could you say that again? It was a bit fast.',
        'Staff: Sure — towel first, then scan your band.',
        'You: So I scan it after the towel — is that right?',
        'Staff: Exactly. Lockers are behind the desk.',
        'You: Got it. Thank you for explaining.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Chồng các đòn làm rõ: say that again → So you mean/is that right → Got it + thanks.',
    },
    targets: [
      target({
        id: 'rv02.t1',
        chunk: 'Grab a towel',
        cueVi: 'lấy khăn trước',
        sourceSentence: 'Staff: Grab a towel, scan your band, the lockers are through there.',
        productionPattern: 'Grab a <towel / seat / card>.',
        transferContext: 'hearing quick instructions',
      }),
      target({
        id: 'rv02.t2',
        chunk: 'scan your band',
        cueVi: 'quét vòng tay',
        sourceSentence: 'Staff: Grab a towel, scan your band, the lockers are through there.',
        productionPattern: 'scan your <band / card / phone>.',
        transferContext: 'hearing entry instructions',
      }),
      target({
        id: 'rv02.t3',
        chunk: 'a bit fast',
        cueVi: 'hơi nhanh',
        sourceSentence: 'You: Sorry, could you say that again? It was a bit fast.',
        productionPattern: 'a bit <fast / unclear / loud>.',
        transferContext: 'asking for slower speech',
      }),
      target({
        id: 'rv02.t4',
        chunk: 'So I scan it after',
        cueVi: 'vậy là tôi quét sau đó',
        sourceSentence: 'You: So I scan it after the towel — is that right?',
        productionPattern: 'So I <scan it / do X> after <the towel>?',
        transferContext: 'paraphrasing a sequence',
      }),
      target({
        id: 'rv02.t5',
        chunk: 'behind the desk',
        cueVi: 'sau quầy',
        sourceSentence: 'Staff: Exactly. Lockers are behind the desk.',
        productionPattern: 'behind the <desk / counter / door>.',
        transferContext: 'locating a facility',
      }),
    ],
    transferTask: {
      prompt: 'Clarify different fast instructions — metro ticket machine — repeat, paraphrase, confirm.',
      promptVi: 'Làm rõ hướng dẫn nhanh khác — máy bán vé metro — lặp lại, diễn giải, xác nhận.',
      changesDimension: 'different venue + same clarify-stack',
    },
    recyclingFrom: ['sv06', 'sv07', 'ch15'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.transfer],
  }),
  spec({
    id: 'rv03',
    level: 'a2',
    track: 'review',
    capabilities: ['ask-price', 'shop-return', 'describe-problem'],
    title: 'Review: shopping problems',
    titleVi: 'Ôn tập: mua sắm gặp vấn đề',
    task: 'Handle a full shopping problem from entry to refund',
    context: 'Returning a broken item at a busy shop.',
    outcome: 'You can run problem → request → solution arc.',
    input: {
      title: 'RV03 · Broken fan',
      text: [
        'You: Excuse me, I bought this fan yesterday and it is not working.',
        'Clerk: Do you have the receipt?',
        'You: Yes, here it is. The motor makes a rattling noise.',
        'Clerk: Would you like a replacement or a refund?',
        'You: A refund, please — I will buy a different model.',
        'Clerk: No problem. It goes back to your card in three days.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Full arc: state problem → show receipt → describe fault → choose refund → confirm timeline.',
    },
    targets: [
      target({
        id: 'rv03.t1',
        chunk: 'it is not working',
        cueVi: 'nó không hoạt động',
        sourceSentence: 'You: Excuse me, I bought this fan yesterday and it is not working.',
        productionPattern: 'it is not <working / charging>.',
        transferContext: 'reporting a dead device',
      }),
      target({
        id: 'rv03.t2',
        chunk: 'the receipt',
        cueVi: 'hóa đơn',
        sourceSentence: 'Clerk: Do you have the receipt?',
        productionPattern: 'the <receipt / box / warranty>.',
        transferContext: 'being asked for proof of purchase',
      }),
      target({
        id: 'rv03.t3',
        chunk: 'a rattling noise',
        cueVi: 'tiếng kêu lạch cạch',
        sourceSentence: 'You: Yes, here it is. The motor makes a rattling noise.',
        productionPattern: 'a <rattling / buzzing / strange> noise.',
        transferContext: 'describing a device fault',
      }),
      target({
        id: 'rv03.t4',
        chunk: 'a replacement or a refund',
        cueVi: 'đổi mới hay hoàn tiền',
        sourceSentence: 'Clerk: Would you like a replacement or a refund?',
        productionPattern: 'a <replacement / refund / repair>.',
        transferContext: 'choosing between remedy options',
      }),
      target({
        id: 'rv03.t5',
        chunk: 'a different model',
        cueVi: 'mẫu khác',
        sourceSentence: 'You: A refund, please — I will buy a different model.',
        productionPattern: 'a different <model / size / brand>.',
        transferContext: 'switching to another product',
      }),
      target({
        id: 'rv03.t6',
        chunk: 'goes back to your card',
        cueVi: 'hoàn về thẻ',
        sourceSentence: 'Clerk: No problem. It goes back to your card in three days.',
        productionPattern: 'goes back to your <card / account>.',
        transferContext: 'confirming refund destination',
      }),
    ],
    transferTask: {
      prompt: 'Handle a different return — a shirt with a hole — full arc including receipt and choice.',
      promptVi: 'Xử lý đổi trả khác — áo bị thủng — toàn arc gồm hóa đơn và lựa chọn.',
      changesDimension: 'different defect + same return arc',
    },
    recyclingFrom: ['sv23', 'ev06', 'ev21'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.transfer],
  }),
  spec({
    id: 'rv04',
    level: 'a2',
    track: 'review',
    capabilities: ['make-plans', 'invite-respond', 'close-conversation'],
    title: 'Review: planning with a friend',
    titleVi: 'Ôn tập: lên kế hoạch với bạn',
    task: 'Plan a full outing — invite, negotiate, confirm, close',
    context: 'Organizing a Saturday hike by messages.',
    outcome: 'You can run invite → negotiate → confirm → close.',
    input: {
      title: 'RV04 · Hike plan',
      text: [
        'You: Want to do something Saturday? Maybe a hike.',
        'Linh: I would love to! How about the trail near the lake?',
        'You: Perfect. Let us meet at eight — it gets hot later.',
        'Linh: Eight works. Should I bring anything?',
        'You: Just water. I will pack snacks.',
        'Linh: Deal. See you Saturday at eight.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Chuỗi plan: invite → accept → time → what to bring → confirm. Tái dùng từ sv24, ev03, ev16.',
    },
    targets: [
      target({
        id: 'rv04.t1',
        chunk: 'Maybe a hike',
        cueVi: 'có thể đi leo núi',
        sourceSentence: 'You: Want to do something Saturday? Maybe a hike.',
        productionPattern: 'Maybe a <hike / movie / picnic>.',
        transferContext: 'suggesting a different activity',
      }),
      target({
        id: 'rv04.t2',
        chunk: 'the trail near the lake',
        cueVi: 'đường mòn gần hồ',
        sourceSentence: 'Linh: I would love to! How about the trail near the lake?',
        productionPattern: 'the <trail / park / beach> near the lake.',
        transferContext: 'suggesting a location',
      }),
      target({
        id: 'rv04.t3',
        chunk: 'it gets hot later',
        cueVi: 'trời nóng dần',
        sourceSentence: 'You: Perfect. Let us meet at eight — it gets hot later.',
        productionPattern: 'it gets <hot / crowded / busy> later.',
        transferContext: 'justifying an early start',
      }),
      target({
        id: 'rv04.t4',
        chunk: 'Eight works',
        cueVi: 'tám giờ được',
        sourceSentence: 'Linh: Eight works. Should I bring anything?',
        productionPattern: '<Eight / That> works.',
        transferContext: 'confirming a time',
      }),
      target({
        id: 'rv04.t5',
        chunk: 'Just water',
        cueVi: 'chỉ cần nước thôi',
        sourceSentence: 'You: Just water. I will pack snacks.',
        productionPattern: 'Just <water / your phone>.',
        transferContext: 'telling someone what to bring',
      }),
      target({
        id: 'rv04.t6',
        chunk: 'I will pack snacks',
        cueVi: 'tôi sẽ mang đồ ăn nhẹ',
        sourceSentence: 'You: Just water. I will pack snacks.',
        productionPattern: 'I will pack <snacks / lunch / the map>.',
        transferContext: 'offering to handle supplies',
      }),
      target({
        id: 'rv04.t7',
        chunk: 'Deal',
        cueVi: 'thống nhất nhé',
        sourceSentence: 'Linh: Deal. See you Saturday at eight.',
        productionPattern: '<Deal / Done / Agreed>.',
        transferContext: 'closing a friendly agreement',
      }),
    ],
    transferTask: {
      prompt: 'Plan a different outing — a beach day — full arc from invite to confirm.',
      promptVi: 'Lên một chuyến khác — ngày biển — toàn arc từ mời đến chốt.',
      changesDimension: 'beach activity + same planning arc',
    },
    recyclingFrom: ['sv24', 'ev03', 'ev16', 'ev24'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.transfer],
  }),
  spec({
    id: 'rv05',
    level: 'a2',
    track: 'review',
    capabilities: ['narrate-past', 'tell-story', 'give-reason'],
    title: 'Review: tell a full story',
    titleVi: 'Ôn tập: kể một câu chuyện',
    task: 'Tell a complete anecdote with sequencing and a point',
    context: 'Sharing a travel mishap with friends.',
    outcome: 'You can build a story arc: setup → events → resolution.',
    input: {
      title: 'RV05 · Lost wallet',
      text: [
        'You: So this happened last month. I was in Hanoi for a work trip.',
        'You: First, I lost my wallet at the airport. Then my phone died.',
        'You: In the end, a taxi driver helped me — he drove me to the embassy.',
        'Mai: What did you do about money?',
        'You: The thing is, I had a backup card in my bag the whole time.',
        'Mai: You know what? That is a lucky story after all.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Story arc: setup → first/then → in the end → twist → comment. Tái dùng từ ch03, ch10, ch14.',
    },
    targets: [
      target({
        id: 'rv05.t1',
        chunk: 'this happened last month',
        cueVi: 'chuyện này xảy ra tháng trước',
        sourceSentence: 'You: So this happened last month. I was in Hanoi for a work trip.',
        productionPattern: 'this happened <last month / last year>.',
        transferContext: 'opening a personal anecdote',
      }),
      target({
        id: 'rv05.t2',
        chunk: 'a work trip',
        cueVi: 'chuyến công tác',
        sourceSentence: 'You: So this happened last month. I was in Hanoi for a work trip.',
        productionPattern: 'a <work / business> trip.',
        transferContext: 'setting a story context',
      }),
      target({
        id: 'rv05.t3',
        chunk: 'I lost my wallet',
        cueVi: 'tôi mất ví',
        sourceSentence: 'You: First, I lost my wallet at the airport. Then my phone died.',
        productionPattern: 'I lost my <wallet / passport / ticket>.',
        transferContext: 'narrating a mishap',
      }),
      target({
        id: 'rv05.t4',
        chunk: 'my phone died',
        cueVi: 'điện thoại hết pin',
        sourceSentence: 'You: First, I lost my wallet at the airport. Then my phone died.',
        productionPattern: 'my <phone / battery> died.',
        transferContext: 'stacking a second problem',
      }),
      target({
        id: 'rv05.t5',
        chunk: 'a taxi driver helped me',
        cueVi: 'một tài xế đã giúp tôi',
        sourceSentence: 'You: In the end, a taxi driver helped me — he drove me to the embassy.',
        productionPattern: 'a <taxi driver / stranger> helped me.',
        transferContext: 'crediting an unexpected helper',
      }),
      target({
        id: 'rv05.t6',
        chunk: 'drove me to the embassy',
        cueVi: 'chở tôi đến đại sứ quán',
        sourceSentence: 'You: In the end, a taxi driver helped me — he drove me to the embassy.',
        productionPattern: 'drove me to <the embassy / the hotel>.',
        transferContext: 'describing a rescue ride',
      }),
      target({
        id: 'rv05.t7',
        chunk: 'a backup card',
        cueVi: 'thẻ dự phòng',
        sourceSentence: 'You: The thing is, I had a backup card in my bag the whole time.',
        productionPattern: 'a <backup card / spare key>.',
        transferContext: 'revealing a hidden safety net',
      }),
      target({
        id: 'rv05.t8',
        chunk: 'the whole time',
        cueVi: 'suốt từ đầu',
        sourceSentence: 'You: The thing is, I had a backup card in my bag the whole time.',
        productionPattern: 'the <whole time / whole day>.',
        transferContext: 'emphasizing duration',
      }),
    ],
    transferTask: {
      prompt: 'Tell a different mishap story — missed train — setup, sequence, rescue, twist.',
      promptVi: 'Kể chuyện rủi khác — lỡ tàu — setup, chuỗi, giải cứu, twist.',
      changesDimension: 'different mishap + full arc',
    },
    recyclingFrom: ['ch03', 'ch10', 'ch14', 'ev04', 'sv21'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.transfer],
  }),
  spec({
    id: 'rv06',
    level: 'a2',
    track: 'review',
    capabilities: ['status-update', 'report-bug', 'ask-help'],
    title: 'Review: a work problem',
    titleVi: 'Ôn tập: vấn đề công việc',
    task: 'Handle a work problem end-to-end: report, discuss, get help',
    context: 'A feature broke after a deploy and you need help.',
    outcome: 'You can chain report → discuss → escalate-help.',
    input: {
      title: 'RV06 · Broken feature',
      text: [
        "You: Heads-up — the export feature broke after yesterday's deploy.",
        'Lead: What is the impact?',
        'You: Users get empty files instead of the report. About a dozen tickets.',
        'Lead: Do you have a fix in mind?',
        'You: I think I know the cause — can you take a quick look at my patch?',
        'Lead: Send it over. Good catch flagging it early.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Work problem arc: heads-up → impact → cause guess → ask for eyes → thanks. Tái dùng dv01-06.',
    },
    targets: [
      target({
        id: 'rv06.t1',
        chunk: "broke after yesterday's deploy",
        cueVi: 'hỏng sau deploy hôm qua',
        sourceSentence: "You: Heads-up — the export feature broke after yesterday's deploy.",
        productionPattern: "broke after <yesterday's deploy / the update>.",
        transferContext: 'linking a failure to a release',
      }),
      target({
        id: 'rv06.t2',
        chunk: 'What is the impact',
        cueVi: 'ảnh hưởng là gì',
        sourceSentence: 'Lead: What is the impact?',
        productionPattern: 'What is the <impact / scope>?',
        transferContext: 'asking about blast radius',
      }),
      target({
        id: 'rv06.t3',
        chunk: 'empty files',
        cueVi: 'file rỗng',
        sourceSentence: 'You: Users get empty files instead of the report. About a dozen tickets.',
        productionPattern: 'empty <files / responses / pages>.',
        transferContext: 'describing a data failure',
      }),
      target({
        id: 'rv06.t4',
        chunk: 'instead of the report',
        cueVi: 'thay vì báo cáo',
        sourceSentence: 'You: Users get empty files instead of the report. About a dozen tickets.',
        productionPattern: 'instead of <the report / the data>.',
        transferContext: 'contrasting expected vs actual',
      }),
      target({
        id: 'rv06.t5',
        chunk: 'a dozen tickets',
        cueVi: 'tầm chục ticket',
        sourceSentence: 'You: Users get empty files instead of the report. About a dozen tickets.',
        productionPattern: 'a <dozen / hundred> tickets.',
        transferContext: 'quantifying user complaints',
      }),
      target({
        id: 'rv06.t6',
        chunk: 'a fix in mind',
        cueVi: 'có hướng sửa chưa',
        sourceSentence: 'Lead: Do you have a fix in mind?',
        productionPattern: 'a <fix / plan> in mind.',
        transferContext: 'asking if there is a proposed solution',
      }),
      target({
        id: 'rv06.t7',
        chunk: 'my patch',
        cueVi: 'bản vá của tôi',
        sourceSentence: 'You: I think I know the cause — can you take a quick look at my patch?',
        productionPattern: 'my <patch / fix / change>.',
        transferContext: 'asking for review on a fix',
      }),
      target({
        id: 'rv06.t8',
        chunk: 'Send it over',
        cueVi: 'gửi qua đây',
        sourceSentence: 'Lead: Send it over. Good catch flagging it early.',
        productionPattern: 'Send it <over / my way>.',
        transferContext: 'requesting the artifact',
      }),
    ],
    transferTask: {
      prompt: 'Handle a different work problem — a missing feature flag — report, impact, ask for help.',
      promptVi: 'Xử lý vấn đề công việc khác — feature flag bị thiếu — báo, impact, xin giúp.',
      changesDimension: 'config issue not code bug + same arc',
    },
    recyclingFrom: ['dv01', 'dv04', 'dv06', 'dv16', 'dv21'],
    sourceRefs: [...SRC.dev],
    researchRefs: [...RES.dev],
  }),
  spec({
    id: 'rv07',
    level: 'a2',
    track: 'review',
    capabilities: ['hedge-statement', 'disagree-politely', 'express-opinion'],
    title: 'Review: polite disagreement',
    titleVi: 'Ôn tập: bất đồng lịch sự',
    task: 'Disagree about a plan using hedges and partial agreement',
    context: 'Friends want to go to a restaurant you did not like.',
    outcome: 'You can push back warmly with an alternative.',
    input: {
      title: 'RV07 · Not that place',
      text: [
        'Tom: Let us go back to that noodle place Friday.',
        'You: I see the appeal, but honestly, I thought it was just okay.',
        'Tom: Really? I loved it.',
        'You: The noodles were great, I agree. The service was slow though.',
        'Tom: Fair enough. What do you suggest?',
        'You: How about that new place by the river? Same price, better reviews.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Disagree êm: I see the appeal → partial agree → specific critique → counter-offer.',
    },
    targets: [
      target({
        id: 'rv07.t1',
        chunk: 'Let us go back to',
        cueVi: 'quay lại chỗ đó đi',
        sourceSentence: 'Tom: Let us go back to that noodle place Friday.',
        productionPattern: 'go back to <that place / the same spot>.',
        transferContext: 'suggesting a return visit',
      }),
      target({
        id: 'rv07.t2',
        chunk: 'I see the appeal',
        cueVi: 'tôi hiểu sức hút của nó',
        sourceSentence: 'You: I see the appeal, but honestly, I thought it was just okay.',
        productionPattern: 'I see the <appeal / point / logic>.',
        transferContext: 'acknowledging a different view',
      }),
      target({
        id: 'rv07.t3',
        chunk: 'just okay',
        cueVi: 'chỉ tạm được',
        sourceSentence: 'You: I see the appeal, but honestly, I thought it was just okay.',
        productionPattern: 'just <okay / average / so-so>.',
        transferContext: 'giving a lukewarm review',
      }),
      target({
        id: 'rv07.t4',
        chunk: 'The noodles were great',
        cueVi: 'mì thì ngon',
        sourceSentence: 'You: The noodles were great, I agree. The service was slow though.',
        productionPattern: 'The <noodles / view / price> was great.',
        transferContext: 'conceding a positive point',
      }),
      target({
        id: 'rv07.t5',
        chunk: 'The service was slow though',
        cueVi: 'nhưng phục vụ chậm',
        sourceSentence: 'You: The noodles were great, I agree. The service was slow though.',
        productionPattern: 'The <service / wait / room> was slow though.',
        transferContext: 'adding a balanced critique',
      }),
      target({
        id: 'rv07.t6',
        chunk: 'that new place by the river',
        cueVi: 'quán mới bên sông',
        sourceSentence: 'You: How about that new place by the river? Same price, better reviews.',
        productionPattern: 'that new place by <the river / the park>.',
        transferContext: 'suggesting a better alternative',
      }),
      target({
        id: 'rv07.t7',
        chunk: 'better reviews',
        cueVi: 'đánh giá tốt hơn',
        sourceSentence: 'You: How about that new place by the river? Same price, better reviews.',
        productionPattern: 'better <reviews / prices / options>.',
        transferContext: 'comparing options by a metric',
      }),
    ],
    transferTask: {
      prompt: 'Disagree about a different choice — a movie pick — hedge, concede, counter.',
      promptVi: 'Bất đồng về lựa chọn khác — phim — hedge, thừa nhận, đề xuất khác.',
      changesDimension: 'entertainment choice + same disagree arc',
    },
    recyclingFrom: ['ch07', 'ch17', 'ev17', 'ev18', 'dv12'],
    sourceRefs: [...SRC.collocations],
    researchRefs: [...RES.transfer],
  }),
  spec({
    id: 'rv08',
    level: 'a2',
    track: 'listening',
    capabilities: ['decode-boundaries', 'decode-reductions', 'place-word-stress'],
    title: 'Review: hear the real sound',
    titleVi: 'Ôn tập: nghe âm thật',
    task: 'Combine all listening skills on a fast spoken exchange',
    context: 'A quick real-world exchange — decode everything.',
    outcome: 'You can apply boundary + reduction + stress together.',
    input: {
      title: 'RV08 · Fast exchange',
      text: [
        'Hear this fast exchange, then decode each piece:',
        '"Whaddya wanna do tonight?" = What do you want to do tonight?',
        '"I dunno, maybe grab a bite?" = I do not know, maybe get food.',
        '"Gotta finish work first, then I am free." = I have got to work first.',
        'Boundaries, reductions, and stress — all at once.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-phonetic-db',
      noteVi: 'Tổng hợp nghe: boundary + gonna/wanna/dunno/gotta + stress pattern trong một đoạn thật.',
    },
    targets: [
      target({
        id: 'rv08.t1',
        chunk: 'Whaddya wanna do tonight',
        cueVi: 'tối nay muốn làm gì',
        sourceSentence: '"Whaddya wanna do tonight?" = What do you want to do tonight?',
        productionPattern: 'Whaddya wanna <do / eat / watch>?',
        transferContext: 'hearing casual evening plans',
        pronunciationNote: '"whaddya-WON-na"',
      }),
      target({
        id: 'rv08.t2',
        chunk: 'I dunno',
        cueVi: 'tôi không biết',
        sourceSentence: '"I dunno, maybe grab a bite?" = I do not know, maybe get food.',
        productionPattern: 'I <dunno / do not know>.',
        transferContext: 'hearing casual uncertainty',
        pronunciationNote: '"dun-NO"',
      }),
      target({
        id: 'rv08.t3',
        chunk: 'grab a bite',
        cueVi: 'ăn gì đó',
        sourceSentence: '"I dunno, maybe grab a bite?" = I do not know, maybe get food.',
        productionPattern: 'grab a <bite / coffee / snack>.',
        transferContext: 'suggesting casual food',
        pronunciationNote: '"grab-uh-BITE"',
      }),
      target({
        id: 'rv08.t4',
        chunk: 'Gotta finish work first',
        cueVi: 'phải xong việc trước',
        sourceSentence: '"Gotta finish work first, then I am free." = I have got to work first.',
        productionPattern: 'Gotta <finish work / run errands> first.',
        transferContext: 'hearing a condition before plans',
        pronunciationNote: '"GOD-uh"',
      }),
      target({
        id: 'rv08.t5',
        chunk: 'then I am free',
        cueVi: 'rồi tôi rảnh',
        sourceSentence: '"Gotta finish work first, then I am free." = I have got to work first.',
        productionPattern: 'then I am <free / done / ready>.',
        transferContext: 'sequencing availability',
        pronunciationNote: "then-I'm-FREE",
      }),
    ],
    supportLadder: ['context', 'audio', 'transcript', 'gloss-vi', 'full-answer'],
    reviewVariants: ['audio-to-meaning', 'meaning-to-en', 'context-to-phrase'],
    transferTask: {
      prompt: 'Decode a different fast exchange — write each line in its full form.',
      promptVi: 'Giải mã một đoạn nhanh khác — viết mỗi câu thành dạng đầy đủ.',
      changesDimension: 'new exchange + full-form expansion',
    },
    recyclingFrom: ['li01', 'li02', 'li04', 'li11', 'pr14'],
    sourceRefs: [...SRC.microskills],
    researchRefs: [...RES.listening],
  }),
];
