/* Survival English sv13–sv24 (A0–A1). */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const SURVIVAL_2: LessonSpec[] = [
  spec({
    id: 'sv13',
    level: 'a1',
    track: 'survival',
    capabilities: ['introduce-self', 'ask-personal-info'],
    title: 'Talk about your family',
    titleVi: 'Nói về gia đình',
    task: 'Say who is in your family and ask about theirs',
    context: 'A classmate shows you a family photo on their phone.',
    outcome: 'You can name close family members and counts.',
    input: {
      title: 'SV13 · Family',
      text: [
        'Hoa: Is this your family, Anh?',
        'Anh: Yes. This is my wife, Lan, and our two kids.',
        'Hoa: How old are they?',
        'Anh: My son is eight and my daughter is five.',
        'Hoa: Do you have brothers or sisters?',
        'Anh: One older brother. He lives in Hanoi.',
        'Hoa: Nice. My family is small — just me and my mom.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: 'my + quan hệ: wife/husband/son/daughter/brother/sister; "How old" hỏi tuổi.',
    },
    targets: [
      target({
        id: 'sv13.t1',
        chunk: 'my wife',
        cueVi: 'vợ tôi',
        sourceSentence: 'Anh: Yes. This is my wife, Lan, and our two kids.',
        productionPattern: 'my <wife / husband / partner>.',
        transferContext: 'introducing a partner at a party',
      }),
      target({
        id: 'sv13.t2',
        chunk: 'our two kids',
        cueVi: 'hai đứa con của chúng tôi',
        sourceSentence: 'Anh: Yes. This is my wife, Lan, and our two kids.',
        productionPattern: 'our <two / three> kids.',
        transferContext: 'describing your household to a landlord',
      }),
      target({
        id: 'sv13.t3',
        chunk: 'How old are they',
        cueVi: 'chúng bao nhiêu tuổi',
        sourceSentence: 'Hoa: How old are they?',
        productionPattern: 'How old <are they / is he / is she>?',
        transferContext: "asking about a friend's baby",
      }),
      target({
        id: 'sv13.t4',
        chunk: 'brothers or sisters',
        cueVi: 'anh chị em',
        sourceSentence: 'Hoa: Do you have brothers or sisters?',
        productionPattern: '<brothers or sisters / siblings / cousins>.',
        transferContext: 'filling in a get-to-know-you form',
      }),
      target({
        id: 'sv13.t5',
        chunk: 'older brother',
        cueVi: 'anh trai',
        sourceSentence: 'Anh: One older brother. He lives in Hanoi.',
        productionPattern: '<older / younger> <brother / sister>.',
        transferContext: 'describing siblings to a pen pal',
      }),
      target({
        id: 'sv13.t6',
        chunk: 'He lives in',
        cueVi: 'anh ấy sống ở',
        sourceSentence: 'Anh: One older brother. He lives in Hanoi.',
        productionPattern: '<He / She> lives in <city>.',
        transferContext: 'saying where your parents live',
      }),
    ],
    transferTask: {
      prompt: 'Describe your household to a new roommate: who, how many, where they live.',
      promptVi: 'Mô tả gia đình bạn cho bạn cùng phòng mới: có ai, bao nhiêu người, sống ở đâu.',
      changesDimension: 'practical purpose (roommate vetting) not photo talk',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv14',
    level: 'a0',
    track: 'survival',
    capabilities: ['schedule-appointment'],
    title: 'Days and times',
    titleVi: 'Ngày và giờ',
    task: 'Say the day and time for a simple appointment',
    context: 'Booking a dentist appointment by phone.',
    outcome: 'You can agree on a day and time in one exchange.',
    input: {
      title: 'SV14 · Appointment',
      text: [
        'Clinic: City Dental, how can I help you?',
        'Anh: I would like to make an appointment.',
        'Clinic: How about Tuesday at ten?',
        'Anh: Tuesday is difficult. Do you have Wednesday?',
        'Clinic: Yes, Wednesday at two thirty.',
        'Anh: That works for me. Thank you.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"How about + giờ/ngày" đề xuất; "That works" = ổn, chốt lịch.',
    },
    targets: [
      target({
        id: 'sv14.t1',
        chunk: 'make an appointment',
        cueVi: 'đặt lịch hẹn',
        sourceSentence: 'Anh: I would like to make an appointment.',
        productionPattern: 'make an appointment for <a checkup / a haircut>.',
        transferContext: 'booking a haircut by phone',
      }),
      target({
        id: 'sv14.t2',
        chunk: 'How about',
        cueVi: 'thế còn ~ thì sao (đề xuất)',
        sourceSentence: 'Clinic: How about Tuesday at ten?',
        productionPattern: 'How about <Tuesday at ten / next week>?',
        transferContext: 'suggesting a lunch day to a friend',
      }),
      target({
        id: 'sv14.t3',
        chunk: 'is difficult',
        cueVi: 'ngày đó khó (bận)',
        sourceSentence: 'Anh: Tuesday is difficult. Do you have Wednesday?',
        productionPattern: '<Tuesday / Morning> is difficult.',
        transferContext: 'declining a proposed meeting day',
      }),
      target({
        id: 'sv14.t4',
        chunk: 'Do you have Wednesday',
        cueVi: 'thứ tư có trống không',
        sourceSentence: 'Anh: Tuesday is difficult. Do you have Wednesday?',
        productionPattern: 'Do you have <Wednesday / anything Friday>?',
        transferContext: 'asking for a different class slot',
      }),
      target({
        id: 'sv14.t5',
        chunk: 'That works for me',
        cueVi: 'vậy được với tôi',
        sourceSentence: 'Anh: That works for me. Thank you.',
        productionPattern: 'That <works / is fine> for me.',
        transferContext: 'confirming a rescheduled interview',
      }),
    ],
    transferTask: {
      prompt: 'Reschedule a gym session — decline the first slot and confirm a new day/time.',
      promptVi: 'Đổi lịch tập gym — từ chối khung giờ đầu và chốt ngày giờ mới.',
      changesDimension: 'reschedule (not first booking) + you must decline first',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv15',
    level: 'a0',
    track: 'survival',
    capabilities: ['ask-price'],
    title: 'Ask and understand prices',
    titleVi: 'Hỏi và hiểu giá',
    task: 'Ask a price and confirm the total before paying',
    context: 'Buying a snack and a drink at a convenience store.',
    outcome: 'You can ask prices, hear the total, and pay correctly.',
    input: {
      title: 'SV15 · At the till',
      text: [
        'Anh: How much is the water?',
        'Cashier: It is ten thousand.',
        'Anh: And the sandwich?',
        'Cashier: Twenty-five thousand.',
        'Anh: How much is that altogether?',
        'Cashier: Thirty-five thousand, please.',
        'Anh: Here you are.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"How much is X" từng món; "altogether" hỏi tổng; "Here you are" khi đưa tiền.',
    },
    targets: [
      target({
        id: 'sv15.t1',
        chunk: 'How much is the water',
        cueVi: 'nước bao nhiêu tiền',
        sourceSentence: 'Anh: How much is the water?',
        productionPattern: 'How much is <the water / this shirt>?',
        transferContext: 'asking for a menu item price',
      }),
      target({
        id: 'sv15.t2',
        chunk: 'It is ten thousand',
        cueVi: 'mười nghìn',
        sourceSentence: 'Cashier: It is ten thousand.',
        productionPattern: 'It is <ten / twenty-five> thousand.',
        transferContext: 'stating a taxi fare',
      }),
      target({
        id: 'sv15.t3',
        chunk: 'And the sandwich',
        cueVi: 'còn cái sandwich thì sao',
        sourceSentence: 'Anh: And the sandwich?',
        productionPattern: 'And <the sandwich / this one>?',
        transferContext: 'adding an item to a price check',
      }),
      target({
        id: 'sv15.t4',
        chunk: 'altogether',
        cueVi: 'tổng cộng',
        sourceSentence: 'Anh: How much is that altogether?',
        productionPattern: 'How much is that <altogether / in total>?',
        transferContext: 'confirming a bill at a restaurant',
      }),
      target({
        id: 'sv15.t5',
        chunk: 'Here you are',
        cueVi: 'đây ạ (đưa tiền)',
        sourceSentence: 'Anh: Here you are.',
        productionPattern: 'Here <you are / it is>.',
        transferContext: 'handing documents to an officer',
      }),
    ],
    transferTask: {
      prompt: 'At a pharmacy, ask the price of two items and the total — then pay.',
      promptVi: 'Ở hiệu thuốc, hỏi giá hai món và tổng tiền — rồi trả tiền.',
      changesDimension: 'different store + item types',
    },
    recyclingFrom: ['sv11'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv16',
    level: 'a0',
    track: 'survival',
    capabilities: ['order-food'],
    title: 'Order food and drink',
    titleVi: 'Gọi đồ ăn thức uống',
    task: 'Order a simple meal at a counter',
    context: 'A quick lunch order at a sandwich shop.',
    outcome: 'You can order, choose size, and finish the transaction.',
    input: {
      title: 'SV16 · Ordering',
      text: [
        'Staff: Hi, what can I get you?',
        'Anh: Can I have a chicken sandwich, please?',
        'Staff: Anything to drink?',
        'Anh: An iced tea, please. Small.',
        'Staff: For here or to go?',
        'Anh: To go, please.',
        'Staff: That will be sixty thousand.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: '"Can I have" gọi món; "for here or to go" hỏi ăn tại chỗ hay mang đi.',
    },
    targets: [
      target({
        id: 'sv16.t1',
        chunk: 'what can I get you',
        cueVi: 'bạn muốn gọi gì',
        sourceSentence: 'Staff: Hi, what can I get you?',
        productionPattern: 'What can I get <you / for you>?',
        transferContext: 'serving a friend at your home',
      }),
      target({
        id: 'sv16.t2',
        chunk: 'Can I have',
        cueVi: 'cho tôi',
        sourceSentence: 'Anh: Can I have a chicken sandwich, please?',
        productionPattern: 'Can I have <a sandwich / some water>?',
        transferContext: 'ordering at a coffee chain',
      }),
      target({
        id: 'sv16.t3',
        chunk: 'Anything to drink',
        cueVi: 'có uống gì không',
        sourceSentence: 'Staff: Anything to drink?',
        productionPattern: 'Anything <to drink / else>?',
        transferContext: 'asking a table guest',
      }),
      target({
        id: 'sv16.t4',
        chunk: 'for here or to go',
        cueVi: 'dùng tại chỗ hay mang đi',
        sourceSentence: 'Staff: For here or to go?',
        productionPattern: 'For here or <to go / takeaway>?',
        transferContext: 'hearing the question at a fast-food counter',
      }),
      target({
        id: 'sv16.t5',
        chunk: 'To go, please',
        cueVi: 'mang đi',
        sourceSentence: 'Anh: To go, please.',
        productionPattern: '<To go / For here>, please.',
        transferContext: 'ordering takeaway coffee',
      }),
      target({
        id: 'sv16.t6',
        chunk: 'That will be',
        cueVi: 'tổng sẽ là',
        sourceSentence: 'Staff: That will be sixty thousand.',
        productionPattern: 'That will be <price>.',
        transferContext: 'hearing the total at a bakery',
      }),
    ],
    transferTask: {
      prompt: 'Order a different meal for a colleague who is not there — item, drink, takeaway.',
      promptVi: 'Gọi một phần khác cho đồng nghiệp vắng mặt — món chính, đồ uống, mang đi.',
      changesDimension: 'ordering for someone else + takeaway context',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv17',
    level: 'a0',
    track: 'survival',
    capabilities: ['ask-directions'],
    title: 'Ask where a place is',
    titleVi: 'Hỏi đường đến một nơi',
    task: 'Ask where a nearby place is and understand the answer',
    context: 'You need a restroom inside a shopping mall.',
    outcome: 'You can ask "Where is the…" and follow short directions.',
    input: {
      title: 'SV17 · Where is it',
      text: [
        'Anh: Excuse me, where is the restroom?',
        'Guard: It is on the second floor, next to the elevator.',
        'Anh: Second floor, next to the elevator?',
        'Guard: Yes. Go up the escalator and turn left.',
        'Anh: Thank you.',
        'Guard: You are welcome.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: '"where is the X" hỏi vị trí; nghe chỉ dẫn: floor + next to + turn.',
    },
    targets: [
      target({
        id: 'sv17.t1',
        chunk: 'where is the restroom',
        cueVi: 'nhà vệ sinh ở đâu',
        sourceSentence: 'Anh: Excuse me, where is the restroom?',
        productionPattern: 'where is the <restroom / exit / counter>?',
        transferContext: 'finding a gate at an airport',
      }),
      target({
        id: 'sv17.t2',
        chunk: 'on the second floor',
        cueVi: 'ở tầng hai',
        sourceSentence: 'Guard: It is on the second floor, next to the elevator.',
        productionPattern: 'on the <second / third> floor.',
        transferContext: 'locating a department in a store',
      }),
      target({
        id: 'sv17.t3',
        chunk: 'next to',
        cueVi: 'ngay cạnh',
        sourceSentence: 'Guard: It is on the second floor, next to the elevator.',
        productionPattern: 'next to <the elevator / the bank>.',
        transferContext: 'describing where a shop sits',
      }),
      target({
        id: 'sv17.t4',
        chunk: 'turn left',
        cueVi: 'rẽ trái',
        sourceSentence: 'Guard: Yes. Go up the escalator and turn left.',
        productionPattern: 'turn <left / right> at the corner.',
        transferContext: 'guiding a friend to your house',
      }),
      target({
        id: 'sv17.t5',
        chunk: 'Go up',
        cueVi: 'đi lên',
        sourceSentence: 'Guard: Yes. Go up the escalator and turn left.',
        productionPattern: 'Go <up / down / straight>.',
        transferContext: 'directing someone in a station',
      }),
    ],
    transferTask: {
      prompt: 'Ask a stranger for the nearest ATM and repeat the directions back to check.',
      promptVi: 'Hỏi người lạ cây ATM gần nhất và lặp lại chỉ dẫn để kiểm tra.',
      changesDimension: 'outdoor landmark + you verify by repeating',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv18',
    level: 'a0',
    track: 'survival',
    capabilities: ['ask-yesno', 'express-preference'],
    title: 'Short answers yes and no',
    titleVi: 'Trả lời ngắn có/không',
    task: 'Answer yes/no questions with short natural replies',
    context: 'A host offers you things at a homestay.',
    outcome: 'You can accept and decline with short polite forms.',
    input: {
      title: 'SV18 · Short answers',
      text: [
        'Host: Would you like some tea?',
        'Anh: Yes, please.',
        'Host: Do you take sugar?',
        'Anh: No, thank you.',
        'Host: Are you hungry?',
        'Anh: A little. But I am okay for now.',
        'Host: Help yourself if you want anything.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Đáp lời mời: "Yes, please" / "No, thank you"; "Help yourself" = cứ tự nhiên.',
    },
    targets: [
      target({
        id: 'sv18.t1',
        chunk: 'Would you like',
        cueVi: 'bạn có muốn ~ không',
        sourceSentence: 'Host: Would you like some tea?',
        productionPattern: 'Would you like <some tea / anything else>?',
        transferContext: 'offering a guest a drink',
      }),
      target({
        id: 'sv18.t2',
        chunk: 'Yes, please',
        cueVi: 'vâng ạ',
        sourceSentence: 'Anh: Yes, please.',
        productionPattern: 'Yes, please. / <Sure, thanks>.',
        transferContext: 'accepting a dessert offer',
      }),
      target({
        id: 'sv18.t3',
        chunk: 'No, thank you',
        cueVi: 'không, cảm ơn',
        sourceSentence: 'Anh: No, thank you.',
        productionPattern: 'No, thank <you>. / I am good.',
        transferContext: 'declining a second helping politely',
      }),
      target({
        id: 'sv18.t4',
        chunk: 'Do you take',
        cueVi: 'bạn có dùng ~ không',
        sourceSentence: 'Host: Do you take sugar?',
        productionPattern: 'Do you take <sugar / milk>?',
        transferContext: 'asking coffee preferences for a coworker',
      }),
      target({
        id: 'sv18.t5',
        chunk: 'A little',
        cueVi: 'một chút',
        sourceSentence: 'Anh: A little. But I am okay for now.',
        productionPattern: '<A little / A bit>.',
        transferContext: 'answering "do you speak English?"',
      }),
      target({
        id: 'sv18.t6',
        chunk: 'Help yourself',
        cueVi: 'cứ tự nhiên',
        sourceSentence: 'Host: Help yourself if you want anything.',
        productionPattern: 'Help yourself to <the fruit / anything>.',
        transferContext: 'inviting a guest to snacks',
      }),
    ],
    transferTask: {
      prompt: "At a colleague's home, accept one offer and decline another politely.",
      promptVi: 'Ở nhà đồng nghiệp, nhận một lời mời và từ chối lời mời khác lịch sự.',
      changesDimension: 'two opposite answers in one exchange',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv19',
    level: 'a0',
    track: 'survival',
    capabilities: ['small-talk', 'greet-leave'],
    title: 'How are you — honest answers',
    titleVi: 'How are you — trả lời thật',
    task: 'Answer "how are you" with more than just "fine"',
    context: 'Catching up with a coworker on Monday morning.',
    outcome: 'You can give a real short answer and ask back.',
    input: {
      title: 'SV19 · Monday',
      text: [
        'Sara: Good morning, Minh. How was your weekend?',
        'Minh: It was good, thanks. Pretty quiet. How about you?',
        'Sara: Busy! I visited my parents.',
        'Minh: That sounds nice.',
        'Sara: Are you ready for the meeting?',
        'Minh: Almost. I need five more minutes.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"How was your weekend" hỏi thăm tự nhiên; "That sounds nice" phản hồi tích cực.',
    },
    targets: [
      target({
        id: 'sv19.t1',
        chunk: 'How was your weekend',
        cueVi: 'cuối tuần thế nào',
        sourceSentence: 'Sara: Good morning, Minh. How was your weekend?',
        productionPattern: 'How was your <weekend / trip / evening>?',
        transferContext: 'asking a neighbor about their holiday',
      }),
      target({
        id: 'sv19.t2',
        chunk: 'Pretty quiet',
        cueVi: 'khá yên tĩnh',
        sourceSentence: 'Minh: It was good, thanks. Pretty quiet. How about you?',
        productionPattern: 'Pretty <quiet / good / busy>.',
        transferContext: 'describing a slow Sunday',
      }),
      target({
        id: 'sv19.t3',
        chunk: 'How about you',
        cueVi: 'còn bạn thì sao',
        sourceSentence: 'Minh: It was good, thanks. Pretty quiet. How about you?',
        productionPattern: 'How about <you / your family>?',
        transferContext: 'returning a holiday question',
      }),
      target({
        id: 'sv19.t4',
        chunk: 'That sounds nice',
        cueVi: 'nghe hay đấy',
        sourceSentence: 'Minh: That sounds nice.',
        productionPattern: 'That sounds <nice / fun / interesting>.',
        transferContext: "reacting to a friend's plan",
      }),
      target({
        id: 'sv19.t5',
        chunk: 'Are you ready for',
        cueVi: 'bạn đã sẵn sàng cho ~ chưa',
        sourceSentence: 'Sara: Are you ready for the meeting?',
        productionPattern: 'Are you ready for <the meeting / lunch>?',
        transferContext: 'checking a teammate before a demo',
      }),
      target({
        id: 'sv19.t6',
        chunk: 'five more minutes',
        cueVi: 'thêm năm phút nữa',
        sourceSentence: 'Minh: Almost. I need five more minutes.',
        productionPattern: 'I need <five / ten> more minutes.',
        transferContext: 'asking for time before a call',
      }),
    ],
    transferTask: {
      prompt: 'Friday afternoon — ask a colleague about their week and answer about yours honestly.',
      promptVi: 'Chiều thứ sáu — hỏi đồng nghiệp tuần qua thế nào và trả lời thật về tuần của bạn.',
      changesDimension: 'week not weekend + end-of-week frame',
    },
    recyclingFrom: ['sv01', 'sv03'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv20',
    level: 'a1',
    track: 'survival',
    capabilities: ['decode-names', 'ask-repetition'],
    title: 'Spell it out',
    titleVi: 'Đánh vần tên',
    task: 'Spell names and words letter by letter',
    context: 'A hotel clerk needs your name spelled for the booking.',
    outcome: 'You can spell your name and catch spelled letters.',
    input: {
      title: 'SV20 · Spelling',
      text: [
        'Clerk: Your name for the booking, please?',
        'Anh: Nguyen. N-G-U-Y-E-N.',
        'Clerk: Sorry, was that G or J?',
        'Anh: G as in green. N-G-U-Y-E-N.',
        'Clerk: Got it — Nguyen. And first name?',
        'Anh: Anh, A-N-H.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Đánh vần từng chữ; "G as in green" phân biệt chữ dễ nhầm (G/J, B/D, M/N).',
    },
    targets: [
      target({
        id: 'sv20.t1',
        chunk: 'Your name for the booking',
        cueVi: 'tên bạn để đặt phòng',
        sourceSentence: 'Clerk: Your name for the booking, please?',
        productionPattern: 'Your <name / ID> for the booking.',
        transferContext: 'confirming a restaurant reservation',
      }),
      target({
        id: 'sv20.t2',
        chunk: 'was that G or J',
        cueVi: 'đó là G hay J',
        sourceSentence: 'Clerk: Sorry, was that G or J?',
        productionPattern: 'was that <G or J / M or N>?',
        transferContext: 'clarifying a letter on a phone call',
      }),
      target({
        id: 'sv20.t3',
        chunk: 'G as in green',
        cueVi: 'chữ G như green',
        sourceSentence: 'Anh: G as in green. N-G-U-Y-E-N.',
        productionPattern: '<letter> as in <word>.',
        transferContext: 'spelling a street name for a driver',
      }),
      target({
        id: 'sv20.t4',
        chunk: 'Got it',
        cueVi: 'hiểu rồi',
        sourceSentence: 'Clerk: Got it — Nguyen. And first name?',
        productionPattern: 'Got it. / <Understood / Okay>.',
        transferContext: 'confirming a spelled email',
      }),
      target({
        id: 'sv20.t5',
        chunk: 'first name',
        cueVi: 'tên (không phải họ)',
        sourceSentence: 'Clerk: Got it — Nguyen. And first name?',
        productionPattern: '<first name / last name / middle name>.',
        transferContext: 'filling a visa form',
      }),
    ],
    transferTask: {
      prompt: 'Spell a difficult street name for a delivery driver and correct one wrong letter.',
      promptVi: 'Đánh vần tên đường khó cho shipper và sửa một chữ họ nghe nhầm.',
      changesDimension: 'street name not personal name + error correction',
    },
    recyclingFrom: ['sv02', 'sv05'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv21',
    level: 'a0',
    track: 'survival',
    capabilities: ['request-help', 'handle-emergency'],
    title: 'I need help',
    titleVi: 'Tôi cần giúp',
    task: 'Ask for urgent help in simple clear phrases',
    context: 'You lost your bag at a station and need staff.',
    outcome: 'You can state an emergency and what you need.',
    input: {
      title: 'SV21 · Lost bag',
      text: [
        'Anh: Excuse me, I need help. I lost my bag.',
        'Staff: Okay, stay calm. Where did you last see it?',
        'Anh: On the train, I think. It is a black backpack.',
        'Staff: What is inside?',
        'Anh: My passport and my phone.',
        'Staff: Follow me to the lost and found office.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Khi mất đồ: I lost my X → mô tả → nói đồ quan trọng bên trong.',
    },
    targets: [
      target({
        id: 'sv21.t1',
        chunk: 'I need help',
        cueVi: 'tôi cần giúp đỡ',
        sourceSentence: 'Anh: Excuse me, I need help. I lost my bag.',
        productionPattern: 'I need <help / a doctor / the police>.',
        transferContext: 'asking a passerby for urgent help',
      }),
      target({
        id: 'sv21.t2',
        chunk: 'I lost my bag',
        cueVi: 'tôi mất túi',
        sourceSentence: 'Anh: Excuse me, I need help. I lost my bag.',
        productionPattern: 'I lost my <bag / phone / keys>.',
        transferContext: 'reporting a lost wallet at a hotel',
      }),
      target({
        id: 'sv21.t3',
        chunk: 'stay calm',
        cueVi: 'bình tĩnh',
        sourceSentence: 'Staff: Okay, stay calm. Where did you last see it?',
        productionPattern: '<Stay calm / Take your time>.',
        transferContext: 'calming a panicked friend',
      }),
      target({
        id: 'sv21.t4',
        chunk: 'Where did you last see it',
        cueVi: 'lần cuối bạn thấy nó ở đâu',
        sourceSentence: 'Staff: Okay, stay calm. Where did you last see it?',
        productionPattern: 'Where did you last <see / have> it?',
        transferContext: 'helping a friend find lost keys',
      }),
      target({
        id: 'sv21.t5',
        chunk: 'a black backpack',
        cueVi: 'balo màu đen',
        sourceSentence: 'Anh: On the train, I think. It is a black backpack.',
        productionPattern: 'It is a <black backpack / red wallet>.',
        transferContext: 'describing lost luggage at an airport',
      }),
      target({
        id: 'sv21.t6',
        chunk: 'lost and found',
        cueVi: 'phòng đồ thất lạc',
        sourceSentence: 'Staff: Follow me to the lost and found office.',
        productionPattern: 'the lost and found <office / desk>.',
        transferContext: 'asking where to claim a lost item',
      }),
    ],
    transferTask: {
      prompt: 'You lost your phone in a taxi — tell the company what, where, and what it looks like.',
      promptVi: 'Bạn để quên điện thoại trên taxi — nói cho hãng xe mất gì, ở đâu, hình dáng ra sao.',
      changesDimension: 'reported over phone + item description changes',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv22',
    level: 'a0',
    track: 'survival',
    capabilities: ['schedule-appointment', 'ask-yesno'],
    title: 'What time is it',
    titleVi: 'Mấy giờ rồi',
    task: 'Ask and tell the time',
    context: 'Coordinating a meetup time with a friend.',
    outcome: 'You can ask the time, say times, and agree on one.',
    input: {
      title: 'SV22 · Time',
      text: [
        'Anh: What time is it now?',
        'Linh: It is almost three.',
        'Anh: What time does the movie start?',
        'Linh: At four thirty. We should leave at four.',
        'Anh: Okay, four it is.',
        'Linh: See you in front of the cinema.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"What time is it" hỏi giờ; "at + giờ" cho lịch; "X it is" = chốt giờ đó.',
    },
    targets: [
      target({
        id: 'sv22.t1',
        chunk: 'What time is it',
        cueVi: 'mấy giờ rồi',
        sourceSentence: 'Anh: What time is it now?',
        productionPattern: 'What time <is it / does it open>?',
        transferContext: 'asking a stranger on the street',
      }),
      target({
        id: 'sv22.t2',
        chunk: 'almost three',
        cueVi: 'gần ba giờ',
        sourceSentence: 'Linh: It is almost three.',
        productionPattern: 'almost <three / noon / midnight>.',
        transferContext: 'estimating time without a clock',
      }),
      target({
        id: 'sv22.t3',
        chunk: 'What time does',
        cueVi: 'mấy giờ ~ bắt đầu',
        sourceSentence: 'Anh: What time does the movie start?',
        productionPattern: 'What time does <the movie / the shop> start/open?',
        transferContext: 'asking when a museum opens',
      }),
      target({
        id: 'sv22.t4',
        chunk: 'At four thirty',
        cueVi: 'lúc bốn giờ ba mươi',
        sourceSentence: 'Linh: At four thirty. We should leave at four.',
        productionPattern: 'At <four thirty / half past nine>.',
        transferContext: 'setting a call time',
      }),
      target({
        id: 'sv22.t5',
        chunk: 'We should leave',
        cueVi: 'chúng ta nên đi',
        sourceSentence: 'Linh: At four thirty. We should leave at four.',
        productionPattern: 'We should <leave / go / book> at four.',
        transferContext: 'planning departure for a bus',
      }),
      target({
        id: 'sv22.t6',
        chunk: 'four it is',
        cueVi: 'chốt bốn giờ nhé',
        sourceSentence: 'Anh: Okay, four it is.',
        productionPattern: '<Four / Saturday> it is.',
        transferContext: 'confirming a dinner day',
      }),
      target({
        id: 'sv22.t7',
        chunk: 'in front of',
        cueVi: 'trước mặt',
        sourceSentence: 'Linh: See you in front of the cinema.',
        productionPattern: 'in front of <the cinema / the gate>.',
        transferContext: 'naming a meeting point',
      }),
    ],
    transferTask: {
      prompt: 'Plan a study session — ask the time, suggest an hour, confirm where to meet.',
      promptVi: 'Lên lịch buổi học nhóm — hỏi giờ, đề xuất giờ, chốt địa điểm gặp.',
      changesDimension: 'planning (not coordinating now) + place confirmation',
    },
    recyclingFrom: ['sv14'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv23',
    level: 'a1',
    track: 'survival',
    capabilities: ['ask-price', 'shop-return'],
    title: 'At the store — a small problem',
    titleVi: 'Ở cửa hàng — vấn đề nhỏ',
    task: 'Point out a small problem with a purchase and ask for help',
    context: 'The shirt you bought has the wrong size on the tag.',
    outcome: 'You can describe a simple defect and ask for an exchange.',
    input: {
      title: 'SV23 · Wrong size',
      text: [
        'Anh: Excuse me, I bought this shirt yesterday.',
        'Clerk: Is there a problem with it?',
        'Anh: The tag says medium, but it fits like a small.',
        'Clerk: Oh, sorry about that. Do you want to exchange it?',
        'Anh: Yes, please. A medium that actually fits.',
        'Clerk: No problem. Let me get the right size.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Khiếu nại nhẹ: I bought X yesterday → the problem → "Do you want to exchange" → yes please.',
    },
    targets: [
      target({
        id: 'sv23.t1',
        chunk: 'I bought this',
        cueVi: 'tôi đã mua cái này',
        sourceSentence: 'Anh: Excuse me, I bought this shirt yesterday.',
        productionPattern: 'I bought <this shirt / it> yesterday.',
        transferContext: 'returning headphones that crackle',
      }),
      target({
        id: 'sv23.t2',
        chunk: 'Is there a problem with it',
        cueVi: 'nó có vấn đề gì không',
        sourceSentence: 'Clerk: Is there a problem with it?',
        productionPattern: 'Is there a problem with <it / the order>?',
        transferContext: 'asking a customer what is wrong',
      }),
      target({
        id: 'sv23.t3',
        chunk: 'the tag says',
        cueVi: 'nhãn ghi',
        sourceSentence: 'Anh: The tag says medium, but it fits like a small.',
        productionPattern: 'The <tag / label> says <medium>.',
        transferContext: 'checking a mismatched price tag',
      }),
      target({
        id: 'sv23.t4',
        chunk: 'exchange it',
        cueVi: 'đổi nó',
        sourceSentence: 'Clerk: Oh, sorry about that. Do you want to exchange it?',
        productionPattern: '<exchange / return> it.',
        transferContext: 'swapping a gift for another color',
      }),
      target({
        id: 'sv23.t5',
        chunk: 'that actually fits',
        cueVi: 'mà thực sự vừa',
        sourceSentence: 'Anh: Yes, please. A medium that actually fits.',
        productionPattern: 'a <medium> that actually <fits / works>.',
        transferContext: 'asking for a charger that works',
      }),
      target({
        id: 'sv23.t6',
        chunk: 'the right size',
        cueVi: 'đúng size',
        sourceSentence: 'Clerk: No problem. Let me get the right size.',
        productionPattern: 'the right <size / model / color>.',
        transferContext: 'confirming the correct shoe size',
      }),
    ],
    transferTask: {
      prompt: 'Return a phone case that does not fit your model — explain the mismatch and ask for the right one.',
      promptVi: 'Đổi ốp điện thoại không vừa máy — giải thích lỗi khác mẫu và xin đúng loại.',
      changesDimension: 'accessory model mismatch (not clothing size)',
    },
    recyclingFrom: ['sv11', 'sv15'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv24',
    level: 'a1',
    track: 'survival',
    capabilities: ['make-plans'],
    title: 'Say your weekend plans',
    titleVi: 'Nói kế hoạch cuối tuần',
    task: 'Say simple plans and invite someone along',
    context: 'Friday chat — a friend asks what you are doing.',
    outcome: 'You can state plans with "going to" and extend an invitation.',
    input: {
      title: 'SV24 · Weekend plan',
      text: [
        'Linh: What are you doing this weekend, Anh?',
        'Anh: I am going to visit my parents on Saturday.',
        'Linh: Nice. And Sunday?',
        'Anh: Nothing yet. Maybe a movie.',
        'Linh: Do you want to join us for lunch?',
        'Anh: Sure, I would love to. What time?',
        'Linh: Around noon, at the new place near the lake.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: '"going to" cho kế hoạch; "Do you want to join" là lời mời; "Around noon" ~ tầm trưa.',
    },
    targets: [
      target({
        id: 'sv24.t1',
        chunk: 'What are you doing this weekend',
        cueVi: 'cuối tuần bạn làm gì',
        sourceSentence: 'Linh: What are you doing this weekend, Anh?',
        productionPattern: 'What are you doing <this weekend / tonight>?',
        transferContext: 'asking a colleague Friday plans',
      }),
      target({
        id: 'sv24.t2',
        chunk: 'I am going to visit',
        cueVi: 'tôi sẽ đi thăm',
        sourceSentence: 'Anh: I am going to visit my parents on Saturday.',
        productionPattern: 'I am going to <visit / see / stay with>.',
        transferContext: 'describing a holiday plan',
      }),
      target({
        id: 'sv24.t3',
        chunk: 'Nothing yet',
        cueVi: 'chưa có gì',
        sourceSentence: 'Anh: Nothing yet. Maybe a movie.',
        productionPattern: '<Nothing yet / Not sure yet>.',
        transferContext: 'answering about evening plans',
      }),
      target({
        id: 'sv24.t4',
        chunk: 'Do you want to join us',
        cueVi: 'bạn có muốn đi cùng không',
        sourceSentence: 'Linh: Do you want to join us for lunch?',
        productionPattern: 'Do you want to join <us / me> for <lunch / coffee>?',
        transferContext: 'inviting a classmate to dinner',
      }),
      target({
        id: 'sv24.t5',
        chunk: 'I would love to',
        cueVi: 'tôi rất muốn',
        sourceSentence: 'Anh: Sure, I would love to. What time?',
        productionPattern: 'I would love to<, but / . Sure>.',
        transferContext: 'accepting a wedding invitation',
      }),
      target({
        id: 'sv24.t6',
        chunk: 'Around noon',
        cueVi: 'tầm trưa',
        sourceSentence: 'Linh: Around noon, at the new place near the lake.',
        productionPattern: 'Around <noon / seven / eight>.',
        transferContext: 'giving an approximate meeting time',
      }),
    ],
    transferTask: {
      prompt: 'Plan a different outing — state your plan, invite someone, and set an approximate time.',
      promptVi: 'Lên kế hoạch đi chơi khác — nói kế hoạch, mời người khác, đặt giờ gần đúng.',
      changesDimension: 'you are the inviter + approximate time',
    },
    recyclingFrom: ['sv01', 'sv19'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
];
