/* Survival English sv01–sv12 (A0–A1) — first conversations.
 * Functions seeded from dim_speaking_functions (fn.01–fn.03). */

import type { LessonSpec } from '../../content-factory/types.ts';
import { RES, SRC, spec, target } from './helpers.ts';

export const SURVIVAL_1: LessonSpec[] = [
  spec({
    id: 'sv01',
    level: 'a0',
    track: 'survival',
    capabilities: ['greet-leave'],
    title: 'Greet someone and say goodbye',
    titleVi: 'Chào hỏi và tạm biệt',
    task: 'Greet a neighbor in the morning and end the exchange politely',
    context: 'You meet a neighbor outside your building in the morning.',
    outcome: 'You can open with a greeting and close without awkwardness.',
    input: {
      title: 'SV01 · Morning greeting',
      text: [
        'Anh meets Mrs. Chen at the elevator.',
        'Anh: Good morning, Mrs. Chen.',
        'Mrs. Chen: Good morning! How are you today?',
        'Anh: I am fine, thank you. And you?',
        'Mrs. Chen: Very well, thanks. Have a nice day.',
        'Anh: You too. See you later.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: 'Chào buổi sáng + hỏi thăm + kết thúc lịch sự. Mẫu "And you?" để hỏi lại ngắn gọn.',
    },
    targets: [
      target({
        id: 'sv01.t1',
        chunk: 'Good morning',
        cueVi: 'chào buổi sáng',
        sourceSentence: 'Anh: Good morning, Mrs. Chen.',
        productionPattern: 'Good <morning / afternoon / evening>.',
        transferContext: 'greeting a coworker in the afternoon',
      }),
      target({
        id: 'sv01.t2',
        chunk: 'How are you',
        cueVi: 'bạn khỏe không',
        sourceSentence: 'Mrs. Chen: Good morning! How are you today?',
        productionPattern: 'How are you <today / doing>?',
        transferContext: 'asking a friend on the phone',
      }),
      target({
        id: 'sv01.t3',
        chunk: 'I am fine, thank you',
        cueVi: 'tôi khỏe, cảm ơn',
        sourceSentence: 'Anh: I am fine, thank you. And you?',
        productionPattern: 'I am <fine / good / okay>, thank you.',
        transferContext: 'answering a doctor at a checkup',
      }),
      target({
        id: 'sv01.t4',
        chunk: 'Have a nice day',
        cueVi: 'chúc một ngày tốt lành',
        sourceSentence: 'Mrs. Chen: Very well, thanks. Have a nice day.',
        productionPattern: 'Have a nice <day / weekend / evening>.',
        transferContext: 'ending a shop exchange',
      }),
      target({
        id: 'sv01.t5',
        chunk: 'See you later',
        cueVi: 'hẹn gặp lại',
        sourceSentence: 'Anh: You too. See you later.',
        productionPattern: 'See you <later / tomorrow / soon>.',
        transferContext: 'leaving a study group',
      }),
    ],
    transferTask: {
      prompt: 'Greet a teammate in the afternoon and close with a different goodbye.',
      promptVi: 'Chào đồng nghiệp buổi chiều rồi kết thúc bằng lời tạm biệt khác.',
      changesDimension: 'time of day + partner + closing phrase',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv02',
    level: 'a0',
    track: 'survival',
    capabilities: ['introduce-self', 'ask-personal-info'],
    title: 'Say your name and ask theirs',
    titleVi: 'Nói tên mình và hỏi tên người khác',
    task: 'Introduce yourself by name and ask the other person theirs',
    context: 'You sit next to a new colleague at a welcome lunch.',
    outcome: 'You can trade names and keep the first exchange going.',
    input: {
      title: 'SV02 · First names',
      text: [
        'Minh: Hi, I am Minh. What is your name?',
        'Sara: I am Sara. Nice to meet you, Minh.',
        'Minh: Nice to meet you too, Sara.',
        'Sara: How do you spell your name?',
        'Minh: M-I-N-H. And you?',
        'Sara: S-A-R-A.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: '"I am + tên" để tự giới thiệu; "How do you spell" hỏi đánh vần.',
    },
    targets: [
      target({
        id: 'sv02.t1',
        chunk: 'I am',
        cueVi: 'tôi là (tự giới thiệu)',
        sourceSentence: 'Minh: Hi, I am Minh. What is your name?',
        productionPattern: 'I am <name>.',
        transferContext: 'introducing yourself at a meetup',
      }),
      target({
        id: 'sv02.t2',
        chunk: 'What is your name',
        cueVi: 'tên bạn là gì',
        sourceSentence: 'Minh: Hi, I am Minh. What is your name?',
        productionPattern: 'What is your <name / phone number>?',
        transferContext: 'asking a receptionist',
      }),
      target({
        id: 'sv02.t3',
        chunk: 'Nice to meet you',
        cueVi: 'rất vui được gặp bạn',
        sourceSentence: 'Sara: I am Sara. Nice to meet you, Minh.',
        productionPattern: 'Nice to <meet / see> you.',
        transferContext: 'meeting a friend of a friend',
      }),
      target({
        id: 'sv02.t4',
        chunk: 'Nice to meet you too',
        cueVi: 'tôi cũng rất vui được gặp bạn',
        sourceSentence: 'Minh: Nice to meet you too, Sara.',
        productionPattern: '<Nice / Good> to meet you too.',
        transferContext: 'replying in a formal introduction',
      }),
      target({
        id: 'sv02.t5',
        chunk: 'How do you spell',
        cueVi: 'bạn đánh vần thế nào',
        sourceSentence: 'Sara: How do you spell your name?',
        productionPattern: 'How do you spell <your name / that word>?',
        transferContext: 'booking an appointment over the phone',
      }),
    ],
    transferTask: {
      prompt: 'Introduce yourself in a video call and ask the other person to spell their name.',
      promptVi: 'Giới thiệu tên mình trong cuộc gọi video và hỏi người kia đánh vần tên.',
      changesDimension: 'channel (video call) + asks spelling instead of name',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv03',
    level: 'a0',
    track: 'survival',
    capabilities: ['ask-personal-info'],
    title: 'Ask where someone is from',
    titleVi: 'Hỏi quê quán',
    task: 'Ask where a new acquaintance comes from and answer the same question',
    context: 'Small talk at a language exchange meetup.',
    outcome: 'You can ask origin and give yours in one line each.',
    input: {
      title: 'SV03 · Where are you from',
      text: [
        'Lan: Hi David. Where are you from?',
        'David: I am from Canada. And you, Lan?',
        'Lan: I am from Vietnam.',
        'David: Oh, nice. Which city?',
        'Lan: I am from Da Nang, on the coast.',
        'David: Is it beautiful there?',
        'Lan: Yes, very beautiful.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: '"Where are you from" hỏi quốc gia/quê; "Which city" hỏi thành phố cụ thể.',
    },
    targets: [
      target({
        id: 'sv03.t1',
        chunk: 'Where are you from',
        cueVi: 'bạn đến từ đâu',
        sourceSentence: 'Lan: Hi David. Where are you from?',
        productionPattern: 'Where are you <from / living now>?',
        transferContext: 'asking a seatmate on a flight',
      }),
      target({
        id: 'sv03.t2',
        chunk: 'I am from',
        cueVi: 'tôi đến từ',
        sourceSentence: 'David: I am from Canada. And you, Lan?',
        productionPattern: 'I am from <place>.',
        transferContext: 'answering a host family',
      }),
      target({
        id: 'sv03.t3',
        chunk: 'And you',
        cueVi: 'còn bạn thì sao',
        sourceSentence: 'David: I am from Canada. And you, Lan?',
        productionPattern: '<Nice, thanks.> And you?',
        transferContext: 'returning any small-talk question',
      }),
      target({
        id: 'sv03.t4',
        chunk: 'Which city',
        cueVi: 'thành phố nào',
        sourceSentence: 'David: Oh, nice. Which city?',
        productionPattern: 'Which <city / part / neighborhood>?',
        transferContext: 'asking follow-up about hometown',
      }),
    ],
    transferTask: {
      prompt: 'At a work dinner, ask a visitor where they are from and which part of that country.',
      promptVi: 'Trong bữa tối công việc, hỏi khách đến từ đâu và ở vùng nào của đất nước đó.',
      changesDimension: 'formal setting + deeper follow-up question',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv04',
    level: 'a0',
    track: 'survival',
    capabilities: ['introduce-self', 'ask-personal-info'],
    title: 'Say what you do',
    titleVi: 'Nói nghề nghiệp của mình',
    task: 'Say your job or field of study and ask the other person theirs',
    context: 'Continuing small talk after names and origin.',
    outcome: 'You can state your role in one sentence and ask back.',
    input: {
      title: 'SV04 · What do you do',
      text: [
        'Sara: So Minh, what do you do?',
        'Minh: I am a software developer. I build mobile apps.',
        'Sara: Interesting. I am a designer.',
        'Minh: Do you like your job?',
        'Sara: Yes, I love it. Do you work here in the city?',
        'Minh: Yes, at a small company near the river.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"What do you do" là câu hỏi nghề nghiệp quen thuộc nhất; trả lời "I am a + nghề".',
    },
    targets: [
      target({
        id: 'sv04.t1',
        chunk: 'what do you do',
        cueVi: 'bạn làm nghề gì',
        sourceSentence: 'Sara: So Minh, what do you do?',
        productionPattern: 'What do you do <for work / for a living>?',
        transferContext: 'asking a partner at a conference',
        pronunciationNote: '"whaddya do" — what-do-you co lại',
      }),
      target({
        id: 'sv04.t2',
        chunk: 'I am a software developer',
        cueVi: 'tôi là lập trình viên',
        sourceSentence: 'Minh: I am a software developer. I build mobile apps.',
        productionPattern: 'I am a <developer / teacher / student>.',
        transferContext: 'writing a short bio for a form',
      }),
      target({
        id: 'sv04.t3',
        chunk: 'Do you like your job',
        cueVi: 'bạn có thích công việc không',
        sourceSentence: 'Minh: Do you like your job?',
        productionPattern: 'Do you like <your job / this city>?',
        transferContext: 'asking a roommate about their day job',
      }),
      target({
        id: 'sv04.t4',
        chunk: 'I love it',
        cueVi: 'tôi rất thích',
        sourceSentence: 'Sara: Yes, I love it. Do you work here in the city?',
        productionPattern: 'I <love / like> it.',
        transferContext: 'answering about a hobby, not a job',
      }),
      target({
        id: 'sv04.t5',
        chunk: 'a small company',
        cueVi: 'một công ty nhỏ',
        sourceSentence: 'Minh: Yes, at a small company near the river.',
        productionPattern: 'at a <small company / big firm / startup>.',
        transferContext: 'describing where a friend works',
      }),
    ],
    transferTask: {
      prompt: 'At a networking event, tell a stranger your field and ask what they do — without using the word "job".',
      promptVi: 'Ở sự kiện networking, nói lĩnh vực của bạn và hỏi nghề người kia — không dùng chữ "job".',
      changesDimension: 'register (formal event) + alternate phrasing required',
    },
    recyclingFrom: ['sv02'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv05',
    level: 'a0',
    track: 'survival',
    capabilities: ['ask-personal-info'],
    title: 'Give your phone number and email',
    titleVi: 'Đọc số điện thoại và email',
    task: 'Say your phone number digit by digit and your email address clearly',
    context: 'A receptionist asks for your contact details to book an appointment.',
    outcome: 'You can dictate numbers and email without confusion.',
    input: {
      title: 'SV05 · Contact details',
      text: [
        'Receptionist: Can I have your phone number, please?',
        'Anh: Sure. It is zero nine zero five, two one three, eight seven six.',
        'Receptionist: And your email?',
        'Anh: It is anh dot nguyen at gmail dot com.',
        'Receptionist: Let me confirm: zero nine zero five, two one three, eight seven six.',
        'Anh: That is correct.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Đọc số theo cụm cho dễ nghe; "dot" và "at" cho email; "Let me confirm" là câu xác nhận.',
    },
    targets: [
      target({
        id: 'sv05.t1',
        chunk: 'Can I have your phone number',
        cueVi: 'cho tôi xin số điện thoại',
        sourceSentence: 'Receptionist: Can I have your phone number, please?',
        productionPattern: 'Can I have your <phone number / name / email>?',
        transferContext: 'a clinic registration desk asking details',
      }),
      target({
        id: 'sv05.t2',
        chunk: 'It is zero nine',
        cueVi: 'đọc số điện thoại',
        sourceSentence: 'Anh: Sure. It is zero nine zero five, two one three, eight seven six.',
        productionPattern: 'It is <number groups>.',
        transferContext: 'dictating a hotel booking reference',
      }),
      target({
        id: 'sv05.t3',
        chunk: 'at gmail dot com',
        cueVi: 'a-còng gmail chấm com',
        sourceSentence: 'Anh: It is anh dot nguyen at gmail dot com.',
        productionPattern: '<name> at <provider> dot com.',
        transferContext: 'spelling an email to a support agent',
      }),
      target({
        id: 'sv05.t4',
        chunk: 'Let me confirm',
        cueVi: 'để tôi xác nhận lại',
        sourceSentence: 'Receptionist: Let me confirm: zero nine zero five, two one three, eight seven six.',
        productionPattern: 'Let me <confirm / check / write that down>.',
        transferContext: 'a waiter repeating your order back',
      }),
      target({
        id: 'sv05.t5',
        chunk: 'That is correct',
        cueVi: 'đúng rồi',
        sourceSentence: 'Anh: That is correct.',
        productionPattern: 'That is <correct / right / it>.',
        transferContext: 'confirming details on a delivery form',
      }),
    ],
    transferTask: {
      prompt: 'Dictate a booking code (letters + numbers) to an airline agent and confirm theirs back.',
      promptVi: 'Đọc mã đặt chỗ (chữ + số) cho nhân viên hàng không và xác nhận lại thông tin.',
      changesDimension: 'mixed letters/digits + you confirm their info',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv06',
    level: 'a0',
    track: 'survival',
    capabilities: ['ask-repetition', 'clarify-meaning'],
    title: 'Ask someone to repeat',
    titleVi: 'Xin người khác nói lại',
    task: 'Ask a speaker to repeat or slow down when you miss something',
    context: 'A shop assistant answers too fast and you lost the key part.',
    outcome: 'You can interrupt politely and get the information again.',
    input: {
      title: 'SV06 · Ask to repeat',
      text: [
        'Clerk: The sale ends next Friday at the second counter upstairs.',
        'Anh: Sorry, could you say that again?',
        'Clerk: Sure. The sale ends next Friday.',
        'Anh: Could you speak more slowly, please?',
        'Clerk: Of course. Next. Friday. Second counter. Upstairs.',
        'Anh: Got it, thank you.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: 'Ba thang xin lại: say that again → speak more slowly → Got it.',
    },
    targets: [
      target({
        id: 'sv06.t1',
        chunk: 'Sorry, could you say that again',
        cueVi: 'xin lỗi, bạn nói lại được không',
        sourceSentence: 'Anh: Sorry, could you say that again?',
        productionPattern: 'Sorry, could you <say that again / repeat that>?',
        transferContext: 'missing a direction on the street',
        pronunciationNote: 'could you SAY that a-GAIN',
      }),
      target({
        id: 'sv06.t2',
        chunk: 'Could you speak more slowly',
        cueVi: 'bạn nói chậm lại được không',
        sourceSentence: 'Anh: Could you speak more slowly, please?',
        productionPattern: 'Could you <speak more slowly / repeat the last part>?',
        transferContext: 'a phone call with a fast speaker',
      }),
      target({
        id: 'sv06.t3',
        chunk: 'Of course',
        cueVi: 'tất nhiên rồi',
        sourceSentence: 'Clerk: Of course. Next. Friday. Second counter. Upstairs.',
        productionPattern: 'Of course. / <Sure / No problem>.',
        transferContext: 'agreeing to a small favor',
      }),
      target({
        id: 'sv06.t4',
        chunk: 'Got it',
        cueVi: 'hiểu rồi',
        sourceSentence: 'Anh: Got it, thank you.',
        productionPattern: 'Got it. / <I see / I understand>.',
        transferContext: 'confirming instructions from a teammate',
      }),
    ],
    transferTask: {
      prompt: 'On a call, ask the speaker to repeat the date AND to speak more slowly, then confirm you got it.',
      promptVi: 'Trong cuộc gọi, xin người nói lặp lại ngày VÀ nói chậm hơn, rồi xác nhận bạn đã nghe được.',
      changesDimension: 'phone channel + two clarification moves in sequence',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv07',
    level: 'a0',
    track: 'survival',
    capabilities: ['clarify-meaning'],
    title: 'Say you do not understand',
    titleVi: 'Nói mình không hiểu',
    task: 'Say clearly that you do not understand and ask what a word means',
    context: 'Someone uses a word you have never heard in a conversation.',
    outcome: 'You can admit not understanding and get a simpler explanation.',
    input: {
      title: 'SV07 · Not understand',
      text: [
        'Tom: The meeting was postponed.',
        'Anh: Sorry, I do not understand. What does postponed mean?',
        'Tom: It means moved to a later time.',
        'Anh: Oh, I see. So the meeting is next week?',
        'Tom: Exactly, next Tuesday.',
        'Anh: Thank you for explaining.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: 'Đừng giả vờ hiểu — "I do not understand" + "What does X mean" là câu cứu cánh.',
    },
    targets: [
      target({
        id: 'sv07.t1',
        chunk: 'I do not understand',
        cueVi: 'tôi không hiểu',
        sourceSentence: 'Anh: Sorry, I do not understand. What does postponed mean?',
        productionPattern: 'I do not <understand / know this word>.',
        transferContext: 'reading a sign you cannot parse',
      }),
      target({
        id: 'sv07.t2',
        chunk: 'What does postponed mean',
        cueVi: 'postponed nghĩa là gì',
        sourceSentence: 'Anh: Sorry, I do not understand. What does postponed mean?',
        productionPattern: 'What does <this word / that phrase> mean?',
        transferContext: 'asking a teacher about a term',
      }),
      target({
        id: 'sv07.t3',
        chunk: 'It means',
        cueVi: 'nghĩa là',
        sourceSentence: 'Tom: It means moved to a later time.',
        productionPattern: 'It means <simpler words>.',
        transferContext: 'explaining an easy word to a friend',
      }),
      target({
        id: 'sv07.t4',
        chunk: 'I see',
        cueVi: 'à hiểu rồi',
        sourceSentence: 'Anh: Oh, I see. So the meeting is next week?',
        productionPattern: 'Oh, I see. / <I get it / That makes sense>.',
        transferContext: 'acknowledging an explanation at work',
      }),
      target({
        id: 'sv07.t5',
        chunk: 'Thank you for explaining',
        cueVi: 'cảm ơn đã giải thích',
        sourceSentence: 'Anh: Thank you for explaining.',
        productionPattern: 'Thank you for <explaining / helping me>.',
        transferContext: 'thanking a colleague after a demo',
      }),
    ],
    transferTask: {
      prompt: 'In a store, say you do not understand a label word and ask what it means — then check your guess.',
      promptVi: 'Trong cửa hàng, nói bạn không hiểu một chữ trên nhãn và hỏi nghĩa — rồi kiểm tra lại dự đoán.',
      changesDimension: 'written word on a label + confirm your own guess',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv08',
    level: 'a0',
    track: 'survival',
    capabilities: ['express-thanks', 'request-help'],
    title: 'Please and thank you',
    titleVi: 'Please và cảm ơn',
    task: 'Make a simple request politely and thank the person',
    context: 'You need a pen at the library desk.',
    outcome: 'You can ask for small things without sounding abrupt.',
    input: {
      title: 'SV08 · Polite small ask',
      text: [
        'Anh: Excuse me. Can I borrow a pen, please?',
        'Librarian: Sure, here you go.',
        'Anh: Thank you very much.',
        'Librarian: You are welcome.',
        'Anh: Could you help me find the English section?',
        'Librarian: Of course. It is on the second floor.',
        'Anh: Thanks a lot.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: '"Can I borrow" + please; trả lời cảm ơn "You are welcome"; "Thanks a lot" thân mật.',
    },
    targets: [
      target({
        id: 'sv08.t1',
        chunk: 'Excuse me',
        cueVi: 'xin lỗi (để bắt chuyện)',
        sourceSentence: 'Anh: Excuse me. Can I borrow a pen, please?',
        productionPattern: 'Excuse me, <can I / where is>?',
        transferContext: 'stopping someone to ask the time',
      }),
      target({
        id: 'sv08.t2',
        chunk: 'Can I borrow',
        cueVi: 'cho tôi mượn',
        sourceSentence: 'Anh: Excuse me. Can I borrow a pen, please?',
        productionPattern: 'Can I borrow <a pen / your charger>?',
        transferContext: 'borrowing a charger from a classmate',
      }),
      target({
        id: 'sv08.t3',
        chunk: 'here you go',
        cueVi: 'đây, của bạn',
        sourceSentence: 'Librarian: Sure, here you go.',
        productionPattern: 'Here you <go / are>.',
        transferContext: 'handing change to a customer',
      }),
      target({
        id: 'sv08.t4',
        chunk: 'Thank you very much',
        cueVi: 'cảm ơn rất nhiều',
        sourceSentence: 'Anh: Thank you very much.',
        productionPattern: 'Thank you <very much / so much>.',
        transferContext: 'thanking a host for dinner',
      }),
      target({
        id: 'sv08.t5',
        chunk: 'You are welcome',
        cueVi: 'không có gì',
        sourceSentence: 'Librarian: You are welcome.',
        productionPattern: 'You are <welcome>. / No problem.',
        transferContext: 'replying when someone thanks you at work',
      }),
      target({
        id: 'sv08.t6',
        chunk: 'Could you help me find',
        cueVi: 'bạn giúp tôi tìm được không',
        sourceSentence: 'Anh: Could you help me find the English section?',
        productionPattern: 'Could you help me <find / carry / open>?',
        transferContext: 'asking a stranger to lift a bag',
      }),
    ],
    transferTask: {
      prompt: 'At an airport counter, make one small request politely and thank the agent.',
      promptVi: 'Ở quầy sân bay, đưa một yêu cầu nhỏ lịch sự và cảm ơn nhân viên.',
      changesDimension: 'high-stress setting + different object of request',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv09',
    level: 'a1',
    track: 'survival',
    capabilities: ['apologize'],
    title: 'Say sorry and respond',
    titleVi: 'Xin lỗi và đáp lại',
    task: 'Apologize for a small mistake and accept an apology',
    context: 'You bump into someone on a crowded train.',
    outcome: 'You can apologize quickly and reply to an apology.',
    input: {
      title: 'SV09 · Sorry',
      text: [
        'Anh: Oh, sorry! I am so sorry.',
        'Woman: No problem, it is okay.',
        'Anh: I did not see you there.',
        'Woman: Really, do not worry about it.',
        'Anh: I am sorry I am late, the train was crowded.',
        'Tom: That is fine. We just started.',
      ].join('\n'),
      origin: 'derived',
      sourceRefId: 'nep-speaking-functions',
      noteVi: 'Xin lỗi ngắn: sorry / I am so sorry; đáp lại: No problem / That is fine / do not worry.',
    },
    targets: [
      target({
        id: 'sv09.t1',
        chunk: 'I am so sorry',
        cueVi: 'tôi xin lỗi rất nhiều',
        sourceSentence: 'Anh: Oh, sorry! I am so sorry.',
        productionPattern: 'I am <so sorry / really sorry>.',
        transferContext: 'stepping on a foot in a crowd',
      }),
      target({
        id: 'sv09.t2',
        chunk: 'No problem',
        cueVi: 'không sao đâu',
        sourceSentence: 'Woman: No problem, it is okay.',
        productionPattern: 'No problem. / <It is okay / All good>.',
        transferContext: 'replying when a colleague apologizes',
      }),
      target({
        id: 'sv09.t3',
        chunk: 'I did not see you',
        cueVi: 'tôi không thấy bạn',
        sourceSentence: 'Anh: I did not see you there.',
        productionPattern: 'I did not <see / hear / notice> you.',
        transferContext: 'explaining why you missed a wave',
      }),
      target({
        id: 'sv09.t4',
        chunk: 'do not worry about it',
        cueVi: 'đừng lo về chuyện đó',
        sourceSentence: 'Woman: Really, do not worry about it.',
        productionPattern: 'Do not worry <about it>.',
        transferContext: 'comforting a friend who broke a cup',
      }),
      target({
        id: 'sv09.t5',
        chunk: 'I am sorry I am late',
        cueVi: 'xin lỗi tôi đến muộn',
        sourceSentence: 'Anh: I am sorry I am late, the train was crowded.',
        productionPattern: 'Sorry I am late — <reason>.',
        transferContext: 'arriving late to a class',
      }),
      target({
        id: 'sv09.t6',
        chunk: 'That is fine',
        cueVi: 'không sao',
        sourceSentence: 'Tom: That is fine. We just started.',
        productionPattern: 'That is <fine / okay / alright>.',
        transferContext: 'accepting an apology at a meeting',
      }),
    ],
    transferTask: {
      prompt: 'You spill coffee on a desk — apologize, explain, accept the other person saying it is fine.',
      promptVi: 'Bạn làm đổ cà phê lên bàn — xin lỗi, giải thích, và đáp lại khi người kia nói không sao.',
      changesDimension: 'apology with physical accident + explanation required',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv10',
    level: 'a0',
    track: 'survival',
    capabilities: ['ask-yesno'],
    title: 'Ask simple yes/no questions',
    titleVi: 'Hỏi câu có/không đơn giản',
    task: 'Ask basic yes/no questions about things around you',
    context: 'You are at a café deciding what to buy.',
    outcome: 'You can form "Is this...? / Do you have...?" questions.',
    input: {
      title: 'SV10 · Simple questions',
      text: [
        'Anh: Is this seat free?',
        'Woman: Yes, it is. Please sit down.',
        'Anh: Do you have wifi here?',
        'Woman: Yes, we do. The password is on the wall.',
        'Anh: Is the coffee good here?',
        'Woman: It is the best in the neighborhood.',
        'Anh: Then one coffee, please.',
      ].join('\n'),
      origin: 'authored',
      noteVi: 'Ba dạng hỏi cơ bản: "Is this X?" / "Do you have X?" / "Is the X Y?".',
    },
    targets: [
      target({
        id: 'sv10.t1',
        chunk: 'Is this seat free',
        cueVi: 'ghế này còn trống không',
        sourceSentence: 'Anh: Is this seat free?',
        productionPattern: 'Is this <seat free / table taken>?',
        transferContext: 'asking in a crowded food court',
      }),
      target({
        id: 'sv10.t2',
        chunk: 'Yes, it is',
        cueVi: 'vâng, đúng rồi',
        sourceSentence: 'Woman: Yes, it is. Please sit down.',
        productionPattern: 'Yes, <it is / we do / I am>.',
        transferContext: 'confirming a bus goes downtown',
      }),
      target({
        id: 'sv10.t3',
        chunk: 'Do you have wifi',
        cueVi: 'quán có wifi không',
        sourceSentence: 'Anh: Do you have wifi here?',
        productionPattern: 'Do you have <wifi / a menu / change>?',
        transferContext: 'asking a hostel for amenities',
      }),
      target({
        id: 'sv10.t4',
        chunk: 'Yes, we do',
        cueVi: 'có chứ (quán có)',
        sourceSentence: 'Woman: Yes, we do. The password is on the wall.',
        productionPattern: 'Yes, we <do / have>.',
        transferContext: 'answering a customer question at your shop',
      }),
      target({
        id: 'sv10.t5',
        chunk: 'the best in the neighborhood',
        cueVi: 'ngon nhất khu này',
        sourceSentence: 'Woman: It is the best in the neighborhood.',
        productionPattern: 'the <best / cheapest> in <the neighborhood / town>.',
        transferContext: 'recommending a restaurant to a tourist',
      }),
    ],
    transferTask: {
      prompt: 'At a gym front desk, ask two yes/no questions about facilities and answer one confirmation.',
      promptVi: 'Ở quầy lễ tân phòng gym, hỏi hai câu có/không về tiện ích và đáp lại một xác nhận.',
      changesDimension: 'new venue + asks about facilities not food',
    },
    recyclingFrom: ['sv08'],
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv11',
    level: 'a0',
    track: 'survival',
    capabilities: ['ask-price', 'express-preference'],
    title: 'This one, that one',
    titleVi: 'Cái này, cái kia',
    task: 'Point at things and say which you want',
    context: 'You are choosing fruit at a market stall.',
    outcome: 'You can identify items with this/that and state a choice.',
    input: {
      title: 'SV11 · Pointing',
      text: [
        'Anh: How much is this mango?',
        'Seller: This one is thirty thousand. That one is fifty.',
        'Anh: Why is that one more expensive?',
        'Seller: It is bigger and sweeter.',
        'Anh: Okay, I will take this one.',
        'Seller: Good choice.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"this one" gần / "that one" xa; "I will take this" = quyết định mua.',
    },
    targets: [
      target({
        id: 'sv11.t1',
        chunk: 'How much is this',
        cueVi: 'cái này bao nhiêu tiền',
        sourceSentence: 'Anh: How much is this mango?',
        productionPattern: 'How much is <this / that / it>?',
        transferContext: 'asking a price at a souvenir shop',
      }),
      target({
        id: 'sv11.t2',
        chunk: 'this one',
        cueVi: 'cái này',
        sourceSentence: 'Seller: This one is thirty thousand. That one is fifty.',
        productionPattern: '<this / that> one is <price>.',
        transferContext: 'comparing two phones in a shop',
      }),
      target({
        id: 'sv11.t3',
        chunk: 'that one',
        cueVi: 'cái kia',
        sourceSentence: 'Seller: This one is thirty thousand. That one is fifty.',
        productionPattern: 'I will take <that one / the big one>.',
        transferContext: 'pointing at a bakery shelf',
      }),
      target({
        id: 'sv11.t4',
        chunk: 'more expensive',
        cueVi: 'đắt hơn',
        sourceSentence: 'Anh: Why is that one more expensive?',
        productionPattern: '<more expensive / cheaper / bigger>.',
        transferContext: 'comparing two hotels',
      }),
      target({
        id: 'sv11.t5',
        chunk: 'I will take this one',
        cueVi: 'tôi lấy cái này',
        sourceSentence: 'Anh: Okay, I will take this one.',
        productionPattern: 'I will take <this one / two of them>.',
        transferContext: 'buying a ticket at a counter',
      }),
      target({
        id: 'sv11.t6',
        chunk: 'Good choice',
        cueVi: 'lựa chọn tốt',
        sourceSentence: 'Seller: Good choice.',
        productionPattern: '<Good / Great> choice.',
        transferContext: 'a waiter approving your order',
      }),
    ],
    transferTask: {
      prompt: 'At a phone shop, compare two items, ask why one costs more, then pick the cheaper one.',
      promptVi: 'Ở cửa hàng điện thoại, so sánh hai sản phẩm, hỏi sao cái kia đắt hơn, rồi chọn cái rẻ hơn.',
      changesDimension: 'tech items + choose the cheaper option',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
  spec({
    id: 'sv12',
    level: 'a0',
    track: 'survival',
    capabilities: ['express-preference', 'express-opinion'],
    title: 'Say what you like',
    titleVi: 'Nói sở thích',
    task: 'Say what you like and dislike in small talk',
    context: 'Chatting about food and hobbies with a new friend.',
    outcome: 'You can state likes/dislikes and ask the same back.',
    input: {
      title: 'SV12 · Likes',
      text: [
        'Linh: Do you like Vietnamese coffee?',
        'Anh: Yes, I love it. It is strong and sweet.',
        'Linh: What about tea?',
        'Anh: I like tea too, but not in the morning.',
        'Linh: Do you like spicy food?',
        'Anh: Not really. I prefer mild food.',
        'Linh: Me too, honestly.',
      ].join('\n'),
      origin: 'authored',
      noteVi: '"Do you like X" → I love it / I like it / Not really / I prefer Y.',
    },
    targets: [
      target({
        id: 'sv12.t1',
        chunk: 'Do you like',
        cueVi: 'bạn có thích ~ không',
        sourceSentence: 'Linh: Do you like Vietnamese coffee?',
        productionPattern: 'Do you like <coffee / spicy food / movies>?',
        transferContext: 'asking a date about music',
      }),
      target({
        id: 'sv12.t2',
        chunk: 'I love it',
        cueVi: 'tôi rất thích',
        sourceSentence: 'Anh: Yes, I love it. It is strong and sweet.',
        productionPattern: 'I <love / like / hate> it.',
        transferContext: 'reacting to a gift',
      }),
      target({
        id: 'sv12.t3',
        chunk: 'What about',
        cueVi: 'còn ~ thì sao',
        sourceSentence: 'Linh: What about tea?',
        productionPattern: 'What about <tea / the weekend>?',
        transferContext: 'asking a follow-up about plans',
      }),
      target({
        id: 'sv12.t4',
        chunk: 'I like tea too',
        cueVi: 'tôi cũng thích trà',
        sourceSentence: 'Anh: I like tea too, but not in the morning.',
        productionPattern: 'I like <it / them> too.',
        transferContext: 'agreeing about a shared hobby',
      }),
      target({
        id: 'sv12.t5',
        chunk: 'Not really',
        cueVi: 'không hẳn',
        sourceSentence: 'Anh: Not really. I prefer mild food.',
        productionPattern: 'Not really. I prefer <mild / quiet>.',
        transferContext: 'answering about horror movies',
      }),
      target({
        id: 'sv12.t6',
        chunk: 'I prefer',
        cueVi: 'tôi thích hơn',
        sourceSentence: 'Anh: Not really. I prefer mild food.',
        productionPattern: 'I prefer <mild food / morning classes>.',
        transferContext: 'choosing between window and aisle seats',
      }),
      target({
        id: 'sv12.t7',
        chunk: 'Me too',
        cueVi: 'tôi cũng vậy',
        sourceSentence: 'Linh: Me too, honestly.',
        productionPattern: 'Me <too / neither>.',
        transferContext: 'agreeing when someone shares a dislike',
      }),
    ],
    transferTask: {
      prompt: 'Talk about weekend activities — say one thing you like and one you do not, then ask back.',
      promptVi: 'Nói về hoạt động cuối tuần — một thứ bạn thích và một thứ không, rồi hỏi lại.',
      changesDimension: 'topic area (activities not food) + two-way exchange',
    },
    sourceRefs: [...SRC.functions],
    researchRefs: [...RES.functions],
  }),
];
